### ISSUE TITLE
Undefined symbol: g_date_time_unref

### ISSUE THREAD

**Issue by juanmanavella** [golemfactory/clay#1019]
I'm facing this issue on three of our Golems 5.3 so far (Debian based):

```
root@milliwatt-g8:~/golem# golemapp --nogui
Traceback (most recent call last):
  File "/home/mfrancis/Projects/golem/golemapp.py", line 7, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/golem/node.py", line 10, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/golem/client.py", line 19, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/golem/core/keysauth.py", line 13, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/golem/core/crypto.py", line 30, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/pyelliptic/__init__.py", line 43, in <module>
  File "/tmp/pip-build-lMvBkI/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/pyelliptic/openssl.py", line 528, in <module>
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/pyelliptic/openssl.py", line 67, in __init__
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 136, in __init__
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._FuncPtr = _FuncPtr
OSError: /tmp/_MEIJERC4K/libgobject-2.0.so.0: undefined symbol: g_date_time_unref
Failed to execute script golemapp

```

**Comment by juanmanavella** [comment]
This seems to be Debian specific. I have fixed it by installing all dependencies required to a proper install from source on Ubuntu based systems: 

> apt-get install openssl python-dev python-pyqt5 qt5-default pyqt5-dev-tools libffi-dev pkg-config libjpeg-dev libopenexr-dev libssl-dev autoconf libgmp-dev libtool python-netifaces python-psutil build-essential python-pip

As stated here: [https://github.com/golemfactory/golem/wiki/Installation](https://github.com/golemfactory/golem/wiki/Installation)

**Comment by juanmanavella** [comment]
Some of the dependencies pulled by Debian package qt5-default fixed this issue, so, I'm clossing this issue.
