### ISSUE TITLE
geth not found when running golemapp.exe on windows

### ISSUE THREAD

**Issue by planetceres** [golemfactory/clay#1061]
When trying to install Golem on Windows, the logs say it can't find geth? 

geth is installed and works independently of golem.

`Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file C:\Users\username\AppData\Local\golem\golem\SimpleEnv\minilight.ini: [Errno 2] No such file or directory: u'C:\\Users\\username\\AppData\\Local\\golem\\golem\\SimpleEnv\\minilight.ini'
INFO     [golem.client                       ] Client "", datadir: C:\Users\username\AppData\Local\golem\golem\default
Traceback (most recent call last):
  File "C:\golem\golemapp.py", line 105, in <module>
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
  File "C:\golem\golemapp.py", line 70, in start
  File "C:\golem\gui\startapp.py", line 134, in start_app
  File "C:\golem\gui\startapp.py", line 70, in start_client
  File "C:\golem\golem\client.py", line 127, in __init__
  File "C:\golem\golem\transactions\ethereum\ethereumtransactionsystem.py", line 30, in __init__
  File "C:\golem\golem\ethereum\client.py", line 20, in __init__
  File "C:\golem\golem\ethereum\node.py", line 80, in __init__
OSError: Ethereum client 'geth' not found
Failed to execute script golemapp`

**Comment by mfranciszkiewicz** [comment]
The directory that contains your `geth` binary is not present in the `PATH` environment variable.

**Comment by planetceres** [comment]
Looks like it's in there. 

Environment variables:
`Geth   C:\Program Files\Geth`
`ETHEREUM_SOCKET       \\.\pipe\geth.ipc`

**Comment by garethjns** [comment]
I've just experienced the same error installing for the first time today (Windows 10 x64), but have managed to fix it.

During the installation of Geth it said the path wasn't updated - I didn't note the exact error, something about the path being too long "1500 > 1024" (?)

I added the Geth path manually to the System paths and still got the error above when running Golemapp. I moved Geth to the start of the path and it now works.

It shouldn't make a different but I'm using https://patheditor2.codeplex.com/ to change the paths rather than that useless box in the Environment Variables dialog.

**Comment by staniko** [comment]
It worked for my already installed geth, but I have the paths close to the root path as garethjns did.
Maybe the scripts have problems with spaces in the path like "c:\Program  Files\...", typical issue - at least for my bash and Powershell scripties ;D.

**Comment by maaktweluit** [comment]
Geth is no longer installed by default in golem since a few versions. It has been moved to a remote Geth instance.

You are still able to install it and make golem use the local instance instead.

Closing this issue for now, please make a new issue or re-open this if you have any trouble running the latest version.
