### ISSUE TITLE
golemapp closes upon selecting "show result" on completed task

### ISSUE THREAD

**Issue by beastybryan** [golemfactory/clay#1125]
I don't know if the number of subtasks assigned, the time frame completed, or the specific nodes attached to make a difference. But I a running an Ubuntu 16.04 LTS and Golem alpha version 0.6.0. I have noticed that the tasks I have completed (there is a blender image output in the path I saved it in, and I can see it), when I right click the completed task and select "Show result", the golemapp shuts down immediately.

Any help, or any other information I could provide to help you fix this I will gladly oblige.
I didn't attach any screenshots considering the problem I am having...
Thank you!

**Comment by maaktweluit** [comment]
Hey beastybryan,

Thanks for the report!
I'll try it tonight on the develop branch, to confirm it is still happening.

Could you please provide the last few lines of your log file after the error occurred? it should be in `~/golem-0.6.0/logs/` when you used the installer or where you extracted your package.

Have a great day!

Maaktweluit

**Comment by beastybryan** [comment]
Sorry I forgot to provide those! I'm pretty sure the last time I used Golem_GUI I completed a rendering and it closed. I will do another rendering today and check the logs immediately, and paste them here to you again if its different from this:
`2017-06-13 22:39:08 WARNING  golem.core.simpleserializer         set/frozenset have known problems with umsgpack: set([u'/home/bryan/Pictures/r2d2.blend', u'/home/bryan/Pictures/Golem_renderings/golem-header.blend'])
2017-06-13 22:39:18 WARNING  golem.core.simpleserializer         set/frozenset have known problems with umsgpack: set([u'/home/bryan/Pictures/r2d2.blend', u'/home/bryan/Pictures/Golem_renderings/golem-header.blend'])
2017-06-14 08:07:23 WARNING  golem.core.simpleserializer         set/frozenset have known problems with umsgpack: set([u'/home/bryan/Pictures/Golem_renderings/golem-header.blend'])
2017-06-14 08:07:32 WARNING  golem.core.simpleserializer         set/frozenset have known problems with umsgpack: set([u'/home/bryan/Pictures/Golem_renderings/golem-header.blend'])
2017-06-14 10:28:02 ERROR    golem.rpc                           RPC: call error: [Failure instance: Traceback (failure with no frames): <class 'autobahn.wamp.exception.ApplicationError'>: ApplicationError(error=<wamp.close.transport_lost>, args=[u'WAMP transport was lost without closing the session before'], kwargs={}, enc_algo=None)
]`

**Comment by maaktweluit** [comment]
Thanks for the info!
If you put code quotes ` on a separate line it becomes a multi line block :)

I've also checked it on develop and the error is still there.

In terminal it shows:
```
Traceback (most recent call last):
  File "/home/maaktweluit/src/golem/gui/controller/taskcontexmenucustomizer.py", line 69, in __show_result_triggered
    self.logic.show_task_result(self.task_desc.definition.task_id)
  File "/home/maaktweluit/src/golem/gui/applicationlogic.py", line 300, in show_task_result
    self.customizer.show_task_result(task_id)
  File "/home/maaktweluit/src/golem/gui/controller/mainwindowcustomizer.py", line 167, in show_task_result
    file_ = t.task_state.outputs[num]
IndexError: list index out of range
Subprocess 2586 exited with code -6
```

```golem_gui.log``` show nothing
```golemclient.log``` only shows:
```
2017-06-20 19:33:17 INFO     golem.network.transport.tcpnetwork  Deserialization of messages from 50.175.188.188:40102 failed, maybe it's still too short?
2017-06-20 19:33:33 INFO     golem.ethereum                      Node terminated in 0.00 s 
```
