### ISSUE TITLE
BMW benchmark error

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1169]
```
WARNING  [golem.docker.task_thread           ] Task stderr:
['blender', '-b', '/golem/resources/bmw27_cpu.blend', '-y', '-P', '/golem/work/blenderscript.py', '-o', '/golem/output/tmp_qqgfyblender_benchmark_1', '-F', 'PNG', '-t', '5', '-f', '1']
Traceback (most recent call last):
  File "/golem/work/job.py", line 57, in <module>
    params.output_format)
  File "/golem/work/job.py", line 51, in run_blender_task
    exit_code = exec_cmd(cmd)
  File "/golem/work/job.py", line 16, in exec_cmd
    pc = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by mfranciszkiewicz** [comment]
Resolved by #1171
