### ISSUE TITLE
golemapp fails to run on linux

### ISSUE THREAD

**Issue by devonhk** [golemfactory/clay#1177]
**Steps to repro**

Download https://github.com/golemfactory/golem/releases/download/0.6.0/golem-linux_x64-0.6.0.tar.gz
Extract
run `sudo ./golemapp`

**Expected behavior**
A GUI window opens

**Actual behavior**
- Python import errors
- Work space specific hardcoded paths?

```
Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /home/user/.local/share/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/home/user/.local/share/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /home/user/.local/share/golem/default 
Traceback (most recent call last):
  File "/home/mfrancis/Projects/golem/golemapp.py", line 105, in <module>
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/home/mfrancis/Projects/golem/golemapp.py", line 70, in start
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 134, in start_app
  File "/home/mfrancis/Projects/golem/gui/startapp.py", line 70, in start_client
  File "/home/mfrancis/Projects/golem/golem/client.py", line 141, in __init__
  File "/home/mfrancis/Projects/golem/golem/transactions/ethereum/ethereumtransactionsystem.py", line 29, in __init__
  File "/home/mfrancis/Projects/golem/golem/ethereum/client.py", line 20, in __init__
  File "/home/mfrancis/Projects/golem/golem/ethereum/node.py", line 80, in __init__
OSError: Ethereum client 'geth' not found
Failed to execute script golemapp```

**Comment by mfranciszkiewicz** [comment]
`OSError: Ethereum client 'geth' not found`

`geth` is missing. To install it, please [follow these instructions](https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum).
