### ISSUE TITLE
Has someone really tested Golem? Did it worked? I need technical proofs. I tried to properly run it but I always get 0 nodes despite following installation instructions (port forwarding, DHCP…)

### ISSUE THREAD

**Issue by garetbale** [golemfactory/clay#1259]

**Comment by SchwiftyQC** [comment]
Same here having difficulties executing script from CLI. The Golem GUI Launches but 0 nodes and not showing any activity. While following https://github.com/golemfactory/golem/wiki/Installation guide. I came across a failed execution of script when attempting to run the CLI command "golemapp --nogui".  The install was successful, port forwarding UDP and TCP enabled for requested ports, Anti-Virus exceptions made and firewalls exceptions made. Even Disabled both my firewall and anti-virus temporarily to see if causing further issue and still received the same failed script error.  

I'm Running Windows 7 Ultimate x64 
I would love to send an error log but I did not one see one generated. 
Please let me know if you need further information and I be happy to assist.

**Comment by ghost** [comment]
Same here, I followed all the installation guide on Windows, but no nodes at all.

**Comment by Elfoniok** [comment]
Hey two things, if you write down your environment, please provide golem version. Than check if your node is listed here:

https://stats.golem.network/show

If not, probably you don't have port forwarded, i know you are writing you have but have you confirmed that those are open?

For example with netcat utility (telnet on windows?)?

For some cases this can be pointless if your ISP is not allowing for this. For example at home my ISP is operating only on IPv6 addresses but since most of internet is working on IPv4 they have something called DualStack-Lite which is translating IPv4 to IPv6 but in the end it doesn't allow for IPv4 port forwarding even if i do this in my ruter configuration.

As for logs, on Windows check out folder
C:\Users\\<username>\.golem\logs pack it and send to us on 
tech@golem.network

**Comment by fudingyu** [comment]
I met same trouble when I run Golem just give me a GUI but I can't do anything and can't click button on gui. not have log file in C:\Users\.golem\logs .
 
![qq 20170817184214](https://user-images.githubusercontent.com/477668/29408781-1febae80-837c-11e7-9e26-5f21ca1843f7.png)
![qq 20170817184222](https://user-images.githubusercontent.com/477668/29408780-1fe57100-837c-11e7-9fa3-d9af396ed386.png)

**Comment by fudingyu** [comment]
And I discover Golem this app be idle, not send any request and not get any data just access fonts.googleapis.com like below: (use Proxifier set global proxy)
[08.17 18:55:27] golem.exe *64 - fonts.googleapis.com:61000 close, 551 bytes sent, 0 bytes received, lifetime <1 sec
[08.17 18:55:36] golem.exe *64 - fonts.googleapis.com:61000 open through proxy 127.0.0.1:6888 SOCKS5
[08.17 18:55:37] golem.exe *64 - fonts.googleapis.com:61000 close, 551 bytes sent, 0 bytes received, lifetime 00:01
[08.17 18:55:45] golem.exe *64 - fonts.googleapis.com:61000 open through proxy 127.0.0.1:6888 SOCKS5
[08.17 18:55:46] golem.exe *64 - fonts.googleapis.com:61000 close, 551 bytes sent, 0 bytes received, lifetime 00:01
[08.17 18:55:54] golem.exe *64 - fonts.googleapis.com:61000 open through proxy 127.0.0.1:6888 SOCKS5

**Comment by Elfoniok** [comment]
In order to tell whats wrong its easier to skip GUI in process. Just launch golem but in a console find and invoke:

golemcli.exe network show

and check output of this command.

**Comment by dayakarreddyn** [comment]
Having same problem, any help would be appreciated.

>golemcli.exe network show
Traceback (most recent call last):                                                
File "C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 27, in <module>                                                        File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 196, in install                                                                    File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 72, in __init__                                                                    File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 512, in __init__                                                                            File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 284, in installWaker                                                                   File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 79, in __init__                                                                        File "C:\Python27\lib\socket.py", line 228, in meth                               
return getattr(self._sock,name)(*args)                                      
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions                                                 
Failed to execute script pyi_rth_twisted

**Comment by Elfoniok** [comment]
Looks like you need to do this in privileged console or set UAC to allow golemcli.exe to access sockets.
