### ISSUE TITLE
golemapp fails on Arch based Linux Distro

### ISSUE THREAD

**Issue by mustafabalci** [golemfactory/clay#1315]
```
WARNING  [golem.appconfig                    ] Can't open file /home/mustafa/.local/share/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/home/mustafa/.local/share/golem/SimpleEnv/minilight.ini'
INFO     [golem.ethereum                     ] geth 1.6.7: /usr/bin/geth
INFO     [golem.ethereum                     ] init file: /home/mustafa/Masaüstü/Klasörlerim/Golem/golem/golem/golem/ethereum/rinkeby.json
WARN [08-28|21:19:41] No etherbase set and no accounts found as default 
INFO [08-28|21:19:41] Allocated cache and file handles         database=/home/mustafa/.local/share/golem/default/ethereum/rinkeby/geth/chaindata cache=16 handles=16
INFO [08-28|21:19:41] Successfully wrote genesis state         database=chaindata                                                                hash=6341fd…67e177
INFO [08-28|21:19:41] Allocated cache and file handles         database=/home/mustafa/.local/share/golem/default/ethereum/rinkeby/geth/lightchaindata cache=16 handles=16
INFO [08-28|21:19:41] Successfully wrote genesis state         database=lightchaindata                                                                hash=6341fd…67e177
INFO     [golem.ethereum                     ] Starting Ethereum node: `/usr/bin/geth --datadir=/home/mustafa/.local/share/golem/default/ethereum/rinkeby --cache=32 --syncmode=light --rinkeby --port=52541 --ipcpath=/tmp/rinkeby-52541 --nousb --verbosity 3`
WARN [08-28|21:19:41] No etherbase set and no accounts found as default 
INFO [08-28|21:19:41] Starting peer-to-peer node               instance=Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.3
INFO [08-28|21:19:41] Allocated cache and file handles         database=/home/mustafa/.local/share/golem/default/ethereum/rinkeby/geth/lightchaindata cache=32 handles=1024
INFO [08-28|21:19:41] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Metropolis: 9223372036854775807 Engine: clique}"
INFO [08-28|21:19:41] Loaded most recent local header          number=0 hash=6341fd…67e177 td=1
INFO [08-28|21:19:41] Starting P2P networking 
INFO [08-28|21:19:43] UDP listener up                          self=enode://2015a388a7d15e726cbe573c7557952c03122445c5486e801d215562b3c7de616b5b0b3e2aa8bde51dd0bbf5d83783d36571046be39135bdb76e57664b27adaa@100.89.231.95:52541
WARN [08-28|21:19:43] Light client mode is an experimental feature 
INFO [08-28|21:19:43] RLPx listener up                         self=enode://2015a388a7d15e726cbe573c7557952c03122445c5486e801d215562b3c7de616b5b0b3e2aa8bde51dd0bbf5d83783d36571046be39135bdb76e57664b27adaa@100.89.231.95:52541
INFO [08-28|21:19:43] IPC endpoint opened: /tmp/rinkeby-52541 
INFO     [golem.ethereum                     ] rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177)
INFO     [golem.ethereum                     ] Node started in 2.400000000000001s: `/usr/bin/geth --datadir=/home/mustafa/.local/share/golem/default/ethereum/rinkeby --cache=32 --syncmode=light --rinkeby --port=52541 --ipcpath=/tmp/rinkeby-52541 --nousb --verbosity 3`
INFO     [twisted                            ] No extra node router roles
INFO     [twisted                            ] Using default node shutdown triggers ['shutdown_on_worker_exit']
INFO     [twisted                            ] Configuring node from local configuration ...
INFO     [twisted                            ] Starting 1 workers ...
INFO     [twisted                            ] Router worker "worker-001" starting ..
INFO     [twisted                            ] Traceback (most recent call last):
INFO     [twisted                            ] File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
INFO     [twisted                            ] mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
INFO     [twisted                            ] File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
INFO     [twisted                            ] __import__(pkg_name)
INFO     [twisted                            ] File "/home/mustafa/Masaüstü/Klasörlerim/Golem/golem/lib/python3.6/site-packages/crossbar/__init__.py", line 34, in <module>
INFO     [twisted                            ] txaio.use_twisted()
INFO     [twisted                            ] File "/home/mustafa/Masaüstü/Klasörlerim/Golem/golem/lib/python3.6/site-packages/txaio/__init__.py", line 109, in use_twisted
INFO     [twisted                            ] from txaio import tx
INFO     [twisted                            ] File "/home/mustafa/Masaüstü/Klasörlerim/Golem/golem/lib/python3.6/site-packages/txaio/tx.py", line 32, in <module>
INFO     [twisted                            ] import inspect
INFO     [twisted                            ] File "/usr/lib/python3.6/inspect.py", line 41, in <module>
INFO     [twisted                            ] import linecache
INFO     [twisted                            ] File "/usr/lib/python3.6/linecache.py", line 11, in <module>
INFO     [twisted                            ] import tokenize
INFO     [twisted                            ] File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
INFO     [twisted                            ] import re
INFO     [twisted                            ] File "/usr/lib/python3.6/re.py", line 142, in <module>
INFO     [twisted                            ] class RegexFlag(enum.IntFlag):
INFO     [twisted                            ] AttributeError: module 'enum' has no attribute 'IntFlag'
WARNING  [twisted                            ] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 1.
ERROR    [twisted                            ] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1.
ERROR    [twisted                            ] crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1. ['import inspect', 'File "/usr/lib/python3.6/inspect.py", line 41, in <module>', 'import linecache', 'File "/usr/lib/python3.6/linecache.py", line 11, in <module>', 'import tokenize', 'File "/usr/lib/python3.6/tokenize.py", line 33, in <module>', 'import re', 'File "/usr/lib/python3.6/re.py", line 142, in <module>', 'class RegexFlag(enum.IntFlag):', "AttributeError: module 'enum' has no attribute 'IntFlag'"]
INFO     [golem.ethereum                     ] Node terminated in 0.00 s
INFO     [twisted                            ] Node shutdown requested ..
INFO     [twisted                            ] Main loop terminated.

```

**Comment by marmistrz** [comment]
Are you using a virtualenv?

**Comment by mustafabalci** [comment]
Yes I'm using a virtualenv

**Comment by marmistrz** [comment]
This looks very similar to: https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag#44466013

Can you try
```
pip uninstall enum34
```
from the virtualenv?

If this doesn't help, please show your
```
pip freeze
```
from within the virtualenv.

Did you use these unofficial instructions for installing: https://github.com/golemfactory/golem/wiki/Installing-Golem-on-Arch-Linux-(unofficial) ?
