### ISSUE TITLE
Golem fails to start due to referencing a non-existant module

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1369]
on 0bc5c6ad
```
ERROR    [golem.core.async                   ] Caught async exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/marcin/proj/golem/golem/node.py", line 60, in _run
    self._setup_apps()
  File "/home/marcin/proj/golem/golem/node.py", line 94, in _setup_apps
    self._apps_manager.load_apps()
  File "/home/marcin/proj/golem/apps/appsmanager.py", line 38, in load_apps
    module = import_module(package)
  File "/home/marcin/venv3/golem/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    
builtins.ModuleNotFoundError: No module named 'apps.dummy.gui.view.gen.ui_DummyWidget'
```

**Comment by marmistrz** [comment]
This happened due to not having rerun `setup.py develop`.
