### ISSUE TITLE
P2PService.remove_peer_by_id fails

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#1376]
`sync_network` is called periodically and logs are flooded with:
```
ERROR    [golem.client                       ] p2pservice.sync_network failed
Traceback (most recent call last):
  File "/Projects/golem/golem/client.py", line 988, in __do_work
    self.p2pservice.sync_network()
  File "/Projects/golem/golem/network/p2p/p2pservice.py", line 223, in sync_network
    self.__sync_peer_keeper()
  File "/Projects/golem/golem/network/p2p/p2pservice.py", line 1034, in __sync_peer_keeper
    self.__remove_sessions_to_end_from_peer_keeper()
  File "/Projects/golem/golem/network/p2p/p2pservice.py", line 1054, in __remove_sessions_to_end_from_peer_keeper
    self.remove_peer_by_id(peer_id)
  File "/Projects/golem/golem/network/p2p/p2pservice.py", line 340, in remove_peer_by_id
    peer = self.peers.pop(peer_id, None)
TypeError: unhashable type: 'Node'
```

**Comment by Elfoniok** [comment]
Fixed here
https://github.com/golemfactory/golem/commit/be2de9fb4ce2f95220d5a5320dbeb967129c2c2b
