### ISSUE TITLE
Could not find platform independent libraries

### ISSUE THREAD

**Issue by prijindal** [golemfactory/clay#1401]
If I try to run ./golemapp it says ```Could not find platform independent libraries```,
I already have docker, geth, hyperg installed and in the path.
I am using Arch Linux, I know Arch Linux is not officially supported, But if all the dependencies are installed, what could be the issues?

**Comment by prijindal** [comment]
This is my console error
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/Projects/golem/golemapp.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/node.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/client.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/core/keysauth.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/venv/lib/python3.5/site-packages/devp2p/crypto.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/__init__.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/openssl.py", line 528, in <module>
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/openssl.py", line 180, in __init__
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
AttributeError: /usr/lib/libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL
[5826] Failed to execute script golemapp
```

**Comment by prijindal** [comment]
Turns out solution was two part
First, setting PYTHONHOME to /usr/bin/python, If you have python, elsewhere use that.
Secondly, replacing the version of libcrypto.so.1.1 in /usr/lib from the default to libcrypto.so.1.0.0.

Warning: If you are replacing libcrypto.so.1.1, do it at your own risk. It might break something
