### ISSUE TITLE
Task header KeyError 

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1518]
Key Error in taskcomputer was observed. We should identify what was the problem here and try to eliminate it. Maybe the tasks are removed from task keeper to early? 

``` 
ERROR    [golem.client                       ] resource_server.sync_network failed
Traceback (most recent call last):
  File "/home/luke/golem/golem/golem/client.py", line 996, in __do_work
    self.resource_server.sync_network()
  File "/home/luke/golem/golem/golem/resource/base/resourceserver.py", line 57, in sync_network
    self._download_resources()
  File "/home/luke/golem/golem/golem/resource/base/resourceserver.py", line 114, in _download_resources
    async=async)
  File "/home/luke/golem/golem/golem/resource/base/resourcesmanager.py", line 415, in pull_resource
    success(entry, task_id)
  File "/home/luke/golem/golem/golem/resource/base/resourceserver.py", line 122, in _download_success
    unpack_delta=False)
  File "/home/luke/golem/golem/golem/client.py", line 438, in task_resource_collected
    unpack_delta
  File "/home/luke/golem/golem/golem/task/taskcomputer.py", line 126, in task_resource_collected
    subtask.short_description, subtask.deadline)
  File "/home/luke/golem/golem/golem/task/taskcomputer.py", line 335, in __compute_task
    task_header = self.task_server.task_keeper.task_headers[task_id]
KeyError: '2e47e00c-fc2d-4b44-a797-df80b65ff090'
```

**Comment by mfranciszkiewicz** [comment]
I haven't been able to reproduce this bug. Most probably resources were downloaded after task's deadline has passed.
