### ISSUE TITLE
Mac is provider, error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1534]
source version

```
WARNING [golem.docker.manager ] DockerMachine: failed to stop the VM: Command '['docker-machine', 'stop', 'golem']' returned non-zero exit status 1.
ERROR [golem.docker.manager ] DockerMachine: failed to start the VM: Command '['docker-machine', 'start', 'golem']' returned non-zero exit status 1.
Exception in thread Thread-324:
Traceback (most recent call last):
File "/Users/ederenn/golem/golem/docker/manager.py", line 407, in _set_docker_machine_env
args=('--shell', 'cmd'))
File "/Users/ederenn/golem/golem/docker/manager.py", line 301, in command
**params)
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker-machine', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/Users/ederenn/golem/golem/docker/manager.py", line 395, in _wait_for_tasks
self.constrain(self.docker_machine, **self._config)
File "/Users/ederenn/golem/golem/docker/manager.py", line 210, in constrain
self._set_docker_machine_env()
File "/Users/ederenn/golem/golem/docker/manager.py", line 410, in _set_docker_machine_env
self.command('regenerate_certs', self.docker_machine)
File "/Users/ederenn/golem/golem/docker/manager.py", line 301, in command
**params)
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker-machine', 'regenerate-certs', 'golem']' returned non-zero exit status 1.
```

**Comment by badb** [comment]
This issue was observed after Golem was stopped, configuration was changed, and then it was restarted. On Mac and Windows, Docker machine was not restarted correctly and throws some regenrate-certs error.  Maybe certs must be regenerated with every config change? Maybe there's a better way? Solve this issue, so that Docker Machine is restarted correctly every time.

**Comment by maaktweluit** [comment]
@ederenn updated the OP with ``` for better formatting, could you check if its still correct?

**Comment by maaktweluit** [comment]
first few googles on this hint to running `docker-machine env golem` after each config change.
Will reproduce the error locally and see if this is indeed the correct solve.

**Comment by mfranciszkiewicz** [comment]
@maaktweluit Golem actually tries to do that. It stops the VM, updates the configuration, starts the VM and runs `docker-machine --shell cmd golem` (the `--shell cmd` part is there for unified output on macOS and windows). 

Note that this is not the issue of regenerating certs, all commands in sequence fail (`stop`, `start`, `env`). `regenerate-certs` is a last resort recovery attempt. It seems that the VM / env variables are broken prior to stopping.

**Comment by maaktweluit** [comment]
@mfranciszkiewicz thanks for the input!

My first check indeed show the command is already called, now digging in deeper.
Not able to reproduce though :(

**Comment by maaktweluit** [comment]
Tested on `0.8.1` and on `0.9.0` and can not reproduce the error, maybe mac osx 10.13 is not affected by this?
@mfranciszkiewicz  did you also get this error on mac high sierra?

**Comment by maaktweluit** [comment]
Reproduced it!

The first tests show it does not happen when only stopping during computation, but will test more to be sure.

Steps taken:
- Accept a task on mac, confirm its calculating
- Hit stop golem
- Change config
- Hit start golem
- Error is there

**Comment by maaktweluit** [comment]
After loads of trying and debugging i have found the underlying error:
```
2017-10-26 11:36:21 WARNING  golem.docker.manager                DockerMachine: failed to stop the VM: Command '['docker-machine', 'stop', 'golem']' returned non-zero exit status 1. -- b'Stopping "golem"...\n(golem) Stopping golem ...\nunexpected EOF\n'
```

stop is the first command that fails and `unexpected EOF` is where you see the issue is happening.

Changed `start` to `restart` and it seems to recover properly now.
Running a few more tests to be 100% sure before pushing my branch and making a PR.
