### ISSUE TITLE
Golem fills logs very quickly if stats.golem.network is down

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1567]
It prints this few times per second:
```
Oct 25 06:25:10 drohlum python[19860]: WARNING  [golem.monitor.transport            ] Problem sending payload to: 'http://stats.golem.network:8881/'
Oct 25 06:25:10 drohlum python[19860]: Traceback (most recent call last):
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/golem/monitor/transport/httptransport.py", line 15, in _post
Oct 25 06:25:10 drohlum python[19860]:     def _post(self, headers, payload):
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/venv/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
Oct 25 06:25:10 drohlum python[19860]:     return request('post', url, data=data, json=json, **kwargs)
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/venv/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
Oct 25 06:25:10 drohlum python[19860]:     return session.request(method=method, url=url, **kwargs)
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
Oct 25 06:25:10 drohlum python[19860]:     resp = self.send(prep, **send_kwargs)
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
Oct 25 06:25:10 drohlum python[19860]:     r = adapter.send(request, **kwargs)
Oct 25 06:25:10 drohlum python[19860]:   File "/home/golem/Projects/golem/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
Oct 25 06:25:10 drohlum python[19860]:     raise ConnectionError(e, request=request)
Oct 25 06:25:10 drohlum python[19860]: ConnectionError: HTTPConnectionPool(host='stats.golem.network', port=8881): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc565036950>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

This made 15G of uncompressed logs in one day (100M after gzipping, though).

**Comment by etam** [comment]
It looks like it was fixed https://github.com/golemfactory/golem/commit/bcb70ea5899fb90c1381544e2ecacd6b9b65cb4c
I just need to make sure which version was installed then.
