### ISSUE TITLE
string index out of range at resourcehandshake.py, line 265, in _nonce_downloaded

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1573]
```
INFO     [golem.resources                    ] Starting resource handshake with 'c66eee0c3b6a092d39c3e2972b9b8a71f361e345bba3ea68ddd
1451ba04504a91bd9bac025c872040f13e2656890773e73cda00ce7513cb7098bcd8a8247253a'                                                     
Unhandled Error
Traceback (most recent call last):
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/tcpnetwork.py", line 479, in dataReceived
    self._interpret(data)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/tcpnetwork.py", line 648, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/tcpnetwork.py", line 621, in _interpret
    SafeProtocol._interpret(self, data)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/tcpnetwork.py", line 508, in _interpret
    self.session.interpret(m)
  File "/home/etam/code/github/golemfactory/golem/golem/task/tasksession.py", line 103, in interpret
    MiddlemanSafeSession.interpret(self, msg)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/session.py", line 285, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/etam/code/github/golemfactory/golem/golem/network/transport/session.py", line 94, in interpret
    action(msg)
  File "/home/etam/code/github/golemfactory/golem/golem/resource/resourcehandshake.py", line 125, in _react_to_resource_handshake_st
art                                                                                                                                
    self._download_handshake_nonce(key_id, msg.resource)
  File "/home/etam/code/github/golemfactory/golem/golem/resource/resourcehandshake.py", line 258, in _download_handshake_nonce
    client_options=self.task_server.get_download_options(key_id)
  File "/home/etam/code/github/golemfactory/golem/golem/resource/base/resourcesmanager.py", line 423, in pull_resource
    success(entry, resource.files, task_id)
  File "/home/etam/code/github/golemfactory/golem/golem/resource/resourcehandshake.py", line 256, in <lambda>
    success=lambda res, files, _: self._nonce_downloaded(key_id, files),
  File "/home/etam/code/github/golemfactory/golem/golem/resource/resourcehandshake.py", line 265, in _nonce_downloaded
    path = files[0]
builtins.IndexError: string index out of range
```
https://github.com/golemfactory/golem/blob/baec2b95/golem/resource/resourcehandshake.py#L265

**Comment by etam** [comment]
@mfranciszkiewicz
