### ISSUE TITLE
check_payments failed

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1600]
```
INFO     [twisted                            ] Could not accept new connection (EMFILE)
ERROR    [golem.client                       ] check_payments failed
Traceback (most recent call last):
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3220, in get
    return next(clone.execute())
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 2363, in next
    obj = self.iterate()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 2345, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/transactions/incomeskeeper.py", line 36, in run_once
    subtask=expected_income.subtask,
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 4988, in get
    return sq.get()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3224, in get
    % self.sql())
golem.model.IncomeDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."created_date", "t1"."modified_date", "t1"."sender_node", "t1"."task", "t1"."subtask", "t1"."transaction", "t1"."block_number", "t1"."value" FROM "income" AS t1 WHERE ((("t1"."sender_node" = ?) AND ("t1"."subtask" = ?)) AND ("t1"."task" = ?))
PARAMS: ['f7f42d54098c71d8c79550a88d6855ab325338b926eccb56d1580d5814ec8ab87dc508ca98dbdf5e6a996bebfd57a0b42264756249714d648334ebb3f3676394', '277408616852483463719828418923990541339', '2fe67c95-9a93-4efc-903d-24adf310c266']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/client.py", line 1007, in __do_work
    self.check_payments()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/client.py", line 919, in check_payments
    after_deadline_nodes = self.transaction_system.check_payments()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/transactions/transactionsystem.py", line 96, in check_payments
    self.incomes_keeper.run_once()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/golem/transactions/incomeskeeper.py", line 42, in run_once
    expected_income.save()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 5165, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3458, in execute
    return self.database.rows_affected(self._execute())
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 2939, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3837, in execute_sql
    self.commit()
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/Users/kennethascheri/GitHub/kascheri12/golem/venv/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: unable to open database file
```

**Comment by kascheri12** [comment]
Here it is again on a different node. This one was running the golem-0.9.0 RC on Ubuntu 16.04. 

```
INFO     [twisted                            ] Could not accept new connection (EMFILE)
INFO     [twisted                            ] Could not accept new connection (EMFILE)
ERROR    [golem.client                       ] check_payments failed
Traceback (most recent call last):
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3220, in get
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2363, in next
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2345, in iterate
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Projects/golem/golem/transactions/incomeskeeper.py", line 36, in run_once
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 4988, in get
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3224, in get
golem.model.IncomeDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."created_date", "t1"."modified_date", "t1"."sender_node", "t1"."task", "t1"."subtask", "t1"."transaction", "t1"."block_number", "t1"."value" FROM "income" AS t1 WH
ERE ((("t1"."sender_node" = ?) AND ("t1"."subtask" = ?)) AND ("t1"."task" = ?))
PARAMS: ['af61cb97b9a6f2aea40b993077dc39e547f44014f22a95135dd71d86764a042eac6c6e0c7d29e8b4fac2eadd993423bca1eab9e324006861c84ce4efe37a453b', '75267593719818191044981609688921778440
', '8cb5b9de-5706-4cd5-a78f-468d0385a2cb']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3830, in execute_sql
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Projects/golem/golem/client.py", line 1012, in __do_work
  File "/Projects/golem/golem/client.py", line 924, in check_payments
  File "/Projects/golem/golem/transactions/transactionsystem.py", line 96, in check_payments
  File "/Projects/golem/golem/transactions/incomeskeeper.py", line 42, in run_once
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 5165, in save
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3458, in execute
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2939, in _execute
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3837, in execute_sql
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3656, in __exit__
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 135, in reraise
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3830, in execute_sql
peewee.OperationalError: unable to open database file
INFO     [twisted                            ] Could not accept new connection (EMFILE)
INFO     [twisted                            ] Could not accept new connection (EMFILE)

```

**Comment by kascheri12** [comment]
Also since I'm getting the `Could not accept new connection (EMFILE)` text over and over again so quickly, it's maxing out the CPU. Would it be possible to also fix so that no info or error message would waste so much spare resources? 
<img width="1125" alt="screen shot 2017-11-01 at 12 39 06 am" src="https://user-images.githubusercontent.com/4165385/32264763-6803a23e-be9d-11e7-93c7-6c13e33135f3.png">

**Comment by badb** [comment]
@Krigpl Can you take a quick look at this one, if this one can still be valid. Please close the issue if it's not.

**Comment by Krigpl** [comment]
The code responsible for these errors doesn't exist anymore. Closing.
