### ISSUE TITLE
No more tETH for testing?

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1601]
Fresh install of golem-0.9.0 on Ubuntu 16.04, can't get tETH to test. I received the same error on a different node also.

```
2017-11-01 08:33:12 INFO     golem.version                       GOLEM Version: 0.9.0
2017-11-01 08:33:12 INFO     golem.version                       P2P Protocol Version: 15
2017-11-01 08:33:12 INFO     golem.version                       Task Protocol Version: 16
2017-11-01 08:33:12 INFO     golem.pay                           Node Ethereum address: 0xf2a2213ec7d5eda1e0a5951106a8bfe3ca2590f8
2017-11-01 08:33:12 ERROR    requests.packages.urllib3.connection Certificate did not match expected hostname: rinkeby.golem.network. Certificate: {'subject': ((('commonName', 'docs.golem.network'),),), 'subjectAltName': [('DNS', 'docs.golem.network')]}
2017-11-01 08:33:12 ERROR    golem.ethereum                      Error downloading node list: hostname 'rinkeby.golem.network' doesn't match 'docs.golem.network'
2017-11-01 08:33:12 INFO     golem.ethereum                      GETH: connecting to remote RPC interface at http://94.23.17.170:55555
2017-11-01 08:33:13 INFO     golem.ethereum                      rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177)
2017-11-01 08:33:13 INFO     golem.ethereum                      Connected to node in 0.4195733070373535s
2017-11-01 08:33:13 INFO     twisted                             New node key pair generated!
2017-11-01 08:33:13 INFO     twisted                             File permissions on node public key fixed!
2017-11-01 08:33:13 INFO     twisted                             File permissions on node private key fixed!
2017-11-01 08:33:13 INFO     twisted                             No extra node router roles
2017-11-01 08:33:13 INFO     twisted                             Using default node shutdown triggers ['shutdown_on_worker_exit']
2017-11-01 08:33:13 INFO     twisted                             Configuring node from local configuration ...
2017-11-01 08:33:13 INFO     twisted                             Starting 1 workers ...
2017-11-01 08:33:13 INFO     twisted                             Router worker "worker-001" starting ..
2017-11-01 08:33:15 INFO     twisted                             Failed to import scrypt. This is not a fatal error but does
2017-11-01 08:33:15 INFO     twisted                             mean that you cannot create or decrypt privkey jsons that use
2017-11-01 08:33:15 INFO     twisted                             scrypt
2017-11-01 08:33:15 INFO     twisted                             CROSSBAR_RICH_LOGGING_ENABLE=True
2017-11-01 08:33:15 INFO     twisted                             {"worker_title": "Router", "level": "info", "python": "CPython", "log_time": 1509525195.542863, "text": "Router worker \"worker-001\" process 2295 starting on CPython-EPollReactor ..", "pid": 2295, "worker_id": "worker-001", "namespace": "crossbar.worker.process.run", "reactor": "EPollReactor"}
2017-11-01 08:33:15 INFO     twisted                             {"log_time": 1509525195.860741, "session_id": 5804185352400972, "text": "Router worker \"worker-001\" session 5804185352400972 initializing ..", "worker_id": "worker-001", "namespace": "crossbar.worker.worker.NativeWorkerSession", "level": "info"}
2017-11-01 08:33:15 INFO     twisted                             {"text": "Router worker \"worker-001\" session ready", "level": "info", "worker_id": "worker-001", "namespace": "crossbar.worker.worker.NativeWorkerSession", "log_time": 1509525195.8727772}
2017-11-01 08:33:15 INFO     twisted                             Router worker "worker-001" process 2294 started
2017-11-01 08:33:15 INFO     twisted                             {"text": "Realm 'golem' started", "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "realm": "golem", "log_time": 1509525195.877325}
2017-11-01 08:33:15 INFO     twisted                             Router 'worker-001': realm 'realm-001' (named 'golem') started
2017-11-01 08:33:15 INFO     twisted                             {"log_time": 1509525195.8792667, "realm_id": "realm-001", "text": "role role-001 on realm realm-001 started", "role_id": "role-001", "namespace": "crossbar.worker.worker.NativeWorkerSession", "level": "info", "role_config": {"name": "anonymous", "permissions": [{"allow": {"subscribe": true, "publish": true, "call": true, "register": true}, "uri": "*"}]}}
2017-11-01 08:33:15 INFO     twisted                             Router 'worker-001': role 'role-001' (named 'anonymous') started on realm 'realm-001'
2017-11-01 08:33:15 INFO     twisted                             {"system": "-", "isError": 0, "log_time": 1509525195.882402, "log_text": "WampWebSocketServerFactory starting on 61000", "message": ["WampWebSocketServerFactory starting on 61000"], "text": "WampWebSocketServerFactory starting on 61000", "time": 1509525195.882402, "namespace": "log_legacy", "level": "info"}
2017-11-01 08:33:15 INFO     twisted                             Router 'worker-001': transport 'transport-001' started
2017-11-01 08:33:15 INFO     twisted                             Local node configuration applied successfully!
2017-11-01 08:33:15 INFO     twisted                             {"log_time": 1509525195.8956416, "session_id": 7872470403924517, "text": ">>>>> session 7872470403924517 JOINED \"golem\" >>>>>\n\n{{'authprovider': 'static', 'transport': {{'websocket_extensions_in_use': [], 'http_headers_received': {{'pragma': 'no-cache', 'upgrade': 'WebSocket', 'user-agent': 'AutobahnPython/0.18.1', 'connection': 'Upgrade', 'sec-websocket-extensions': 'permessage-deflate; client_no_context_takeover; client_max_window_bits', 'host': 'localhost:61000', 'sec-websocket-protocol': 'wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json', 'cache-control': 'no-cache', 'sec-websocket-key': 'eBUDWZOiiq39NzaLwOj8WA==', 'sec-websocket-version': '13'}}, 'type': 'websocket', 'http_headers_sent': {{}}, 'protocol': 'wamp.2.msgpack.batched', 'cbtid': None, 'peer': 'tcp4:127.0.0.1:55876'}}, 'authmethod': 'anonymous', 'session': 7872470403924517, 'authrole': 'anonymous', 'authid': 'JK66-E5AA-M5FJ-X9WR-A3UG-QGTV'}}\n", "details": {"authprovider": "static", "transport": {"websocket_extensions_in_use": [], "http_headers_received": {"pragma": "no-cache", "upgrade": "WebSocket", "user-agent": "AutobahnPython/0.18.1", "connection": "Upgrade", "sec-websocket-extensions": "permessage-deflate; client_no_context_takeover; client_max_window_bits", "host": "localhost:61000", "sec-websocket-protocol": "wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json", "cache-control": "no-cache", "sec-websocket-key": "eBUDWZOiiq39NzaLwOj8WA==", "sec-websocket-version": "13"}, "type": "websocket", "http_headers_sent": {}, "protocol": "wamp.2.msgpack.batched", "cbtid": null, "peer": "tcp4:127.0.0.1:55876"}, "authmethod": "anonymous", "session": 7872470403924517, "authrole": "anonymous", "authid": "JK66-E5AA-M5FJ-X9WR-A3UG-QGTV"}, "namespace": "crossbar.router.router.Router", "realm": "golem", "level": "info"}
2017-11-01 08:33:17 WARNING  golem.docker.manager                Docker: pulling image golemfactory/base:1.2
2017-11-01 08:33:26 INFO     golem.pay                           Peer count: 238
2017-11-01 08:33:28 WARNING  golem.docker.manager                Docker: pulling image golemfactory/blender:1.3
2017-11-01 08:33:39 INFO     golem.pay                           Peer count: 238
2017-11-01 08:33:39 INFO     golem.pay                           Synchronized!
2017-11-01 08:33:39 INFO     golem.pay                           ETH: 0.0
2017-11-01 08:33:39 INFO     golem.pay                           Requesting tETH
2017-11-01 08:33:47 WARNING  golem.docker.manager                Docker: pulling image golemfactory/luxrender:1.2
2017-11-01 08:34:03 WARNING  golem.resources                     create HyperG logsdir: /home/kascheri12003/.local/share/golem/default/logs
2017-11-01 08:34:03 INFO     twisted                             ProtocolFactory starting on 40102
2017-11-01 08:34:03 INFO     twisted                             Starting factory <golem.network.transport.network.ProtocolFactory object at 0x7efd611a7668>
2017-11-01 08:34:03 INFO     twisted                             ProtocolFactory starting on 40103
2017-11-01 08:34:03 INFO     twisted                             Starting factory <golem.network.transport.network.ProtocolFactory object at 0x7efd60311b38>
2017-11-01 08:34:05 WARNING  golem.monitor                       Port status: 40102: timeout, 40103: timeout
2017-11-01 08:35:28 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
2017-11-01 08:33:15 INFO     twisted                             {"log_time": 1509525195.860741, "session_id": 5804185352400972, "t
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Projects/golem/golem/ethereum/paymentprocessor.py", line 391, in _run
    
  File "/Projects/golem/golem/ethereum/paymentprocessor.py", line 355, in get_ether_from_faucet
    
  File "/Projects/golem/golem/ethereum/node.py", line 56, in tETH_faucet_donate
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/requests/api.py", line 70, in get
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/requests/api.py", line 56, in request
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    
  File "/Projects/golem/venv/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
NoneType
2017-11-01 08:35:36 INFO     golem.pay                           Peer count: 239
2017-11-01 08:35:36 INFO     golem.pay                           ETH: 0.0
2017-11-01 08:35:36 INFO     golem.pay                           Requesting tETH
```

**Comment by Elfoniok** [comment]
Hey, thanks for pointing this out!

Looks like we had problem with our faucet, should be working fine now,
as a side not we should also handle this kind of error  gracefully.

**Comment by Krigpl** [comment]
Closing as this shouldn't be happening anymore.
