### ISSUE TITLE
object is not iterable, error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1607]
``` Traceback (most recent call last):
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\iocpreactor\reactor.py", line 119, in _callEventCallback
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 92, in _cbRead
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 118, in _handleRead
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 69, in _dispatchData
    
  File "C:\Users\badb\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\iocpreactor\tcp.py", line 75, in dataReceived
    
  File "C:\Sources\golem\golem\network\transport\tcpnetwork.py", line 479, in dataReceived
    
  File "C:\Sources\golem\golem\network\transport\tcpnetwork.py", line 503, in _interpret
    
  File "C:\Sources\golem\golem\network\transport\tcpnetwork.py", line 576, in _data_to_messages
    
  File "C:\Sources\golem\golem\network\transport\message.py", line 163, in deserialize
    
  File "C:\Sources\golem\golem\network\transport\message.py", line 349, in __init__
    
  File "C:\Sources\golem\golem\network\transport\message.py", line 44, in __init__
    
  File "C:\Sources\golem\golem\network\transport\message.py", line 175, in load_slots
    
builtins.TypeError: 'int' object is not iterable
```

binnary version, windows, computing two tasks
https://www.blendswap.com/blends/view/39708, single frame and simple bmw scene from test_tasks.
error occurred after adding second task, it was repeated during computation (after the timeout of the first task).
bmw test: 400x400, 1-5 frames, 30 min per task, 5 subtasks, 5 min per subtask
particles: 400x400, 1 frame, 30 min per task, 10 subtasks, 5 min per subtask

**Comment by ederenn** [comment]
encountered again, Windows, source version, branch: develop, up to date

``` 2017-11-21 11:42:36 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\iocpreactor\reactor.py", line 119, in _callEventCallback
    evt.callback(rc, numBytes, evt)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 92, in _cbRead
    if self._handleRead(rc, data, evt):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 118, in _handleRead
    return self._dispatchData()
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 75, in _dispatchData
    self.dataReceived(self._readBuffers[full_buffers][0:remainder])
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\iocpreactor\tcp.py", line 75, in dataReceived
    self.protocol.dataReceived(rbuffer)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\endpoints.py", line 119, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\tcpnetwork.py", line 481, in dataReceived
    self._interpret(data)
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\tcpnetwork.py", line 505, in _interpret
    mess = self._data_to_messages()
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\tcpnetwork.py", line 585, in _data_to_messages
    msg = Message.deserialize(buf, self.session.decrypt)
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\message.py", line 163, in deserialize
    slots=slots
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\message.py", line 515, in __init__
    super(MessageSetTaskSession, self).__init__(**kwargs)
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\message.py", line 44, in __init__
    self.load_slots(slots)
  File "C:\Users\ederenn\Projects\golem\golem\network\transport\message.py", line 175, in load_slots
    for slot, value in slots:
builtins.TypeError: 'int' object is not iterable

2017-11-21 11:43:01 INFO     golem.task.taskcomputer             b'Task 06dd3fa3-a9b0-4e3e-b56a-ccc2d98e20cd request rejected: No more subtasks in 06dd3fa3-a9b0-4e3e-b56a-ccc2d98e20c```
