### ISSUE TITLE
umsgpack.DuplicateKeyException: encountered duplicate key: -15, <class 'int'>, error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1616]
encountered on windows, source version
Golem is not passing "Render Local Test" for files from examples_blender (scene-helicopter-27-cycles.blend, cube.blend, bmw27_cpu.blend) 

``` 2017-11-03 13:32:16 INFO     twisted                             Scheduling retry 1 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x00000198A0BCA320> in 2.244528152354863 seconds.
2017-11-03 13:32:16 CRITICAL twisted                             Traceback (most recent call last):
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 104, in unserialize
    raw_msgs = self._serializer.unserialize(payload)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 302, in unserialize
    msgs.append(umsgpack.unpackb(data))
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 867, in _unpackb3
    return _unpack(io.BytesIO(s), options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 683, in _unpack_map
    v = _unpack(fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 683, in _unpack_map
    v = _unpack(fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\umsgpack.py", line 680, in _unpack_map
    raise DuplicateKeyException("encountered duplicate key: %s, %s" % (str(k), str(type(k))))
umsgpack.DuplicateKeyException: encountered duplicate key: -15, <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\autobahn\wamp\websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "C:\Users\Magdalena \Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 106, in unserialize
    raise ProtocolError("invalid serialization of WAMP message ({0})".format(e))
autobahn.wamp.exception.ProtocolError: invalid serialization of WAMP message (encountered duplicate key: -15, <class 'int'>)

2017-11-03 13:32:16 WARNING  twisted                             dropping connection to peer tcp4:127.0.0.1:56945 with abort=False: None ```

**Comment by maaktweluit** [comment]
@ederenn are you still able to reproduce this issue? else i think we can close it

**Comment by ederenn** [comment]
not seen in a while

**Comment by maaktweluit** [comment]
Ok, will close then, please re-open when it shows again
