### ISSUE TITLE
Service Error - Too many open files

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1618]
```
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 390, in _run
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 136, in is_synchronized
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 123, in check
    
  File "/Users/golem/Desktop/golem/golem/ethereum/client.py", line 47, in is_syncing
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/utils/functional.py", line 14, in inner
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/eth.py", line 56, in syncing
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/providers/manager.py", line 44, in request_blocking
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/providers/rpc.py", line 52, in make_request
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/sessions.py", line 535, in post
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(24, 'Too many open files'))
NoneType: None
INFO     [twisted                            ] Could not accept new connection (EMFILE)
INFO     [twisted                            ] Could not accept new connection (EMFILE)
```

**Comment by Krigpl** [comment]
Geth servers are more stable now
