### ISSUE TITLE
Failed to establish a new connection: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1655]
MacOS 10.13.1
Running from source - develop branch. Just pulled latest code this morning (11/13/17)

I'm getting this error when starting my node.

```
INFO     [golem.network.p2p.p2pservice       ] Connection to peer failure None.
INFO     [golem.pay                          ] Peer count: 284 
INFO     [golem.pay                          ] Synchronized! 
INFO     [golem.pay                          ] ETH: 0.0 
INFO     [golem.pay                          ] Requesting tETH 
INFO     [golem.network.p2p.p2pservice       ] Connection to peer failure None.
INFO     [golem.network.p2p.p2pservice       ] Connection to peer failure None.
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/ascherik/Git/kascheri12/golem/golem/ethereum/paymentprocessor.py", line 391, in _run
    self.get_ether_from_faucet() and \
  File "/Users/ascherik/Git/kascheri12/golem/golem/ethereum/paymentprocessor.py", line 355, in get_ether_from_faucet
    tETH_faucet_donate(addr)
  File "/Users/ascherik/Git/kascheri12/golem/golem/ethereum/node.py", line 56, in tETH_faucet_donate
    response = requests.get(request)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ascherik/Git/kascheri12/golem/venv/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='188.165.227.180', port=4000): Max retries exceeded with url: /donate/38596092a806f92681cb74e2eaca94d9485f9ebc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10c230eb8>: Failed to establish a new connection: [Errno 60] Operation timed out',))
 
NoneType: None
INFO     [golem.pay                          ] Peer count: 281 
INFO     [golem.pay                          ] ETH: 0.0 
INFO     [golem.pay                          ] Requesting tETH 
INFO     [golem.network.p2p.p2pservice       ] Connection to peer failure None.
```

**Comment by maaktweluit** [comment]
@kascheri12 Thanks for the report!

server `188.165.227.180', port=4000 `is fixed now, please test again.
