### ISSUE TITLE
ERROR    [golem.client] check_payments failed ... peewee.OperationalError: database is locked

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1657]
Ubuntu 16.04
golem-0.9.0 RC

```
ERROR    [golem.client                       ] check_payments failed
Traceback (most recent call last):
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3220, in get
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2363, in next
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2345, in iterate
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Projects/golem/golem/transactions/incomeskeeper.py", line 36, in run_once
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 4988, in get
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3224, in get
golem.model.IncomeDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."created_date", "t1"."modified_date", "t1"."sender_node", "t1"."task", "t1"."subtask", "t1"."transaction", "t1"."block_number", "t1"."value" FROM "income" AS t1 WHERE ((
("t1"."sender_node" = ?) AND ("t1"."subtask" = ?)) AND ("t1"."task" = ?))
PARAMS: ['99fd6aaf7eb342900d2b46d173242526c7847645232906a6fa8e94f7e085cefad3fb3904efd9892cfe03eb64afb8f52914a6c55745ef41aaf62fb4800e6e1903', '255684798306557049004730501721903785333', '6
1ccb411-f94c-4cd6-a872-f03472a8f647']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3830, in execute_sql
sqlite3.OperationalError: database is locked
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Projects/golem/golem/client.py", line 1012, in __do_work
  File "/Projects/golem/golem/client.py", line 924, in check_payments
  File "/Projects/golem/golem/transactions/transactionsystem.py", line 96, in check_payments
  File "/Projects/golem/golem/transactions/incomeskeeper.py", line 42, in run_once
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 5165, in save
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3458, in execute
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 2939, in _execute
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3837, in execute_sql
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3656, in __exit__
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 135, in reraise
  File "/Projects/golem/venv/lib/python3.5/site-packages/peewee.py", line 3830, in execute_sql
peewee.OperationalError: database is locked
```

**Comment by ggruszczynski** [comment]
Hi,
Thank you for feedback.
`sqlite3.OperationalError: database is locked` seems to be a known issue: https://github.com/golemfactory/golem/issues/1605
Hopefully, it is solved in:
https://github.com/golemfactory/golem/pull/1621
This is in a main-develop branch which will be deployed in next release.
