### ISSUE TITLE
WARNING  [apps.core] This is not my subtask

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1662]
This is new. Doesn't seem to be causing any problems yet, but interesting to see because these are my subtasks actually..

MacOS 10.13.1
golem-0.9.0 RC

Task Settings
```
>> tasks show 06b5fad8-9cfe-455f-b96f-652a0abe0d12
bid: 5.0
duration: 72000
id: 06b5fad8-9cfe-455f-b96f-652a0abe0d12
legacy: false
name: Golem Header Task AVI
options:
  compositing: false
  format: AVI
  frame_count: 100
  frames: 1-100
  output_path: Golem Header Task AVI.AVI
  resolution:
  - 300
  - 200
preview: null
progress: 0.00 %
resources:
- /Users/ascherik/Downloads/golem-header.blend
status: Computing
subtask_timeout: 0:40:00
subtasks: 100
time_remaining: 0
time_started: 1510702210.014605
timeout: '20:00:00'
type: Blender

```

Log from golemapp:
```
WARNING  [apps.core                          ] This is not my subtask 325656621659878591848873787001841130828
Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/golem/core/common.py", line 141, in func_wrapper
  File "/Users/golem/Desktop/golem/apps/rendering/task/framerenderingtask.py", line 97, in computation_finished
  File "/Users/golem/Desktop/golem/apps/core/task/coretask.py", line 206, in computation_finished
  File "/Users/golem/Desktop/golem/apps/rendering/task/framerenderingtask.py", line 148, in accept_results
  File "/Users/golem/Desktop/golem/apps/rendering/task/framerenderingtask.py", line 355, in _collect_frames
  File "/Users/golem/Desktop/golem/apps/blender/task/blenderrendertask.py", line 581, in _put_frame_together
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/PIL/Image.py", line 1885, in save
KeyError: 'AVI'
```

This warning is showing up many times, here are 3 examples of the output when I look into the subtask details.
```
>> subtasks show 325656621659878591848873787001841130828
description: 'path_root: /Users/ascherik/Downloads, start_task: 86, end_task: 86,
  total_tasks: 100, outfilebasename: Golem Header Task AVI, scene_file: /golem/resources/golem-header.blend'
node_id: e5b5aa48b886666696f006daeb9b27f5cfa600bf8f50c4b5fff95703fdfd13a011d13e93c548d3bf367f8c305a0b91b3a0bb09a8f7876dcf31208dd048b1abf6
node_ip_address: 35.197.73.6
node_name: kascheri12/501
node_performance: '106.23331921387698'
node_port: 0
progress: 1.0
results:
- /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/Golem
  Header Task AVI_860086.png
status: Finished
stderr: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/325656621659878591848873787001841130828/stderr.log
stdout: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/325656621659878591848873787001841130828/stdout.log
subtask_id: '325656621659878591848873787001841130828'
time_remaining: 0.0
time_started: 1510703948.641224

>> subtasks show 89057389100458194214588606177719052151
description: 'path_root: /Users/ascherik/Downloads, start_task: 87, end_task: 87,
  total_tasks: 100, outfilebasename: Golem Header Task AVI, scene_file: /golem/resources/golem-header.blend'
node_id: e5b5aa48b886666696f006daeb9b27f5cfa600bf8f50c4b5fff95703fdfd13a011d13e93c548d3bf367f8c305a0b91b3a0bb09a8f7876dcf31208dd048b1abf6
node_ip_address: 35.197.73.6
node_name: kascheri12/501
node_performance: '106.23331921387698'
node_port: 0
progress: 1.0
results:
- /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/Golem
  Header Task AVI_870087.png
status: Finished
stderr: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/89057389100458194214588606177719052151/stderr.log
stdout: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/89057389100458194214588606177719052151/stdout.log
subtask_id: '89057389100458194214588606177719052151'
time_remaining: 0.0
time_started: 1510703976.591691

>> subtasks show 223273354485775691484538880183921328473
description: 'path_root: /Users/ascherik/Downloads, start_task: 89, end_task: 89,
  total_tasks: 100, outfilebasename: Golem Header Task AVI, scene_file: /golem/resources/golem-header.blend'
node_id: e5b5aa48b886666696f006daeb9b27f5cfa600bf8f50c4b5fff95703fdfd13a011d13e93c548d3bf367f8c305a0b91b3a0bb09a8f7876dcf31208dd048b1abf6
node_ip_address: 35.197.73.6
node_name: kascheri12/501
node_performance: '106.23331921387698'
node_port: 0
progress: 1.0
results:
- /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/Golem
  Header Task AVI_890089.png
status: Finished
stderr: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/223273354485775691484538880183921328473/stderr.log
stdout: /Users/ascherik/Library/Application Support/golem/default/res/06b5fad8-9cfe-455f-b96f-652a0abe0d12/tmp/223273354485775691484538880183921328473/stdout.log
subtask_id: '223273354485775691484538880183921328473'
time_remaining: 0.0
time_started: 1510704048.550291

```

**Comment by maaktweluit** [comment]
~~relates to #1630~~

Thanks @etam: not related, only the same error message

**Comment by etam** [comment]
@maaktweluit it's not related

@kascheri12 I'm curious about AVI format used here. How did you create this task? Did it work with earlier golem?

The "this is not my subtask" message is a misinterpretation in KeyError exception handling. It needs to be fixed.

**Comment by kascheri12** [comment]
@etam I created the task using a .task file with formatted json task object. I read through Blender documentation that the engine can render files in AVI format so I tried to plug it in to see if it would work. It did not finish to completion, although all the frames were rendered, but not stitched together.
