### ISSUE TITLE
Ran low on tGNT, node requested more, received errors

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1676]
MacOS 10.13.1
golem-0.9.0 RC

```
INFO     [golem.pay                          ] GNT: 105.33333333333333
DEBUG:eth.chain.tx	deserialized tx tx=b'd1da3c71'
INFO     [golem.pay                          ] Batch payments: cef1fd, value: 6.666667
WARNING  [golem.task.taskkeeper              ] Too many tasks from e5b5aa48b886666696f006daeb9b27f5cfa600bf8f50c4b5fff95703fdfd13a011d13e93c548d3bf367f8c305a0b91b3a0bb09a8f7876dcf31208dd048b1abf6, dropping 1 tasks
WARNING  [golem.task.taskkeeper              ] Too many tasks from e5b5aa48b886666696f006daeb9b27f5cfa600bf8f50c4b5fff95703fdfd13a011d13e93c548d3bf367f8c305a0b91b3a0bb09a8f7876dcf31208dd048b1abf6, dropping 1 tasks
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.0030034
INFO     [golem.pay                          ] GNT: 98.66666666666666
INFO     [golem.pay                          ] Requesting tGNT
DEBUG:eth.chain.tx	deserialized tx tx=b'402978a5'
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 392, in _run
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 368, in get_gnt_from_faucet
    
  File "/Users/golem/Desktop/golem/golem/ethereum/client.py", line 79, in send
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/eth.py", line 253, in sendRawTransaction
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/providers/manager.py", line 52, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
NoneType: None
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.0030034
INFO     [golem.pay                          ] GNT: 98.66666666666666
INFO     [golem.pay                          ] Requesting tGNT
DEBUG:eth.chain.tx	deserialized tx tx=b'402978a5'
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 392, in _run
    
  File "/Users/golem/Desktop/golem/golem/ethereum/paymentprocessor.py", line 368, in get_gnt_from_faucet
    
  File "/Users/golem/Desktop/golem/golem/ethereum/client.py", line 79, in send
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/eth.py", line 253, in sendRawTransaction
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/web3/providers/manager.py", line 52, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
NoneType: None
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.00208262
INFO     [golem.pay                          ] GNT: 98.66666666666666
INFO     [golem.pay                          ] Requesting tGNT
DEBUG:eth.chain.tx	deserialized tx tx=b'd55cc5d6'
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.00208262
INFO     [golem.pay                          ] GNT: 1098.6666666666667
INFO     [golem.pay                          ] Checking 0xcef1 tx [2]
INFO     [golem.pay                          ] Confirmed 0xcef1: block aa164da018505958544bba2125fb916b36c0907150d838ef8ee63f4b50f8e40a (1262330), gas 46039, fee 460390000000000
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.0013955
INFO     [golem.pay                          ] GNT: 1098.6666666666667
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.0013955
INFO     [golem.pay                          ] GNT: 1098.6666666666667
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.0013955
INFO     [golem.pay                          ] GNT: 1098.6666666666667
```

**Comment by Krigpl** [comment]
Fixed by #1772
