### ISSUE TITLE
Windows source setup develop error

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1689]
On windows, running from latest source, get the following error:

`python setup.py develop`

```
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    update_variables()
  File "C:\BuildbotWorker\unittest_windows\build\setup_util\setup_commons.py", line 222, in update_variables
    version = get_version()
  File "C:\BuildbotWorker\unittest_windows\build\setup_util\setup_commons.py", line 242, in get_version
    tags = Repo(get_golem_path()).tags
  File "C:\BuildbotWorker\unittest_windows\build\.venv\lib\site-packages\git\repo\base.py", line 352, in tags
    return TagReference.list_items(self)
  File "C:\BuildbotWorker\unittest_windows\build\.venv\lib\site-packages\git\util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "C:\BuildbotWorker\unittest_windows\build\.venv\lib\site-packages\git\refs\symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "C:\BuildbotWorker\unittest_windows\build\.venv\lib\site-packages\git\refs\symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

**Comment by maaktweluit** [comment]
Quick google shows we should update https://github.com/gitpython-developers/GitPython

The latest master is not released yet.

Fixed when running:

`pip install git+https://github.com/gitpython-developers/GitPython`
