### ISSUE TITLE
Hard Code in MacOS Brew installation?

### ISSUE THREAD

**Issue by Kennyl** [golemfactory/clay#1693]
'''golemapp --monitor

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/golemapp.py", line 127, in <module>
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/click/core.py", line 697, in main
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  File "/Users/golem/Desktop/golem/golemapp.py", line 78, in start
  File "/Users/golem/Desktop/golem/golem/core/common.py", line 178, in config_logging
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1226, in mkdir
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 387, in wrapped
PermissionError: [Errno 13] Permission denied: 'logs'
'''
or need create a user golem at MacOS?

**Comment by maaktweluit** [comment]
hey @Kennyl , 

Thank you for the report!
What version of golem are you running? it looks like `0.9.0`
The log folder should be created in `~/.golem` in this version, could you check who owns this folder? the command for that is: `ls -lah ~/.golem`

If you ran golem with `sudo` before you should run it with sudo again or `chown` all folders back to your regular user.
If this is the case also look at `~/Library/Application\ Support/golem`

Hope it helps, you can also poke me on Rocket chat under the same username for any questions :)

**Comment by Kennyl** [comment]
yes current is 0.9.0
Following is permission checking (it seems ok for me)
```
$ls -lah ~/.golem
total 0
drwxr-xr-x    3 apple  staff    96B Nov 22 18:30 .
drwxr-xr-x+ 171 apple  staff   5.3K Nov 23 18:02 ..
drwxr-xr-x    4 apple  staff   128B Nov 22 20:41 logs
🍎:💻 [apple]11:49:05 ~
$ls -lah ~/.golem/logs
total 280
drwxr-xr-x  4 apple  staff   128B Nov 22 20:41 .
drwxr-xr-x  3 apple  staff    96B Nov 22 18:30 ..
-rw-r--r--@ 1 apple  staff   6.0K Nov 22 18:53 .DS_Store
-rw-r--r--@ 1 apple  staff   128K Nov 23 13:42 golem.log
🍎:💻 [apple]11:49:14 ~
$ls -lah ~/Library/Application\ Support/golem
total 32
drwxr-xr-x   10 apple  staff   320B Nov 23 13:22 .
drwx------+ 140 apple  staff   4.4K Nov 22 18:29 ..
drwx------    7 apple  staff   224B Nov 22 18:29 Cache
-rw-r--r--    1 apple  staff   7.0K Nov 22 18:29 Cookies
-rw-r--r--    1 apple  staff     0B Nov 22 18:29 Cookies-journal
drwx------    7 apple  staff   224B Nov 22 18:29 GPUCache
drwx------    2 apple  staff    64B Nov 22 18:29 Local Storage
-rw-------    1 apple  staff    69B Nov 22 18:30 Preferences
-rw-r--r--    1 apple  staff    51B Nov 23 13:22 config.json
drwxr-xr-x    8 apple  staff   256B Nov 22 18:44 default
```
log
```
2017-11-24 11:58:37 ERROR    golem.core.async                    Caught async exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/golem/Desktop/golem/golem/node.py", line 61, in _run
    
  File "/Users/golem/Desktop/golem/golem/node.py", line 99, in _setup_apps
    
  File "/Users/golem/Desktop/golem/golem/environments/environmentsmanager.py", line 32, in add_environment
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/enforce/decorators.py", line 112, in universal
    
  File "/Users/golem/Desktop/golem/golem/docker/environment.py", line 40, in check_support
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/enforce/decorators.py", line 112, in universal
    
  File "/Users/golem/Desktop/golem/golem/docker/environment.py", line 31, in check_docker_images
    
  File "/Users/golem/Desktop/golem/golem/docker/environment.py", line 31, in <genexpr>
    
  File "/Users/golem/Desktop/golem/golem/docker/image.py", line 25, in is_available
    
  File "/Users/golem/Desktop/golem/golem/docker/client.py", line 12, in local_client
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/docker/client.py", line 56, in __init__
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/docker/auth/auth.py", line 188, in load_config
    
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/docker/auth/auth.py", line 130, in parse_auth
    
docker.errors.InvalidConfigFile: Invalid configuration for registry https://index.docker.io/v1/
```

**Comment by maaktweluit** [comment]
Indeed, permissions also look good to me :)

The error posted is related to docker machine, can you stop golem and re-create the machine?

```
# Quit golem if running, then run:
docker-machine rm golem
docker-machine create --driver xhyve golem
```

Maybe you run into #1698 after this.
When this is the case another fix to try is removing all docker working files: stop golem, then `sudo rm -rd ~/.docker` **please note**: this deletes ALL docker images, not only golem related ones.

**Comment by Kennyl** [comment]
after 
``` 
rm -rd ~/.docker
``` 
is okay, but I need discard virtualbox docker image.

and i got same issue as #1659

given ```{error:{}}``` json when http://localhost:3292/api or http://localhost:3292
