### ISSUE TITLE
Error setting up source on clean windows

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1707]
When setting up windows from source with @ederenn this error shows when running `pip install -r requirements.txt`

The error is when installing `zope.interface`
```
Exception:
Traceback (most recent call last):
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\ederenn\projects\golem-env\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 4: invalid continuation byte
```

This issue seems related: https://github.com/zopefoundation/zope.interface/issues/76, but updating zope.interface only silences the issue, `Twisted` has the same error.

**Comment by Krigpl** [comment]
FWIW, https://github.com/pypa/pip/issues/4251#issuecomment-279117184 makes this error go away (it's a workaround, not a solution though)

**Comment by mfranciszkiewicz** [comment]
For anyone encountering this issue, here is a quick workaround:
`pip\compat\__init__.py:70`
```
if sys.version_info >= (3,):
    def console_to_str(s):
        try:
            return s.decode(sys.__stdout__.encoding)
        except UnicodeDecodeError:
            try:
                return s.decode('utf_8')
            except UnicodeDecodeError:
                from ctypes import cdll
                os_encoding = 'cp' + str(cdll.kernel32.GetACP())
                return s.decode(os_encoding)
```

**Comment by Elfoniok** [comment]
Actually for me worked
```
import locale
def console_to_str(s):
    return s.decode(locale.getpreferredencoding() or "utf-8", 'replace')
```

**Comment by badb** [comment]
It's not a problem related to  Golem itself. 

@maaktweluit Can you please add this solution to [Common problems](https://github.com/golemfactory/golem/wiki/Common-problems) wiki section and close this issue? Or is it still blocking mulit-os tests?

**Comment by maaktweluit** [comment]
@badb Yes, i'll add it to this page and then close the issue.
We applied the "fix" where we needed for multi-OS and it is no longer blocking.

**Comment by maaktweluit** [comment]
Added here after updating the page to the new headers and template: https://github.com/golemfactory/golem/wiki/Common-problems#unicodedecodeerror-utf-8-codec-can-t-decode
