### ISSUE TITLE
umsgpack.InvalidStringException: unpacked string is invalid utf-8, Failed to execute golemapp

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1716]
on Windows, source version
Golem was running two tasks in timeout, no actions on my side were taken, received fatal error pop-up "Failed to execute golemapp" for no reason.
Around that time, on one of the seed servers, git develop version of Golem was launched as well

```Traceback (most recent call last):
File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 595, in _unpack_string
    return bytes.decode(data, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 9: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 104, in unserialize
    raw_msgs = self._serializer.unserialize(payload)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 302, in unserialize
    msgs.append(umsgpack.unpackb(data))
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 867, in _unpackb3
    return _unpack(io.BytesIO(s), options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in _unpack_array
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 652, in <listcomp>
    return [_unpack(fp, options) for i in xrange(length)]
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 672, in _unpack_map
    k = _unpack(fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 693, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\umsgpack.py", line 599, in _unpack_string
    raise InvalidStringException("unpacked string is invalid utf-8")
umsgpack.InvalidStringException: unpacked string is invalid utf-8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\autobahn\wamp\websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\autobahn\wamp\serializer.py", line 106, in unserialize
    raise ProtocolError("invalid serialization of WAMP message ({0})".format(e))
autobahn.wamp.exception.ProtocolError: invalid serialization of WAMP message (unpacked string is invalid utf-8)
```

**Comment by ederenn** [comment]
related to 
https://github.com/golemfactory/golem/issues/1616

**Comment by maaktweluit** [comment]
@ederenn are you still able to reproduce this issue? else i think we can close it

**Comment by ederenn** [comment]
not seen recently
