### ISSUE TITLE
Docker machine is not available: '{0169423F-46B4-CDE9-91AF-1E9D5B6CD945}

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1739]
encountered on Windows, source version

```2017-12-08 11:57:29 DEBUG    golem.docker.manager                b'docker_machine_command: ['docker', '--help']'
2017-12-08 11:57:29 DEBUG    golem.docker.manager                b'docker_machine_command_output: b'\nUsage:\tdocker COMMAND\n\nA self-sufficient runtime for containers\n\nOptions:\n      --config string      Location of client config files (default\n                           "C:\\Users\\ederenn\\.docker")\n  -D, --debug              Enable debug mode\n      --help               Print usage\n  -H, --host list          Daemon socket(s) to connect to\n  -l, --log-level string   Set the logging level\n                           ("debug"|"info"|"warn"|"error"|"fatal")\n                           (default "info")\n      --tls                Use TLS; implied by --tlsverify\n      --tlscacert string   Trust certs signed only by this CA (default\n                           "C:\\Users\\ederenn\\.docker\\ca.pem")\n      --tlscert string     Path to TLS certificate file (default\n                           "C:\\Users\\ederenn\\.docker\\cert.pem")\n      --tlskey string      Path to TLS key file (default\n                           "C:\\Users\\ederenn\\.docker\\key.pem")\n      --tlsverify          Use TLS and verify the remote\n  -v, --version            Print version information and quit\n\nManagement Commands:\n  config      Manage Docker configs\n  container   Manage containers\n  image       Manage images\n  network     Manage networks\n  node        Manage Swarm nodes\n  plugin      Manage plugins\n  secret      Manage Docker secrets\n  service     Manage services\n  stack       Manage Docker stacks\n  swarm       Manage Swarm\n  system      Manage Docker\n  volume      Manage volumes\n\nCommands:\n  attach      Attach local standard input, output, and error streams to a running container\n  build       Build an image from a Dockerfile\n  commit      Create a new image from a container\'s changes\n  cp          Copy files/folders between a container and the local filesystem\n  create      Create a new container\n  diff        Inspect changes to files or directories on a container\'s filesystem\n  events      Get real time events from the server\n  exec        Run a command in a running container\n  export      Export a container\'s filesystem as a tar archive\n  history     Show the history of an image\n  images      List images\n  import      Import the contents from a tarball to create a filesystem image\n  info        Display system-wide information\n  inspect     Return low-level information on Docker objects\n  kill        Kill one or more running containers\n  load        Load an image from a tar archive or STDIN\n  login       Log in to a Docker registry\n  logout      Log out from a Docker registry\n  logs        Fetch the logs of a container\n  pause       Pause all processes within one or more containers\n  port        List port mappings or a specific mapping for the container\n  ps          List containers\n  pull        Pull an image or a repository from a registry\n  push        Push an image or a repository to a registry\n  rename      Rename a container\n  restart     Restart one or more containers\n  rm          Remove one or more containers\n  rmi         Remove one or more images\n  run         Run a command in a new container\n  save        Save one or more images to a tar archive (streamed to STDOUT by default)\n  search      Search the Docker Hub for images\n  start       Start one or more stopped containers\n  stats       Display a live stream of container(s) resource usage statistics\n  stop        Stop one or more running containers\n  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE\n  top         Display the running processes of a container\n  unpause     Unpause all processes within one or more containers\n  update      Update configuration of one or more containers\n  version     Show the Docker version information\n  wait        Block until one or more containers stop, then print their exit codes\n\nRun \'docker COMMAND --help\' for more information on a command.\n''
2017-12-08 11:57:29 WARNING  golem.docker.manager                b"Docker machine is not available: '{0169423F-46B4-CDE9-91AF-1E9D5B6CD945}'"
2017-12-08 11:57:29 DEBUG    golem.docker.manager                b'docker_machine_command: ['docker', 'images', '-q', 'golemfactory/base:1.2']'
2017-12-08 11:57:29 ERROR    golem.docker.manager                b"Docker: error pulling images: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1."
2017-12-08 11:57:29 DEBUG    golem.docker.manager                b'docker_machine_command: ['docker', 'images', '-q', 'golemfactory/base:1.2']'
2017-12-08 11:57:30 ERROR    golem.core.async                    b'Caught async exception:\nTraceback (most recent call last):
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\_threads\_threadworker.py", line 46, in work
    task()
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\_threads\_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "C:\Users\ederenn\Projects\golem\golem\node.py", line 60, in _run
    self._setup_docker()
  File "C:\Users\ederenn\Projects\golem\golem\node.py", line 91, in _setup_docker
    docker_manager.check_environment()
  File "C:\Users\ederenn\Projects\golem\golem\docker\manager.py", line 146, in check_environment
    self.build_images()
  File "C:\Users\ederenn\Projects\golem\golem\docker\manager.py", line 313, in build_images
    if not cls.command('images', args=[version]):
  File "C:\Users\ederenn\Projects\golem\golem\docker\manager.py", line 299, in command
    **params)
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\ederenn\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1.
'
```

**Comment by badb** [comment]
Is probably related to: https://github.com/golemfactory/golem/issues/1786
