### ISSUE TITLE
'Message error: invalid timestamp: 1512736858.895651'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1740]
Windows, source version, encountered several times

golem app is running in console window, electron server as well, when trying to open GUI golem app froze. 
Nothing was showing in console window or in logs - after hitting ctrl c once in console window with golemapp it started running again (without terminating the proces)
in logs appeared 'Message error: invalid timestamp: 1512736858.895651' multiple times

``` 2017-12-08 13:40:35 INFO     golem.network.transport.session     b'Disconnecting 188.165.220.221 : 45694 reason: REASON.ProtocolVersion'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512736858.895651'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512736858.900127'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512736863.006102'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512736864.39275'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512737104.890427'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512737104.895129'
2017-12-08 14:30:55 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512737104.897362'
(...)
2017-12-08 14:30:56 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512737878.836268'
2017-12-08 14:30:56 INFO     golem.network.transport.message     b'Message error: invalid timestamp: 1512738018.041325'
2017-12-08 14:30:56 INFO     golem.network.transport.session     b'Disconnecting 79.219.73.156 : 40854 reason: REASON.ProtocolVersion'
2017-12-08 14:30:56 INFO     golem.network.p2p.peersession       b'Starting peer session '188.165.227.180':40102'
2017-12-08 14:30:56 INFO     golem.network.p2p.p2pservice        b'Adding peer 'c28ad8e156524f622f5dcb0dc3fe55fa5b61a825a642b80db46b87d69423e7645fa324e093104b301723b07afbce4328112181e1aa1b51b8eaf6752665ee3dd5', key id difficulty: 1'```

later in the day, appeared again
full stack in link below

https://drive.google.com/open?id=1-woVBYbppcnwk--1vqTgqIx9uG3bmNEo

**Comment by jiivan** [comment]
```python
>>> datetime.datetime.utcfromtimestamp(1512736858.895651)
datetime.datetime(2017, 12, 8, 12, 40, 58, 895651)

>>> datetime.datetime.utcfromtimestamp(1512736858.895651) + datetime.timedelta(hours=2)
datetime.datetime(2017, 12, 8, 14, 40, 58, 895651)
```

**Comment by jiivan** [comment]
Standard `FUTURE_TIME_TOLERANCE` is 5 minutes. Received messages were 10 minutes from the future.

**Comment by jiivan** [comment]
Looks like fixed in golem-messages. Please re-open if it appears again.

**Comment by Slavenin** [comment]
It appears again.
My log contains ~6.5 mb such messages

> 2018-07-26 11:08:59 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:09:10 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:09:20 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:09:30 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:09:41 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:09:52 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:10:02 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 
> 2018-07-26 11:10:14 WARNING  golem.task.taskkeeper               Wrong task header received: Deadline already passed 
>  task_id = 11b28f3e-904d-11e8-8c77-65684fed3648 
>  node name = GeeXiew 

and every second appending new

**Comment by ederenn** [comment]
encountered again in 0.17.0

```2018-08-13 12:31:13 INFO     golem.network.transport.session     Disconnecting '99.249.44.83':40102 reason: <REASON.BadProtocol: 'bad_protocol'>
2018-08-13 12:31:13 WARNING  golem.task.taskserver               Wrong task header received
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 313, in add_task_header
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskbase.py", line 235, in validate
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskbase.py", line 156, in validate
ValueError: Deadline already passed 
 task_id = dfe02036-9ed0-11e8-8b53-d276138057ae 
 node name = waiKail 
```



```
2018-08-13 12:47:45 WARNING  golem.task.taskserver               Wrong task header received
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 313, in add_task_header
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskbase.py", line 235, in validate
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskbase.py", line 156, in validate
ValueError: Deadline already passed 
 task_id = 364deb08-9ee2-11e8-ad0e-380f9240faff 
 node name = Zagreu5 
```

**Comment by etam** [comment]
I'll make a new issue for that, because it seems it's different

**Comment by etam** [comment]
#3230
