### ISSUE TITLE
'NoneType' object has no attribute 'items' in web3/formatters.py output_block_formatter

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1761]
```
(golem) [15:53] etam@etam-komp:~/code/github/golemfactory/golem (develop *$=)> ./golemapp.py 
INFO     [golem.version                      ] GOLEM Version: 0.9.1 
INFO     [golem.version                      ] P2P Protocol Version: 18 
INFO     [golem.version                      ] Task Protocol Version: 18 
INFO     [golem.pay                          ] Node Ethereum address: 0xcb0eb9b07a51daafd8a09b34bc6bac3f01f6bab6 
ERROR    [golem.ethereum                     ] Error downloading node list: Expecting value: line 1 column 1 (char 0) 
INFO     [golem.ethereum                     ] GETH: connecting to remote RPC interface at http://94.23.17.170:55555 
Traceback (most recent call last):
  File "./golemapp.py", line 147, in <module>
    start()
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./golemapp.py", line 104, in start
    geth_port=geth_port, **config)
  File "/home/etam/code/github/golemfactory/golem/golem/node.py", line 30, in __init__
    **config_overrides
  File "/home/etam/code/github/golemfactory/golem/golem/client.py", line 174, in __init__
    start_geth=start_geth
  File "/home/etam/code/github/golemfactory/golem/golem/transactions/ethereum/ethereumtransactionsystem.py", line 42, in __init__
    client=Client(datadir, port, start_geth),
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/client.py", line 21, in __init__
    Client.node.start(port)
  File "/home/etam/code/github/golemfactory/golem/golem/report.py", line 117, in wrapper
    return func(*args, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/node.py", line 142, in start
    identified_chain = self.identify_chain()
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/node.py", line 180, in identify_chain
    genesis = self.web3.eth.getBlock(0)['hash']
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/web3/utils/functional.py", line 15, in inner
    return formatter(value)
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/eth_utils/functional.py", line 16, in <lambda>
    return lambda x: f(g(x))
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/etam/.virtualenvs/golem/lib/python3.6/site-packages/web3/formatters.py", line 213, in output_block_formatter
    for key, value in block.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

This happened only once, so it might be triggered if there is a problem in talking with geth.

**Comment by mfranciszkiewicz** [comment]
Fixed in https://github.com/golemfactory/golem/pull/1778
