### ISSUE TITLE
Money gone for a tick

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1769]
While testing branch `b0.10.0` I see my finds, ETH or GNT becoming empty for one or more ticks.

Tested this on source and binaries, mac and linux both have the same result.

ETH gone:
```
2017-12-15 12:28:35 INFO     golem.pay                           Peer count: 311 
2017-12-15 12:28:35 INFO     golem.pay                           ETH: 0.01581288 
2017-12-15 12:28:36 INFO     golem.pay                           GNT: 1034.0833333333333 
2017-12-15 12:28:48 INFO     golem.pay                           Peer count: 312 
2017-12-15 12:28:48 ERROR    golem.ethereum                      Ethereum RPC: {'message': 'missing trie node 5da8866484b97dcac37baa6b54e3474e6e01954488564832e5ca1ab5711e2fe4 (path 03030202)', 'code': -32000} 
2017-12-15 12:28:48 INFO     golem.pay                           ETH: 0.0 
2017-12-15 12:28:48 INFO     golem.pay                           Requesting tETH 
2017-12-15 12:28:49 ERROR    golem.ethereum                      tETH Faucet error code 400 
2017-12-15 12:29:01 INFO     golem.pay                           Peer count: 311 
2017-12-15 12:29:02 INFO     golem.pay                           ETH: 0.01581288 
2017-12-15 12:29:02 INFO     golem.pay                           GNT: 1034.0833333333333
```

GNT gone:
```
2017-12-15 13:58:16 INFO     golem.pay                           Peer count: 315
2017-12-15 13:58:16 INFO     golem.pay                           ETH: 0.00164276
2017-12-15 13:58:16 INFO     golem.pay                           GNT: 0.0
2017-12-15 13:58:16 INFO     golem.pay                           Requesting tGNT
2017-12-15 13:58:17 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner

  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork

--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/paymentprocessor.py", line 392, in _run

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/paymentprocessor.py", line 368, in get_gnt_from_faucet

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/client.py", line 79, in send

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/eth.py", line 253, in sendRawTransaction

  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/providers/manager.py", line 52, in request_blocking

builtins.ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

**Comment by ederenn** [comment]
On Windows branch b.0.10.0 encountered the same - buouncing GNT, between -5 and 4135,25
several times

``````
2017-12-14 15:01:12 ERROR    golem.ethereum                      b"Ethereum RPC: {'code': -32000, 'message': 'missing trie node e7ae9a4ce7845f21b1a372ee8a0ce64b0fcb59e8cc336b0d83ac9735355e5556 (path 0f000c0c)'} "```
