### ISSUE TITLE
Error: database is locked

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#1775]
```
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 456 s 
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 443 s 
ERROR    [golem.network.history              ] Cannot log message: SubtaskPayment(timestamp=1513608253.070525, encrypted=True, sig=b't\xfd\x95K<\xd2\x01\xba!\x10^\xc3BS\x019@\xda\xd1)\xea?\xa2\xf9.&K\xfd\xe6\x02\xc8\xe8)\x85\t6\xa0\t\x8c+B\xf8[<\xaf\xe6\x11\x08\xf0a\x89\x18\x02\x8e/\xb0\x17\xad\xd1q\x0e\x9ffm\x00', slots=[['subtask_id', '317965324641458339017115498666206926375'], ['reward', 33333333333333334], ['transaction_id', '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963'], ['block_number', 1436526]])
Exception in thread Thread-74:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

Exception in thread Thread-76:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

Exception in thread Thread-78:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

INFO     [golem.network.p2p.p2pservice       ] Connecting to peer '94.23.57.58':40104
INFO     [golem.network.p2p.peersession      ] Starting peer session '94.23.57.58':40104
INFO     [golem.network.p2p.p2pservice       ] Adding peer '10be7dc2ba86f7defbd71c31156a1eee125c8cba59c0014399883a8fb9452ec942859ac8280a1d52b94f367d511ec8628984c592abf49e037f4c3f06fe972690', key id difficulty: 0
INFO     [golem.network.transport.session    ] Disconnect reason: REASON.Bootstrap
INFO     [golem.network.transport.session    ] Closing 94.23.57.58 : 40104
INFO     [golem.pay                          ] Peer count: 25 
Exception in thread Thread-82:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 430 s 
Exception in thread Thread-86:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 417 s 
ERROR    [golem.network.history              ] Cannot log message: SubtaskPayment(timestamp=1513608283.027797, encrypted=True, sig=b'\t\xeb\x17\xa5\x9e\xb2d,`\x94\xf9}) \tG\x95>\xdab\xf4\xcc1\x0e\xc2\t\x84*pO{\xe55h\xf1*\xc9#B\xd6\x8b\xd5R\xad\xa0\xe3v\x9d\x0cvl\x8e\x11nO\xaazAp\xbe\xcdA0[\x00', slots=[['subtask_id', '317965324641458339017115498666206926375'], ['reward', 33333333333333334], ['transaction_id', '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963'], ['block_number', 1436526]])
WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '147841919028710565816649958338723937646' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 404 s 
WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '107924207671022946536743015656105657415' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
INFO     [golem.network.p2p.p2pservice       ] add peer to incoming 'Rebbu Bootstrap Go' '94.23.57.58' 0 ('10be7dc2ba86f7defbd71c31156a1eee125c8cba59c0014399883a8fb9452ec942859ac8280a1d52b94f367d511ec8628984c592abf49e037f4c3f06fe972690')
WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '79022882564455999314189263554826149973' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
Exception in thread Thread-107:
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chfast/Projects/golem/golem/golem/task/taskserver.py", line 488, in reward_for_subtask_paid
    value=expected_income.value,
  File "/home/chfast/Projects/golem/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
    value=value
  File "/home/chfast/Projects/golem/golem/golem/transactions/incomeskeeper.py", line 65, in received
    expected_income.delete_instance()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 5155, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3556, in execute
    return self.database.rows_affected(self._execute())
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/chfast/.virtualenvs/golem/lib/python3.5/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '321261301196953748557975010656144373118' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '218122473891143680754969565633408638340' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
WARNING  [golem.task.taskserver              ] Received unexpected payment confirmation message for subtask '32264236795973905991021717687837855713' 
 (value: 16666666666666667 GNT, transaction_id: '654c1ebca998d80c395818711e54a24560ef3685a722688689e76e4c9cb78963', block number:1436526)
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 391 s 
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288 
INFO     [golem.pay                          ] GNT: 1000.8 
INFO     [golem.pay                          ] Next sendout in 378 s 
INFO     [golem.network.p2p.p2pservice       ] Connecting to peer '94.23.57.58':40104
INFO     [golem.network.p2p.peersession      ] Starting peer session '94.23.57.58':40104
INFO     [golem.network.p2p.p2pservice       ] Adding peer '10be7dc2ba86f7defbd71c31156a1eee125c8cba59c0014399883a8fb9452ec942859ac8280a1d52b94f367d511ec8628984c592abf49e037f4c3f06fe972690', key id difficulty: 0
INFO     [golem.network.transport.session    ] Disconnect reason: REASON.Bootstrap
INFO     [golem.network.transport.session    ] Closing 94.23.57.58 : 40104
INFO     [golem.network.p2p.p2pservice       ] add peer to incoming 'Rebbu Bootstrap Go' '94.23.57.58' 0 ('10be7dc2ba86f7defbd71c31156a1eee125c8cba59c0014399883a8fb9452ec942859ac8280a1d52b94f367d511ec8628984c592abf49e037f4c3f06fe972690')
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] ETH: 0.02901288
```

**Comment by jiivan** [comment]
https://stackoverflow.com/questions/21921712/concurrent-writes-with-sqlite-and-peewee#21949046

I may add that, from my experience, this lock fails under heavy load and database ends in unusable state. It may be a good idea to allow only one process/thread to write to db.

**Comment by mfranciszkiewicz** [comment]
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#sqliteq

**Comment by Elfoniok** [comment]
For the record, this is explanation of this error. Looks like simultaneously drop and select cause this:
http://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked

**Comment by Elfoniok** [comment]
Actually from this:
https://github.com/mackyle/sqlite/blob/58f507c7a066d40b077fe8c89fc36aa3a7a88e00/src/main.c#L1415
It looks like we are getting SQLITE_BUSY error

**Comment by Elfoniok** [comment]
Fix is here:
https://github.com/golemfactory/golem/pull/1925
For now we will retry operation when DB is busy, at later time it might be good to actually decrease concurrency in accessing sqlite writes in golem.
