### ISSUE TITLE
year is out of range

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#1798]
```
Dec 21 10:22:07 drohlum golemapp[5207]: INFO     [golem.network.p2p.peersession      ] Starting peer session '194.181.80.91':22823
Dec 21 10:22:08 drohlum golemapp[5207]: INFO     [golem.network.p2p.peersession      ] Failed to decrypt message from '194.181.80.91':22823, maybe it's not encrypted? ECIESDecryptionError('wrong ecies header',)
Dec 21 10:22:08 drohlum golemapp[5207]: Unhandled Error
Dec 21 10:22:08 drohlum golemapp[5207]: Traceback (most recent call last):
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]: --- <exception caught here> ---
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 486, in dataReceived
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 510, in _interpret
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 590, in _data_to_messages
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/src/golem-messages/golem_messages/message.py", line 253, in deserialize
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/src/golem-messages/golem_messages/message.py", line 25, in verify_time
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]: builtins.ValueError: year is out of range
Dec 21 10:22:08 drohlum golemapp[5207]: CRITICAL [twisted                            ] Unhandled Error
Dec 21 10:22:08 drohlum golemapp[5207]: Traceback (most recent call last):
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]: --- <exception caught here> ---
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 486, in dataReceived
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 510, in _interpret
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 590, in _data_to_messages
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/src/golem-messages/golem_messages/message.py", line 253, in deserialize
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]:   File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/src/golem-messages/golem_messages/message.py", line 25, in verify_time
Dec 21 10:22:08 drohlum golemapp[5207]:     
Dec 21 10:22:08 drohlum golemapp[5207]: builtins.ValueError: year is out of range
```
golem 0.10.0, but I think I've seen it before.

**Comment by etam** [comment]
This is also corelated with this:
```
Dec 21 16:29:38 drohlum golem-bootstrap-go[17327]: Peer connection from 200.69.141.134:58738
Dec 21 16:29:38 drohlum golem-bootstrap-go[17327]: Peer session error: unsupported msg type 55324
```

**Comment by badb** [comment]
I believe this should be solved with new golem-messages updates. @jiivan Can you confirm?

**Comment by jiivan** [comment]
`ValueError` will be handled in next library release

Unsupported msg type can be either deserialization problem (library changed significantly since boostrap-go release) or a malicious message. There is no such type as `55324`
