### ISSUE TITLE
'NoneType' object has no attribute 'task_keeper'

### ISSUE THREAD

**Issue by Slavenin** [golemfactory/clay#1806]
Hi! I can not run golem on w10. All stop on "golem starting" stage. Client version latest (0.10)  In log:
```
2017-12-25 10:48:13 WARNING  golem.appconfig                     b"Can't open file C:\\Users\\mbaru\\AppData\\Local\\golem\\golem\\SimpleEnv\\minilight.ini: [Errno 2] No such file or directory: 'C:\\\\Users\\\\mbaru\\\\AppData\\\\Local\\\\golem\\\\golem\\\\SimpleEnv\\\\minilight.ini'"
2017-12-25 10:48:13 INFO     golem.ethereum                      b'geth 1.7: C:\\Program Files\\Geth\\geth.EXE'
2017-12-25 10:48:13 INFO     golem.ethereum                      b'init file: C:\\Program Files (x86)\\Golem\\golem\\ethereum\\rinkeby.json'
2017-12-25 10:48:14 INFO     golem.ethereum                      b'Starting Ethereum node: `C:\\Program Files\\Geth\\geth.EXE --datadir=C:\\Users\\mbaru\\AppData\\Local\\golem\\golem\\default\\ethereum\\rinkeby --cache=32 --syncmode=light --rinkeby --port=50507 --ipcpath=C:\\Users\\mbaru\\AppData\\Local\\Temp\\rinkeby-50507 --nousb --verbosity 3`'
2017-12-25 10:48:16 INFO     golem.ethereum                      b'rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177)'
2017-12-25 10:48:16 INFO     golem.ethereum                      b'Node started in 2.3000000000000007s: `C:\Program Files\Geth\geth.EXE --datadir=C:\Users\mbaru\AppData\Local\golem\golem\default\ethereum\rinkeby --cache=32 --syncmode=light --rinkeby --port=50507 --ipcpath=C:\Users\mbaru\AppData\Local\Temp\rinkeby-50507 --nousb --verbosity 3`'
2017-12-25 10:48:16 INFO     twisted                             File permissions on node public key fixed!
2017-12-25 10:48:16 INFO     twisted                             File permissions on node private key fixed!
2017-12-25 10:48:16 INFO     twisted                             No extra node router roles
2017-12-25 10:48:16 INFO     twisted                             Using default node shutdown triggers ['shutdown_on_worker_exit']
2017-12-25 10:48:16 INFO     twisted                             Configuring node from local configuration ...
2017-12-25 10:48:16 INFO     twisted                             Starting 1 workers ...
2017-12-25 10:48:16 INFO     twisted                             Router worker "worker-001" starting ..
2017-12-25 10:48:29 INFO     twisted                             Failed to import scrypt. This is not a fatal error but does
2017-12-25 10:48:29 INFO     twisted                             mean that you cannot create or decrypt privkey jsons that use
2017-12-25 10:48:29 INFO     twisted                             scrypt
2017-12-25 10:48:29 INFO     twisted                             CROSSBAR_RICH_LOGGING_ENABLE=True
2017-12-25 10:48:29 INFO     twisted                             {"python": "CPython", "worker_title": "Router", "pid": 3084, "worker_id": "worker-001", "namespace": "crossbar.worker.process.run", "log_time": 1514188109.7406342, "reactor": "IOCPReactor", "level": "info", "text": "Router worker \"worker-001\" process 3084 starting on CPython-IOCPReactor .."}
2017-12-25 10:48:30 INFO     twisted                             {"session_id": 4797454649084819, "text": "Router worker \"worker-001\" session 4797454649084819 initializing ..", "worker_id": "worker-001", "namespace": "crossbar.worker.worker.NativeWorkerSession", "log_time": 1514188110.5816154, "level": "info"}
2017-12-25 10:48:30 INFO     twisted                             Router worker "worker-001" process 10024 started
2017-12-25 10:48:30 INFO     twisted                             {"log_time": 1514188110.7127602, "text": "Router worker \"worker-001\" session ready", "level": "info", "worker_id": "worker-001", "namespace": "crossbar.worker.worker.NativeWorkerSession"}
2017-12-25 10:48:30 INFO     twisted                             Router 'worker-001': realm 'realm-001' (named 'golem') started
2017-12-25 10:48:30 INFO     twisted                             {"log_time": 1514188110.7192795, "text": "Realm 'golem' started", "level": "info", "realm": "golem", "namespace": "crossbar.worker.worker.NativeWorkerSession"}
2017-12-25 10:48:30 INFO     twisted                             Router 'worker-001': role 'role-001' (named 'anonymous') started on realm 'realm-001'
2017-12-25 10:48:30 INFO     twisted                             {"role_id": "role-001", "realm_id": "realm-001", "text": "role role-001 on realm realm-001 started", "namespace": "crossbar.worker.worker.NativeWorkerSession", "log_time": 1514188110.7222867, "level": "info", "role_config": {"permissions": [{"allow": {"call": true, "register": true, "publish": true, "subscribe": true}, "uri": "*"}], "name": "anonymous"}}
2017-12-25 10:48:30 INFO     twisted                             {"log_text": "WampWebSocketServerFactory starting on 61000", "time": 1514188110.7283018, "namespace": "log_legacy", "log_time": 1514188110.7283018, "text": "WampWebSocketServerFactory starting on 61000", "message": ["WampWebSocketServerFactory starting on 61000"], "isError": 0, "level": "info", "system": "-"}
2017-12-25 10:48:30 INFO     twisted                             Router 'worker-001': transport 'transport-001' started
2017-12-25 10:48:30 INFO     twisted                             Local node configuration applied successfully!
2017-12-25 10:48:30 INFO     twisted                             {"session_id": 4186599452500246, "text": ">>>>> session 4186599452500246 JOINED \"golem\" >>>>>\n\n{{'authid': 'RXMY-C7C9-3W9H-9VTK-GA77-76UV', 'transport': {{'type': 'websocket', 'websocket_extensions_in_use': [], 'cbtid': None, 'protocol': 'wamp.2.msgpack.batched', 'peer': 'tcp4:127.0.0.1:50541', 'http_headers_sent': {{}}, 'http_headers_received': {{'sec-websocket-protocol': 'wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json', 'sec-websocket-key': 'x8XKx6QCQAO4QqzQU07t7g==', 'cache-control': 'no-cache', 'sec-websocket-version': '13', 'upgrade': 'WebSocket', 'sec-websocket-extensions': 'permessage-deflate; client_no_context_takeover; client_max_window_bits', 'pragma': 'no-cache', 'connection': 'Upgrade', 'user-agent': 'AutobahnPython/0.18.1', 'host': '127.0.0.1:61000'}}}}, 'authmethod': 'anonymous', 'session': 4186599452500246, 'authrole': 'anonymous', 'authprovider': 'static'}}\n", "realm": "golem", "namespace": "crossbar.router.router.Router", "log_time": 1514188110.7939768, "level": "info", "details": {"authid": "RXMY-C7C9-3W9H-9VTK-GA77-76UV", "transport": {"type": "websocket", "websocket_extensions_in_use": [], "cbtid": null, "protocol": "wamp.2.msgpack.batched", "peer": "tcp4:127.0.0.1:50541", "http_headers_sent": {}, "http_headers_received": {"sec-websocket-protocol": "wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json", "sec-websocket-key": "x8XKx6QCQAO4QqzQU07t7g==", "cache-control": "no-cache", "sec-websocket-version": "13", "upgrade": "WebSocket", "sec-websocket-extensions": "permessage-deflate; client_no_context_takeover; client_max_window_bits", "pragma": "no-cache", "connection": "Upgrade", "user-agent": "AutobahnPython/0.18.1", "host": "127.0.0.1:61000"}}, "authmethod": "anonymous", "session": 4186599452500246, "authrole": "anonymous", "authprovider": "static"}}
2017-12-25 10:48:31 ERROR    twisted                             AttributeError: 'NoneType' object has no attribute 'task_keeper': Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\Program Files\Python35\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\Program Files\Python35\lib\site-packages\autobahn\wamp\protocol.py", line 883, in onMessage
    
  File "C:\Program Files\Python35\lib\site-packages\txaio\tx.py", line 408, in as_future
    
--- <exception caught here> ---
  File "C:\Program Files\Python35\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\golem\golem\client.py", line 646, in get_task_stats
    
  File "C:\golem\golem\client.py", line 617, in get_task_count
    
builtins.AttributeError: 'NoneType' object has no attribute 'task_keeper'

2017-12-25 10:48:31 INFO     twisted                             {"session_id": 7982754641358373, "text": ">>>>> session 7982754641358373 JOINED \"golem\" >>>>>\n\n{{'authid': 'XAJ4-65GM-XRA9-RRER-WTVY-E9VS', 'transport': {{'type': 'websocket', 'websocket_extensions_in_use': [], 'cbtid': None, 'protocol': 'wamp.2.msgpack', 'peer': 'tcp4:127.0.0.1:50549', 'http_headers_sent': {{}}, 'http_headers_received': {{'sec-websocket-key': 'GJ9+ToczyalS0cRGVJS1/A==', 'sec-websocket-version': '13', 'upgrade': 'websocket', 'origin': 'file://', 'connection': 'Upgrade', 'accept-language': 'ru', 'sec-websocket-protocol': 'wamp.2.msgpack, wamp.2.json', 'accept-encoding': 'gzip, deflate', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) golem/0.1.5 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36', 'host': '127.0.0.1:61000'}}}}, 'authmethod': 'anonymous', 'session': 7982754641358373, 'authrole': 'anonymous', 'authprovider': 'static'}}\n", "realm": "golem", "namespace": "crossbar.router.router.Router", "log_time": 1514188111.375021, "level": "info", "details": {"authid": "XAJ4-65GM-XRA9-RRER-WTVY-E9VS", "transport": {"type": "websocket", "websocket_extensions_in_use": [], "cbtid": null, "protocol": "wamp.2.msgpack", "peer": "tcp4:127.0.0.1:50549", "http_headers_sent": {}, "http_headers_received": {"sec-websocket-key": "GJ9+ToczyalS0cRGVJS1/A==", "sec-websocket-version": "13", "upgrade": "websocket", "origin": "file://", "connection": "Upgrade", "accept-language": "ru", "sec-websocket-protocol": "wamp.2.msgpack, wamp.2.json", "accept-encoding": "gzip, deflate", "sec-websocket-extensions": "permessage-deflate; client_max_window_bits", "pragma": "no-cache", "cache-control": "no-cache", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) golem/0.1.5 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36", "host": "127.0.0.1:61000"}}, "authmethod": "anonymous", "session": 7982754641358373, "authrole": "anonymous", "authprovider": "static"}}
2017-12-25 10:48:43 ERROR    golem.docker.manager                b"DockerMachine: failed to start the VM: Command '['docker-machine', 'start', 'golem']' returned non-zero exit status 1"
2017-12-25 10:48:43 ERROR    golem.core.async                    b'Caught async exception:\nTraceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inner
    
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    
  File "C:\Program Files\Python35\lib\site-packages\twisted\_threads\_threadworker.py", line 46, in work
    
  File "C:\Program Files\Python35\lib\site-packages\twisted\_threads\_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "C:\Program Files\Python35\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    
  File "C:\Program Files\Python35\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    
  File "C:\Program Files\Python35\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    
  File "C:\Program Files\Python35\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    
  File "C:\golem\gui\startapp.py", line 106, in session_ready
    
  File "C:\golem\golem\docker\manager.py", line 139, in check_environment
    
  File "C:\golem\golem\docker\manager.py", line 410, in _set_docker_machine_env
    
  File "C:\golem\golem\docker\manager.py", line 301, in command
    
  File "C:\Program Files\Python35\lib\subprocess.py", line 316, in check_output
    
  File "C:\Program Files\Python35\lib\subprocess.py", line 398, in run
    
subprocess.CalledProcessError: Command '['docker-machine', 'regenerate-certs', 'golem']' returned non-zero exit status 1
'

```

**Comment by badb** [comment]
Hi @Slavenin 
Have you uninstall 0.9.0 version before installing 0.10.0? This log looks like it comes from the old Golem version - there are references to x86 paths and old minilight checks.
Can you please try to unistall all golem version that you may have installed on your machine and then try to install 0.10.0 again?

**Comment by Slavenin** [comment]
@badb, i unistall golem 0.10 and install 0.9. This work. I unistall 0.9 and install 0.10 and i have again this error in log.

**Comment by Slavenin** [comment]
I unistall all components (golem, vb, geth, etc.) and install 0.10. This work! Tnx!!!
