### ISSUE TITLE
[ERR] Failed to execute script golemapp

### ISSUE THREAD

**Issue by Gffy** [golemfactory/clay#1815]
OS: windows server 2012 R2

**Comment by Gffy** [comment]
There is no C:\Program Files\Geth. Is it ok?

**Comment by maaktweluit** [comment]
Hey @Gffy 
Thanks for the report!

Geth is indeed no longer installed by default, a remote Geth server is used.

Could you please check the logs? 
They are in `%LOCALAPPDATA%\golem\golem\default\logs`.

You can paste errors here or send the whole file.

**Comment by Gffy** [comment]
[golem.log](https://github.com/golemfactory/golem/files/1593318/golem.log)

**Comment by maaktweluit** [comment]
There are 2 errors in your log that can cause the problem:

```
2017-12-29 17:42:44 ERROR    golem                               b'Service Error: Traceback (most recent call last):\n  File "C:\\Python36\\lib\\threading.py", line 916, in _bootstrap_inner\n    \n  File "C:\\Python36\\lib\\threading.py", line 864, in run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_threadworker.py", line 46, in work\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_team.py", line 190, in doWork\n    \n--- <exception caught here> ---\n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 250, in inContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 266, in <lambda>\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 443, in _run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 414, in get_gnt_from_faucet\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\client.py", line 70, in get_transaction_count\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\utils\\functional.py", line 14, in inner\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\eth.py", line 229, in getTransactionCount\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\providers\\manager.py", line 52, in request_blocking\n    \nbuiltins.ValueError: {\'code\': -32000, \'message\': \'missing trie node 8b882936eaeee3f72391b2d81ba946ff363043eb69fd0e56f8dff8f81cdb9214 (path 0d0f0c)\'}\n'
```
This error should be investigated more ( looks like #1086 )

And 

```
2017-12-29 17:43:01 ERROR    twisted                             b'Failed to start native worker: A process has ended with a probable error condition: process ended with exit code -1. '
2017-12-29 17:43:01 ERROR    twisted                             b'crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code -1. [] '
```
This will be solved in #1602

**Comment by Gffy** [comment]
It works! UAC must be on.

**Comment by Poppiii** [comment]
I have the same issue but on Windows 10. (golem version 0.11.0)
I checked if geth is running in the background and golem.log is only showing this:

> 2018-01-29  21:30:52 INFO     golem.version                       b'GOLEM Version: 0.11.0 '
2018-01-29 21:30:52 INFO     golem.version                       b'Protocol Version: 20 '
2018-01-29 21:30:52 INFO     golem.version                       b'golem_messages Version: 1.5.1 '

**Comment by maaktweluit** [comment]
Hey @Poppiii,

Thank you for the report!
Since this is an old issue with old resolutions i've created a new issue #1994 for investigating your error.
Going to reply there now :)
