### ISSUE TITLE
Error: missing trie state

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1825]
Encountered several times today on Windows binaries, 0.10.1
Golemapp is opened and running with no computations 

message in logs:

```
2017-12-29 17:38:44 ERROR    golem                               b'Service Error: Traceback (most recent call last):\n  File "C:\\Python36\\lib\\threading.py", line 916, in _bootstrap_inner\n    \n  File "C:\\Python36\\lib\\threading.py", line 864, in run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_threadworker.py", line 46, in work\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_team.py", line 190, in doWork\n    \n--- <exception caught here> ---\n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 250, in inContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 266, in <lambda>\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 443, in _run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 419, in get_gnt_from_faucet\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\client.py", line 79, in send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\eth_utils\\string.py", line 85, in inner\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\eth.py", line 253, in sendRawTransaction\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\providers\\manager.py", line 52, in request_blocking\n    \nbuiltins.ValueError: {\'code\': -32000, \'message\': \'known transaction: 3739a0836345c133be52c5410c73689536ef397982de55416a7ebe547302c702\'}\n'
NoneType: None
```

could be related to: https://github.com/golemfactory/golem/issues/1815
https://github.com/golemfactory/golem/issues/1236

**Comment by badb** [comment]
@ederenn Are you sure that that's a proper issue number that it's related to? Also how is the error in issue title related to the message in logs?

**Comment by ederenn** [comment]
you were right, there was an error in issue number

**Comment by badb** [comment]
Both issues you mentioned still seems to be unrelated. However, this error should be investigated further, there's a risk that it may have cause problems with payment matching. This issue #1832 may be related.
