### ISSUE TITLE
 CRITICAL twisted                             b'Unhandled error in Deferred: '

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1861]
encountered on windows, binaries, build from here:
https://buildbot.golem.network/buildbot/#/builders/1/builds/33

```
2018-01-05 17:00:25 CRITICAL twisted                             b'Unhandled error in Deferred: '
2018-01-05 17:00:25 CRITICAL twisted                             b' '
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 476, in add_task
KeyError: '71abe5b6-f538-48e9-a271-ce0768f830d3'
2018-01-05 17:00:34 INFO     golem.pay                           b'Peer count: 25 '
2018-01-05 17:00:34 INFO     golem.pay                           b'ETH: 0.01735466 '
2018-01-05 17:00:34 INFO     golem.pay                           b'TestGNT: 984.1666666666666 '
2018-01-05 17:00:44 INFO     golem.network.p2p.peersession       b'Starting peer session '203.220.92.119':51580'
2018-01-05 17:00:47 INFO     golem.pay                           b'Peer count: 25 '
2018-01-05 17:00:47 INFO     golem.pay                           b'ETH: 0.01735466 '
2018-01-05 17:00:47 INFO     golem.pay                           b'TestGNT: 984.1666666666666 '
2018-01-05 17:00:56 INFO     golem.network.p2p.peersession       b"Failed to decrypt message from '67.242.87.170':40102, maybe it's not encrypted? ECIESDecryptionError('Fail to verify data',)"
2018-01-05 17:00:56 INFO     golem.network.transport.session     b"Failed to verify message signature (SetTaskSession(timestamp=1515167878.361386, encrypted=True, sig=b'\\x0bzrb\\xbf\\x81[=P\\xc9\\xa2\\xa1\\\\\\x0e4b\\x95\\x87AJ\\x80\\xe0\\x03\\x13k\\xa5\\xfeT\\x07\\xfc6\\xe1I\\xff\\xda\\xd8\\xacJ\\xdb\\x07\\xce(\\xa7\\x9co\\xd7\\xea\\x1c\\xa4\\x93V\\x01\\xe2\\x15&\\x1e\\xf3\\xc9\\x14\\xcdq$:\\x8d\\x01', slots=[['key_id', None], ['node_info', None], ['conn_id', None], ['super_node_info', None]]) from 67.242.87.170:40102)"
2018-01-05 17:00:56 INFO     golem.network.transport.session     b'Disconnecting 67.242.87.170 : 40102 reason: REASON.Unverified'
2018-01-05 17:00:56 INFO     golem.network.p2p.peersession       b'Starting peer session '188.165.227.180':40104'
2018-01-05 17:00:59 INFO     twisted                             b'Starting factory <golem.network.transport.network.OutgoingProtocolFactoryWrapper object at 0x00000167E1B62710> '
```

lux task and 5 blender tasks (from test scenarios - single frame, multiple frames)
all were in preparing or waiting state
after clicking lux file settings interface crashed and went completely blank

**Comment by maaktweluit** [comment]
@ederenn is this bug still there? If not sure i propose to close it since its 1 year+ old

**Comment by tworec** [comment]
there are no more Lux tasks supported, isn't it?
