### ISSUE TITLE
Failed to compute benchmark

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#1873]
Seems like there is a problem with DUMMYPOW benchmark, because it benchmark loading indicator hanging in GUI;
```
WARNING  [golem.task                         ] Failed to compute benchmark
ERROR    [golem.task.benchmarkmanager        ] Unable to run DUMMYPOW benchmark: 
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/mdt/projects/golem/golem/docker/task_thread.py", line 94, in run
    self.task_computer.task_computed(self)
  File "/Users/mdt/projects/golem/golem/task/localcomputer.py", line 95, in task_computed
    self.computation_failure(task_thread)
  File "/Users/mdt/projects/golem/golem/task/localcomputer.py", line 108, in computation_failure
    self.error_callback(to_unicode(task_thread.error_msg))
  File "/Users/mdt/projects/golem/golem/task/benchmarkmanager.py", line 42, in error_callback
    error(err_msg)
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 498, in errback
    fail = failure.Failure(fail)
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 218, in __init__
    raise TypeError("Strings are not supported by Failure")
TypeError: Strings are not supported by Failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/mdt/projects/golem/golem/docker/task_thread.py", line 107, in run
    self._fail(exc)
  File "/Users/mdt/projects/golem/golem/task/taskthread.py", line 87, in _fail
    if "exit code 137" in error_msg:
TypeError: argument of type 'TypeError' is not iterable
```

**Comment by badb** [comment]
Related to #1862

**Comment by etam** [comment]
#1862 is fixed

The first backtrace comes from this: At `BenchmarkManager.run_benchmark` we pass a string to the error callback. But it should be an exception http://twistedmatrix.com/trac/ticket/5948
https://github.com/twisted/twisted/commit/8a9e920d63accc2ad14dc4069f07c8ceed96d47e
