### ISSUE TITLE
task computing error CRITICAL twisted

### ISSUE THREAD

**Issue by josephyoungh** [golemfactory/clay#1878]
ERROR    golem.task.taskthread               b'Task computing error: Subtask computation failed with exit code 1'
ERROR    golem.task.taskthread b"Task computing error: [Errno 2] No such file or directory: 'C:\\\\Users\\\\josep\\\\AppData\\\\Local\\\\golem\\\\golem\\\\default\\\\tmp\\\\output\\\\stdout.log'"
CRITICAL twisted                             b'Unhandled error in Deferred: '
 CRITICAL twisted                             b' '
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 1301, in _inlineCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 920, in run_benchmark
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 1278, in returnValue
twisted.internet.defer._DefGen_Return: 247.49330626291334

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 921, in success
AttributeError: 'NoneType' object has no attribute 'send'

ERROR    golem.network.transport.tcpnetwork  ResourceHandshakeStart(timestamp=1515592616.393527, encrypted=False, sig=None, slots=[['resource', 'de081496d1cbcbe6623cd43041654c19a66fd52c35cfad957095e5dfedb0bc58']])
2018-01-10 05:56:56 ERROR    golem.network.transport.tcpnetwork  b'Send message failed - connection closed.'

**Comment by badb** [comment]
Hi @josephyoungh!
Can  you please send us full log to contact@golem.network and reference this issue number in your mail?

Did this error occur while you were trying to add a task? What scene did you use?

**Comment by badb** [comment]
With updated Golem network better information about failed tasks should be available in logs also potential problems with sending resources should be fixed, so I'm closing this issue. 
@josephyoungh Feel free to comment and reopen if you observe similiar behaviour in 0.11.0!
