### ISSUE TITLE
Dummy task test fails

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#189]
```
_________________________________________________________________________________ TestDummyTask.test_dummy_task_computation _________________________________________________________________________________

self = <test_dummy_task.TestDummyTask testMethod=test_dummy_task_computation>, mocks = (), error_msg = 'Computation timed out'

    def test_dummy_task_computation(self, *mocks):
        error_msg = runner.run_simulation(
            num_computing_nodes=2, num_subtasks=3, timeout=120)
>       self.assertIsNone(error_msg)
E       AssertionError: 'Computation timed out' is not None

tests/golem/task/dummy/test_dummy_task.py:12: AssertionError
------------------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------------------
[REQUESTER 18645] Starting...
[REQUESTER 18645] Started in 2.7 s
[REQUESTER 18645] Listening on 10.30.10.213:40105
[COMPUTER  18765] Starting...
[COMPUTER  18764] Starting...
[COMPUTER  18765] Started in 2.7 s
[COMPUTER  18765] Connecting to requesting node at 10.30.10.213:40105 ...
[COMPUTER  18764] Started in 2.7 s
[COMPUTER  18764] Connecting to requesting node at 10.30.10.213:40105 ...
Stopping nodes...
------------------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------------------

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

No handlers could be found for logger "golem.appconfig"

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt


Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

No handlers could be found for logger "golem.appconfig"
No handlers could be found for logger "golem.appconfig"
Unhandled Error
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/endpoints.py", line 102, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 436, in dataReceived
    self._interpret(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 597, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 570, in _interpret
    self._stream_data_received(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 578, in _stream_data_received
    self.consumer.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 851, in dataReceived
    (self.chunk_size,) = struct.unpack("!L", loc_data[:LONG_STANDARD_SIZE])
struct.error: unpack requires a string argument of length 4

Unhandled Error
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/endpoints.py", line 102, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 436, in dataReceived
    self._interpret(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 597, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 570, in _interpret
    self._stream_data_received(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 578, in _stream_data_received
    self.consumer.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 851, in dataReceived
    (self.chunk_size,) = struct.unpack("!L", loc_data[:LONG_STANDARD_SIZE])
struct.error: unpack requires a string argument of length 4
```

**Comment by azawlocki** [comment]
What branch is it? I cannot reproduce it in develop.

**Comment by chfast** [comment]
Upgrading pycryptodome to 3.4 helped. Not sure due to upgrade or just simply reinstallation.

**Comment by slowkow** [comment]
I already installed these packages:

```
sudo apt install scrypt
pip install scrypt
pip install pycryptodome
```

Now, when I run `golemapp --nogui` I get `Failed to import scrypt`.

Do you have advice for how to resolve the scrypt error?
