### ISSUE TITLE
Subtask exception in task thread during benchmark

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#1902]
After adding task for bmw27_cpu.blend with parameters:
Dimensions: 1920x1024
Frame range: 2;6;7
Format: PNG
Task timeout: 1d
Subtask amount: 10
Subtask timeout: 4h
Your bid: 0,00001 GNT/h

task is accepted by golem, but after some time this exception occurs:

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/home/wolverine/src/golem.network/golem/golem/docker/task_thread.py", line 94, in run
    self.task_computer.task_computed(self)
  File "/home/wolverine/src/golem.network/golem/golem/task/localcomputer.py", line 92, in task_computed
    if self.is_success(task_thread):
  File "/home/wolverine/src/golem.network/golem/apps/core/benchmark/benchmarkrunner.py", line 66, in is_success
    return self.benchmark.verify_result(res["data"])
  File "/home/wolverine/src/golem.network/golem/apps/dummy/benchmark/benchmark.py", line 55, in verify_result
    self.verifier.start_verification(sd, filepath, [], [])
  File "/home/wolverine/src/golem.network/golem/apps/core/task/verifier.py", line 19, in start_verification
    self.callback(subtask_id=self.subtask_info['subtask_id'],
KeyError: 'subtask_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/wolverine/src/golem.network/golem/golem/docker/task_thread.py", line 107, in run
    self._fail(str(exc))
  File "/home/wolverine/src/golem.network/golem/golem/task/taskthread.py", line 94, in _fail
    self.task_computer.task_computed(self)
  File "/home/wolverine/src/golem.network/golem/golem/task/localcomputer.py", line 92, in task_computed
    if self.is_success(task_thread):
  File "/home/wolverine/src/golem.network/golem/apps/core/benchmark/benchmarkrunner.py", line 66, in is_success
    return self.benchmark.verify_result(res["data"])
  File "/home/wolverine/src/golem.network/golem/apps/dummy/benchmark/benchmark.py", line 55, in verify_result
    self.verifier.start_verification(sd, filepath, [], [])
  File "/home/wolverine/src/golem.network/golem/apps/core/task/verifier.py", line 19, in start_verification
    self.callback(subtask_id=self.subtask_info['subtask_id'],
KeyError: 'subtask_id'
```

**Comment by etam** [comment]
I got the same error, when trying `./golemcli.py envs recount DUMMYPOW`

**Comment by ederenn** [comment]
Encountered this on Mac, source from new develop
visible only in console window, in logs showing shortened version

in console:
```ERROR    [golem.task.taskthread              ] Task computing error: 'subtask_id'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/a/Projects/golem/golem/docker/task_thread.py", line 94, in run
    self.task_computer.task_computed(self)
  File "/Users/a/Projects/golem/golem/task/localcomputer.py", line 92, in task_computed
    if self.is_success(task_thread):
  File "/Users/a/Projects/golem/apps/core/benchmark/benchmarkrunner.py", line 66, in is_success
    return self.benchmark.verify_result(res["data"])
  File "/Users/a/Projects/golem/apps/dummy/benchmark/benchmark.py", line 55, in verify_result
    self.verifier.start_verification(sd, filepath, [], [])
  File "/Users/a/Projects/golem/apps/core/task/verifier.py", line 19, in start_verification
    self.callback(subtask_id=self.subtask_info['subtask_id'],
KeyError: 'subtask_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/a/Projects/golem/golem/docker/task_thread.py", line 107, in run
    self._fail(str(exc))
  File "/Users/a/Projects/golem/golem/task/taskthread.py", line 94, in _fail
    self.task_computer.task_computed(self)
  File "/Users/a/Projects/golem/golem/task/localcomputer.py", line 92, in task_computed
    if self.is_success(task_thread):
  File "/Users/a/Projects/golem/apps/core/benchmark/benchmarkrunner.py", line 66, in is_success
    return self.benchmark.verify_result(res["data"])
  File "/Users/a/Projects/golem/apps/dummy/benchmark/benchmark.py", line 55, in verify_result
    self.verifier.start_verification(sd, filepath, [], [])
  File "/Users/a/Projects/golem/apps/core/task/verifier.py", line 19, in start_verification
    self.callback(subtask_id=self.subtask_info['subtask_id'],
KeyError: 'subtask_id'
```


in logs:

```
2018-01-15 15:05:01 INFO     golem.token                         b'TestGNT: 1000.0 GNTW: 0.0 '
2018-01-15 15:05:01 ERROR    golem.task.taskthread               b'Task computing error: 'subtask_id''
2018-01-15 15:05:04 INFO     golem.client                        b'Starting p2p server ... '
2018-01-15 15:05:04 INFO     golem.client                        b'Starting task server ... '
```

**Comment by ederenn** [comment]
on Windows - binaries from new develop
in logs only shortened version:

```2018-01-16 12:45:53 INFO     golem.token                         b'TestGNT: 1000.0 GNTW: 0.0 '
2018-01-16 12:45:58 ERROR    golem.task.taskthread               b'Task computing error: 'subtask_id''
2018-01-16 12:46:02 INFO     twisted                             b'Starting factory <golem.network.transport.network.OutgoingProtocolFactoryWrapper object at 0x000002849F979710> '
2018-01-16 12:46:02 INFO     golem.network.p2p.peersession       b'Starting peer session '94.23.196.166':40102'```
