### ISSUE TITLE
Exception occurs when docker is not available for the user

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#1916]
Exception occurs when docker is not configured for the user running golemapp, i.e. user is not added to group `docker` or doesn't have permission to access docker socket. Perhaps message for improper docker configuration should be printed and we should disallow starting of golemapp. Related to issue #1914 .

```
ERROR    [golem.docker.manager               ] Docker: error pulling images: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1
ERROR    [golem.core.async                   ] Caught async exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/wolverine/.virtualenvs/golem-devel/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/wolverine/src/golem.network/golem/golem/node.py", line 62, in _run
    self._setup_docker()
  File "/home/wolverine/src/golem.network/golem/golem/node.py", line 93, in _setup_docker
    docker_manager.check_environment()
  File "/home/wolverine/src/golem.network/golem/golem/docker/manager.py", line 146, in check_environment
    self.build_images()
  File "/home/wolverine/src/golem.network/golem/golem/docker/manager.py", line 313, in build_images
    if not cls.command('images', args=[version]):
  File "/home/wolverine/src/golem.network/golem/golem/docker/manager.py", line 299, in command
    **params)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1
```

**Comment by maaktweluit** [comment]
Seems on develop this has been solved already, same as for the other docker related issue.

Both now exit the application properly.

Have looked into making the error more clear, but "pulling images" can be failing for more reasons.
Propose to leave as is for now, this can be tested easily in support chat with `docker run hello-world`

```
(.venv) golem@golem-tests:~/src/golem$ python golemapp.py
INFO     [talkback                           ] Enabling talkback 'sentry' service 
INFO     [talkback                           ] Enabling talkback 'sentry-metrics' service 
INFO     [golemapp                           ] GOLEM Version: 0.15.1+dev111.g1292d58 
INFO     [golemapp                           ] Protocol Version: 26-testnet 
INFO     [golemapp                           ] golem_messages Version: 2.6.0 
INFO     [golemapp                           ] system: Linux, release: 4.13.0-39-generic, version: #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018, machine: x86_64 
INFO     [golemapp                           ] cpu: GenuineIntel Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 4 cores 
INFO     [golemapp                           ] memory: 7.8 GiB, swap: 8.0 GiB 
INFO     [golemapp                           ] Ethereum chain: rinkeby 
INFO     [app                                ] New account, need to create new password 
INFO     [app                                ] Terms of use must be accepted before using Golem. Run `golemcli terms show` to display the terms and `golemcli terms accept` to accept them. 
ERROR    [golem.docker.manager               ] Docker: error pulling images: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1.
ERROR    [app                                ] Stopping because of 'keys or docker' error: <twisted.python.failure.Failure twisted.internet.defer.FirstError: FirstError[#2, [Failure instance: Traceback: <class 'subprocess.CalledProcessError'>: Command '['docker', 'images', '-q', 'golemfactory/base:1.2']' returned non-zero exit status 1.
/usr/lib/python3.6/threading.py:916:_bootstrap_inner
/usr/lib/python3.6/threading.py:864:run
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py:46:work
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/golem/src/golem/.venv/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/golem/src/golem/golem/node.py:237:start_docker
/home/golem/src/golem/golem/report.py:121:wrapper
/home/golem/src/golem/golem/docker/manager.py:149:check_environment
/home/golem/src/golem/golem/docker/manager.py:320:build_images
/home/golem/src/golem/golem/docker/manager.py:306:command
/usr/lib/python3.6/subprocess.py:336:check_output
/usr/lib/python3.6/subprocess.py:418:run
]]> 
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down .. 
(.venv) golem@golem-tests:~/src/golem$ 
```
