### ISSUE TITLE
 ERROR    twisted                             AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1939]
Mac, source version, b0.11.0, after update in evening 19.01 

most probably, during task with external textures and assets
```
2018-01-19 22:14:58 ERROR    twisted                             AttributeError: 'NoneType' object has no attribute 'items': Traceback (most recent call last):
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/ederenn/golem/golem/client.py", line 730, in get_subtasks_borders
    part)
  File "/Users/ederenn/golem/golem/task/taskmanager.py", line 700, in get_subtasks_borders
    ) for subtask_id, subtask in task.get_subtasks(part).items()
builtins.AttributeError: 'NoneType' object has no attribute 'items'
 ```

encountered in three minuts 6 times

**Comment by badb** [comment]
Resolved by #1941
