### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1967]
Windows, binaries, b0.11.0
golem was working normally, no sleep mode

warning should be formatted in some more readable way
```
2018-01-23 19:49:27 WARNING  golem.monitor.transport             b'Problem sending payload to: 'https://stats.golem.network/''
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\util\connection.py", line 60, in create_connection
  File "C:\Python36\lib\socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connection.py", line 150, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000025B4FB75278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\adapters.py", line 423, in send
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\packages\urllib3\util\retry.py", line 376, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='stats.golem.network', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000025B4FB75278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\monitor\transport\httptransport.py", line 17, in _post
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\api.py", line 110, in post
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\api.py", line 56, in request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\sessions.py", line 609, in send
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stats.golem.network', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000025B4FB75278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2018-01-23 19:49:27 ERROR    golem                               b'Service Error: Traceback (most recent call last):\n  File "C:\\Python36\\lib\\threading.py", line 916, in _bootstrap_inner\n    \n  File "C:\\Python36\\lib\\threading.py", line 864, in run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_threadworker.py", line 46, in work\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\_threads\\_team.py", line 190, in doWork\n    \n--- <exception caught here> ---\n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 250, in inContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\threadpool.py", line 266, in <lambda>\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 412, in _run\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 109, in is_synchronized\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\paymentprocessor.py", line 92, in check\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\ethereum\\client.py", line 41, in get_peer_count\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\utils\\functional.py", line 14, in inner\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\net.py", line 24, in peerCount\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\providers\\manager.py", line 44, in request_blocking\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\providers\\rpc.py", line 52, in make_request\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\web3\\utils\\compat\\compat_requests.py", line 21, in make_post_request\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\requests\\sessions.py", line 535, in post\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\requests\\sessions.py", line 488, in request\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\requests\\sessions.py", line 609, in send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\requests\\adapters.py", line 487, in send\n    \nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'94.23.57.58\', port=55555): Max retries exceeded with url: / (Caused by NewConnectionError(\'<requests.packages.urllib3.connection.HTTPConnection object at 0x0000025B4B7AFC88>: Failed to establish a new connection: [WinError 10051] Pr\xc3\xb3ba przeprowadzenia operacji, wykonywanej przez gniazdo, na nieosi\xc4\x85galnej sieci\',))\n'
NoneType: None
```

**Comment by badb** [comment]
This was caused by a specific situation with updating certificates for golem monitor service. Taking into account that this error was only printed once we can assume that this full traceback is not a problem and a warning level is apropriate.
