### ISSUE TITLE
 local variable 'own_key' referenced before assignment

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1995]
Windows and Mac
binaries 0.11.0

```2018-01-30 13:02:06 ERROR    golem.network.transport.message     b'Error serializing message: UnboundLocalError("local variable 'own_key' referenced before assignment",)'
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\pyelliptic\ecc.py", line 299, in raw_get_ecdh_key
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_messages\message\base.py", line 147, in serialize
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_messages\cryptography.py", line 228, in ecies_encrypt
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\pyelliptic\ecc.py", line 324, in raw_get_ecdh_key
UnboundLocalError: local variable 'own_key' referenced before assignment
2018-01-30 13:02:06 CRITICAL twisted                             b'Unhandled Error\nTraceback (most recent call last):\n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\log.py", line 103, in callWithLogger\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\log.py", line 86, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    \n--- <exception caught here> ---\n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\iocpreactor\\reactor.py", line 119, in _callEventCallback\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 92, in _cbRead\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 118, in _handleRead\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 75, in _dispatchData\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\iocpreactor\\tcp.py", line 75, in dataReceived\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\twisted\\internet\\endpoints.py", line 125, in dataReceived\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\tcpnetwork.py", line 302, in dataReceived\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\tcpnetwork.py", line 334, in _interpret\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\p2p\\peersession.py", line 114, in interpret\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\session.py", line 91, in interpret\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\p2p\\peersession.py", line 310, in _react_to_hello\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\p2p\\peersession.py", line 124, in send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\session.py", line 210, in send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\session.py", line 124, in send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\tcpnetwork.py", line 262, in send_message\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\golem\\network\\transport\\tcpnetwork.py", line 414, in _prepare_msg_to_send\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\golem_messages\\shortcuts.py", line 19, in dump\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\golem_messages\\message\\base.py", line 147, in serialize\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\golem_messages\\cryptography.py", line 228, in ecies_encrypt\n    \n  File "C:\\BuildbotWorker\\buildpackage_windows\\build\\.venv\\lib\\site-packages\\pyelliptic\\ecc.py", line 324, in raw_get_ecdh_key\n    \nbuiltins.UnboundLocalError: local variable \'own_key\' referenced before assignment\n '```

**Comment by ederenn** [comment]
moved to https://github.com/golemfactory/golem-messages/issues/114
