### ISSUE TITLE
ValueError: Empty host name

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#1996]
Windows Mac, binaries 0.11.0

```2018-01-30 12:50:22 ERROR    golem.client                        b'p2pservice.sync_network failed '
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork_helpers.py", line 42, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork_helpers.py", line 69, in __validate
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork_helpers.py", line 98, in validate_hostname
ValueError: Empty host name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 1162, in _run
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\p2p\p2pservice.py", line 240, in sync_network
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\p2p\p2pservice.py", line 971, in __sync_free_peers
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpserver.py", line 155, in _add_pending_request
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\p2p\p2pservice.py", line 536, in get_socket_addresses
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpserver.py", line 236, in get_socket_addresses
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork_helpers.py", line 44, in __init__
ipaddress.AddressValueError: Empty host name```

**Comment by ederenn** [comment]
duplicated https://github.com/golemfactory/golem/issues/1827

**Comment by maaktweluit** [comment]
This looks like a duplicate of #1827 with open pending solve #1871
