### ISSUE TITLE
Bug in metrics calculator

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#2001]
Traceback (most recent call last):
  File "/golem/work/job.py", line 70, in <module>
    params.xres, params.yres)
  File "/golem/work/job.py", line 60, in run_img_compare_task
    output_filename_path=file_path)
  File "/golem/scripts/img_metrics_calculator.py", line 38, in compare_crop_window
    img_metrics = compare_images(cropped_img, scene_crop)
  File "/golem/scripts/img_metrics_calculator.py", line 109, in compare_images
    SSIM_normal, MSE_normal = compare_mse_ssim(image_a, image_b)
  File "/golem/scripts/img_metrics_calculator.py", line 158, in compare_mse_ssim
    cv2.cvtColor(image_b, cv2.COLOR_BGR2GRAY))
  File "/golem/scripts/img_metrics_calculator.py", line 148, in mean_squared_error
    mse = np.sum((image_a.astype("float") - image_b.astype("float")) ** 2)
ValueError: operands could not be broadcast together with shapes (11,11) (10,11)

Testeted with bmw 555x55 divided on 2 subtasks.

**Comment by Elfoniok** [comment]
Fixe is here https://github.com/golemfactory/golem/pull/2172
