### ISSUE TITLE
Requested CPUs are not available

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#2071]
There's an error in terminal while startup. 
```
ERROR    [golem.task.taskthread              ] Task computing error: 400 Client Error: Bad Request ("b'Requested CPUs are not available - requested 0,1,2, available: 0'")
ERROR    [golem.task.taskthread              ] ['  File "/Users/mdt/projects/golem/golem/docker/task_thread.py", line 78, in run\n    host_config=host_config) as job:\n', '  File "/Users/mdt/projects/golem/golem/docker/job.py", line 186, in __enter__\n    self._prepare()\n', '  File "/Users/mdt/projects/golem/golem/docker/job.py", line 154, in _prepare\n    environment=environment\n', '  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/docker/api/container.py", line 119, in create_container\n    return self.create_container_from_config(config, name)\n', '  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/docker/api/container.py", line 130, in create_container_from_config\n    return self._result(res, True)\n', '  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/docker/client.py", line 150, in _result\n    self._raise_for_status(response)\n', '  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/docker/client.py", line 146, in _raise_for_status\n    raise errors.APIError(e, response, explanation=explanation)\n']
WARNING  [golem.task                         ] Failed to compute benchmark 400 Client Error: Bad Request ("b'Requested CPUs are not available - requested 0,1,2, available: 0'")
ERROR    [golem.task.benchmarkmanager        ] Unable to run DUMMYPOW benchmark: 400 Client Error: Bad Request ("b'Requested CPUs are not available - requested 0,1,2, available: 0'")
```

same error occurs when local test runs while creating task as well,  and local test result returns with `Error` status all the time.

I had to stop Golem on GUI and re-arrange my resources to overcome this issue.

**Comment by badb** [comment]
@mdtanrikulu Did you try to run two instances of Golem on the same machine?

**Comment by mdtanrikulu** [comment]
@badb No, I'm not. Time to time I'm switching between binary and source versions but didn't run two instances.

**Comment by badb** [comment]
Any configuration changes?

**Comment by mdtanrikulu** [comment]
I faced with the same issue between `0.18.3` binary and `b0.19` branch. 
@badb I changed the config but not much difference, changed %62 system resource to %61. 
When I try to run b0.19, what I have is;
```
INFO     [golem.task.benchmarkmanager        ] Running benchmark for DUMMYPOW
WARNING  [golem.task.taskthread              ] Task computing error
WARNING  [golem.task                         ] Failed to compute benchmark 400 Client Error: Bad Request ("Requested CPUs are not available - requested 0,1, available: 0")
ERROR    [golem.task.benchmarkmanager        ] Unable to run DUMMYPOW benchmark: 400 Client Error: Bad Request ("Requested CPUs are not available - requested 0,1, available: 0")
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/Users/mdt/projects/golem/golem/client.py", line 303, in start
    self.start_network()
  File "/Users/mdt/projects/golem/golem/client.py", line 355, in start_network
    task_finished_cb=self._task_finished_cb,
  File "/Users/mdt/projects/golem/golem/task/taskserver.py", line 117, in __init__
    finished_cb=task_finished_cb)
  File "/Users/mdt/projects/golem/golem/task/taskcomputer.py", line 78, in __init__
    sync_wait(deferred, BENCHMARK_TIMEOUT)
  File "/Users/mdt/projects/golem/golem/core/deferred.py", line 33, in sync_wait
    result.raiseException()
  File "/Users/mdt/projects/golem/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
Exception: 400 Client Error: Bad Request ("Requested CPUs are not available - requested 0,1, available: 0")
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
INFO     [golem.network.concent.client       ] Waiting for received messages queue to empty
INFO     [golem.network.concent.client       ] <ConcentClientService(Thread-1, started daemon 123145472069632)> stopped
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..
Sentry is attempting to send 1 pending error messages
```

And after this error started electron with `0.18.3` binary and everything was fine.
Then I switched back to b0.19 everything was fine too.

**Comment by mfranciszkiewicz** [comment]
@mdtanrikulu fixed in https://github.com/golemfactory/golem/pull/3702

**Comment by mdtanrikulu** [comment]
Confirmed.
