### ISSUE TITLE
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2095]
windows, source version 

```2018-02-11 00:46:01 WARNING  golem.monitor.transport             b'Problem sending payload to: 'https://stats.golem.network/''
Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\monitor.py", line 34, in run
    msg = self.queue.get(True, self.monitor_sender_thread_timeout)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 436, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\OpenSSL\SSL.py", line 1714, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\OpenSSL\SSL.py", line 1447, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 443, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\transport\httptransport.py", line 17, in _post
    r = requests.post(self.url, data=payload, headers=headers, timeout=self.timeout)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
2018-02-11 01:22:25 WARNING  golem.monitor.transport             b'Problem sending payload to: 'https://stats.golem.network/''
Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\transport\httptransport.py", line 17, in _post
    r = requests.post(self.url, data=payload, headers=headers, timeout=self.timeout)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
2018-02-11 01:48:37 ERROR    golem.decorators                    b'Error in <function DefaultJSONSender.send at 0x00000204BF32CD90>'
Traceback (most recent call last):
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\decorators.py", line 12, in _wrapper
    return f(*args, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\transport\sender.py", line 14, in send
    return self.transport.post_json(msg)
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\transport\httptransport.py", line 27, in post_json
    return self._post(self.json_headers, json_payload)
  File "C:\Users\Magdalena Szydlowska\Projects\golem\golem\monitor\transport\httptransport.py", line 17, in _post
    r = requests.post(self.url, data=payload, headers=headers, timeout=self.timeout)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\Magdalena Szydlowska\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 311, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 301, in _send_until_done
    return self.connection.send(data)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\OpenSSL\SSL.py", line 1538, in send
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Magdalena Szydlowska\Projects\golem-env\lib\site-packages\OpenSSL\SSL.py", line 1447, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')```

**Comment by etam** [comment]
The error was properly handled, but needlessly printed too much stack traces.
