### ISSUE TITLE
Problems with closing Golem on Linux

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2132]
### Symptoms:
when closing source version of Golem on Linux  with ctrl c from time to time appears:

in console window:

```
WARNING  [golem.network.concent.client       ] Concent request failed with status 400 and response: '{"error": "Unknown message type or not a Golem message."}'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ederenn/projects/golem/golem/network/concent/client.py", line 196, in _loop
    req = self._queue.get(timeout=constants.PING_TIMEOUT)
  File "/usr/lib/python3.5/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ederenn/projects/golem/golem/network/concent/client.py", line 131, in run
    self._loop()
  File "/home/ederenn/projects/golem/golem/network/concent/client.py", line 202, in _loop
    self.keys_auth.public_key,
  File "/home/ederenn/projects/golem/golem/network/concent/client.py", line 80, in send_to_concent
    response.text
golem.network.concent.exceptions.ConcentRequestException: Concent request exception (400): {"error": "Unknown message type or not a Golem message."}

INFO     [golem_sci.client                   ] Peer count: 25 

ederenn@ederenn-VirtualBox:~/bin$ 
```

#### Appeared on:
Linux, Ubuntu 16.04
 GOLEM Version: 0.11.0+dev333.g76e625b 
2018-02-14 18:11:20 INFO     golem.version                       Protocol Version: 23 
2018-02-14 18:11:20 INFO     golem.version                       golem_messages Version: 1.8.1

**Comment by Wiezzel** [comment]
I got a similar error for this version (0.11.0+dev333.g76e625b) However, it isn't related to closing golem. It just occurs a few seconds after starting.
```
WARNING  [golem.network.concent.client       ] Concent failed with status 500 and body: '<h1>Server Error (500)</h1>'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/adam/golem/golem/network/concent/client.py", line 196, in _loop
    req = self._queue.get(timeout=constants.PING_TIMEOUT)
  File "/usr/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/adam/golem/golem/network/concent/client.py", line 131, in run
    self._loop()
  File "/home/adam/golem/golem/network/concent/client.py", line 202, in _loop
    self.keys_auth.public_key,
  File "/home/adam/golem/golem/network/concent/client.py", line 69, in send_to_concent
    response.text
golem.network.concent.exceptions.ConcentServiceException: Concent service exception (500): <h1>Server Error (500)</h1>
```
For the current version (0.13.0+dev23.g322cd13) the problem does not reproduce.
@badb Should I investigate this further?
