### ISSUE TITLE
 subtask_id = msg.task_to_compute.compute_task_def.get('subtask_id') builtins.AttributeError: 'NoneType' object has no attribute 'compute_task_def'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2149]
### Symptoms:

after putting computer in sleep mode -  golem is running with no computations requested,
appeared in `golem.log` several times
logs from sleep mode: 

```
2018-02-19 16:05:19 CRITICAL twisted                             An exception was raised from application code while processing a reactor selectable
Traceback (most recent call last):
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/kqreactor.py", line 293, in _doWriteOrRead
    why = selectable.doRead()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/Users/ederenn/projects/golem/golem/network/transport/tcpnetwork.py", line 378, in dataReceived
    self._interpret(data)
  File "/Users/ederenn/projects/golem/golem/network/transport/tcpnetwork.py", line 576, in _interpret
    SafeProtocol._interpret(self, data)
  File "/Users/ederenn/projects/golem/golem/network/transport/tcpnetwork.py", line 405, in _interpret
    self.session.interpret(m)
  File "/Users/ederenn/projects/golem/golem/task/tasksession.py", line 128, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/Users/ederenn/projects/golem/golem/network/transport/session.py", line 75, in interpret
    action(msg)
  File "/Users/ederenn/projects/golem/golem/network/history.py", line 293, in wrapper
    return func(self, msg, *args, **kwargs)
  File "/Users/ederenn/projects/golem/golem/task/tasksession.py", line 702, in _react_to_subtask_result_accepted
    subtask_id = msg.task_to_compute.compute_task_def.get('subtask_id')
builtins.AttributeError: 'NoneType' object has no attribute 'compute_task_def'
```

#### Encountered on
Mac Os Sierra
  GOLEM Version: 0.11.0+dev399.g0bfff9e72 
  Protocol Version: 23 
  golem_messages Version: 1.9.0

**Comment by badb** [comment]
It was already fixed in https://github.com/golemfactory/golem/commit/c9d45d47312ca8eda6ed3ee597ac46daba238ea5
