### ISSUE TITLE
KeysAuth decode_hex: Value must be an instance of str or bytes

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2150]
### Symptomps:

in `golem.log`

```
2018-02-19 12:08:16 CRITICAL twisted                             b'Unhandled Error\nTraceback (most recent call last):\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 103, in callWithLogger\n    return callWithContext({"system": lp}, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 86, in callWithContext\n    return context.call({ILogContext: newCtx}, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext\n    return func(*args,**kw)\n--- <exception caught here> ---\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\reactor.py", line 119, in _callEventCallback\n    evt.callback(rc, numBytes, evt)\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 92, in _cbRead\n    if self._handleRead(rc, data, evt):\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 118, in _handleRead\n    return self._dispatchData()\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 75, in _dispatchData\n    self.dataReceived(self._readBuffers[full_buffers][0:remainder])\n  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\tcp.py", line 75, in dataReceived\n    self.protocol.dataReceived(rbuffer)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\tcpnetwork.py", line 378, in dataReceived\n    self._interpret(data)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\tcpnetwork.py", line 405, in _interpret\n    self.session.interpret(m)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 116, in interpret\n    BasicSafeSession.interpret(self, msg)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\session.py", line 75, in interpret\n    action(msg)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 401, in _react_to_rand_val\n    self.__set_verified_conn()\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 517, in __set_verified_conn\n    self.p2p_service.add_peer(self.key_id, self)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\p2pservice.py", line 295, in add_peer\n    self.keys_auth.get_difficulty(peer.key_id)\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\core\\keysauth.py", line 183, in get_difficulty\n    return int(math.floor(256 - math.log2(sha2(decode_hex(key_id)))))\n  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\utils.py", line 58, in decode_hex\n    raise TypeError(\'Value must be an instance of str or bytes\')\nbuiltins.TypeError: Value must be an instance of str or bytes\n '
```

#### Encountered on
Windows 10
GOLEM Version: 0.11.0+dev399.g0bfff9e '
'Protocol Version: 23 '
'golem_messages Version: 1.9.0 '

**Comment by etam** [comment]
Decoded stacktrace:
```
Unhandled Error
Traceback (most recent call last):
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\python\\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\reactor.py", line 119, in _callEventCallback
    evt.callback(rc, numBytes, evt)
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 92, in _cbRead
    if self._handleRead(rc, data, evt):
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 118, in _handleRead
    return self._dispatchData()
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\abstract.py", line 75, in _dispatchData
    self.dataReceived(self._readBuffers[full_buffers][0:remainder])
  File "C:\\Users\\ederenn\\Projects\\golem-env\\lib\\site-packages\\twisted\\internet\\iocpreactor\\tcp.py", line 75, in dataReceived
    self.protocol.dataReceived(rbuffer)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\tcpnetwork.py", line 378, in dataReceived
    self._interpret(data)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\tcpnetwork.py", line 405, in _interpret
    self.session.interpret(m)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 116, in interpret
    BasicSafeSession.interpret(self, msg)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\transport\\session.py", line 75, in interpret
    action(msg)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 401, in _react_to_rand_val
    self.__set_verified_conn()
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\peersession.py", line 517, in __set_verified_conn
    self.p2p_service.add_peer(self.key_id, self)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\network\\p2p\\p2pservice.py", line 295, in add_peer
    self.keys_auth.get_difficulty(peer.key_id)
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\core\\keysauth.py", line 183, in get_difficulty
    return int(math.floor(256 - math.log2(sha2(decode_hex(key_id)))))
  File "C:\\Users\\ederenn\\Projects\\golem\\golem\\utils.py", line 58, in decode_hex
    raise TypeError(\'Value must be an instance of str or bytes\')
builtins.TypeError: Value must be an instance of str or bytes
```

**Comment by kascheri12** [comment]
I believe I have the same error on Ubuntu.

```
GOLEM Version: 0.11.0+dev451.g054df1c 
Protocol Version: 23 
golem_messages Version: 1.9.0 
hyperg Version: 0.2.5
```

```
2018-02-24 05:12:25 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/home/kentrendz/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/kentrendz/golem/golem/network/transport/tcpnetwork.py", line 377, in dataReceived
    self._interpret(data)
  File "/home/kentrendz/golem/golem/network/transport/tcpnetwork.py", line 404, in _interpret
    self.session.interpret(m)
  File "/home/kentrendz/golem/golem/network/p2p/peersession.py", line 116, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/kentrendz/golem/golem/network/transport/session.py", line 75, in interpret
    action(msg)
  File "/home/kentrendz/golem/golem/network/p2p/peersession.py", line 401, in _react_to_rand_val
    self.__set_verified_conn()
  File "/home/kentrendz/golem/golem/network/p2p/peersession.py", line 517, in __set_verified_conn
    self.p2p_service.add_peer(self.key_id, self)
  File "/home/kentrendz/golem/golem/network/p2p/p2pservice.py", line 295, in add_peer
    self.keys_auth.get_difficulty(peer.key_id)
  File "/home/kentrendz/golem/golem/core/keysauth.py", line 183, in get_difficulty
    return int(math.floor(256 - math.log2(sha2(decode_hex(key_id)))))
  File "/home/kentrendz/golem/golem/utils.py", line 58, in decode_hex
    raise TypeError('Value must be an instance of str or bytes')
builtins.TypeError: Value must be an instance of str or bytes
```

For what it's worth - this happened about the same time I issued `network connect 35.197.98.8 40102` command from `kascheri12` node. This Ubuntu node was a fresh new VM. Golemapp was running but wouldn't seem to connect to any nodes using `network connect` command. I then tried to issue from `kascheri12` and this error showed up on `kascheri12/503` log.

[Edit]: I confirmed that this error seems to be related to issuing the `network connect` command from a different node. I repeated this from multiple different nodes and the above error message showed in logs of `kascheri12/503` node each time.
