### ISSUE TITLE
in add_task     resource_manager_result, package_hash = resource_server_result TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2153]
### Symptoms:
Windows, source version, on private connection, requester site, during computations of cube.blend 
Task was in preparing state, passed set timeout time (15 min) - but still in preparing, no timeout state itself.

from `golem.log`

```
2018-02-19 19:25:37 ERROR    golem.resource.hyperdrive.resourcesmanager b'Error adding task: <twisted.python.failure.Failure requests.exceptions.HTTPError: [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly: Connection done.>]
]>'
2018-02-19 19:25:37 ERROR    golem.resource.base.resourceserver  b"Resource server: add_task error: [Failure instance: Traceback (failure with no frames): <class 'requests.exceptions.HTTPError'>: [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly: Connection done.>]\n]\n]"
2018-02-19 19:25:37 CRITICAL twisted                             b'Unhandled error in Deferred: '
2018-02-19 19:25:37 CRITICAL twisted                             b' '
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\ederenn\Projects\golem\golem\client.py", line 487, in add_task
    resource_manager_result, package_hash = resource_server_result
TypeError: 'NoneType' object is not iterable
```

### Encountered on:
Windows 10
'GOLEM Version: 0.11.0+dev399.g0bfff9e '
'Protocol Version: 99 '
'golem_messages Version: 1.9.0 '

**Comment by maaktweluit** [comment]
Could you attach the logs of the other node in the private network? there might be a related error there

**Comment by ederenn** [comment]
[mac priv.log](https://github.com/golemfactory/golem/files/1740172/mac.priv.log)
logs of the provider

**Comment by maaktweluit** [comment]
Thank you for the logs!

Indeed not much in the logs around this time, there is a warning 7 minutes later, seems un-related.

**Comment by Wiezzel** [comment]
I couldn't run version `0.11.0+dev399.g0bfff9e` so I investigated this issue on `0.14.0`.

The error was caused by hyperdrive connection failure. I assume that investigating why hyperdrive did fail is beyond the scope of my task. I will upload a fix to handle this kind of issues gracefully and don't display any tracebacks or critical-level messages.
