### ISSUE TITLE
Strange Error from epollreactor

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#2166]
Unhandled Error
Traceback (most recent call last):
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1072, in doRead
    transport = self.transport(skt, protocol, addr, self, s, self.reactor)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/tcp.py", line 786, in __init__
    self.startReading()
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/abstract.py", line 438, in startReading
    self.reactor.addReader(self)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 110, in addReader
    EPOLLIN, EPOLLOUT)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 94, in _add
    self._poller.modify(fd, flags)
builtins.FileNotFoundError: [Errno 2] No such file or directory

CRITICAL [twisted                            ] Unhandled Error
Traceback (most recent call last):
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1072, in doRead
    transport = self.transport(skt, protocol, addr, self, s, self.reactor)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/tcp.py", line 786, in __init__
    self.startReading()
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/abstract.py", line 438, in startReading
    self.reactor.addReader(self)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 110, in addReader
    EPOLLIN, EPOLLOUT)
  File "/home/elfoniok/golem-env3.6/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 94, in _add
    self._poller.modify(fd, flags)
builtins.FileNotFoundError: [Errno 2] No such file or directory

**Comment by mfranciszkiewicz** [comment]
This issue seems to have been caused by verification callbacks, run outside the main thread. `reactor.callFromThread([callback])` fixed that (version 0.12.0).
