### ISSUE TITLE
unhandled exception 'secp256k1_recovery not enabled'

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2168]
[secp256k1](https://github.com/bitcoin-core/secp256k1) library has optional "ECDSA pubkey recovery module", which is not built by default (requires `./configure --enable-module-recovery`).

[secp256k1-py](https://github.com/ludbb/secp256k1-py) python module in setup.py searches for the secp256k1 library and uses it. (if it's not installed, it builds one by itself, with pubkey recovery module enabled ofc).

Ethereum python module requires recovery module enabled in secp256k1-py.

So, if there is secp256k1 library built with default config and installed system-wide, we get the following exception:

```
INFO     [golem.pay                          ] Requesting GNT from faucet
DEBUG:eth.chain.tx      deserialized tx tx=b'059351f0'
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", 
line 46, in work                                                                                                                   
    task()
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190
, in doWork                                                                                                                        
    task()
--- <exception caught here> ---
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 
250, in inContext                                                                                                                  
    result = inContext.theWork()
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 
266, in <lambda>                                                                                                                   
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122
, in callWithContext                                                                                                               
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85,
 in callWithContext                                                                                                                
    return func(*args,**kw)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/golem/ethereum/paymentprocessor.py", line 337, in _run
    self.get_gnt_from_faucet():
  File "/home/etam/code/github/golemfactory/golem/log_hardware/golem/ethereum/paymentprocessor.py", line 330, in get_gnt_from_faucet
    self._sci.request_gnt_from_faucet()
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/src/golem-sci/golem_sci/implementation.py", line 250, in request
_gnt_from_faucet                                                                                                                   
    self.GAS_FAUCET,
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/src/golem-sci/golem_sci/implementation.py", line 275, in _send_t
ransaction                                                                                                                         
    self._tx_sign(tx)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/golem/transactions/ethereum/ethereumtransactionsystem.py", line 47, i
n <lambda>                                                                                                                         
    lambda tx: tx.sign(node_priv_key),
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/ethereum/transactions.py", line 128,
 in sign                                                                                                                           
    pk.ecdsa_sign_recoverable(rawhash, raw=True)
  File "/home/etam/code/github/golemfactory/golem/log_hardware/venv/lib/python3.6/site-packages/secp256k1/__init__.py", line 398, in
 ecdsa_sign_recoverable                                                                                                            
    raise Exception("secp256k1_recovery not enabled")
builtins.Exception: secp256k1_recovery not enabled
NoneType: None
```

**Comment by etam** [comment]
@Krigpl

**Comment by etam** [comment]
https://github.com/golemfactory/golem-smart-contracts-interface/pull/14
