### ISSUE TITLE
[ERR] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2184]
Pulled the latest code from git develop branch and I'm getting an error on Ubuntu machine but not Mac.

I used these commands:
```
cd ~/golem
git pull
sudo pip3 install -r requirements.txt
sudo python3 setup.py develop
sudo shutdown -r now

```

the following version:
`golem==0.11.0+dev435.g36c057ea4`

And when I run golemapp, this error only on ubuntu nodes:
```
Traceback (most recent call last):
  File "/usr/local/bin/golemapp", line 11, in <module>
    load_entry_point('golem', 'gui_scripts', 'golemapp')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kentrendz/golem/golemapp.py", line 15, in <module>
    from golem.node import Node
  File "/home/kentrendz/golem/golem/node.py", line 4, in <module>
    from golem.client import Client
  File "/home/kentrendz/golem/golem/client.py", line 60, in <module>
    from golem.task.taskserver import TaskServer
  File "/home/kentrendz/golem/golem/task/taskserver.py", line 25, in <module>
    from .server import concent
  File "/home/kentrendz/golem/golem/task/server/concent.py", line 4, in <module>
    from golem.network.concent.handlers_library import library
  File "/home/kentrendz/golem/golem/network/concent/handlers_library.py", line 29
    self._handlers: typing.Dict[message.base.Message, weakref.ref] = {}
                  ^
SyntaxError: invalid syntax
```

**Comment by maaktweluit** [comment]
Hey @kascheri12 

Thank you for the report!
We recently upgraded all python versions to 3.6, on mac this was already default but on ubuntu the default is 3.5. Could you try this again with `python3.6` ?

**Comment by kascheri12** [comment]
@maaktweluit 
I installed python3.6 like this:
```
sudo add-apt-repository ppa:jonathonf/python-3.6
sudo apt-get update && sudo apt-get install python3.6 -y
```

Now I'm getting this error when I run `sudo python3.6 setup.py develop`

```
kenneth@ubuntu:~/golem$ sudo python3.6 setup.py develop
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
kenneth@ubuntu:~/golem$
```

**Comment by maaktweluit** [comment]
`setuptools` is part of `python3.6-dev` can you try installing that package too?

I also recommend to try `python3.6-venv`, it helps to **not** run golem as sudo

**Comment by kascheri12** [comment]
Thanks @maaktweluit 
I have used your suggestions on all my ubuntu nodes and now they're up and running!
No errors and everything is running well so far. I'm running tests on my kascheri12* nodes and subtasks are being computed and Finishing now. Looking good!

**Comment by badb** [comment]
@maaktweluit @dixon-hill It's probably a good idea to put this in Common Problem wiki section!

**Comment by maaktweluit** [comment]
@badb Updated the page with both errors and the solutions.
