### ISSUE TITLE
zipfile FileNotFoundError

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2350]
#### Encountered on 
Linux
GOLEM Version: 0.13.0+dev13.g7c4c89b 
Protocol Version: 25 
golem_messages Version: 1.16.0 

after upgrading binaries by switching files. this message appeared in `golem.log` in first five minutes of running Golem

```
2018-03-12 18:57:13 ERROR    golem.core.async                    Caught async exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/lib/python3.6/threading.py", line 864, in run
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/resource/base/resourceserver.py", line 160, in extract_packages
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/result/resultpackage.py", line 122, in extract
    
  File "/usr/lib/python3.6/zipfile.py", line 1090, in __init__
    
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/ComputerRes/1b1af9c4-3c13-4af1-a2b1-f6c61662607c/resources/scene-Helicopter-27-cycles.blend'
```

**Comment by maaktweluit** [comment]
I suspect this has something to do with the data-dir being used in an old version, `0.13.0+dev12` or before
