### ISSUE TITLE
Exception occured while updating stat 'tasks_requested '

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2351]
#### Encountered on
Linux, binaries
GOLEM Version: 0.13.0+dev13.g7c4c89b 
 Protocol Version: 25 
 golem_messages Version: 1.16.0 

during computations of a task
1 frame Full HD with 5 subtasks (Helicopter) or 10 frames 400x400 with 30 subtasks (Helicopter) 
Golem was running normally, no switching off application

```
2018-03-12 19:18:02 ERROR    golem.core.statskeeper              Exception occured while updating stat 'tasks_requested': OperationalError('database is locked',)
2018-03-12 19:18:04 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 390, in dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 416, in _interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 127, in interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 76, in interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/history.py", line 286, in wrapper
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 731, in _react_to_subtask_result_accepted
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 400, in subtask_accepted
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/transactions/incomeskeeper.py", line 94, in update_awaiting
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 5165, in save
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3458, in execute
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2939, in _execute
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 218, in execute_sql
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 216, in execute_sql
    
peewee.OperationalError: database is locked
```

**Comment by ederenn** [comment]
Encountered it for second time, same day, twice


this time probably due to switching off Golem - restart test
- task with cube 400x400, 2 frames, 6 subtasks, 
- start a task, wait for few subtasks to be verified
- switch it off quickly, wait for timeout with turned off Golem
- turn it on (no restart)



```
2018-03-12 20:13:34 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/lib/python3.6/threading.py", line 864, in run
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/paymentprocessor.py", line 364, in _run
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/paymentprocessor.py", line 247, in sendout
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 5165, in save
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3458, in execute
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2939, in _execute
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 218, in execute_sql
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 216, in execute_sql
    
peewee.OperationalError: database is locked
NoneType: None
```

```
2018-03-12 21:19:02 ERROR    golem.client                        task_server.sync_network failed 
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 210, in execute_sql
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3837, in execute_sql
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 135, in reraise
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
peewee.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 216, in execute_sql
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 1165, in _run
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 115, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 778, in __remove_old_tasks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ranking/helper/trust.py", line 45, in decrease
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ranking/manager/database_manager.py", line 24, in increase_negative_computed
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 4977, in create
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 5170, in save
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3584, in execute
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2939, in _execute
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 218, in execute_sql
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 135, in reraise
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 216, in execute_sql
peewee.OperationalError: database is locked
```

**Comment by ederenn** [comment]
Linux, binaries 

GOLEM Version: 0.13.0+dev1.g7bb905c 
 Protocol Version: 25 
golem_messages Version: 1.16.0

```2018-03-13 16:04:07 ERROR    golem.core.statskeeper              Exception occured while updating stat 'tasks_requested': OperationalError('database is locked',)```
