### ISSUE TITLE
ERROR: AttributeError: 'CannotAssignTask' object has no attribute 'subtask_id'

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#2362]
Seeing this error many times on GOLEM Version: 0.13.0+dev63.gd8bc869 
Ubuntu

```
ERROR    [golem.network.history              ] message_to_model(CannotAssignTask(header=MessageHeader(type_=2003, timestamp=1521058227, encrypted=True), sig=b' \x9d~9HP\x02\xd2\xfe\xc5\xb1C\x05\x95l\x86>\xa3\x9b\x1a\xf3\xa2\x8f\x07\x14\xf8\ty+\xfd^\x02>+\x8f\x01\xc4\x81P~\xea\xd5UA5\xe15\x89\xab\xfc3t!\xfe\xc7\xae[\xe03\x13\xab\xdc\xce\xe7\x01', slots=[['task_id', '3076ea74-eb8f-4109-9f98-29cb1dc53025'], ['reason', 'no_more_subtasks']]), '22628924bfc0a9d9fdb74922183f2a681872a7bfd663ff0c079721506851a0cbee34b9c226a7c542bda1eac9b907da29b698ddac18d402c1f1021132bd0c9ec4', <Actor.Provider: 'provider'>, <Actor.Requestor: 'requestor'>) failed:
Traceback (most recent call last):
  File "/home/kentrendz/golem/golem/network/history.py", line 298, in add
    remote_role=remote_role,
  File "/home/kentrendz/golem/golem/network/history.py", line 271, in message_to_model
    'subtask': msg.subtask_id,
AttributeError: 'CannotAssignTask' object has no attribute 'subtask_id'
```

**Comment by badb** [comment]
Hi!
Can you please make sure that you have run `python setup.py develop` and you are using the proper version of golem-messages?
