### ISSUE TITLE
Found in Golem error log w/version 13.0 

### ISSUE THREAD

**Issue by wp31** [golemfactory/clay#2376]
```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10f9bb550>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f9bb550>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/localcomputer.py", line 69, in run
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/localcomputer.py", line 161, in _get_task_thread
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py", line 46, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/image.py", line 38, in is_available
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/api/image.py", line 143, in inspect_image
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/client.py", line 112, in _get
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f9bb550>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2018-03-15 13:51:05 WARNING  apps.blender                        Crop for verification render failure ConnectionError(MaxRetryError("HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f9bb550>: Failed to establish a new connection: [Errno 60] Operation timed out',))",),) 
2018-03-15 13:52:33 WARNING  golem.task                          Computation failed
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10f0de9b0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f0de9b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/localcomputer.py", line 69, in run
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/localcomputer.py", line 161, in _get_task_thread
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py", line 46, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/image.py", line 38, in is_available
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/api/image.py", line 143, in inspect_image
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/docker/client.py", line 112, in _get
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f0de9b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
2018-03-15 13:52:33 WARNING  apps.blender                        Crop for verification render failure ConnectionError(MaxRetryError("HTTPSConnectionPool(host='192.168.64.18', port=2376): Max retries exceeded with url: /v1.21/images/golemfactory%2Fblender%3A1.4/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f0de9b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))",),) 
```

**Comment by wp31** [comment]
I don't seem to be getting this error anymore.  :)
