### ISSUE TITLE
blender verification error,  IndexError: list index out of range

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2486]
#### Encountered on:

Windows
GOLEM Version: 0.13.0+dev200.g004d33d '
Protocol Version: 26-testnet '
golem_messages Version: 1.17.2 '

from `golem.log`
```
2018-03-23 14:23:56 ERROR    golem.task.taskthread               b'Task computing error'
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem\golem\docker\task_thread.py", line 106, in run
    self.task_computer.task_computed(self)
  File "C:\Users\ederenn\Projects\golem\golem\task\localcomputer.py", line 94, in task_computed
    self.computation_success(task_thread)
  File "C:\Users\ederenn\Projects\golem\golem\task\localcomputer.py", line 105, in computation_success
    self.success_callback(task_thread.result, self._get_time_spent())
  File "C:\Users\ederenn\Projects\golem\apps\blender\task\blendercropper.py", line 213, in crop_rendered
    verification_context.errback, self.crop_counter)
  File "C:\Users\ederenn\Projects\golem\apps\blender\task\blendercropper.py", line 167, in _render_one_crop
    minx, maxx, miny, maxy = verify_ctx.crop_values[crop_number]
IndexError: list index out of range
```

**Comment by Elfoniok** [comment]
Here is fix
https://github.com/golemfactory/golem/pull/2494
