### ISSUE TITLE
Unhandled exception when monitor was unavailable

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2506]
```
Unhandled error in Deferred:
CRITICAL [twisted                            ] Unhandled error in Deferred: 

CRITICAL [twisted                            ]  
Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/twisted/internet/defer.py", 
line 653, in _runCallbacks                                                                                                         
    current.result = callback(current.result, *args, **kw)
  File "/home/etam/code/github/golemfactory/golem/golem/client.py", line 383, in connect
    ports=public_ports)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/pydispatch/dispatcher.py", l
ine 338, in send                                                                                                                   
    **named
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/pydispatch/robustapply.py", 
line 55, in robustApply                                                                                                            
    return receiver(*arguments, **named)
  File "/home/etam/code/github/golemfactory/golem/golem/monitor/monitor.py", line 82, in p2p_listener
    result = self.ping_request(ports)
  File "/home/etam/code/github/golemfactory/golem/golem/monitor/monitor.py", line 112, in ping_request
    result = response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by etam** [comment]
Note that this is quite serious, because it broke the startup procedure of golem and made it not functioning.
