### ISSUE TITLE
Creating new task fails if transaction system doesn't know about funds yet

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#2585]
```
ERROR    [golem.client                       ] Cannot create task {... cut ...}                                                                                                   
Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/golem/golem/client.py", line 658, in create_task
    task = yield self.enqueue_new_task(t_dict)
  File "/home/etam/code/github/golemfactory/golem/golem/client.py", line 533, in enqueue_new_task
    self.funds_locker.lock_funds(task)
  File "/home/etam/code/github/golemfactory/golem/golem/transactions/ethereum/fundslocker.py", line 62, in lock_funds                                                                                                                             
    if tfl.gnt_lock() > gnt - lock_gnt:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by maaktweluit** [comment]
+1 had this too today: restarted golem with task that timed out, restart triggered this error
