### ISSUE TITLE
OSError: cannot identify image file 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2621]
#### Encountered on
Windows
 Golem source 
'GOLEM Version: 0.15.0 '
'Protocol Version: 26 '
'golem_messages Version: 1.17.2 

in terminal window

```ERROR    [golem.client                       ] b'task_server.sync_network failed '
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem\golem\client.py", line 1246, in _run
    self._client.task_server.sync_network()
  File "C:\Users\ederenn\Projects\golem\golem\task\taskserver.py", line 123, in sync_network
    self.__remove_old_tasks()
  File "C:\Users\ederenn\Projects\golem\golem\task\taskserver.py", line 788, in __remove_old_tasks
    nodes_with_timeouts = self.task_manager.check_timeouts()
  File "C:\Users\ederenn\Projects\golem\golem\task\taskmanager.py", line 572, in check_timeouts
    t.computation_failed(s.subtask_id)
  File "C:\Users\ederenn\Projects\golem\golem\core\common.py", line 148, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Users\ederenn\Projects\golem\apps\rendering\task\framerenderingtask.py", line 84, in computation_failed
    self._update_frame_task_preview()
  File "C:\Users\ederenn\Projects\golem\apps\rendering\task\framerenderingtask.py", line 290, in _update_frame_task_preview
    self.__mark_sub_frame(sub, frame, sent_color)
  File "C:\Users\ederenn\Projects\golem\apps\rendering\task\framerenderingtask.py", line 404, in __mark_sub_frame
    with self._open_frame_preview(preview_task_file_path) as img_task:
  File "C:\Users\ederenn\Projects\golem\apps\rendering\task\framerenderingtask.py", line 306, in _open_frame_preview
    return Image.open(preview_file_path)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'C:\\Users\\ederenn\\AppData\\Local\\golem\\golem\\default\\mainnet\\res\\d2665fa2-3d87-11e8-ba71-9d5cb6e59b28\\tmp\\current_task_preview0.PNG'
```

**Comment by ederenn** [comment]
Encountered on:
Windows, Golem version 0.16.0, binary release

appeared in logs during task computations

```
2018-06-18 16:19:24 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\iocpreactor\reactor.py", line 119, in _callEventCallback
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 92, in _cbRead
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 118, in _handleRead
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\iocpreactor\abstract.py", line 75, in _dispatchData
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\iocpreactor\tcp.py", line 75, in dataReceived
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork.py", line 340, in dataReceived
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\tcpnetwork.py", line 366, in _interpret
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\tasksession.py", line 119, in interpret
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\session.py", line 76, in interpret
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\tasksession.py", line 477, in _react_to_want_to_compute_task
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskmanager.py", line 360, in get_next_subtask
    
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\core\task\coretask.py", line 555, in accepting_qed
    
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\blender\task\blenderrendertask.py", line 475, in query_extra_data
    
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 340, in _update_frame_task_preview
    
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 450, in __mark_sub_frame
    
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 352, in _open_frame_preview
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PIL\Image.py", line 2519, in open
    
builtins.OSError: cannot identify image file 'C:\\Users\\ederenn\\AppData\\Local\\golem\\golem\\default\\mainnet\\res\\939eb540-72ff-11e8-a234-9d5cb6e59b28\\tmp\\current_task_preview2.PNG'

2018-06-18 16:19:24 WARNING  apps.core                           b'Waiting for results from Miracolix on 939eb540-72ff-11e8-a234-9d5cb6e59b28'
2018-06-18 16:19:27 ERROR    golem.client                        b'task_server.sync_network failed'
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 1366, in _run
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 137, in sync_network
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 870, in __remove_old_tasks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskmanager.py", line 694, in check_timeouts
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\common.py", line 147, in func_wrapper
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 130, in computation_failed
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 336, in _update_frame_task_preview
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 450, in __mark_sub_frame
  File "C:\BuildbotWorker\buildpackage_windows\build\apps\rendering\task\framerenderingtask.py", line 352, in _open_frame_preview
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PIL\Image.py", line 2519, in open
OSError: cannot identify image file 'C:\\Users\\ederenn\\AppData\\Local\\golem\\golem\\default\\mainnet\\res\\939eb540-72ff-11e8-a234-9d5cb6e59b28\\tmp\\current_task_preview4.PNG'
```
