### ISSUE TITLE
crossbar.error.cannot_start: Failed to start native worker

### ISSUE THREAD

**Issue by alphabt** [golemfactory/clay#2697]
Running `golemapp --mainnet` in Ubuntu errored out with:

```
crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 120. []
```

**Logs**
[golem.log](https://github.com/golemfactory/golem/files/1932711/golem.log)
[golem.error.log](https://github.com/golemfactory/golem/files/1932714/golem.error.log)

**Environment**
Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-1012-azure x86_64)
Azure B1S VM 1G Memory

**Repro**
```
$ wget https://raw.githubusercontent.com/golemfactory/golem/develop/Installer/Installer_Linux/install.sh
--2018-04-20 14:47:31--  https://raw.githubusercontent.com/golemfactory/golem/develop/Installer/Installer_Linux/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12310 (12K) [text/plain]
Saving to: ‘install.sh’

install.sh                    100%[===============================================>]  12.02K  --.-KB/s    in 0s

2018-04-20 14:47:31 (125 MB/s) - ‘install.sh’ saved [12310/12310]

$ chmod +x install.sh
$ ./install.sh
Docker not found. Do you want to install it? (y/n) y


INSTALLING GOLEM DEPENDENCIES



INSTALLING DOCKER

OK


Installing HyperG


Extracting templates from packages: 100%
Extracting templates from packages: 100%

sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting


Docker installed successfully



Done installing Golem dependencies



Installing Golem



Downloading Golem package



Downloading ui package (it may take awhile)



Installing Golem into /home/<snipped>/golem



You need to restart your PC to finish installation

$ sudo shutdown -r now
Connection to <snipped>.westus2.cloudapp.azure.com closed by remote host.
Connection to <snipped>.westus2.cloudapp.azure.com closed.

$ sudo usermod -aG docker $USER
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting

$ golemapp --mainnet

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO     [talkback                           ] Disabling talkback service
INFO     [golemapp                           ] GOLEM Version: 0.15.0
INFO     [golemapp                           ] Protocol Version: 26
INFO     [golemapp                           ] golem_messages Version: 1.17.2
INFO     [golemapp                           ] system: Linux, release: 4.13.0-1012-azure, version: #15-Ubuntu SMP Thu Mar 8 10:47:27 UTC 2018, machine: x86_64
INFO     [golemapp                           ] cpu: GenuineIntel Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz, 1 cores
INFO     [golemapp                           ] memory: 899.5 MiB, swap: 0 Bytes
INFO     [golemapp                           ] Ethereum chain: mainnet
INFO     [golem.db                           ] Creating tables, schema version 14
INFO     [golem.rpc.cert                     ] Creating an RSA key pair: '/home/<snipped>/.local/share/golem/default/mainnet/crossbar/rpc_key.pem'
INFO     [golem.rpc.cert                     ] Creating a self-signed certificate: '/home/<snipped>/.local/share/golem/default/mainnet/crossbar/rpc_cert.pem'
WARNING  [twisted                            ] dropping connection to peer process:3051 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
WARNING  [twisted                            ] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 120.
ERROR    [twisted                            ] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 120.
ERROR    [twisted                            ] ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 120.', []], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 384, in processEnded

  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/controller/native.py", line 82, in connectionLost

  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 500, in errback

  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks

--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks

  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/controller/process.py", line 506, in on_ready_error

autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 120.', []], kwargs={}, enc_algo=None)

ERROR    [twisted                            ] crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 120. []
```

**Comment by badb** [comment]
Quick guess is that 899.5 MiB may not be enough. We will investigate further.
