### ISSUE TITLE
 AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2835]
### encountered on 
golem source version, branch b0.16.0
b'GOLEM Version: 0.15.1+dev309.g398e18d'
b'Protocol Version: 27'
b'golem_messages Version: 2.9.4

```
2018-05-30 14:37:07 ERROR    twisted                             AttributeError: 'str' object has no attribute 'name': Traceback (most recent call last):
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/ederenn/projects/golem/golem/client.py", line 877, in get_subtasks_frames
    return self.task_server.task_manager.get_output_states(task_id)
  File "/Users/ederenn/projects/golem/golem/core/common.py", line 147, in func_wrapper
    return func(*args, **kwargs)
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 792, in get_output_states
    return self.tasks[task_id].get_output_states()
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 166, in get_output_states
    insort(result, (k, v.serialize()))
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 91, in serialize
    return self.status.name, self.started
builtins.AttributeError: 'str' object has no attribute 'name'
```

**Comment by Wiezzel** [comment]
`TaskStatus` was changed from string to enum in https://github.com/golemfactory/golem/pull/2709 Looks like you restored some old task which was incompatible with the new code.

**Comment by Wiezzel** [comment]
Cannot reproduce the issue with any newly-created tasks.
