### ISSUE TITLE
ValueError: unknown file extension: .

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2836]
### encountered on
golem source version, branch b0.16.0

b'GOLEM Version: 0.15.1+dev309.g398e18d'
b'Protocol Version: 27'
b'golem_messages Version: 2.9.4

```
2018-05-30 16:48:58 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "golemapp.py", line 196, in start
    node.start()
  File "/Users/ederenn/projects/golem/golem/node.py", line 117, in start
    self._reactor.run()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/golem_verificator/rendering_verifier.py", line 70, in success
    self.verification_completed()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/golem_verificator/core_verifier.py", line 47, in verification_completed
    result=self._get_answer())
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/golem_verificator/core_verifier.py", line 124, in callback
    entry.cb(*args, **kwargs)
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 212, in verification_finished
    self.verification_finished(subtask_id, verdict, result)
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 147, in verification_finished
    verdict, result)
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 232, in verification_finished
    self.accept_results(subtask_id, result['extra_data']['results'])
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 201, in accept_results
    self._collect_frame_part(num_start, result_file, parts)
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 439, in _collect_frame_part
    self._put_frame_together(frame_num, num_start)
  File "/Users/ederenn/projects/golem/apps/blender/task/blenderrendertask.py", line 633, in _put_frame_together
    image.save(output_file_name, self.output_format)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/PIL/Image.py", line 1878, in save
    raise ValueError('unknown file extension: {}'.format(ext))
builtins.ValueError: unknown file extension: .
```
appears during multiframe, multisubtask task. (more subtasks than frames)
in interface several frames are shown as stuck in `verifying` state - are not finishing at all nor end in timeout. As a result, whole task ends in timeout.
For example: Helicopter scene, Low Res, two frames, two subtasks per frame, task timeout 1 hour, subtask timeout 15 min.

Two subtasks are finished, two in verification. After time of subtask timeout passes (15 minutes), subtasks still staying in verification state until whole task timeout.

 it is possible to see results of computations in second preview window, even though subtask is not finished

<img width="1243" alt="screen shot 2018-05-30 at 16 56 55" src="https://user-images.githubusercontent.com/32061891/40735755-48864a48-643c-11e8-8c05-42e6485d11e4.png">
<img width="757" alt="screen shot 2018-05-30 at 16 56 21" src="https://user-images.githubusercontent.com/32061891/40735774-55704bfa-643c-11e8-8bbb-5e68afaf40d0.png">

in subtask timeout should be included time for verification on requestor's side and added check, if  this time had passed

**Comment by badb** [comment]
Neither me, nor @maaktweluit are not able to reproduce this error. Were the files added by hand or from some scripts? 
@ederenn Can you try to repeat this on Monday?
