### ISSUE TITLE
error on receiving eth balance

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2945]
#### Encountered on:
Mac OS, golem 0.16.1 release binaries, during computations of a task. Task has finished in timeout
```
2018-06-29 15:57:24 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/ethereumtransactionsystem.py", line 234, in _run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/ethereumtransactionsystem.py", line 225, in _refresh_balances
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 160, in get_eth_balance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_sci/client.py", line 109, in get_balance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/eth.py", line 108, in getBalance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/manager.py", line 106, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'missing trie node 18ad5a6ea579094ae896b7da80d2050de01d1a2d16dd565da756e5d7a3ddf07a (path )'}
NoneType: None
```

```
018-06-29 15:57:46 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/ethereumtransactionsystem.py", line 234, in _run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/ethereumtransactionsystem.py", line 225, in _refresh_balances
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 160, in get_eth_balance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_sci/client.py", line 109, in get_balance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/eth.py", line 108, in getBalance
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/web3/manager.py", line 106, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'missing trie node 18ad5a6ea579094ae896b7da80d2050de01d1a2d16dd565da756e5d7a3ddf07a (path )'}
NoneType: None
```

**Comment by ederenn** [comment]
Encountered after waking up suspended machine with running Golem
windows binaries, rc 18.3 
https://buildbot.golem.network/buildbot/#/builders/2/builds/3296

```
2018-12-19 12:11:18 WARNING  golem.ethereum.transactionsystem    Failed to update balances: ValueError({'code': -32000, 'message': 'missing trie node 7608023b6263b2c618f1b371f214a1a0f5a64886b6c7bb7aae45d26117d5e9f5 (path )'},)
2018-12-19 12:11:19 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    
  File "C:\Python36\lib\threading.py", line 864, in run
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\_threads\_threadworker.py", line 46, in work
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\_threads\_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 701, in _run
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\paymentprocessor.py", line 191, in sendout
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\paymentprocessor.py", line 131, in __get_next_batch
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 174, in get_gntb_balance
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 329, in _call
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\contract.py", line 1031, in call
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\contract.py", line 1262, in call_contract_function
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_utils\functional.py", line 22, in inner
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\eth.py", line 270, in call
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 106, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'missing trie node 7608023b6263b2c618f1b371f214a1a0f5a64886b6c7bb7aae45d26117d5e9f5 (path )'}
NoneType: None
```
