### ISSUE TITLE
Unable to use `GNTDeposit` contract

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2948]
it is not possible to run golem from source
 b'GOLEM Version: 0.16.1+dev163.g4d164a7'
 b'Protocol Version: 28'
 b'golem_messages Version: 2.10.0'

```
INFO     [golem_sci.factory                  ] b'Geth version: 1.8.10'
WARNING  [golem_sci.implementation           ] b'Unable to use `GNTDeposit` contract: AttributeError("module 'golem_sci.contracts.data.mainnet' has no attribute 'gntdeposit'",)'
WARNING  [golem_sci.implementation           ] b'Unable to use `Faucet` contract: AttributeError("module 'golem_sci.contracts.data.mainnet' has no attribute 'faucet'",)'
ERROR    [golem.node                         ] b'Stopping because of 'setup client' error: <twisted.python.failure.Failure builtins.AttributeError: 'NoneType' object has no attribute 'events'>'
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\ederenn\Projects\golem\golem\node.py", line 345, in _setup_client
    self.client = self._client_factory(self._keys_auth)
  File "C:\Users\ederenn\Projects\golem\golem\node.py", line 105, in <lambda>
    task_finished_cb=self._try_shutdown
  File "C:\Users\ederenn\Projects\golem\golem\client.py", line 197, in __init__
    address=geth_address,
  File "C:\Users\ederenn\Projects\golem\golem\transactions\ethereum\ethereumtransactionsystem.py", line 68, in __init__
    incomes_keeper=EthereumIncomesKeeper(self._sci),
  File "C:\Users\ederenn\Projects\golem\golem\transactions\ethereum\ethereumincomeskeeper.py", line 33, in __init__
    self._on_forced_subtask_payment,
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\golem_sci\implementation.py", line 693, in subscribe_to_forced_subtask_payments
    cb,
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\golem_sci\implementation.py", line 391, in _create_subscription
    filter_id = contract.events[event_name].createFilter(
AttributeError: 'NoneType' object has no attribute 'events'
WARNING  [twisted                            ] session closed with reason wamp.close.transport_lost [()]
WARNING  [twisted                            ] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 1.
```

**Comment by Slavenin** [comment]
Hi! I install last version golem and this errors return.
```
2018-08-07 17:15:25 WARNING  golem_sci.implementation            Unable to use `GNTDeposit` contract: AttributeError("module 'golem_sci.contracts.data.mainnet' has no attribute 'gntdeposit'",)
2018-08-07 17:15:25 WARNING  golem_sci.implementation            Unable to use `Faucet` contract: AttributeError("module 'golem_sci.contracts.data.mainnet' has no attribute 'faucet'",)
```

**Comment by Krigpl** [comment]
Hi @Slavenin, this is expected as `GNTDeposit` is not yet available on mainnet (and `Faucet` will never be). Nothing to worry about.
