### ISSUE TITLE
Golem dies after first geth's read-timeout

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#2969]
There is a 10 seconds timeout. If connection is done, then Golem fails to start properly.
We have reconnection method implemented and later if Golem was started properly and disconnect with geth later than it tries to reconnect.

**Comment by prekucki** [comment]
```
[u'Err', u'INFO     [golem.client                       ] Client "", datadir: /home/dev/worker-dir-48d15c88713f4798a623246eec43ff1d/run/sid/rinkeby']
[u'Err', u'INFO     [golem.core.hardware                ] updating config: name: custom, num_cores: 1, max_memory_size: 1.4 GiB, max_resource_size: 1.0 GiB']
[u'Err', u'INFO     [golem.core.hardware                ] Config change detected.']
[u'Err', u'INFO     [golem.pay                          ] Node Ethereum address: 0xF012279e053cD61195806eEC7894c7DB8BF88Ed1']
[u'Err', u'INFO     [golem.ethereum                     ] GETH: connecting to remote RPC interface at https://rinkeby.golem.network:55555']
[u'Err', u'INFO     [golem.ethereum                     ] Connected to node in 0.2695481777191162s']
[u'Err', u'INFO     [golem_sci.factory                  ] Geth version: 1.8.2']
[u'Err', u'INFO     [golem_sci.transactionsstorage      ] Initiating TransactionStorage with nonce=0']
[u'Err', u"ERROR    [golem.node                         ] Stopping because of 'setup client' error: <twisted.python.failure.Failure requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='rinkeby.golem.network', port=55555): Read timed out. (read timeout=10)>"]
[u'Err', u'WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..']
[u'Out', u'Sentry is attempting to send 1 pending error messages']
[u'Out', u'Waiting up to 10 seconds']
```

**Comment by etam** [comment]
```
ERROR    [golem.node                         ] Stopping because of 'setup client' error: <twisted.python.failure.Failure requests.ex
ceptions.ReadTimeout: HTTPConnectionPool(host='94.23.17.170', port=55555): Read timed out. (read timeout=10)>                      
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/raven/breadcr
umbs.py", line 375, in getresponse                                                                                                 
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/requests/adap
ters.py", line 440, in send                                                                                                        
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='94.23.17.170', port=55555): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/twisted/inter
net/defer.py", line 653, in _runCallbacks                                                                                          
    current.result = callback(current.result, *args, **kw)
  File "/home/etam/code/github/golemfactory/golem/golem/node.py", line 343, in _setup_client
    self.client = self._client_factory(self._keys_auth)
  File "/home/etam/code/github/golemfactory/golem/golem/node.py", line 101, in <lambda>
    task_finished_cb=self._try_shutdown
  File "/home/etam/code/github/golemfactory/golem/golem/client.py", line 210, in __init__
    ETHEREUM_FAUCET_ENABLED,
  File "/home/etam/code/github/golemfactory/golem/golem/transactions/ethereum/ethereumtransactio
nsystem.py", line 68, in __init__                                                                                                  
    incomes_keeper=EthereumIncomesKeeper(self._sci),
  File "/home/etam/code/github/golemfactory/golem/golem/transactions/ethereum/ethereumincomeskee
per.py", line 27, in __init__                                                                                                      
    self._on_batch_event,
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/golem_sci/imp
lementation.py", line 218, in subscribe_to_batch_transfers                                                                         
    cb,
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/golem_sci/imp
lementation.py", line 396, in _create_subscription                                                                                 
    logs = self._geth_client.get_filter_logs(filter_id)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/golem_sci/cli
ent.py", line 221, in get_filter_logs                                                                                              
    lambda: self.web3.eth.getFilterLogs(filter_id),
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/golem_sci/cli
ent.py", line 227, in _convert_filter_not_found_error                                                                              
    return f()
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/golem_sci/cli
ent.py", line 221, in <lambda>                                                                                                     
    lambda: self.web3.eth.getFilterLogs(filter_id),
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/eth.py",
 line 325, in getFilterLogs                                                                                                        
    "eth_getFilterLogs", [filter_id],
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/manager.
py", line 103, in request_blocking                                                                                                 
    response = self._make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/manager.
py", line 86, in _make_request                                                                                                     
    return request_func(method, params)
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/web3/middleware.py", line 33, i
n middleware                                                                                                                       
    result = make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/gas_price_strategy.py", line 18, in middleware                                                                                  
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/formatting.py", line 50, in apply_formatters                                                                                    
    response = make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/attrdict.py", line 18, in middleware                                                                                            
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/formatting.py", line 50, in apply_formatters                                                                                    
    response = make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/normalize_errors.py", line 9, in middleware                                                                                     
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/formatting.py", line 50, in apply_formatters                                                                                    
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/formatting.py", line 50, in apply_formatters                                                                                    
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/middlewa
re/formatting.py", line 50, in apply_formatters                                                                                    
    response = make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/web3/providers.py", line 14, in
 make_request                                                                                                                      
    return self.provider.make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/golem/ethereum/web3/providers.py", line 14, in
 make_request                                                                                                                      
    return self.provider.make_request(method, params)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/provider
s/rpc.py", line 67, in make_request                                                                                                
    **self.get_request_kwargs()
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/web3/utils/re
quest.py", line 21, in make_post_request                                                                                           
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/requests/sess
ions.py", line 555, in post                                                                                                        
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/requests/sess
ions.py", line 508, in request                                                                                                     
    resp = self.send(prep, **send_kwargs)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/raven/breadcr
umbs.py", line 326, in send                                                                                                        
    resp = real_send(self, request, *args, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/requests/sess
ions.py", line 618, in send                                                                                                        
    r = adapter.send(request, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/venv/lib/python3.6/site-packages/requests/adap
ters.py", line 521, in send                                                                                                        
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='94.23.17.170', port=55555): Read timed out. (read timeout=10)
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by Krigpl** [comment]
This has been solved.
