### ISSUE TITLE
it's not possible to withdraw all available ETH, because of transaction costs

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3028]
withdrawing ETH with button "copy balance" gives error in logs

```
2018-07-12 14:26:41 ERROR    twisted                             NotEnoughFunds: Not enough ETH available. Required: 6196610000000000, available: 5656610000000000: Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 995, in withdraw
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\transactions\ethereum\ethereumtransactionsystem.py", line 150, in withdraw
    
golem.transactions.ethereum.exceptions.NotEnoughFunds: Not enough ETH available. Required: 6196610000000000, available: 5656610000000000
```

it should be possible to withdraw ETH balance minus transaction costs in an automated way

**Comment by mdtanrikulu** [comment]
@ederenn Could you confirm if it is resolved already?

**Comment by ederenn** [comment]
checked on `dev297.g609873b`, Mac and Windows

for Mac is resolved, for Windows still returning error

```2018-07-26 17:54:29 ERROR    twisted                             Exception: Not enough ETH for transaction. Got 0.02104162357125, required 0.02108362357125: Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 1080, in withdraw
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\transactions\ethereum\ethereumtransactionsystem.py", line 218, in withdraw
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 249, in transfer_eth
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 335, in _sign_and_send_transaction
    
builtins.Exception: Not enough ETH for transaction. Got 0.02104162357125, required 0.02108362357125
```

**Comment by Krigpl** [comment]
Fixed
