### ISSUE TITLE
  Exception while processing transaction, in request_blocking raise ValueError(response["error"]

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3059]
#### Encountered on:
golem version 0.16.1+dev250.g5688d9b
Protocol Version: 28
golem_messages Version: 2.10.0

during withdrawing  all ETH tokens from wallet

```
2018-07-18 15:47:05 ERROR    golem_sci.implementation            Exception while processing transaction 0x88fbf5760bdc09472e67d29f4aba0274058655b21e89a1f9fed4fcce0fe8cb1b: ValueError({'code': -32000, 'message': 'known transaction: 88fbf5760bdc09472e67d29f4aba0274058655b21e89a1f9fed4fcce0fe8cb1b'},)
Traceback (most recent call last):
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\golem_sci\implementation.py", line 512, in _process_sent_transactions
    self._geth_client.send(tx)
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\golem_sci\client.py", line 98, in send
    return self.web3.eth.sendRawTransaction(hex_data).hex()
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\web3\eth.py", line 250, in sendRawTransaction
    [raw_transaction],
  File "C:\Users\ederenn\Projects\golem-env\lib\site-packages\web3\manager.py", line 106, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'known transaction: 88fbf5760bdc09472e67d29f4aba0274058655b21e89a1f9fed4fcce0fe8cb1b'}
```

**Comment by Krigpl** [comment]
Fixed in #3080
