### ISSUE TITLE
Start task is empty

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3085]
#### Encountered on:

Mac Os binaries, release 0.16.2 version

during computations of Classroom blender file 
full HD, 5 frames, 10 subtasks, 2h for task, 20 min for subtask

all subtasks were failing - in settings for task all subtasks dots were turning red (failed) after blue (dowloading), no grey dot for verification.

task ended in timeout, all subtasks failed

in `golem.log`

```
2018-07-24 14:50:36 CRITICAL twisted                             An exception was raised from application code while processing a reactor selectable
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/kqreactor.py", line 293, in _doWriteOrRead
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpnetwork.py", line 340, in dataReceived
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpnetwork.py", line 366, in _interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 119, in interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 76, in interpret
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 477, in _react_to_want_to_compute_task
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 360, in get_next_subtask
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/core/task/coretask.py", line 555, in accepting_qed
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 402, in query_extra_data
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 382, in _choose_frames
    
builtins.TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

from cli for several subtasks

```
iMac-ederenn:~ ederenn$ golemcli subtasks show abbe1202-8f3a-11e8-9b03-6015c9f98f86
description: 'path_root: /Users/ederenn/Downloads/classroomgolem, start_task: 5, end_task:
  5, total_tasks: 10, outfilebasename: books, scene_file: /golem/resources/classroom.blend'
node_id: ea132c218557d87ca584a311fc827dd4f2684bb583a276dba909a4c6b871414ab5dbd0e6dc06d1cf490b1d2c2ce94907340d95ee6563d79161b144a49dceff86
node_ip_address: 46.239.40.167
node_name: ryzenGolem
node_performance: '722.9221587848756'
node_port: 0
progress: 1.0
results:
- /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/books_50003.png
status: Failure
stderr: /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/abbe1202-8f3a-11e8-9b03-6015c9f98f86/stderr.log
stdout: /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/abbe1202-8f3a-11e8-9b03-6015c9f98f86/stdout.log
subtask_id: abbe1202-8f3a-11e8-9b03-6015c9f98f86
time_remaining: 0.0
time_started: 1532434281.87556

iMac-ederenn:~ ederenn$ golemcli subtasks show 8ee2434c-8f3d-11e8-abe2-6015c9f98f86
description: 'path_root: /Users/ederenn/Downloads/classroomgolem, start_task: 7, end_task:
  7, total_tasks: 10, outfilebasename: books, scene_file: /golem/resources/classroom.blend'
node_id: 021cbf8b46073aced1689984d3e95df5069362c7782a7a0a920cbe61d810ef6448e0998886e4f57d605f99e351747fe0731f79dba00dadc43e7f657de3fdb138
node_ip_address: 62.108.16.94
node_name: GP102
node_performance: '630.6352230561275'
node_port: 0
progress: 1.0
results:
- /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/books_70004.png
status: Failure
stderr: /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/8ee2434c-8f3d-11e8-abe2-6015c9f98f86/stderr.log
stdout: /Users/ederenn/Library/Application Support/golem/default/mainnet/res/85b0c050-8f3a-11e8-ba9d-6015c9f98f86/tmp/8ee2434c-8f3d-11e8-abe2-6015c9f98f86/stdout.log
subtask_id: 8ee2434c-8f3d-11e8-abe2-6015c9f98f86
time_remaining: 0.0
time_started: 1532435530.3142788
```

**Comment by etam** [comment]
This happened to me also. 0.18.1:
```
2018-11-08 01:00:20 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/data/golem/golem_git/golem/network/transport/tcpnetwork.py", line 333, in dataReceived
    self._interpret(data)
  File "/data/golem/golem_git/golem/network/transport/tcpnetwork.py", line 359, in _interpret
    self.session.interpret(m)
  File "/data/golem/golem_git/golem/task/tasksession.py", line 138, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/data/golem/golem_git/golem/network/transport/session.py", line 75, in interpret
    action(msg)
  File "/data/golem/golem_git/golem/task/tasksession.py", line 537, in _react_to_want_to_compute_task
    msg.num_cores, self.address)
  File "/data/golem/golem_git/golem/task/taskmanager.py", line 407, in get_next_subtask
    node_name
  File "/data/golem/golem_git/apps/blender/task/blenderrendertask.py", line 445, in query_extra_data
    self.total_tasks)
  File "/data/golem/golem_git/apps/rendering/task/framerenderingtask.py", line 381, in _choose_frames
    return [frames[int((start_task - 1) / parts)]], parts
builtins.TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
