### ISSUE TITLE
resource allocation error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3108]
#### Encountered on:

Linux, Golem version: 0.16.1+dev308.g8b5a757

After first launch of Golem or when machine on which Golem is running, is put to sleep, pressing Start/Stop button ends in resource allocation error.

<img width="459" alt="screen shot 2018-07-30 at 20 49 41" src="https://user-images.githubusercontent.com/32061891/43471063-6243e768-94ea-11e8-9a7d-80f6281c6cf5.png">

```
2018-07-30 11:49:19 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'

2018-07-30 11:49:24 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'

2018-07-30 11:49:32 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'

2018-07-30 11:49:36 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'

2018-07-30 11:49:40 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'

2018-07-30 11:49:49 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'
```

**Comment by ederenn** [comment]
encountered again on  Linux  GOLEM Version: 0.17.0+dev99.g6d235f1
```2018-08-28 13:18:52 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'
```

**Comment by ederenn** [comment]
repeated on Windows and Linux
0.18.0 rc binaries
https://buildbot.golem.network/buildbot/#/builders/1/builds/2713

Golem was running for some time, computing tasks with success. App was stopped and started from interface with "Stop/Start Golem" button. After starting error showed up in interface as "Resource allocation error". No additional resources changes, just stopping app.

 in 'golem.log


```2018-10-16 20:20:52 INFO     golem.client                        Pausing ...
2018-10-16 20:20:52 INFO     golem.client                        Paused
2018-10-16 20:20:55 ERROR    twisted                             TypeError: activate_hw_preset() missing 1 required positional argument: 'name': Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 1523, in unwindGenerator
    
builtins.TypeError: activate_hw_preset() missing 1 required positional argument: 'name'
```
To have node working it needed to be restarted three times.
After first time it was still showing resource allocation error.
After second time interface seems to be stuck on "connecting to the network" state

**Comment by etam** [comment]
@mdtanrikulu For me it looks like a problem on Electron side. `env.hw.preset.activate` RPC call expects an argument, but it gets none. And there was nothing changed since it was created.

**Comment by mdtanrikulu** [comment]
@ederenn Does it resolved with previous release? Can we close?

**Comment by ederenn** [comment]
When Golem is stopped and system was restarted, after pressing Start button "resource allocation error" can be seen in interface but it does not crash the app, Golem continues to launch normally.

**Comment by shadeofblue** [comment]
@ederenn is this still an issue then? or can we mark it as resolved?

**Comment by ederenn** [comment]
On Linux, binary golem-0.18.3+dev771.gdeb8b58, electron 0.1.18 it doesn't exist.
On Windows there is another problem. It gives blank in electron. Steps to reproduce:
- Launch Golem, stop it with a button "start/stop"
- restart whole system
- launch Golem from shortcut again, enter password, press "start/stop" button
- it gives blank in electron
