### ISSUE TITLE
ValueError: unknown file extension: .

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3174]
#### Encountered on:
Mac OS, binaries 0.17.0 version

small task 400x400, 4 frames, 4 subtasks, helicopter.blend
task ended in timeout, in interface it was shown that task was still in verification

in 'golem.log`

```
2018-08-10 15:12:20 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golemapp.py", line 188, in start
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 122, in start
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_verificator/blender_verifier.py", line 86, in success
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/golem_verificator/core_verifier.py", line 40, in verification_completed
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/verification_queue.py", line 85, in callback
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/core/task/coretask.py", line 209, in verification_finished
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 147, in verification_finished
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/core/task/coretask.py", line 229, in verification_finished
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 199, in accept_results
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 426, in _collect_frames
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 636, in _put_frame_together
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/PIL/Image.py", line 1878, in save
    
builtins.ValueError: unknown file extension: .
```

nothing in output in json, 
```
      "output_path": "/Users/ederenn/Documents",
        "format": "",
```

```
iMac1017:~ ederenn$ golemcli tasks dump 73bc65a8-9c9d-11e8-b5e7-6015c9f98f86 

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

{
    "duration": 2185.9426097869873,
    "preview": null,
    "id": "73bc65a8-9c9d-11e8-b5e7-6015c9f98f86",
    "name": "heli27_cpur",
    "type": "Blender",
    "subtasks": 4,
    "progress": 0.0,
    "options": {
        "frame_count": 4,
        "output_path": "/Users/ederenn/Documents",
        "format": "",
        "resolution": [
            400,
            400
        ],
        "frames": "1-4",
        "compositing": false
    },
    "time_started": 1533906070.1007931,
    "time_remaining": null,
    "last_updated": 1533907870.061128,
    "status": "Timeout",
    "estimated_cost": "133333333333333336",
    "estimated_fee": "2240000000000000",
    "timeout": "0:30:00",
    "subtask_timeout": "0:10:00",
    "bid": 0.2,
    "resources": [
        "/Users/ederenn/Desktop/pliki testowe/heli27_cpu.blend"
    ],
    "cost": null,
    "fee": null
}
Completed in 0.00 s
```

task created around 3 PM, 30 min timeout

res for that task:
https://drive.google.com/open?id=1oTzWA8usKNJEb-_ko2T-syHPc17k3Y7c

```
iMac1017:~ ederenn$ golemcli tasks subtasks 73bc65a8-9c9d-11e8-b5e7-6015c9f98f86 

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

node         id                                    ETA      status     completion
-----------  ------------------------------------  -------  ---------  ------------
GP102        7fcb8466-9c9d-11e8-9103-6015c9f98f86  0:00:00  Verifying  0.00 %
Pukerud      87666c36-9c9d-11e8-830a-6015c9f98f86  0:00:00  Failure    0.00 %
GolemGuy     88de8238-9c9d-11e8-9d45-6015c9f98f86  0:00:00  Verifying  0.00 %
Tirao        8979cdd8-9c9d-11e8-a728-6015c9f98f86  0:00:00  Verifying  0.00 %
Firstishe_2  ef01b764-9c9e-11e8-98d2-6015c9f98f86  0:00:00  Verifying  0.00 %
```

**Comment by ederenn** [comment]
[golem.log](https://github.com/golemfactory/golem/files/2284109/golem.log)
around 3 PM, 10.08.2018

**Comment by ederenn** [comment]
try to reproduce if possible

**Comment by ederenn** [comment]
not repeated on 19.0
