### ISSUE TITLE
builtins.AttributeError: 'NoneType' object has no attribute 'cur_port' in golem/client.py

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3213]
```
2018-08-22 21:33:47 ERROR    twisted                             AttributeError: 'NoneType' object has no attribute 'cur_port': Traceback (most recent call last):
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/blue/PycharmProjects/golem/golem/client.py", line 1386, in connection_status
    listen_port = self.get_p2p_port()
  File "/home/blue/PycharmProjects/golem/golem/client.py", line 947, in get_p2p_port
    return self.p2pservice.cur_port
builtins.AttributeError: 'NoneType' object has no attribute 'cur_port'
```

**Comment by etam** [comment]
The only way that could happen, is that `connection_status` was called through rpc before `start_network`.

This will be fixed by #2702

**Comment by shadeofblue** [comment]
@etam and what's the plan regarding the merge of #2702 ?

**Comment by etam** [comment]
The plan is to have it merged together with https://github.com/golemfactory/golem-electron/pull/396. I wanted to merge it quickly (https://github.com/golemfactory/golem-electron/pull/396#discussion_r211215697), but @mdtanrikulu insisted on consulting something with @jamuszyn.
