### ISSUE TITLE
Wrong task header received: Deadline already passed

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3230]
Example:
```
2018-08-27 12:20:32 WARNING  golem.task.taskserver               Wrong task header received
Traceback (most recent call last):
  File "/data/golem/golem_git/golem/task/taskserver.py", line 315, in add_task_header
    TaskHeader.validate(th_dict_repr)
  File "/data/golem/golem_git/golem/task/taskbase.py", line 235, in validate
    return TaskFixedHeader.validate(fixed_header)
  File "/data/golem/golem_git/golem/task/taskbase.py", line 156, in validate
    raise ValueError(msg)
ValueError: Deadline already passed 
 task_id = cfc3db7a-a887-11e8-b953-65684fed3648 
 node name = [...]
```

What's worth noting: the task was running and explicitly deleted long ago (about 16 hours). For some reason the header is still propagated.

**Comment by etam** [comment]
There are 2 things to do:
1. Don't write full traceback in such case. A good idea is to change `validate` method to raise a custom exception, which will be handled by simply printing the message. But keep the current generic Exception handler, that prints the traceback, in case something unexpected happens.
2. Find out why outdated headers are propagated and fix that.
