### ISSUE TITLE
Blockchain monitor exception: NoneType is not iterable

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#3237]
```2018-08-28 11:37:31 WARNING  golem.network.transport.tcpnetwork  No addresses for connection given
2018-08-28 11:37:31 WARNING  golem.network.transport.tcpnetwork  No addresses for connection given
2018-08-28 11:37:32 INFO     golem.resources                     Starting resource handshake with 'd276138057ae4593cc9bc834a9a2e515d3aa0e089adb516e1d4c3786797c136b0d95898eee7cfae8ddb532cab426962edb70a3ffbb3ffea2f09e716a5696e150'
2018-08-28 11:37:33 INFO     golem.task.taskkeeper               Adding task '85397e00-aa80-11e8-884d-d276138057ae' support=<SupportStatus ok ({})>
2018-08-28 11:37:33 INFO     golem.task.taskkeeper               Unsupported task 85397e00-aa80-11e8-884d-d276138057ae, reason: {<UnsupportReason.MASK_MISMATCH: 'mask_mismatch'>: '3cb5cdee7597f1c044dc8a4e65e6315c7d2a18aef99bfb915176ce7670495b5b6eb6aa15bc0d90744fcebe06fa8041fb15fd5c32448e9e44d7bf613b663bafdf'}
2018-08-28 11:37:38 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B41766C828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2018-08-28 11:37:38 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B4175754A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2018-08-28 11:37:38 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B4174BCDA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2018-08-28 11:37:38 WARNING  golem.ethereum.node                 GETH: reconnecting to another provider
2018-08-28 11:37:38 ERROR    golem_sci.implementation            Blockchain monitor exception: TypeError("argument of type 'NoneType' is not iterable",)
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 410, in _monitor_blockchain
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 416, in _monitor_blockchain_single
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 430, in _update_block_numbers
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\client.py", line 154, in get_block_number
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\eth.py", line 101, in blockNumber
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 105, in request_blocking
TypeError: argument of type 'NoneType' is not iterable
2018-08-28 11:37:38 INFO     golem.ethereum.node                 GETH: connecting to remote RPC interface at https://geth.golem.network:2137
2018-08-28 11:37:39 INFO     golem.client                        Shutting down ...
2018-08-28 11:37:39 INFO     golem.client                        Stopping network ...
2018-08-28 11:37:39 INFO     golem.network.concent.client        Waiting for received messages queue to empty
2018-08-28 11:37:39 INFO     golem.network.concent.client        <ConcentClientService(Thread-3, started daemon 1084)> stopped
2018-08-28 11:37:39 WARNING  golem.core.processmonitor           Subprocess 7288 terminated
```

**Comment by Krigpl** [comment]
Fixed in https://github.com/golemfactory/golem/pull/3294
