### ISSUE TITLE
restart of timed out subtasks is not working 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3248]
#### Encountered on:
Golem ver. 0.17.0+dev94.g09f3405 

Steps to reproduce:

- create a multisubtask task, switch Golem off, before the task is completed, wait for task timeout.
(in this scenario used: bmw_cp27.blend, 400x400, 2 frames, 10 subtasks, 15 min for a task 5 min for a subtask. 7 subtasks compleated, 3 subtasks in timeout)
- turn Golem on, choose to restart task with restart icon, choose "restart all timed out subtasks"
- task will be restarted, finished subtasks will be shown in status restarted. no new nodes are starting computations

in `golem log`

```
18-08-29 06:06:50 INFO     golem.ethereum.fundslocker          Locking funds for task: '64837992-ab8c-11e8-a929-b4b0ce494777' price: 16666666666666668.000000 num: 10
2018-08-29 06:06:50 INFO     golem.ethereum.transactionsystem    Locking 0.166667 GNT and ETH for 10 payments
2018-08-29 06:06:50 INFO     golem.client                        Enqueue new task "'64837992-ab8c-11e8-a929-b4b0ce494777'"
2018-08-29 06:06:50 INFO     golem.network.p2p.p2pservice        Estimated network size: 64
2018-08-29 06:06:50 WARNING  golem.network.p2p.p2pservice        Cannot compute percentile rank. No host performance info is available
2018-08-29 06:06:50 INFO     golem.client                        Task 64837992-ab8c-11e8-a929-b4b0ce494777 initial mask size: 0 expected number of providers: 20 potential number of providers: 0
2018-08-29 06:06:50 INFO     golem.task.taskmanager              Task 64837992-ab8c-11e8-a929-b4b0ce494777 added
2018-08-29 06:06:51 INFO     golem.task.taskmanager              Task 64837992-ab8c-11e8-a929-b4b0ce494777 started
2018-08-29 06:06:55 WARNING  apps.core                           This is not my subtask 66035c30-ab8c-11e8-8b7f-b4b0ce494777
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 147, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/core/task/coretask.py", line 470, in _mark_subtask_failed
KeyError: '0e291e07-10a8-40ab-a5fe-986ba37a5d56'
2018-08-29 06:06:55 WARNING  apps.core                           This is not my subtask 6615ff70-ab8c-11e8-9039-b4b0ce494777
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 147, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/core/task/coretask.py", line 470, in _mark_subtask_failed
KeyError: 'cb49e43f-dcc0-48fe-8f80-bc13f091c02d'
2018-08-29 06:06:56 WARNING  apps.core                           This is not my subtask 662fea54-ab8c-11e8-86d4-b4b0ce494777
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 147, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/core/task/coretask.py", line 470, in _mark_subtask_failed
KeyError: 'b41e1b1a-17e0-41eb-8a51-9d0b3253fefe'
2018-08-29 06:06:56 INFO     golem.task.taskserver               requestor node is blacklisted; 380f9240faff8d2076da44447ed62e3a9319ac8da13c73c4438027347feeda2f7130d8da23804777444f267920efded556484fe48d5adc34dac9a81da26ba7c5
2018-08-29 06:06:57 INFO     golem.ethereum.paymentprocessor     Next sendout in 78748 s
2018-08-29 06:07:01 INFO     golem.task.taskserver               requestor node is blacklisted; 380f9240faff8d2076da44447ed62e3a9319ac8da13c73c4438027347feeda2f7130d8da23804777444f267920efded556484fe48d5adc34dac9a81da26ba7c5
2018-08-29 06:07:07 INFO     golem.task.taskserver               requestor node is blacklisted;
```

from Golem cli:

```
ederenn@ubuntu:~$ golemcli tasks subtasks 64837992-ab8c-11e8-a929-b4b0ce494777
node             id                                    ETA      status    completion
---------------  ------------------------------------  -------  --------  ------------
SerbianGolem     655d4886-ab8c-11e8-a7fa-b4b0ce494777  0:00:00  Finished  100.00 %
defitek          6566c9e8-ab8c-11e8-988d-b4b0ce494777  0:00:00  Finished  100.00 %
                 66035c30-ab8c-11e8-8b7f-b4b0ce494777  0:00:00  Restart   0.00 %
                 6615ff70-ab8c-11e8-9039-b4b0ce494777  0:00:00  Restart   0.00 %
                 662fea54-ab8c-11e8-86d4-b4b0ce494777  0:00:00  Restart   0.00 %
LegendDedoGolem  6650d8d2-ab8c-11e8-bff2-b4b0ce494777  0:00:00  Finished  100.00 %
Cloud9           66781866-ab8c-11e8-bdfa-b4b0ce494777  0:00:00  Finished  100.00 %
defitek          66a5ad6e-ab8c-11e8-b869-b4b0ce494777  0:00:00  Finished  100.00 %
defitek          66ddd664-ab8c-11e8-a397-b4b0ce494777  0:00:00  Finished  100.00 %
defitek          6717a9b6-ab8c-11e8-97c7-b4b0ce494777  0:00:00  Finished  100.00 %
```

restarted subtasks have status in logs:   `This is not my subtask 662fea54-ab8c-11e8-86d4-b4b0ce494777`

same situation is, when subtask is restarted manually from second preview window after the task ends in timeout

**Comment by etam** [comment]
The same happens, when restarting successfully finished subtask.

**Comment by etam** [comment]
#3280

**Comment by shadeofblue** [comment]
I believe it's fixed
