### ISSUE TITLE
ModuleNotFoundError: No module named 'golem.transactions'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3250]
Encountered on:

Linux
Golem ver. 0.17.0+dev94.g09f3405

```
0.000000 GNT, 0.023577 ETH
2018-08-29 16:04:50 ERROR    golem.node                          Stopping because of 'setup client' error: <twisted.python.failure.Failure builtins.ModuleNotFoundError: No module named 'golem.transactions'>
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 359, in _setup_client
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 109, in <lambda>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 197, in __init__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/fundslocker.py", line 31, in __init__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/fundslocker.py", line 71, in restore
ModuleNotFoundError: No module named 'golem.transactions'
```

**Comment by shadeofblue** [comment]
allegedly fixed in: https://github.com/golemfactory/golem/pull/3251
