### ISSUE TITLE
Golem seed 0.17.1 crashed on error when it couldn't connect to geth

### ISSUE THREAD

**Issue by ktomala** [golemfactory/clay#3285]
```

Sep 07 11:40:10 ip-172-31-58-191 python[3696]: ERROR    [golem_sci.implementation           ] Blockchain monitor exception: TypeError("argument of type 'NoneType' is no
Sep 07 11:40:10 ip-172-31-58-191 python[3696]: Traceback (most recent call last):
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 410, in _monitor_blockc
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     self._monitor_blockchain_single()
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 416, in _monitor_blockc
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     if not self._update_block_numbers():
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 430, in _update_block_n
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     latest_block = self._geth_client.get_block_number()
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/golem_sci/client.py", line 154, in get_block_number
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     return self.web3.eth.blockNumber
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/web3/eth.py", line 101, in blockNumber
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     return self.web3.manager.request_blocking("eth_blockNumber", [])
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:   File "/data/golem/golem_git/venv/lib/python3.6/site-packages/web3/manager.py", line 105, in request_blocking
Sep 07 11:40:10 ip-172-31-58-191 python[3696]:     if "error" in response:
Sep 07 11:40:10 ip-172-31-58-191 python[3696]: TypeError: argument of type 'NoneType' is not iterable

**Comment by Krigpl** [comment]
Same error as in #3237 - and hopefully already fixed, closing.
