### ISSUE TITLE
AttributeError: 'RenderingTaskDefinition' object has no attribute 'concent_enabled'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3300]
```
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/Users/ederenn/projects/golem/golem/client.py", line 293, in start
    self.start_network()
  File "/Users/ederenn/projects/golem/golem/client.py", line 381, in start_network
    self.clean_old_tasks()
  File "/Users/ederenn/projects/golem/golem/client.py", line 1350, in clean_old_tasks
    for task in self.get_tasks():
  File "/Users/ederenn/projects/golem/golem/client.py", line 1062, in get_tasks
    return list(filter(None, tasks))
  File "/Users/ederenn/projects/golem/golem/client.py", line 1060, in <genexpr>
    tasks = (self.get_task(task_id) for task_id in task_ids)
  File "/Users/ederenn/projects/golem/golem/client.py", line 1022, in get_task
    task_dict = self.task_server.task_manager.get_task_dict(task_id)
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 984, in get_task_dict
    self.get_task_definition_dict(task))
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 155, in get_task_definition_dict
    return task_type.task_builder_type.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/blender/task/blenderrendertask.py", line 662, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 515, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/rendering/task/renderingtask.py", line 295, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 618, in build_dictionary
    return definition.to_dict()
  File "/Users/ederenn/projects/golem/apps/core/task/coretaskstate.py", line 122, in to_dict
    'concent_enabled': self.concent_enabled
AttributeError: 'RenderingTaskDefinition' object has no attribute 'concent_enabled'
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
INFO     [golem.network.concent.client       ] Waiting for received messages queue to empty
INFO     [golem.network.concent.client       ] <ConcentClientService(Thread-1, started daemon 123145428717568)> stopped
WARNING  [golem.core.processmonitor          ] Subprocess 901 terminated
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..

```

#### Encountered on:
```
INFO     [golemapp                           ] GOLEM Version: 0.17.1+dev184.g3f6c514
INFO     [golemapp                           ] Protocol Version: 29
INFO     [golemapp                           ] golem_messages Version: 2.12.3
```
after trying to run Golem from source, on develop branch, update from Golem 0.17.0

**Comment by ederenn** [comment]
same problem when switching from 0.17.1 to develop 0.17.1+dev184.g3f6c514

```
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/Users/ederenn/projects/golem/golem/client.py", line 293, in start
    self.start_network()
  File "/Users/ederenn/projects/golem/golem/client.py", line 381, in start_network
    self.clean_old_tasks()
  File "/Users/ederenn/projects/golem/golem/client.py", line 1350, in clean_old_tasks
    for task in self.get_tasks():
  File "/Users/ederenn/projects/golem/golem/client.py", line 1062, in get_tasks
    return list(filter(None, tasks))
  File "/Users/ederenn/projects/golem/golem/client.py", line 1060, in <genexpr>
    tasks = (self.get_task(task_id) for task_id in task_ids)
  File "/Users/ederenn/projects/golem/golem/client.py", line 1022, in get_task
    task_dict = self.task_server.task_manager.get_task_dict(task_id)
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 996, in get_task_dict
    self.get_task_definition_dict(task))
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 155, in get_task_definition_dict
    return task_type.task_builder_type.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/blender/task/blenderrendertask.py", line 662, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 515, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/rendering/task/renderingtask.py", line 295, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 618, in build_dictionary
    return definition.to_dict()
  File "/Users/ederenn/projects/golem/apps/core/task/coretaskstate.py", line 122, in to_dict
    'concent_enabled': self.concent_enabled
AttributeError: 'RenderingTaskDefinition' object has no attribute 'concent_enabled'
```

**Comment by shadeofblue** [comment]
we should ensure that's still an issue by:
1) running 0.17.1 on testnet by executing some tasks on it
2) upgrading to 0.18.0 and seeing if Golem can still run normally and list already computed tasks

**Comment by jiivan** [comment]
Tested on *0.17.1* vs current *b0.18.0* (9c0da23) and got:
```python
Traceback (most recent call last):
  File "/home/dariusz/repo/golem2/golem/client.py", line 292, in start
    self.start_network()
  File "/home/dariusz/repo/golem2/golem/client.py", line 380, in start_network
    self.clean_old_tasks()
  File "/home/dariusz/repo/golem2/golem/client.py", line 1438, in clean_old_tasks
    for task in self.get_tasks():
  File "/home/dariusz/repo/golem2/golem/client.py", line 1130, in get_tasks
    return list(filter(None, tasks))
  File "/home/dariusz/repo/golem2/golem/client.py", line 1128, in <genexpr>
    tasks = (self.get_task(task_id) for task_id in task_ids)
  File "/home/dariusz/repo/golem2/golem/client.py", line 1090, in get_task
    task_dict = self.task_server.task_manager.get_task_dict(task_id)
  File "/home/dariusz/repo/golem2/golem/task/taskmanager.py", line 1028, in get_task_dict
    self.get_task_definition_dict(task))
  File "/home/dariusz/repo/golem2/golem/task/taskmanager.py", line 163, in get_task_definition_dict
    return task_type.task_builder_type.build_dictionary(definition)
  File "/home/dariusz/repo/golem2/apps/blender/task/blenderrendertask.py", line 704, in build_dictionary
    dictionary = super().build_dictionary(definition)
  File "/home/dariusz/repo/golem2/apps/rendering/task/framerenderingtask.py", line 512, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/home/dariusz/repo/golem2/apps/rendering/task/renderingtask.py", line 304, in build_dictionary
    dictionary = parent.build_dictionary(definition)
  File "/home/dariusz/repo/golem2/apps/core/task/coretask.py", line 623, in build_dictionary
    return definition.to_dict()
  File "/home/dariusz/repo/golem2/apps/core/task/coretaskstate.py", line 114, in to_dict
    'compute_on': self.compute_on,
AttributeError: 'RenderingTaskDefinition' object has no attribute 'compute_on'
```
