### ISSUE TITLE
golem upgrade from 0.17.0 to 0.17.1 fails with "Exception: Storage already exists, can't override

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3305]
first run of Golem after update from 0.17.0 to 0.17.1 on Mac OS 
Golem seemed to hang on
`2018-09-12 15:09:11 INFO     golem.ethereum.transactionsystem    Initializing transaction storage from old path: /Users/ederenn/Library/Application Support/golem/default/mainnet/transactions.json`

after running Golem on debug got:

```
DEBUG    [raven.base.Client                  ] Sending message of length 2803 to https://talkback.golem.network/api/5/store/
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golemapp.py", line 269, in <module>
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golemapp.py", line 182, in start
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 81, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 94, in backwards_compatibility_tx_storage
Exception: Storage already exists, can't override
[13190] Failed to execute script golemapp
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
iMac1017:~ ederenn$
```

**Comment by maaktweluit** [comment]
@shadeofblue was this fixed in the linked PR?

**Comment by Krigpl** [comment]
Ancient.
