### ISSUE TITLE
status of a whole task is not updated

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3370]
status of a whole task is not updated

#### Encountered on: 

Mac OS, source, GOLEM Version: 0.17.1+dev330.gfcfdf5b

task:
20 frames, 40 subtasks, 400x400, task timeout 1 hour, subtask timeout 10 min

all subtasks of a task are computed with success both in cli and interface

```
(venv) iMac1017:golem ederenn$ python golemcli.py tasks subtasks f9de82ec-c562-11e8-95a7-6015c9f98f86 --mainnet
node            id                                    ETA      status    completion
--------------  ------------------------------------  -------  --------  ------------
mf.ubuntu/1     083ad836-c563-11e8-b649-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  0b3eaf94-c563-11e8-b37c-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     0bcc16e2-c563-11e8-8e01-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  3c6e4bba-c563-11e8-ba6b-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     5f384a38-c563-11e8-b0eb-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     6b23651c-c563-11e8-81c0-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  72aa5da4-c563-11e8-8911-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     a1fa2422-c563-11e8-bd2a-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     acb0f21a-c563-11e8-a86f-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c0542c24-c563-11e8-ad98-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     ce14a69a-c563-11e8-924a-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  f105b9a8-c563-11e8-bc7a-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     fc8d9f06-c563-11e8-831e-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     133cf062-c564-11e8-af07-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  227cfc8c-c564-11e8-b05c-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     467724fa-c564-11e8-9adb-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     509cd006-c564-11e8-8bea-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  708f484c-c564-11e8-b2c4-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     7b821164-c564-11e8-af38-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     911cb6c8-c564-11e8-a4db-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  a0d8230c-c564-11e8-beda-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     c608c0f4-c564-11e8-ac94-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     d0bdf38c-c564-11e8-81e4-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  ec224a58-c564-11e8-b803-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     f64f0c4c-c564-11e8-a28d-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     1a0e078c-c565-11e8-b8b4-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  2065ea86-c565-11e8-9702-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     3c0ca0ca-c565-11e8-8301-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     4628c82c-c565-11e8-9857-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     6958dc74-c565-11e8-88b8-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  7506cdba-c565-11e8-b65e-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     91dc9f34-c565-11e8-ba08-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     9ad08608-c565-11e8-beae-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c0203d74-c565-11e8-b3d0-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     ca7aaa9e-c565-11e8-9d92-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/1     db2fbfb6-c565-11e8-8da8-6015c9f98f86  0:00:00  Failure   0.00 %
oncoming storm  f0684038-c565-11e8-99ba-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     1201e370-c566-11e8-9266-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     33fb5466-c566-11e8-94ca-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  3e7db50a-c566-11e8-b1de-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     4de77b24-c567-11e8-940d-6015c9f98f86  0:00:00  Finished  100.00 %
(venv) iMac1017:golem ederenn$ 
```

task itself has ended in timeout 

```
f9de82ec-c562-11e8-95a7-6015c9f98f86  1:25:27          40  Timeout   50.00 %
(venv) iMac1017:golem ederenn$ 
```

<img width="480" alt="screen shot 2018-10-01 at 13 38 34" src="https://user-images.githubusercontent.com/32061891/46291174-17324b00-c58e-11e8-9066-f61d6281881a.png">

logs
https://drive.google.com/open?id=1btRdW90rhZsAfmOSg0cQmvDyHnc8Oe91

**Comment by ederenn** [comment]
from debug  of another task
```
INFO     [apps.core                          ] Caught error unknown file extension: .
Traceback (most recent call last):
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/PIL/Image.py", line 1876, in save
    format = EXTENSION[ext]
KeyError: '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 244, in verification_finished
    self.accept_results(subtask_id, result['extra_data']['results'])
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 202, in accept_results
    self._collect_frame_part(num_start, result_file, parts)
  File "/Users/ederenn/projects/golem/apps/rendering/task/framerenderingtask.py", line 440, in _collect_frame_part
    self._put_frame_together(frame_num, num_start)
  File "/Users/ederenn/projects/golem/apps/blender/task/blenderrendertask.py", line 682, in _put_frame_together
    image.save(output_file_name, self.output_format)
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/PIL/Image.py", line 1878, in save
    raise ValueError('unknown file extension: {}'.format(ext))
ValueError: unknown file extension: .
```

**Comment by ederenn** [comment]
```WARNING  [apps.blender.task.blenderrendertask] Trying to save /Users/ederenn/Documents/the great white sharkkk1.0001. failed, ValueError('unknown file extension: .',)```

**Comment by Elfoniok** [comment]
Above exception is caused by the result of some other bug which causing the blenderrendertask file extension to disappear (as one can see from above log) and crash saving image. 

Proper error handling will be added to mitigate this error. However this not solve problem with task status not updating. Either the original cause (which is unknown, ederenn can provide more details about problems with output format not specified) or even something else might causing this (in example still not fixed updating preview from different threads).

**Comment by ederenn** [comment]
https://github.com/golemfactory/golem-electron/issues/445
most likely related

**Comment by ederenn** [comment]
still observed GOLEM Version: 0.17.1+dev340.g9b9ed2f

cli for task:

`16bd1a98-c65a-11e8-bae0-6015c9f98f86  2:34:53                  60  Computing  36.67 %`
`16bd1a98-c65a-11e8-bae0-6015c9f98f86  4:30:19                  60  Timeout   36.67 %`

```
(venv) iMac1017:golem ederenn$ python golemcli.py --mainnet tasks subtasks 16bd1a98-c65a-11e8-bae0-6015c9f98f86 
node            id                                    ETA      status    completion
--------------  ------------------------------------  -------  --------  ------------
oncoming storm  2330ccac-c65a-11e8-a7eb-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  6e08e688-c65a-11e8-9382-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  9e43c018-c65a-11e8-be3a-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  e82af8ac-c65a-11e8-9aa8-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  1873971c-c65b-11e8-9138-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  62f3354a-c65b-11e8-93de-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  92a34e10-c65b-11e8-9ac3-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  dfb1b1ec-c65b-11e8-832b-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  0e2f5722-c65c-11e8-9d40-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  5818c40c-c65c-11e8-afb1-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  872dc21c-c65c-11e8-b29d-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  d4110b1e-c65c-11e8-93c5-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  03bfb568-c65d-11e8-b853-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  4da82e78-c65d-11e8-8ebc-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  7d5586a2-c65d-11e8-a428-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c7444174-c65d-11e8-8ec0-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  f786a01e-c65d-11e8-ba7c-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  446a0774-c65e-11e8-a675-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  74b13a5e-c65e-11e8-9dfc-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c19485e2-c65e-11e8-9296-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  f0aabdd8-c65e-11e8-b3ae-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  3d8df306-c65f-11e8-8e7f-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  6dd55946-c65f-11e8-bce2-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  b7bdc870-c65f-11e8-8cac-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  e76c72d8-c65f-11e8-a47b-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  344fe9c2-c660-11e8-b37e-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  63fe7c1a-c660-11e8-ae75-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  b0495cf4-c660-11e8-96c8-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  df5f47c2-c660-11e8-8373-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  2c42c2d0-c661-11e8-b5e3-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  5bf1837a-c661-11e8-8879-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  a96bd576-c661-11e8-b81b-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  d91c09ba-c661-11e8-b89f-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  25ff3cc2-c662-11e8-a9fa-6015c9f98f86  0:00:00  Finished  100.00 %
mf.ubuntu/2     27099680-c662-11e8-81ad-6015c9f98f86  0:00:00  Failure   100.00 %
oncoming storm  55ae0fb6-c662-11e8-9b74-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  855cf9ca-c662-11e8-9a01-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  cf45303e-c662-11e8-8f73-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  ff8c9c28-c662-11e8-9eab-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  4a0df936-c663-11e8-aed8-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  7924594a-c663-11e8-9022-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c69fa58a-c663-11e8-bbf6-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  f8181502-c663-11e8-a5de-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  459431d0-c664-11e8-9eb0-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  76743ce6-c664-11e8-b676-6015c9f98f86  0:00:00  Failure   0.00 %
```

finished subtasks with success: 43 out of 60


[dev340g9b9ed2f.log](https://github.com/golemfactory/golem/files/2439174/dev340g9b9ed2f.log)

**Comment by ederenn** [comment]
repeated on source, branch b0.18.0

GOLEM Version: 0.17.1+dev381.g9c0da23, rendering on GPU, mainnet

task was uploaded manually from GUI, **Blender file is in PNG format**
resolution set from user's presets 
all subtasks were finished but task has ended in timeout

from golemcli for task: 

`5e9c6950-c8b1-11e8-88a5-6015c9f98f86  1:50:46                   8  Timeout   50.00 %`

```
(venv) iMac1017:golem ederenn$ python golemcli.py --mainnet tasks dump 5e9c6950-c8b1-11e8-88a5-6015c9f98f86
{
    "duration": 6670.636889219284,
    "preview": null,
    "id": "5e9c6950-c8b1-11e8-88a5-6015c9f98f86",
    "name": "Table_GPU4",
    "type": "Blender_NVGPU",
    "subtasks": 8,
    "progress": 0.5,
    "options": {
        "frame_count": 4,
        "output_path": "/Users/ederenn/Documents",
        "format": "",
        "resolution": [
            400,
            400
        ],
        "frames": "1-4",
        "compositing": false
    },
    "time_started": 1538752475.8599958,
    "time_remaining": 6670.636889219284,
    "last_updated": 1538754276.548077,
    "status": "Timeout",
    "estimated_cost": "266666666666666672",
    "estimated_fee": "1344000000000000",
    "compute_on": "gpu",
    "timeout": "0:30:00",
    "subtask_timeout": "0:10:00",
    "bid": 0.2,
    "resources": [
        "/Users/ederenn/Desktop/GPUvsCPU/Table_GPU.blend"
    ],
    "concent_enabled": false,
    "cost": null,
    "fee": null
}
```

for subtasks:

```
(venv) iMac1017:golem ederenn$ python golemcli.py --mainnet tasks subtasks  5e9c6950-c8b1-11e8-88a5-6015c9f98f86
node            id                                    ETA      status    completion
--------------  ------------------------------------  -------  --------  ------------
oncoming storm  6b891598-c8b1-11e8-a8a5-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  7cd37f80-c8b1-11e8-92d5-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  8ce9ac9e-c8b1-11e8-ab9d-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  9d9a3254-c8b1-11e8-9b67-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  b0acdcb6-c8b1-11e8-a04d-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  c0c49288-c8b1-11e8-a7d1-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  d0dc9166-c8b1-11e8-9c0c-6015c9f98f86  0:00:00  Finished  100.00 %
oncoming storm  e0f2d36c-c8b1-11e8-aa23-6015c9f98f86  0:00:00  Finished  100.00 %
```


(If all settings for task were set manually task has been finished successfully)

**Comment by shadeofblue** [comment]
@ederenn please verify if it's reproducible under 0.18.2 -> plus suggest a way to reproduce reliably

**Comment by ederenn** [comment]
not seen in current (18.3) version
