### ISSUE TITLE
AttributeError: module 'golem_sci.contracts' has no attribute 'GNT'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3400]
#### Encountered on:

source, develop, mainnet, Windows
Golem version 0.17.1+dev411.g283898a

when installing `python setup.py develop`
```
(golem-env) C:\Users\ederenn\Projects\golem>python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from golem.docker.manager import DockerManager
  File "C:\Users\ederenn\Projects\golem\golem\docker\manager.py", line 10, in <module>
    from golem.docker.config import DockerConfigManager, APPS_DIR, IMAGES_INI, \
  File "C:\Users\ederenn\Projects\golem\golem\docker\config.py", line 6, in <module>
    from golem.core.hardware import cpu_cores_available
  File "C:\Users\ederenn\Projects\golem\golem\core\hardware.py", line 7, in <module>
    from golem.appconfig import \
  File "C:\Users\ederenn\Projects\golem\golem\appconfig.py", line 8, in <module>
    from golem.config.active import ENABLE_TALKBACK
  File "C:\Users\ederenn\Projects\golem\golem\config\active.py", line 13, in <module>
    from golem.config.environments.testnet import *  # noqa
  File "C:\Users\ederenn\Projects\golem\golem\config\environments\testnet.py", line 27, in <module>
    class EthereumConfig:
  File "C:\Users\ederenn\Projects\golem\golem\config\environments\testnet.py", line 42, in EthereumConfig
    contracts.GNT: '0x924442A66cFd812308791872C4B242440c108E19',
AttributeError: module 'golem_sci.contracts' has no attribute 'GNT'
````

**Comment by shadeofblue** [comment]
[ probably a temporary issue in requirements vs golem core code - we didn't see it afterwards ]
