### ISSUE TITLE
Golem shouldn't try to lock the deposit with the Concent service disabled

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3425]
When golem is running with Concent disabled (e.g. specifically, when running on mainnet now), it should probably not try to lock the deposit...

```
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/blue/golem/golem/golem/ethereum/transactionsystem.py", line 756, in _run
    self.concent_withdraw()
  File "/home/blue/golem/golem/golem/ethereum/transactionsystem.py", line 617, in concent_withdraw
    timelock = self.concent_timelock()
  File "/home/blue/golem/golem/golem/ethereum/transactionsystem.py", line 552, in concent_timelock
    account_address=account_address,
  File "/home/blue/.virtualenvs/golem/lib/python3.6/site-packages/golem_sci/implementation.py", line 761, in get_deposit_locked_until
    self._gntdeposit.functions.getTimelock(account_address))
builtins.AttributeError: 'NoneType' object has no attribute 'functions'
```

**Comment by shadeofblue** [comment]
duplicate of: https://github.com/golemfactory/golem/issues/3398
