### ISSUE TITLE
autobahn.wamp.exception.ProtocolError: Unexpected message <class 'autobahn.wamp.message.Abort'>

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3450]
#### Encountered on:
Mac OS, binaries, rc 0.18.0

https://buildbot.golem.network/buildbot/#/builders/7/builds/2650

after restarting golem in interface was shown error "restart golem"
in `golem.log`

Golem from binaries was running, it has been closed after successful providing - quit from interface and dock.  Restarted from spotlight, encountered this error, restarted for second time (again quit from interface and dock, and restart from spotlight), encountered error for the second time in row.

```
2018-10-16 16:03:28 CRITICAL twisted                             Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/crossbar/router/session.py", line 533, in onMessage
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/crossbar/router/router.py", line 285, in process
autobahn.wamp.exception.ProtocolError: Unexpected message <class 'autobahn.wamp.message.Abort'>
```

[golem.log](https://github.com/golemfactory/golem/files/2483827/golem.log)

**Comment by shadeofblue** [comment]
@ederenn has this issue repeated itself lately? were there any more issues or just the error message?

**Comment by mdtanrikulu** [comment]
Had the same issue and there was an error message on electron console, when I have the error.
```
WS: connection error: wamp.error.protocol_violation Can not encode message
```
