### ISSUE TITLE
setup.py imports golem code, requires dependencies, it's supposed to install

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3485]
Running `setup.py develop` in a clean new environment fails:

```
Traceback (most recent call last):
  File "./setup.py", line 13, in <module>
    from golem.docker.manager import DockerManager
  File "/home/etam/code/github/golemfactory/golem/golem/docker/manager.py", line 10, in <module>
    from golem.docker.config import DockerConfigManager, APPS_DIR, IMAGES_INI, \
  File "/home/etam/code/github/golemfactory/golem/golem/docker/config.py", line 6, in <module>
    from golem.core.hardware import cpu_cores_available
  File "/home/etam/code/github/golemfactory/golem/golem/core/hardware.py", line 3, in <module>
    import humanize
ModuleNotFoundError: No module named 'humanize'
```

Workaround: use `pip install -r requirements.txt` before.

**Comment by Wiezzel** [comment]
Is `setup.py develop` really supposed to install dependencies? I **never** run it without installing the requirements first.

**Comment by etam** [comment]
> Is `setup.py develop` really supposed to install dependencies?

I think it does.

https://caremad.io/posts/2013/07/setup-vs-requirement/
https://stackoverflow.com/a/49684835/952263
