### ISSUE TITLE
RuntimeError: Message unsigned

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3516]
#### Encountered on:
Mac OS,  develop, Golem version 0.18.1+dev162.g9ba999a, mainnet

requested file: animation blender_discboy, used frame 20th; 1 frame, 10 subtasks

in `golem.log`

```
2018-11-05 15:27:49 INFO     apps.blender.verification           Finished verification of subtask 'a18dbee8-e106-11e8-a66e-6015c9f98f86'
2018-11-05 15:27:57 INFO     golem.ethereum.paymentprocessor     Payment a18dbe to 0xe855 (0.050000)
2018-11-05 15:27:57 INFO     golem.ethereum.paymentprocessor     GNTB reserved 2.116667
2018-11-05 15:27:57 INFO     golem.ethereum.fundslocker          Removing subtask lock for task '955120e8-e106-11e8-ba05-6015c9f98f86'
2018-11-05 15:27:57 INFO     golem.ethereum.transactionsystem    Unlocking 0.050000 GNT and ETH for 1 payments
2018-11-05 15:27:57 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "golemapp.py", line 184, in start
    node.start()
  File "/Users/ederenn/projects/golem/golem/node.py", line 158, in start
    self._reactor.run()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/ederenn/golem/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/Users/ederenn/projects/golem/apps/blender/verification_queue.py", line 84, in callback
    result=args[0][2])
  File "/Users/ederenn/projects/golem/apps/core/task/coretask.py", line 215, in verification_finished_
    verification_finished()
  File "/Users/ederenn/projects/golem/golem/core/common.py", line 195, in func_wrapper
    return func(*args, **kwargs)
  File "/Users/ederenn/projects/golem/golem/task/taskmanager.py", line 753, in verification_finished_
    verification_finished()
  File "/Users/ederenn/projects/golem/golem/task/tasksession.py", line 254, in verification_finished
    remote_role=Actor.Provider,
  File "/Users/ederenn/projects/golem/golem/network/history.py", line 295, in add
    raise RuntimeError("Message unsigned")
builtins.RuntimeError: Message unsigned
```

**Comment by ederenn** [comment]
fix for unassigned messages https://github.com/golemfactory/golem/pull/3515
