### ISSUE TITLE
Golemapp crashes after switching from source Golem to binary Golem

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3527]
#### Encountered on:
Mac OS

running first GOLEM Version: 0.18.1+dev162.g9ba999a from source, stopped it completely, then tried nnext day to run binary Golem 0.18.1 

Golemapp has crashed

in `golem.log`

```
2018-11-07 13:07:47 CRITICAL golem.client                        Can't start network. Giving up.
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 292, in start
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 344, in start_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 83, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 133, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 292, in restore_tasks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/core/task/coretaskstate.py", line 68, in __setstate__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/semantic_version/base.py", line 77, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/semantic_version/base.py", line 203, in parse
TypeError: expected string or bytes-like object
```

**Comment by shadeofblue** [comment]
@ederenn this is not about binary vs source but rather about develop vs stable ... we don't support downgrades from higher versions to lower ones
