### ISSUE TITLE
Geth connectivity issues 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3535]
#### Encountered on:
Windows, binaries 0.18.1 
after first run of Golem, freshly installed on clean system, got in interface error with connection

Network was working normally at that time

from `golem.log`

```
018-11-07 14:55:03 WARNING  golem.ethereum.node                 GETH: reconnecting to another provider
2018-11-07 14:55:03 ERROR    golem.node                          Stopping because of 'setup client' error: <twisted.python.failure.Failure requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://proxy.geth.golem.network:2137/>
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 372, in _setup_client
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 111, in <lambda>
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 200, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 186, in start
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 175, in _init
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 219, in _subscribe_to_events
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 221, in subscribe_to_batch_transfers
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 415, in _create_subscription
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\client.py", line 252, in get_logs
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\eth.py", line 330, in getLogs
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 103, in request_blocking
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 86, in _make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\middleware.py", line 36, in middleware
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\gas_price_strategy.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\attrdict.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\normalize_errors.py", line 9, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\providers.py", line 14, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\providers.py", line 14, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\providers\rpc.py", line 67, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\utils\request.py", line 22, in make_post_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\models.py", line 935, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://proxy.geth.golem.network:2137/
2018-11-07 14:55:03 INFO     golem.ethereum.node                 GETH: connecting to remote RPC interface at https://1.geth.golem.network:55555
2018-11-07 14:55:05 INFO     golem.rpc                           Client connected. Starting WAMP-Ticket authentication on realm golem as crsb_user CrossbarUsers.golemapp
2018-11-07 14:55:05 INFO     golem.rpc                           WAMP-Ticket challenge received: Challenge(method=wampcra, extra={'challenge': '{"authid": "golemapp", "authrole": "admin", "authmethod": "wampcra", "authprovider": "static", "session": 3252893920137831, "nonce": "tgXPARVjYXbARi+yamm1t17lXNdaEMEkspvZILzuFazsNdz1zEWW3u2vBF2xy6ga", "timestamp": "2018-11-07T13:55:05.878Z"}'})
2018-11-07 14:55:08 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: 502 Server Error: Bad Gateway for url: https://1.geth.golem.network:55555/
2018-11-07 14:55:08 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: 502 Server Error: Bad Gateway for url: https://1.geth.golem.network:55555/
2018-11-07 14:55:08 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: 502 Server Error: Bad Gateway for url: https://1.geth.golem.network:55555/
2018-11-07 14:55:08 WARNING  golem.ethereum.node                 GETH: reconnecting to another provider
2018-11-07 14:55:08 ERROR    golem_sci.implementation            Blockchain monitor exception: HTTPError('502 Server Error: Bad Gateway for url: https://1.geth.golem.network:55555/',)
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 433, in _monitor_blockchain
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 439, in _monitor_blockchain_single
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 453, in _update_block_numbers
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\client.py", line 154, in get_block_number
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\eth.py", line 101, in blockNumber
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 103, in request_blocking
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\manager.py", line 86, in _make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\middleware.py", line 36, in middleware
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\gas_price_strategy.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\attrdict.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\normalize_errors.py", line 9, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\providers.py", line 14, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\web3\providers.py", line 14, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\providers\rpc.py", line 67, in make_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\web3\utils\request.py", line 22, in make_post_request
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\requests\models.py", line 935, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://1.geth.golem.network:55555/
2018-11-07 14:55:08 INFO     golem.ethereum.node                 GETH: connecting to remote RPC interface at https://geth.golem.network:55555
2018-11-07 14:55:08 INFO     golem.ethereum.node                 Connected to node in 0.10059642791748047s
2018-11-07 14:55:08 INFO     golem.ethereum.node                 Connected to node in 4.780908823013306s
2018-11-07 14:55:24 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
```

**Comment by ktomala** [comment]
It seems that web3 implementation in Golem is working incorrectly, because when this error happens I have checked with issuing requests via curl to the specified Geth instances and they were responding correctly. I think it might be related to some masked issue with TLS negotiation. During the 502 Bad Gateway error there was also error with ethereum.web3 saying "Connection refused", but looking into tcpdump during this connection attempt it seemed that the packets are sent back to Golem client from the Geth instance.

**Comment by ederenn** [comment]
first run of Golem 0.18.2 installed on clean system, connected eventually but encountered Geth problems

```
2018-11-15 12:17:39 INFO     golem_sci.factory                   Geth version: 1.8.17
2018-11-15 12:17:39 INFO     golem_sci.transactionsstorage       Initiating JsonTransactionStorage with nonce=0
2018-11-15 12:17:39 INFO     golem_sci.implementation            Address not provided for Contract.GNTDeposit, won't be able to use it
2018-11-15 12:17:39 INFO     golem_sci.implementation            Address not provided for Contract.Faucet, won't be able to use it
2018-11-15 12:17:49 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:17:59 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:18:09 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:18:20 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:18:30 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:18:40 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:18:50 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:00 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:10 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:20 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:30 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:40 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:19:51 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:20:01 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-15 12:20:09 INFO     golem.ethereum.transactionsystem    Can't use GNTDeposit on mainnet yet: AttributeError("'NoneType' object has no attribute 'abi'",)
2018-11-15 12:20:10 INFO     golem.ethereum.transactionsystem    Initial balances: 0.000000 GNTB, 0.000000 GNT, 0.000000 ETH
```

**Comment by ederenn** [comment]
same situation on source GOLEM Version: 0.18.2+dev218.g0be2f9a, during first run of mainnet node

```
2018-11-19 17:59:09 INFO     golem_sci.implementation            Address not provided for Contract.Faucet, won't be able to use it
2018-11-19 17:59:20 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 17:59:30 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 17:59:40 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 17:59:50 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 18:00:00 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 18:00:10 WARNING  golem.ethereum.web3.middleware      GETH: request failure, retrying: HTTPSConnectionPool(host='proxy.geth.golem.network', port=2137): Read timed out. (read timeout=10)
2018-11-19 18:00:15 INFO     golem.ethereum.transactionsystem    Can't use GNTDeposit on mainnet yet: AttributeError("'NoneType' object has no attribute 'abi'",)
```

with every start of source four times in row

**Comment by Krigpl** [comment]
Mitigated in #3579
