### ISSUE TITLE
Critical error on start in golem/rpc/session.py

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3578]
#### Encountered on:

Linux,mainnet   GOLEM Version: 0.18.2+dev218.g0be2f9a 

while running node for the first time got:

```
INFO     [golem.task.taskserver              ]  Port 40103 opened - listening
INFO     [golem.client                       ] Golem is listening on ports: P2P=40102, Task=40103, Hyperdrive=3282
INFO     [golem.network.upnp                 ] IGD: starting discovery
WARNING  [golem.network.upnp                 ] IGD: discovery error: Miniupnpc Unknown Error
INFO     [golem.network.history              ] Sweeping messages
Unhandled error in Deferred:
CRITICAL [twisted                            ] Unhandled error in Deferred:

CRITICAL [twisted                            ] 
Traceback (most recent call last):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/ederenn/projects/golem/golem/rpc/session.py", line 201, in register_procedures
    deferred = self.register(procedure, uri)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 1500, in register
    raise exception.TransportLost()
autobahn.wamp.exception.TransportLost

ederenn@ederenn-ubnt1804:~/bin$ 
```
After restart node has started

**Comment by maaktweluit** [comment]
Maybe caused by #3368 ?
