### ISSUE TITLE
'BlenderVerifier' object has no attribute 'callback'

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3592]
Golem 0.18.1

```
2018-11-23 01:23:29 INFO     apps.blender.verification           Running verification of subtask '3cae51d8-eeb8-11e8-9b19-1f8e0cdf9006'
2018-11-23 01:23:29 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/data/golem/golem_git/golemapp.py", line 184, in start
    node.start()
  File "/data/golem/golem_git/golem/node.py", line 133, in start
    self._reactor.run()
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/data/golem/golem_git/apps/blender/verification_queue.py", line 87, in callback
    self._process_queue()
  File "/data/golem/golem_git/apps/blender/verification_queue.py", line 66, in _process_queue
    self._run(entry, verifier_cls)
  File "/data/golem/golem_git/apps/blender/verification_queue.py", line 95, in _run
    result = entry.start(verifier_cls)
  File "/data/golem/golem_git/apps/blender/verification_task.py", line 24, in start
    self.verifier.task_timeout(self.subtask_id)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/golem_verificator/verifier.py", line 65, in task_timeout
    self.callback(subtask_id=subtask_id,
builtins.AttributeError: 'BlenderVerifier' object has no attribute 'callback'
```

**Comment by Elfoniok** [comment]
Fix is here
https://github.com/golemfactory/golem/pull/3597

**Comment by shadeofblue** [comment]
@etam do you have an idea how to reproduce that issue so that we could verify the pull request indeed fixes it?

**Comment by etam** [comment]
I'm not sure, but this seems to be a corner case when while a subtask is being verified it's marked as timed-out.
