### ISSUE TITLE
update 0.18.1 to develop failed on Windows

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3667]
#### Encountered on:
Windows, mainnet, GOLEM Version: 0.18.2+dev330.gb51111f

after upgrading from 0.18.1 release version to develop build got error in logs:

```
2018-12-13 16:28:38 ERROR    golem.node                          Stopping because of 'setup client' error: <twisted.python.failure.Failure builtins.Exception: TransactionStorage initialization failed. Has nonce=0 while network_nonce is=21>
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 56, in curry
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 441, in _setup_client
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 138, in <lambda>
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 177, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 210, in start
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\ethereum\transactionsystem.py", line 183, in _init
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\factory.py", line 86, in new_sci
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\implementation.py", line 113, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\golem_sci\transactionsstorage.py", line 26, in init
Exception: TransactionStorage initialization failed. Has nonce=0 while network_nonce is=21
2018-12-13 16:28:39 INFO     golem.rpc                           Client connected. Starting WAMP-Ticket authentication on realm golem as crsb_user CrossbarUsers.golemapp
2018-12-13 16:28:39 INFO     golem.rpc                           WAMP-Ticket challenge received: Challenge(method=wampcra, extra={'challenge': '{"authid": "golemapp", "authrole": "admin", "authmethod": "wampcra", "authprovider": "static", "session": 79990991679811, "nonce": "iAvnBxtQOGtT9TBqx0fgj3skJ6FJpUFA07TvGlb4stzFsb1bGSSSY1q8m0TMISPh", "timestamp": "2018-12-13T15:28:39.537Z"}'})
2018-12-13 16:28:59 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
```

**Comment by etam** [comment]
probably related: #3098

**Comment by shadeofblue** [comment]
@etam probably not -> that change has long made it to the stable version

**Comment by Krigpl** [comment]
Ancient.
