### ISSUE TITLE
cannot serialize unknown object: Node

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#3705]
Golem version: golem-0.18.3+dev579.g1f4d3ac

Steps to reproduce:
- run two Golem instances using the same binary,
- once both instances are up, try manually connecting using `golemcli` (`network connect <address> <port>`),
- after a short time (a couple of seconds) the below exception is thrown on connection target instance.

```
2019-01-04 17:03:05 INFO     golem.network.transport.tcpnetwork  Failed to deserialize message (SerializationError('TODO: TAG BIGNUM for bigger bignum bytes_info=24, len(ull)=8\n',)) b'\x03\xf6\x00\x00\x00\x00\\/\x83\xb9\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x86\xf1\xf7\xe8t\xed\xa9n%\x05\xd52\xa7\xcf_f\xad\xaeV\x06A\x16\x0b\x8b\xa978\x96\x8e:=Y\xffX\x94\xeb\x8e\x11frAq\xe3o#\xf5\xa6A\xe27\xc4\x82uAQ\xd7\x9a\xbe\xa1PXP\xd0D\xea\xf1S\xb8\x82\xe1\xbcIt\xa3\xc3\xf5\xef\x97\xa9\xcbl\x13\xb5\xc9\xc4KX\xc9=MY\xbb\x16.]\x8c[ :\x8ch\xf3e\xd2.\x89\x8c\xd6t\x1da+X\xbe8\x1c<\xe7\x95\xb9\x81\x1c\x99\xd3\xfe\t\xb0xi\x84V\x1c\xcb^u\x14\xc1\x90\xf6\xaf\xac\x94X\x85\x8c\x18\xb7o-\xd0)\xf8[\xba4lQ\xda\xa6"\xa7\xf7\'\xcb\xb8|\xe6\xac\x16\x84\x94$\r\x1d\x0e\xeflR\x9eK\xe4\xd7\xf9\x14N q\xbf$\x02\xc2\xd4X'
2019-01-04 17:03:05 ERROR    golem.network.transport.tcpnetwork  Cannot serialize message: 'Peers'(header=MessageHeader(type_=1004, timestamp=1546617785, encrypted=True), sig=None, slots=[['peers', [{'address': '10.30.10.104', 'port': 40102, 'node': <Node '', (key: '0637bea56d6b7bb44136c5d9e7fcd64dae69ecc56a79263c3a787c86b2ee978873838b0e7f41891a5e1dd5c586a0a450c9a68e6f10b7a13c33ce7b0396a8d90e')>}]]])
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/serializer.py", line 13, in _curry
ValueError: cannot serialize unknown object: <Node '', (key: '0637bea56d6b7bb44136c5d9e7fcd64dae69ecc56a79263c3a787c86b2ee978873838b0e7f41891a5e1dd5c586a0a450c9a68e6f10b7a13c33ce7b0396a8d90e')>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 289, in send_message
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 467, in _prepare_msg_to_send
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/shortcuts.py", line 17, in dump
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/message/base.py", line 220, in serialize
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/serializer.py", line 15, in _curry
golem_messages.exceptions.SerializationError: cannot serialize unknown object: <Node '', (key: '0637bea56d6b7bb44136c5d9e7fcd64dae69ecc56a79263c3a787c86b2ee978873838b0e7f41891a5e1dd5c586a0a450c9a68e6f10b7a13c33ce7b0396a8d90e')>
2019-01-04 17:03:05 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 335, in dataReceived
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 361, in _interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 118, in interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 75, in interpret
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 331, in _react_to_get_peers
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 506, in _send_peers
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 128, in send
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 201, in send
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 115, in send
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 289, in send_message
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 467, in _prepare_msg_to_send
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/shortcuts.py", line 17, in dump
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/message/base.py", line 220, in serialize
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_messages/serializer.py", line 15, in _curry
    
golem_messages.exceptions.SerializationError: cannot serialize unknown object: <Node '', (key: '0637bea56d6b7bb44136c5d9e7fcd64dae69ecc56a79263c3a787c86b2ee978873838b0e7f41891a5e1dd5c586a0a450c9a68e6f10b7a13c33ce7b0396a8d90e')>
```

**Comment by etam** [comment]
I confirm. This happens on the node that is trying to connect to the other. This exception also makes the connection attempt to fail, so nodes stay not knowing about each other.
