### ISSUE TITLE
task_to_compute.sig: AttributeError: 'NoneType' object has no attribute 'sig'

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3730]
on 0.18.3:
```
2019-01-09 16:43:05 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/data/golem/golem_git/golemapp.py", line 184, in start
    node.start()
  File "/data/golem/golem_git/golem/node.py", line 133, in start
    self._reactor.run()
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/data/golem/golem_git/apps/blender/verification_queue.py", line 84, in callback
    result=args[0][2])
  File "/data/golem/golem_git/apps/core/task/coretask.py", line 227, in verification_finished_
    verification_finished()
  File "/data/golem/golem_git/golem/core/common.py", line 195, in func_wrapper
    return func(*args, **kwargs)
  File "/data/golem/golem_git/golem/task/taskmanager.py", line 745, in verification_finished_
    verification_finished()
  File "/data/golem/golem_git/golem/task/tasksession.py", line 218, in verification_finished
    if not task_to_compute.sig:
builtins.AttributeError: 'NoneType' object has no attribute 'sig'
```

**Comment by etam** [comment]
log line before:
```
2019-01-10 05:14:52 WARNING  golem.network.history               TaskToCompute message not found for node None, subtask '9dad3c5e-1491-11e9-a770-839b6556940b'
```

**Comment by etam** [comment]
later happens this:
```
2019-01-10 05:10:31 INFO     golem.network.p2p.p2pservice        Can't remove peer [... node id ...], unknown peer
```

**Comment by etam** [comment]
fix merged to b0.19
