### ISSUE TITLE
'TaskComputer' object has no attribute 'counting_task'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3752]
####: Encountered on:

Windows, mainnet
```
2019-01-14 16:53:30 INFO     golemapp                            GOLEM Version: 0.18.3+dev588.g4f32537
2019-01-14 16:53:30 INFO     golemapp                            Protocol Version: 31
2019-01-14 16:53:30 INFO     golemapp                            golem_messages Version: 2.22.2
```
Two nodes connected by cli network connect, on one requested task, after provider starts subtask computations in logs appears `'TaskComputer' object has no attribute 'counting_task'`
This happens in stacks during computations of every started subtask. Subtasks are finished successfully.

```
2019-01-14 16:56:35 INFO     golem.client                        Updating masks
2019-01-14 16:56:35 INFO     golem.resources                     Finished resource handshake with '0e9c5f4a..9cbc33fb'
2019-01-14 16:56:58 INFO     golem.resource.base.resourceserver  Extracting task resource: 'C:\\Users\\ederenn\\AppData\\Local\\golem\\golem\\default\\mainnet\\ComputerRes\\e92aa6ee-1814-11e9-9b9b-0e9c5f4ab51d\\resources\\e92aa6ee-1814-11e9-9b9b-0e9c5f4ab51d'
2019-01-14 16:56:58 INFO     golem.task.taskcomputer             Starting computation of subtask '017eba8a-1815-11e9-99bd-0e9c5f4ab51d' (task: 'e92aa6ee-1814-11e9-9b9b-0e9c5f4ab51d', deadline: 1547482011, docker images: [{'repository': 'golemfactory/blender', 'image_id': None, 'tag': '1.4'}])
2019-01-14 16:56:59 ERROR    twisted                             AttributeError: 'TaskComputer' object has no attribute 'counting_task': Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 872, in get_task_stats
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 1335, in get_provider_status
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskcomputer.py", line 249, in get_environment
    
builtins.AttributeError: 'TaskComputer' object has no attribute 'counting_task'

**Comment by etam** [comment]
#3362 by @Krigpl removed `counting_task` from `TaskComputer`, but this was in `marketplace` branch.
#3439 by @mdtanrikulu on `0.18.0` branch added a new use for `counting_task`.
branches were merged and here we are

**Comment by etam** [comment]
merged to `b0.19`
