### ISSUE TITLE
Stopping because of 'setup client' error: Start was not called

### ISSUE THREAD

**Issue by Wiezzel** [golemfactory/clay#3779]
During startup the following error occurred and Golem stopped:
```
Stopping because of 'setup client' error: Start was not called
```
Version: b0.19 (6ec4e13fba79b011864d1b453afc78716164c31c)
OS: Win

```python
2019-01-18 13:37:28 DEBUG    golem.node                          <twisted.python.failure.Failure builtins.RuntimeError: Start was not called>
Traceback (most recent call last):
  File "C:\Users\golem\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\golem\golem\node.py", line 58, in curry
    return f(self, *args, **kwargs)
  File "C:\golem\golem\node.py", line 446, in _setup_client
    self.client = self._client_factory(self._keys_auth)
  File "C:\golem\golem\node.py", line 142, in <lambda>
    update_hw_preset=self.upsert_hw_preset
  File "C:\golem\golem\client.py", line 143, in __init__
    if not transaction_system.deposit_contract_available:
  File "C:\golem\golem\ethereum\transactionsystem.py", line 55, in curry
    raise RuntimeError('Start was not called')
RuntimeError: Start was not called
```

**Comment by Wiezzel** [comment]
This behavior repeats. I attach the full log.
[golem.log](https://github.com/golemfactory/golem/files/2772921/golem.log)

**Comment by Wiezzel** [comment]
And with loglevel=DEBUG:
[golem.log](https://github.com/golemfactory/golem/files/2772929/golem.log)

**Comment by Wiezzel** [comment]
@jiivan You recently modified the line that raises the error.
https://github.com/golemfactory/golem/commit/e7c24fa58979673600660fb572073bafc8a30a0a#diff-9f351727974c5655127c6a4dc0671995R144

**Comment by ZmijaWA** [comment]
The same on linux:

```
INFO     [golem.node                         ] Waiting for password to unlock the account. Run `golemcli account unlock` and enter your password.
INFO     [golem.node                         ] Got password
DEBUG    [golem.core.keysauth                ] Existing keys loaded
INFO     [talkback                           ] Enabling talkback 'sentry' service
INFO     [talkback                           ] Enabling talkback 'sentry-metrics' service
DEBUG    [golem.task.taskarchiver            ] Starting taskarchiver in dir: '/home/ederenn/.local/share/golem/default/rinkeby'
INFO     [golem.task.taskarchiver            ] Task archive not loaded: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/rinkeby/task_archive.pickle'
INFO     [golem.client                       ] Client ''(30e55006..19e73fb0), datadir: /home/ederenn/.local/share/golem/default/rinkeby
ERROR    [golem.node                         ] Stopping because of 'setup client' error: Start was not called
DEBUG    [raven.base.Client                  ] Sending message of length 2635 to https://talkback.golem.network/api/2/store/
DEBUG    [golem.node                         ] <twisted.python.failure.Failure builtins.RuntimeError: Start was not called>
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 58, in curry
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 445, in _setup_client
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 141, in <lambda>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 144, in __init__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 55, in curry
RuntimeError: Start was not called
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
```
