### ISSUE TITLE
Unable to see task details

### ISSUE THREAD

**Issue by ZmijaWA** [golemfactory/clay#3793]

**Comment by ZmijaWA** [comment]
**Description**
_(Short description what is wrong, what area and where)_
Golem Version: 0.18.3+dev739.gb7573ca
Golem-Messages version:
Electron version (if used): 0.18
OS: MAC
Branch (if launched from source):
Mainnet/Testnet: Mainnet
Description of the issue:

Unable to see task details without reload Golem when task is in the 

> Waiting for computation

 status.

**Repro steps**
_(short steps description how it happens)_

- Start any task
- check the status - make sure it is > Waiting for computation
- press task details button


**Actual result**
_(What is the result of this issue)_

- White screen apears

**Expected result**
_(What is the expected result)_

- Details information should appear

**Logs**
_(Any additional information that could help to resolve the issue, which systems were checked to reproduce the issue)_

```
main.bundle.js:57 TypeError: Cannot set property 'checked' of undefined
    at t.<anonymous> (main.bundle.js:280)
    at Ui (main.bundle.js:57)
    at qi (main.bundle.js:57)
    at Xo (main.bundle.js:57)
    at $o (main.bundle.js:57)
    at Ho (main.bundle.js:57)
    at Yo (main.bundle.js:57)
    at No (main.bundle.js:57)
    at yo (main.bundle.js:57)
    at Object.enqueueSetState (main.bundle.js:57)
za @ main.bundle.js:57
Ya.n.callback @ main.bundle.js:57
Ui @ main.bundle.js:57
qi @ main.bundle.js:57
Xo @ main.bundle.js:57
$o @ main.bundle.js:57
Ho @ main.bundle.js:57
Yo @ main.bundle.js:57
No @ main.bundle.js:57
yo @ main.bundle.js:57
enqueueSetState @ main.bundle.js:57
b.setState @ main.bundle.js:65
o.onStateChange @ main.bundle.js:1
notify @ main.bundle.js:1
e.notifyNestedSubs @ main.bundle.js:1
o.onStateChange @ main.bundle.js:1
notify @ main.bundle.js:1
e.notifyNestedSubs @ main.bundle.js:1
o.onStateChange @ main.bundle.js:1
k @ main.bundle.js:1
(anonymous) @ main.bundle.js:121
(anonymous) @ main.bundle.js:8
dispatch @ main.bundle.js:1
(anonymous) @ main.bundle.js:1
(anonymous) @ main.bundle.js:8
a @ main.bundle.js:19
c @ main.bundle.js:19
o @ main.bundle.js:19
(anonymous) @ main.bundle.js:8
C @ main.bundle.js:8
M @ main.bundle.js:8
b @ main.bundle.js:8
Promise resolved (async)
O @ main.bundle.js:8
(anonymous) @ main.bundle.js:8
C @ main.bundle.js:8
M @ main.bundle.js:8
k @ main.bundle.js:8
z @ main.bundle.js:8
C @ main.bundle.js:8
M @ main.bundle.js:8
b @ main.bundle.js:8
o @ main.bundle.js:8
put @ main.bundle.js:8
(anonymous) @ main.bundle.js:8
(anonymous) @ main.bundle.js:8
a @ main.bundle.js:19
c @ main.bundle.js:19
o @ main.bundle.js:19
(anonymous) @ main.bundle.js:8
emit @ main.bundle.js:8
(anonymous) @ main.bundle.js:8
(anonymous) @ main.bundle.js:1
value @ main.bundle.js:280
Xo @ main.bundle.js:57
$o @ main.bundle.js:57
Ho @ main.bundle.js:57
Yo @ main.bundle.js:57
ns @ main.bundle.js:57
Vn @ main.bundle.js:57
main.bundle.js:1 uncaught at ye TypeError: Cannot set property 'checked' of undefined
    at t.<anonymous> (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:280:21689)
    at Ui (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:52867)
    at qi (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:53178)
    at Xo (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:84735)
    at $o (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:81032)
    at Ho (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:80531)
    at Yo (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:80357)
    at No (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:79730)
    at yo (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:78962)
    at Object.enqueueSetState (file:///Applications/golem.app/Contents/Resources/app.asar/app/main.bundle.js:57:54498)
```


**Proposed Solution**
_(What could be a solution for that issue)_

**Comment by ZmijaWA** [comment]
Works with the new electron RC v3
