### ISSUE TITLE
Unable do deserialize Force Payment from yesterday in Golem-Messages 2.23

### ISSUE THREAD

**Issue by pawelkisielewicz** [golemfactory/clay#3795]
It is discovered working on https://github.com/golemfactory/concent/issues/1055. 
In `ForcePayment` test (scripts/node_integration_tests/playbooks/concnet/force_payment) there is checked case with `ForcePayment` from yesterday:
``` python
class ForcePayment(ConcentTestPlaybook):
    provider_node_script = 'provider/day_backwards'
    requestor_node_script = 'requestor/day_backwards_dont_pay'
```
and in this scripts nodes are running with freeze time a day ago- yesterday. It was supported in the past, but in Golem-Messages 2.23 there is validation for this case and it is returned as validation error: `Golem Message contains wrong fields. Deadline already passed`.
Test `force_payment.py` should be fixed. Please provide more information about new "business logic", what should be tested now.

**Comment by shadeofblue** [comment]
@pawelkisielewicz could you provide some information on were exactly are you getting this error from? Golem? Concent? I suspect that's an issue with the validator itself...

**Comment by mplebanski** [comment]
There are more issues with the validator. I just wanted to create a new issue for that but found this one. Here is the log:

```
INFO     [golem.resources                    ] Finished resource handshake with '0c8ed0ce..e3b59bbd'
INFO     [golem.task.tasksession             ] Received offer to compute. task_id='7049e968-1e58-11e9-a6cb-15127dda1506', node="''(0c8ed0ce..e3b59bbd)"
INFO     [golem.task.taskrequestorstats      ] Received work offers: 3
INFO     [golem.task.taskserver              ] provider 0c8ed0ce7687e641fed3377fd0e8beb626de454e1da71e7320faf286197ffdd87476bcf80047e9d9cb7e67385145d4c5dc93ed68ae4df765aa436f6ee3b59bbd is not allowed for this task at this moment (either waiting for results or previously failed)
Unhandled Error
Traceback (most recent call last):
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/mplebanski/Projects/golem/golem/network/transport/tcpnetwork.py", line 335, in dataReceived
    self._interpret(data)
  File "/home/mplebanski/Projects/golem/golem/network/transport/tcpnetwork.py", line 361, in _interpret
    self.session.interpret(m)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 119, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/mplebanski/Projects/golem/golem/network/transport/session.py", line 75, in interpret
    action(msg)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 419, in _react_to_find_node
    self._send_peers(node_key_id=msg.node_key_id)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 506, in _send_peers
    alpha=SEND_PEERS_NUM)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 663, in find_node
    return [_mapper(peer) for peer in neighbours]
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 663, in <listcomp>
    return [_mapper(peer) for peer in neighbours]
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 660, in _mapper
    "node": peer,
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 53, in __init__
    super().__init__(*args, **kwargs)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 30, in __init__
    self[key] = value
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/p2p.py", line 112, in __setitem__
    super().__setitem__(key, value)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 82, in __setitem__
    validator(value=value)  # noqa pylint:disable=not-callable
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/validators.py", line 36, in validate_port
    validate_integer(field_name, value)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/validators.py", line 31, in validate_integer
    value=value,
golem_messages.exceptions.FieldError: Should be an integer [port:None]
```

**Comment by shadeofblue** [comment]
@mplebanski can a `port` indeed be `None`? 
anyway, it _is_ a different issue...

**Comment by shadeofblue** [comment]
anyway, @jiivan could you please have a look at it? I'm unsure - but if the error happens on deserialization, it's pretty obvious the validator will always fail as the `deadline` for the task will almost always be over when `ForcePayment` happens

**Comment by pawelkisielewicz** [comment]
Problem I discovered:

golem console:
```
Waiting for ForcePayment...
Waiting for ForcePaymentCommitted.
WARNING  [golem.network.concent.client       ] Concent request failed with status 400 and response: '{"error": "Golem Message contains wrong fields. Deadline already passed [deadline:1548144836]"}'
Test run failed after 724.0052318572998 seconds on step 24: step_wait_force_payment_committed
Waiting for the Provider subprocess to shut-down
Waiting for the Requestor subprocess to shut-down
Waiting for ForcePaymentCommitted...
```

In concent logs there is no more, only:
```08:08:30 INFO     | Golem Message contains wrong fields. FieldError ```

I've investigated this and problem comes from golem-messages, there is validator (golem_messages/datastructures/tasks.py):
```python
 'deadline': (
            validators.validate_integer,
            functools.partial(
                _fail_if,
                check=lambda x: x > time.time(), 
                fail_msg="Deadline already passed",
            ),
        ),
```

I think there is no issue (bug) in concent or golem-messages. It was tested previous with times from yesterday, but in Golem-Messages 2.23 it was decided to add this validator. I think that to resolve this case test should be updated to new code: we should't test messages from the past and send regular message (with current time).

**Comment by shadeofblue** [comment]
fixed in https://github.com/golemfactory/golem-messages/pull/312
