### ISSUE TITLE
potential issue with validating ports

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#3797]
moved from a comment by @mplebanski 

There are more issues with the validator. I just wanted to create a new issue for that but found this one. Here is the log (it's a log from Golem core):

```
INFO     [golem.resources                    ] Finished resource handshake with '0c8ed0ce..e3b59bbd'
INFO     [golem.task.tasksession             ] Received offer to compute. task_id='7049e968-1e58-11e9-a6cb-15127dda1506', node="''(0c8ed0ce..e3b59bbd)"
INFO     [golem.task.taskrequestorstats      ] Received work offers: 3
INFO     [golem.task.taskserver              ] provider 0c8ed0ce7687e641fed3377fd0e8beb626de454e1da71e7320faf286197ffdd87476bcf80047e9d9cb7e67385145d4c5dc93ed68ae4df765aa436f6ee3b59bbd is not allowed for this task at this moment (either waiting for results or previously failed)
Unhandled Error
Traceback (most recent call last):
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/mplebanski/Projects/golem/golem/network/transport/tcpnetwork.py", line 335, in dataReceived
    self._interpret(data)
  File "/home/mplebanski/Projects/golem/golem/network/transport/tcpnetwork.py", line 361, in _interpret
    self.session.interpret(m)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 119, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/mplebanski/Projects/golem/golem/network/transport/session.py", line 75, in interpret
    action(msg)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 419, in _react_to_find_node
    self._send_peers(node_key_id=msg.node_key_id)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/peersession.py", line 506, in _send_peers
    alpha=SEND_PEERS_NUM)
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 663, in find_node
    return [_mapper(peer) for peer in neighbours]
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 663, in <listcomp>
    return [_mapper(peer) for peer in neighbours]
  File "/home/mplebanski/Projects/golem/golem/network/p2p/p2pservice.py", line 660, in _mapper
    "node": peer,
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 53, in __init__
    super().__init__(*args, **kwargs)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 30, in __init__
    self[key] = value
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/p2p.py", line 112, in __setitem__
    super().__setitem__(key, value)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 82, in __setitem__
    validator(value=value)  # noqa pylint:disable=not-callable
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/validators.py", line 36, in validate_port
    validate_integer(field_name, value)
  File "/home/mplebanski/Projects/golem/venv/lib/python3.6/site-packages/golem_messages/validators.py", line 31, in validate_integer
    value=value,
golem_messages.exceptions.FieldError: Should be an integer [port:None]
```

**Comment by mplebanski** [comment]
It happens when there are three nodes in play. Two of them are on the same host and the last one is remote.

First is started with:

```
python golemapp.py --password=abcd --datadir=/home/mplebanski/Projects/golem/node_A --rpc-address=localhost:61000 --accept-terms 
```

Second:

```
python golemapp.py --password=abcd --datadir=/home/mplebanski/Projects/golem/node_B --rpc-address=localhost:61001 --accept-terms --peer=localhost:40102
```

and third (remote):

```
python golemapp.py --password=abcd --datadir=/home/mplebanski/Projects/golem/node_A --rpc-address=localhost:61000 --accept-terms 
```

Problem dissapears when second node is started with:

```
python golemapp.py --password=abcd --datadir=/home/mplebanski/Projects/golem/node_B --rpc-address=localhost:61001 --accept-terms --peer=--peer=5.226.70.49:40102
```

meaning that probably `localhost` in command line argument `--peer` is improperly handled.

EDIT: After further investigation it turns out that both `127.0.0.1` and `localhost` are causing the problem. I thought it's only `localhost`. Only pointing to the local peer with it's external IP address makes the problem disappear.

**Comment by pawelkisielewicz** [comment]
Probably resolved in https://github.com/golemfactory/golem/pull/3819. There is added validation checking if port > 0 (and some other checks for port and address). This sessions are rejected, so they will not fail in golem-messages validation any more.
