### ISSUE TITLE
restarting frame of a finished task gives critical error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3807]
#### Encountered on:
Linux, 0.18.3+dev739.gb7573ca, mainnet

Steps to reproduce:
- create a task with at least two frames, wait for task to finish 
- go to second preview window with frames marked as rectangles
- hover over one frame and click resubmit
- task ends in timeout not in restart 

(settings used for this task: small_shark.blend 400x400, 2 frames, 4 subtasks, computed on cpu, performance 0, bid 0,2, task timeout 30min, subtask timeout 15 min)

<img width="476" alt="screen shot 2019-01-23 at 19 08 40" src="https://user-images.githubusercontent.com/32061891/51627817-9683ca00-1f43-11e9-84a6-c5907dbab7d1.png">

```
2019-01-23 18:56:23 INFO     golem.task.taskmanager              Task d1ee7c2e-1f31-11e9-9131-0e9c5f4ab51d put into restarted state
2019-01-23 18:56:23 INFO     golem.ethereum.fundslocker          Locking funds for task: '323a6d5a-1f38-11e9-b151-0e9c5f4ab51d' price: 0.066667 num: 4
2019-01-23 18:56:23 INFO     golem.ethereum.transactionsystem    Locking 0.266667 GNT and ETH for 4 payments
2019-01-23 18:56:23 INFO     golem.task.rpc                      Enqueue new task <Task: <TaskHeader: '323a6d5a-1f38-11e9-b151-0e9c5f4ab51d'>>
2019-01-23 18:56:23 INFO     golem.task.rpc                      Resource package created. Informing subsystems. task_id='323a6d5a-1f38-11e9-b151-0e9c5f4ab51d'
2019-01-23 18:56:23 INFO     golem.network.p2p.p2pservice        Estimated network size: 7.0
2019-01-23 18:56:23 INFO     golem.network.p2p.p2pservice        Performance for env `BLENDER`: rank(0.0) = 0.0
2019-01-23 18:56:23 INFO     golem.task.rpc                      Task 323a6d5a-1f38-11e9-b151-0e9c5f4ab51d initial mask size: 0 expected number of providers: 20 potential number of providers: 7
2019-01-23 18:56:23 INFO     golem.task.taskmanager              Task 323a6d5a-1f38-11e9-b151-0e9c5f4ab51d added
2019-01-23 18:56:30 INFO     golem.ethereum.paymentprocessor     Next sendout in 72401 s
2019-01-23 18:56:33 CRITICAL twisted                             Unhandled error in Deferred:
2019-01-23 18:56:33 CRITICAL twisted                             
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/deferred.py", line 28, in sync_wait
  File "/usr/lib/python3.6/queue.py", line 172, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/rpc.py", line 187, in _restart_subtasks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/deferred.py", line 30, in sync_wait
twisted.internet.defer.TimeoutError: Command timed out
```

**Comment by ederenn** [comment]
reproduced on task created several days ago

Linux, mainnet, golem-0.18.3+dev771.gdeb8b58

steps to reproduce:
it is needed to have a finished with success multi frame task at least two days old
in this example small_shark.blend, 400x400 2 frames, 4 subtasks, bid 0.2
- go to second preview window, with frames listed as rectangles, hover over one frame and click resubmit
- in task list chosen task will change status from finished to timeout

in task list there were three tasks, `c6dab040-22f5-11e9-8df7-0e9c5f4ab51d` task has been restarted

```
ederenn@ubuntu:~$ golemcli --mainnet tasks show 
id                                    ETA                subtasks_count  status    completion
------------------------------------  ---------------  ----------------  --------  ------------
e780eabe-2325-11e9-b7bc-0e9c5f4ab51d  0:00:00                         4  Finished  100.00 %
c6dab040-22f5-11e9-8df7-0e9c5f4ab51d  3 days, 1:27:24                 4  Timeout   50.00 %
0317b52c-2558-11e9-8285-0e9c5f4ab51d  0:00:00                         4  Finished  100.00 %
ederenn@ubuntu:~$ 
```

After this unsuccessful restart Golem has been closed and relaunched on debug
In task list restarted/timed out task disappeared, there were only two visible left
One frame of task  `e780eabe-2325-11e9-b7bc-0e9c5f4ab51` has been restarted and immediately was put in timeout state instead of restart.

```
ederenn@ubuntu:~$ golemcli --mainnet tasks show 
id                                    ETA        subtasks_count  status    completion
------------------------------------  -------  ----------------  --------  ------------
e780eabe-2325-11e9-b7bc-0e9c5f4ab51d  0:00:00                 4  Finished  100.00 %
0317b52c-2558-11e9-8285-0e9c5f4ab51d  0:00:00                 4  Finished  100.00 %
ederenn@ubuntu:~$ golemcli --mainnet tasks show 
id                                    ETA                 subtasks_count  status    completion
------------------------------------  ----------------  ----------------  --------  ------------
e780eabe-2325-11e9-b7bc-0e9c5f4ab51d  2 days, 20:03:30                 4  Timeout   50.00 %
0317b52c-2558-11e9-8285-0e9c5f4ab51d  0:00:00                          4  Finished  100.00 %
ederenn@ubuntu:~$
```

regular logs with `c6dab040-22f5-11e9-8df7-0e9c5f4ab51d` task 
[golem.log](https://github.com/golemfactory/golem/files/2817767/golem.log)

logs on debug with `e780eabe-2325-11e9-b7bc-0e9c5f4ab51dv` task
[golemDEBUG.log](https://github.com/golemfactory/golem/files/2817776/golemDEBUG.log)


<img width="484" alt="screen shot 2019-01-31 at 16 01 04" src="https://user-images.githubusercontent.com/32061891/52063178-5ee3d600-2572-11e9-9753-a6722eb9a6fe.png">

**Comment by kmazurek** [comment]
Preliminary observations from debug logs: task `c6dab040-22f5-11e9-8df7-0e9c5f4ab51d` gets restored from a pickle which is removed immediately after restoring. This is due to the task being recognised as too old (default: 3 days + task timeout).

**Comment by shadeofblue** [comment]
@zakaprov @ederenn this seems more like a "feature" than a bug ...

**Comment by kmazurek** [comment]
The root issue here is a race condition - it's possible for a client (e.g. Electron app) to get a list of tasks (`comp.tasks`) before the outdated ones have been removed (via [`clean_old_tasks`](https://github.com/golemfactory/golem/blob/85fea6dabb190102add7f2fb79aa0d70538e5f49/golem/client.py#L1162)). This leads to a situation where the client displays tasks which are no longer available in core.

The initial approach here (#3855) was flawed and therefore was reverted. Properly deleting a task currently requires it to be registered in the task manager, which in turn requires it to be restored from a pickle.

Fixing this properly requires properly deleting outdated tasks before they are made available to clients. Since this is a larger change, it falls out of scope for this release. The issue for this is #3862. To remedy this in 0.19, task cleaning will be disabled.
