### ISSUE TITLE
Can't restore task with short_description

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3813]
#### Encountered on:
Linux, mainnet, source branch `b0.19`
GOLEM Version: 0.18.3+dev766.gcc40b5b
Protocol Version: 31
golem_messages Version: 2.24.0

upgraded from:

INFO     [golemapp                           ] GOLEM Version: 0.18.3+dev745.gb7573ca
INFO     [golemapp                           ] Protocol Version: 31
INFO     [golemapp                           ] golem_messages Version: 2.23.0

node was run after pull, in `golem.log`:

```
ERROR    [golem.task.taskkeeper              ] Problem restoring dumpfile: /home/ederenn/.local/share/golem/default/mainnet/tasks/comp_task_keeper.pickle; deleting broken file
Traceback (most recent call last):
  File "/home/ederenn/projects/golem/golem/task/taskkeeper.py", line 157, in restore
    data = pickle.load(f)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 84, in __setitem__
    super().__setitem__(key, value)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 58, in __setitem__
    raise KeyError("Invalid key: {}".format(key))
KeyError: 'Invalid key: short_description'
```

**Comment by ederenn** [comment]
in provider's logs

```
2019-01-24 15:59:41 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/ederenn/projects/golem/golem/ethereum/transactionsystem.py", line 821, in _run
    self._incomes_keeper.update_overdue_incomes()
  File "/home/ederenn/projects/golem/golem/ethereum/incomeskeeper.py", line 181, in update_overdue_incomes
    incomes=incomes,
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/ederenn/projects/golem/golem/network/concent/client.py", line 415, in income_listener
    message_class_name='SubtaskResultsAccepted',
  File "/home/ederenn/projects/golem/golem/network/history.py", line 343, in get
    return MessageHistoryService.get_sync_as_message(**query)
  File "/home/ederenn/projects/golem/golem/network/history.py", line 122, in get_sync_as_message
    return db_msg.as_message()
  File "/home/ederenn/projects/golem/golem/model.py", line 514, in as_message
    msg = pickle.loads(self.msg_data)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 84, in __setitem__
    super().__setitem__(key, value)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/golem_messages/datastructures/__init__.py", line 58, in __setitem__
    raise KeyError("Invalid key: {}".format(key))
builtins.KeyError: 'Invalid key: short_description'
NoneType: None
```

**Comment by shadeofblue** [comment]
@ederenn please confirm if this is still an issue

**Comment by ederenn** [comment]
not seen in `GOLEM Version: 0.18.3+dev771.gdeb8b58`
