### ISSUE TITLE
KeyError: 'subtask_timeout'

### ISSUE THREAD

**Issue by ZmijaWA** [golemfactory/clay#3814]
**Description**
_(Short description what is wrong, what area and where)_
Golem Version: 0.18.3 +760
Golem-Messages version:
Electron version (if used):
OS: MAC
Branch (if launched from source):
Mainnet/Testnet: Mainnet

Description of the issue:
This issue appears when you add a new task:
for example:
1frame
1h for task
1 subtask
400x400
small_shark scene

**Repro steps**
_(short steps description how it happens)_
read above

**Actual result**
_(What is the result of this issue)_

Actually, the task is handled by the node that is connected. Only this info in the log file is something that should not happen - especially ERROR  :)

**Expected result**
_(What is the expected result)_
clear log, task is finished
**Logs**
_(Any additional information that could help to resolve the issue, which systems were checked to reproduce the issue)_

```
2019-01-24 15:58:04 ERROR    twisted                             KeyError: 'subtask_timeout': Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/rpc.py", line 570, in get_estimated_cost
    
builtins.KeyError: 'subtask_timeout'


**Proposed Solution**
_(What could be a solution for that issue)_


```

**Comment by shadeofblue** [comment]
@ZmijaWA okay, we have established this is an issue in Golem Electron @mdtanrikulu

**Comment by shadeofblue** [comment]
@ederenn @mdtanrikulu is this still an issue?

**Comment by ederenn** [comment]
on binary dev771 it was ok
