### ISSUE TITLE
[0.19.0] Images not supported

### ISSUE THREAD

**Issue by ghost** [golemfactory/clay#3916]
Hi guys ! 

# Setup
- MacOS Mojave 10.14.3 (18D109)
- Radeon Pro 555X

# Logs

```
2019-02-04 21:34:49 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-04 21:34:49 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-04 21:34:49 WARNING  golem.docker.manager                Docker: pulling image 'golemfactory/base:1.2'
2019-02-04 21:34:58 WARNING  golem.docker.manager                Docker: pulling image 'golemfactory/blender:1.4'
2019-02-04 21:35:16 WARNING  golem.docker.manager                Docker: pulling image 'golemfactory/luxrender:1.2'
2019-02-04 21:35:21 WARNING  golem.docker.manager                Docker: pulling image 'golemfactory/image_metrics:1.6'
2019-02-04 21:36:14 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 699, in _run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 590, in _get_funds_from_faucet
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 712, in tETH_faucet_donate
    
builtins.KeyError: 'paydate'
NoneType: None
2019-02-04 21:36:26 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:36:39 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:36:52 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:37:05 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:37:09 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-04 21:37:09 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-04 21:37:19 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:37:31 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:37:44 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:38:10 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:38:23 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 699, in _run
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 590, in _get_funds_from_faucet
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/ethereum/transactionsystem.py", line 712, in tETH_faucet_donate
    
builtins.KeyError: 'paydate'
NoneType: None
2019-02-04 21:38:36 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:38:49 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:39:02 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:39:15 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:39:28 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:39:41 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:39:54 WARNING  golem.ethereum.transactionsystem    tETH Faucet error code 403
2019-02-04 21:41:16 WARNING  golem.network.p2p.peersession       PEER DUPLICATED: 'Drohlum compute' '94.23.196.166' : 40104 AND 'Drohlum compute' : 40104
2019-02-04 21:42:48 WARNING  golem.network.p2p.peersession       PEER DUPLICATED: 'testnet-gf-compute-0 compute' '35.190.194.220' : 48130 AND 'testnet-gf-compute-0 compute' : 40102
2019-02-04 21:47:26 WARNING  golem.network.p2p.peersession       PEER DUPLICATED: 'Ruggu compute' '188.165.227.180' : 47452 AND 'Ruggu compute' : 40104
2019-02-04 22:28:25 WARNING  golem.clientconfigdescriptor        max_price value 'nan' is not a number
2019-02-04 23:35:01 WARNING  golem.core.processmonitor           Subprocess 9370 terminated
2019-02-04 23:35:01 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-05 02:13:52 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-05 02:13:52 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-05 10:15:30 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-05 10:15:30 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-05 10:15:31 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
2019-02-05 10:15:35 WARNING  golem.network.upnp                  IGD: discovery error: no devices discovered
2019-02-05 10:15:38 WARNING  golem.client                        Port 40102 unreachable: timeout
2019-02-05 10:15:38 WARNING  golem.client                        Port 40103 unreachable: timeout
2019-02-05 10:15:38 WARNING  golem.client                        Port 3282 unreachable: timeout
2019-02-05 10:15:39 WARNING  golem.network.p2p.peersession       PEER DUPLICATED: 'testnet-gf-compute-1 compute' '35.205.37.180' : 40102 AND 'testnet-gf-compute-1 compute' : 40102
2019-02-05 10:17:42 WARNING  golem.core.processmonitor           Subprocess 1160 terminated
2019-02-05 10:17:42 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-05 10:17:42 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
2019-02-05 10:18:02 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-05 10:18:02 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-05 10:21:20 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-05 10:21:20 WARNING  golem.resources                     Cannot connect to Hyperdrive daemon
2019-02-05 10:21:25 WARNING  golem.network.upnp                  IGD: discovery error: no devices discovered
2019-02-05 10:21:27 WARNING  golem.client                        Port 40102 unreachable: timeout
2019-02-05 10:21:27 WARNING  golem.client                        Port 40103 unreachable: timeout
2019-02-05 10:21:27 WARNING  golem.client                        Port 3282 unreachable: timeout
2019-02-05 10:21:28 WARNING  golem.network.p2p.peersession       PEER DUPLICATED: 'testnet-gf-compute-1 compute' '35.205.37.180' : 40102 AND 'testnet-gf-compute-1 compute' : 40102
2019-02-05 10:21:47 WARNING  golem.core.processmonitor           Subprocess 1234 terminated
2019-02-05 10:21:47 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-08 20:16:39 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-08 20:16:39 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-08 20:17:09 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-08 20:17:17 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-08 20:17:17 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-08 20:17:35 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-11 02:04:50 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-11 02:04:50 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-11 09:56:31 WARNING  twisted                             Native worker received SIGTERM - shutting down ..
2019-02-13 17:53:30 WARNING  golem.docker.manager                Image golemfactory/nvgpu:1.1 is not supported
2019-02-13 17:53:30 WARNING  golem.docker.manager                Image golemfactory/blender_nvgpu:1.1 is not supported
2019-02-13 17:53:42 WARNING  twisted                             Native worker received SIGTERM - shutting down ..

```

**Comment by mfranciszkiewicz** [comment]
Hello @JulianMaurin, these images are supported only on Linux systems with an NVIDIA card.

**Comment by ghost** [comment]
Does it mean this version is not compatible with MacOS and Radeon ?

**Comment by maaktweluit** [comment]
@JulianMaurin that is correct, currently GPU is only supported on Linux
