### ISSUE TITLE
error , variable`start_task` is None

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3960]
####: Encountered on:
Mac OS, Golem 0.19.0 binaries, release version

Critical appears during computations of restarted task restarted by timed out subtasks.

```
2019-03-05 17:52:41 DEBUG    golem.task.taskmanager              check_next_subtask('10703c787ec9fafb158a2a26c4e8d2752bf82abcc11fb5cf917743af0cc3469c0d50afde64162575a7f6ed6b18f809a1d0438edcebe7fad5198574a6d060d3b4', 'Kelebron 3', '55df885e-3f5f-11e9-86d5-6015c9f98f86', 119947080605216656)
2019-03-05 17:52:41 DEBUG    golem.task.taskmanager              Should accept client verdict. verdict=AcceptClientVerdict.ACCEPTED, task=55df885e-3f5f-11e9-86d5-6015c9f98f86, node=10703c78..d060d3b4
2019-03-05 17:52:41 CRITICAL twisted                             Unhandled error in Deferred:
2019-03-05 17:52:41 CRITICAL twisted                             
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 575, in _offer_chosen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 400, in get_next_subtask
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 441, in query_extra_data
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 379, in _choose_frames
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

logs on debug
https://drive.google.com/open?id=1HlrOTpDGt24RVXl-ksmHihCiuqYl8_e7

**Comment by shadeofblue** [comment]
@ederenn does this error have any influence on Golem's functioning?

**Comment by ederenn** [comment]
tasks are finished but this error is repeated in logs in hundreds for one task

**Comment by shadeofblue** [comment]
@ederenn is this still happening?

**Comment by ederenn** [comment]
yes, it still does

after restart of timed out task by button "restart all timed out subtasks"
errors are appearing in `golem.log`
restarted task has been finished

```
2019-06-14 19:49:37 ERROR    golem.core.golem_async              Caught async exception:
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 414, in _offer_chosen
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 440, in get_next_subtask
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 367, in query_extra_data
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 373, in _choose_frames
    
builtins.TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

2019-06-14 19:49:37 CRITICAL twisted                             Unhandled error in Deferred:
2019-06-14 19:49:37 CRITICAL twisted                             
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 414, in _offer_chosen
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 440, in get_next_subtask
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/blender/task/blenderrendertask.py", line 367, in query_extra_data
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/rendering/task/framerenderingtask.py", line 373, in _choose_frames
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by ederenn** [comment]
reproduced on: Linux 18.04
task:
```
(golem-env) ederenn@GOLEM2008-UBNT18:~/projects/golem$ python golemcli.py --mainnet tasks dump 4cef41e8-92a0-11e9-a599-5ad86f3605c2
{
    "preview": "/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/4cef41e8-92a0-11e9-a599-5ad86f3605c2/tmp/current_task_preview0.PNG",
    "id": "4cef41e8-92a0-11e9-a599-5ad86f3605c2",
    "name": "scene-Helicopter-r2",
    "type": "Blender",
    "subtasks_count": 4,
    "progress": 1.0,
    "options": {
        "frame_count": 2,
        "output_path": "/home/ederenn/Documents/scene-Helicopter-r2_2019-06-19_16-08-54/scene-Helicopter-r2_2019-06-19_16-12-49/scene-Helicopter-r2_2019-06-19_16-19-15/scene-Helicopter-r2_2019-06-19_16-41-19",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1-2",
        "compositing": false,
        "samples": 30
    },
    "time_started": 1560955279.4782124,
    "time_remaining": 0.0,
    "last_updated": 1560955417.0613973,
    "status": "Finished",
    "estimated_cost": "133333333333333344",
    "estimated_fee": "672000000000000",
    "compute_on": "cpu",
    "timeout": "0:10:00",
    "subtask_timeout": "0:10:00",
    "bid": 0.2,
    "resources": [
        "/home/ederenn/Desktop/Host_Share_Folder/test files/scene-Helicopter-27-cycles.blend"
    ],
    "concent_enabled": false,
    "cost": null,
    "fee": null
}
Completed in 0.00 s
```

restarted 2 subtasks of a finished task
