### ISSUE TITLE
BLENDER_NVGPU doesn't work on develop > 0.19

### ISSUE THREAD

**Issue by kbeker** [golemfactory/clay#3980]
```bash
INFO     [golem.task.benchmarkmanager        ] Running benchmark for BLENDER_NVGPU
WARNING  [golem.task.taskthread              ] Task computing error 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
WARNING  [golem.task                         ] Failed to compute benchmark 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
ERROR    [golem.task.benchmarkmanager        ] Unable to run BLENDER_NVGPU benchmark: 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/home/kbeker/GITHUB/codepoets/golem/golem/client.py", line 311, in start
    self.start_network()
  File "/home/kbeker/GITHUB/codepoets/golem/golem/client.py", line 363, in start_network
    task_finished_cb=self._task_finished_cb,
  File "/home/kbeker/GITHUB/codepoets/golem/golem/task/taskserver.py", line 117, in __init__
    finished_cb=task_finished_cb)
  File "/home/kbeker/GITHUB/codepoets/golem/golem/task/taskcomputer.py", line 78, in __init__
    sync_wait(deferred, BENCHMARK_TIMEOUT)
  File "/home/kbeker/GITHUB/codepoets/golem/golem/core/deferred.py", line 33, in sync_wait
    result.raiseException()
  File "/home/kbeker/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
Exception: 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
```

Every time, when I want to run `golemapp` benchmark raises with above exception.
System:

```bash
Operating System: Manjaro Linux
Kernel: Linux 4.19.20-1-MANJARO
```

VGA controller:
```bash
01:00.0 VGA compatible controller: NVIDIA Corporation GP106BM [GeForce GTX 1060 Mobile 6GB] (rev a1) (prog-if 00 [VGA controller])
        Subsystem: Micro-Star International Co., Ltd. [MSI] GP106M [GeForce GTX 1060 Mobile 6GB]
        Flags: bus master, fast devsel, latency 0, IRQ 146
        Memory at de000000 (32-bit, non-prefetchable) [size=16M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at e000 [size=128]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia
```

**Comment by mfranciszkiewicz** [comment]
Please make sure that:
- your `docker-ce` version matches the requirement of `nvidia-docker2`
- you use the proprietary NVIDIA driver

You can test that everything is working properly with:
`docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`

**Comment by kbeker** [comment]
@mfranciszkiewicz I did what you mentioned above and now I'm getting new exception:

```bash
INFO     [golem.task.benchmarkmanager        ] Running benchmark for BLENDER_NVGPU
WARNING  [golem.docker.task_thread           ] Task stderr:
/bin/sh: 1: python3: not found

WARNING  [golem.task.taskthread              ] Task computing error Subtask computation failed with exit code 127
WARNING  [golem.task                         ] Failed to compute benchmark Subtask computation failed with exit code 127
ERROR    [golem.task.benchmarkmanager        ] Unable to run BLENDER_NVGPU benchmark: Subtask computation failed with exit code 127
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/home/kbeker/GITHUB/codepoets/golem/golem/client.py", line 311, in start
    self.start_network()
  File "/home/kbeker/GITHUB/codepoets/golem/golem/client.py", line 363, in start_network
    task_finished_cb=self._task_finished_cb,
  File "/home/kbeker/GITHUB/codepoets/golem/golem/task/taskserver.py", line 117, in __init__
    finished_cb=task_finished_cb)
  File "/home/kbeker/GITHUB/codepoets/golem/golem/task/taskcomputer.py", line 78, in __init__
    sync_wait(deferred, BENCHMARK_TIMEOUT)
  File "/home/kbeker/GITHUB/codepoets/golem/golem/core/deferred.py", line 33, in sync_wait
    result.raiseException()
  File "/home/kbeker/.virtualenvs/golem/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
Exception: Subtask computation failed with exit code 127
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
```

Any ideas?

**Comment by kbeker** [comment]
@mfranciszkiewicz I added python3 to this docker image and it has increased his size by 10 mb. I'm going to do PR with this change to fix this problem.

**Comment by shadeofblue** [comment]
@kbeker I think it should be resolved by porting the changes that we made on the base blender image for non-gpu computations to the NVGPU image

**Comment by shadeofblue** [comment]
(sorry, accidental)

**Comment by kbeker** [comment]
@shadeofblue ok, so I won't touch this, because I don't have enough knowledge about docker. I left my fix on branch `origin/bugfix-ngpu-dockerfile` and for quick fix I think it would be enough :)

**Comment by ederenn** [comment]
same happens on builds based on 0.20.+ 
requestors: all OS

from provider logs:
```
2019-08-07 15:38:47 INFO     golem.task.taskcomputer             Starting computation of subtask 'ad5cebde-b918-11e9-9539-fc42bebd7d6f' (task: 'e5cb1706-b916-11e9-a3da-fc42bebd7d6f', deadline: 1565185725, docker images: [{'repository': 'golemfactory/blender_nvgpu', 'image_id': None, 'tag': '1.4'}])
2019-08-07 15:38:47 WARNING  golem.task.taskthread               Task computing error 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
```
 
requestor:
```
ederenn@GOLEM2008-VM-UBNT18:~$ golemcli tasks subtasks show ed25bf5a-b91a-11e9-89af-5dbf74ee525e
---
deadline: 1565186493
extra_data:
  crops:
    - borders_x:
        - 0.0
        - 1.0
      borders_y:
        - 0.0
        - 0.5
      outfilebasename: Table_GPU_2
  entrypoint: python3 /golem/entrypoints/render_entrypoint.py
  frames:
    - 1
  output_format: PNG
  path_root: /home/ederenn/Desktop/Host_Share_Folder/test files
  resolution:
    - 400
    - 400
  samples: 200
  scene_file: /golem/resources/Table_GPU.blend
  start_task: 2
  total_tasks: 4
  use_compositing: false
node_id: 5ad86f3605c2afd3ac50153c2ebaec4308eb78ace49cc83d2dda8812a887636dabd7c286e0bc7d59f3c75b60084c8ea96b0dd87dd99e2f70133d892934d07c7d
node_name: tempest
price: 120545558515856880
progress: 1.0
results: []
status: Failure
stderr: "400 Client Error: Bad Request (\"Unknown runtime specified nvidia\")"
stdout: ""
subtask_id: ed25bf5a-b91a-11e9-89af-5dbf74ee525e
time_started: 1565186091.0
```

provider has problems with running benchmarks but node continues to work:
```
2019-08-07 16:15:24 INFO     golem.task.benchmarkmanager         BLENDER performance is 1095.96
2019-08-07 16:15:24 INFO     golem.task.benchmarkmanager         Running benchmark for BLENDER_NVGPU
2019-08-07 16:15:24 WARNING  golem.task.taskthread               Task computing error 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
2019-08-07 16:15:24 WARNING  golem.task                          Failed to compute benchmark 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
2019-08-07 16:15:24 ERROR    golem.task.benchmarkmanager         Unable to run BLENDER_NVGPU benchmark: 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
2019-08-07 16:15:24 ERROR    twisted                             Exception: 400 Client Error: Bad Request ("Unknown runtime specified nvidia"): Traceback (most recent call last):
Failure: builtins.Exception: 400 Client Error: Bad Request ("Unknown runtime specified nvidia")
```

**Comment by mfranciszkiewicz** [comment]
`nvidia-docker2` is now deprecated. The `nvidia` runtime is no longer available out of the box and needs to be configured manually or by updating our installer
