### ISSUE TITLE
Blender: nvcc compiler not found

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4022]
## Description After upgrading  CUDA Nvidia drivers Golem is not starting

 

**Golem Version**:  0.19.0

**Protocol Version**: 31 

**Golem-Messages version**: 2.24.3

**Electron version** (if used):  0.1.18

**OS** : Ubuntu 18.04

**Branch** (if launched from source): -

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

Precompiled binaries based on  CUDA are incompatible with newest driver version.
There is no nvcc compilator in docker image
before on this computer was used  40x.xx beta version,  it is not possible to install version 41x

NVIDIA version: GeForce RTX 2070

**Actual result**:

Golem is shutting down after benchmark

```WARNING  [golem.task.taskthread              ] Task computing error
WARNING  [golem.task                         ] Failed to compute benchmark Subtask computation failed with exit code 1
ERROR    [golem.task.benchmarkmanager        ] Unable to run BLENDER_NVGPU benchmark: Subtask computation failed with exit code 1
CRITICAL [golem.client                       ] Can't start network. Giving up.
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 311, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 363, in start_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 117, in __init__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 79, in __init__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/deferred.py", line 33, in sync_wait
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
Exception: Subtask computation failed with exit code 1
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
INFO     [golem.network.concent.client       ] Waiting for received messages queue to empty
INFO     [golem.network.concent.client       ] <ConcentClientService(Thread-1, started daemon 139771456255744)> stopped
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down ..
```

**Screenshots**:

-

## Logs and any additional context

https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html#cuda-error-kernel-compilation-failed

https://github.com/flathub/org.blender.Blender/issues/8#issuecomment-367265713

```
CUDA version 10.0 detected, build may succeed but only CUDA 8.0 is officially supported.
Compiling CUDA kernel ...
"/usr/local/cuda/bin/nvcc" -arch=sm_75 --cubin "/usr/share/blender/scripts/addons/cycles/source/kernel/kernels/cuda/kernel.cu" -o "/home/ederenn/.cache/cycles/kernels/cycles_kernel_sm75_78F3CD3A6B833245ABFC15B6E5CDBEE8.cubin" -m64 --ptxas-options="-v" --use_fast_math -DNVCC -D__KERNEL_CUDA_VERSION__=101 -I"/usr/share/blender/scripts/addons/cycles/source" 


## Proposed Solution?

**Comment by mfranciszkiewicz** [comment]
Solution: 
We should precompile Cycles' CUDA kernel and filter for the Shader Model 7.5 cards (drivers) and add them to the blender_nvgpu image.
