### ISSUE TITLE
``` ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4038]
## Description

**Golem Version**:0.19.1

**Golem-Messages version** (leave empty if unsure):2.24.3

**Electron version** (if used):0.1.19

**OS** [e.g. Windows 10 Pro]: Windows

**Branch** (if launched from source): -

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

first lauch of a Golem on a clean system ends with error. Interface hangs on Generating keys, from golem`golem.log` 

**Actual result**:

Golem does not start

```
2019-03-22 08:04:59 ERROR    twisted                             ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`.: Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\websocket.py", line 95, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\autobahn\wamp\protocol.py", line 895, in onMessage
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 209, in set_password
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\keysauth.py", line 82, in __init__
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\keysauth.py", line 115, in _load_or_generate_keys
    
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\keysauth.py", line 175, in _save_private_key
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_keyfile\keyfile.py", line 39, in create_keyfile_json
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_keyfile\keyfile.py", line 126, in _create_v3_keyfile_json
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_utils\crypto.py", line 9, in keccak
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\main.py", line 38, in __call__
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\main.py", line 22, in _hasher_first_run
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\backends\auto.py", line 18, in keccak256
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\backends\auto.py", line 11, in _initialize
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\utils.py", line 15, in auto_choose_backend
    
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eth_hash\utils.py", line 52, in choose_available_backend
    
builtins.ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`.
```

build used:
https://buildbot.golem.network/buildbot/#/builders/2/builds/3966

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by Wiezzel** [comment]
Probably related to #4042

**Comment by ZmijaWA** [comment]
@shadeofblue the same as #4042, it is not a bug anymore.

**Comment by ZmijaWA** [comment]
This is not a problem anymore.
