### ISSUE TITLE
Golem App crashed

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#404]
```
2016-05-28 22:48:38,979 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.25 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Bolt.006

2016-05-28 22:48:39,018 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.29 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.004

2016-05-28 22:48:39,022 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.29 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.005

2016-05-28 22:48:39,023 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.29 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Profile-056.005

2016-05-28 22:48:39,024 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.30 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.006

2016-05-28 22:48:39,026 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.30 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.007

2016-05-28 22:48:39,028 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.30 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.008

2016-05-28 22:48:39,047 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.32 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.009

2016-05-28 22:48:39,051 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.32 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.010

2016-05-28 22:48:39,053 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.32 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.011

2016-05-28 22:48:39,057 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.33 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.013

2016-05-28 22:48:39,059 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.33 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.014

2016-05-28 22:48:39,078 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Curve.015

2016-05-28 22:48:39,082 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Initializing

2016-05-28 22:48:39,082 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Loading render kernels (may take a few minutes the first time)
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Waiting for render to start

2016-05-28 22:48:39,082 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Scene
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Shaders

2016-05-28 22:48:39,082 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Background
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Camera
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Objects
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.35 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Objects | Copying Transformations to device
2016-05-28 22:48:39,083 - golem.docker.job.container - DEBUG - 

2016-05-28 22:48:39,095 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.37 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Objects | Applying Static Transformations

2016-05-28 22:48:39,100 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.37 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Meshes Flags
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.37 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Meshes

2016-05-28 22:48:39,117 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.39 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Mesh | Computing normals

2016-05-28 22:48:39,134 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.41 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Mesh | Copying Mesh to device
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.41 | Mem:26.35M, Peak:26.35M | Scene, RenderLayer | Updating Mesh | Computing attributes

2016-05-28 22:48:39,134 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.41 | Mem:26.36M, Peak:26.36M | Scene, RenderLayer | Updating Mesh | Copying Attributes to device

2016-05-28 22:48:39,135 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.41 | Mem:26.38M, Peak:26.38M | Scene, RenderLayer | Updating Scene BVH | Building
2016-05-28 22:48:39,135 - golem.docker.job.container - DEBUG - 
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.41 | Mem:26.38M, Peak:26.38M | Scene, RenderLayer | Updating Scene BVH | Building BVH

2016-05-28 22:48:39,490 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.76 | Mem:26.38M, Peak:26.38M | Scene, RenderLayer | Updating Scene BVH | Packing BVH triangles and strands

2016-05-28 22:48:39,507 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.78 | Mem:26.38M, Peak:26.38M | Scene, RenderLayer | Updating Scene BVH | Packing BVH nodes

2016-05-28 22:48:39,549 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:26.38M, Peak:26.38M | Scene, RenderLayer | Updating Scene BVH | Copying BVH to device
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:60.45M, Peak:60.45M | Scene, RenderLayer | Updating Objects Flags
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:60.45M, Peak:60.45M | Scene, RenderLayer | Updating Images

2016-05-28 22:48:39,549 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:60.45M, Peak:60.45M | Scene, RenderLayer | Updating Images | Loading Scratches-01.png@1
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:60.45M, Peak:60.45M | Scene, RenderLayer | Updating Images | Loading Scratches-02.png@1

2016-05-28 22:48:39,552 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.46M, Peak:64.46M | Scene, RenderLayer | Updating Camera Volume
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.46M, Peak:64.46M | Scene, RenderLayer | Updating Hair Systems
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.46M, Peak:64.46M | Scene, RenderLayer | Updating Hair settings | Copying Hair settings to device
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.46M, Peak:64.46M | Scene, RenderLayer | Updating Lookup Tables
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Lights
2016-05-28 22:48:39,553 - golem.docker.job.container - DEBUG - 
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Lights | Computing distribution
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Particle Systems
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Particle Systems | Copying Particles to device
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Film

2016-05-28 22:48:39,553 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.71M, Peak:64.71M | Scene, RenderLayer | Updating Integrator

2016-05-28 22:48:39,553 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Updating Lookup Tables
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Updating Baking
Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Updating Device | Writing constant memory

2016-05-28 22:48:39,553 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Path Tracing Tile 0/1, Sample 0/9

2016-05-28 22:48:39,553 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.82 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Path Tracing Tile 1/1, Sample 0/9

2016-05-28 22:48:39,556 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.83 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Path Tracing Tile 1/1, Sample 9/9

2016-05-28 22:48:39,557 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.83 | Mem:64.75M, Peak:64.75M | Scene, RenderLayer | Finished

2016-05-28 22:48:39,560 - golem.docker.job.container - DEBUG - Fra:1 Mem:63.47M (0.00M, Peak 78.04M) | Time:00:00.83 | Sce: Scene Ve:0 Fa:0 La:0
2016-05-28 22:48:39,561 - golem.docker.job.container - DEBUG - 

2016-05-28 22:48:39,690 - golem.docker.job.container - DEBUG - Saved: /golem/output/out10001.png
 Time: 00:00.96 (Saving: 00:00.12)


2016-05-28 22:48:39,823 - golem.docker.job.container - DEBUG - 
Blender quit

2016-05-28 22:48:40,210 - requests.packages.urllib3.connectionpool - DEBUG - "POST /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e/wait HTTP/1.1" 200 17
2016-05-28 22:48:40,211 - docker.auth.auth - DEBUG - File doesn't exist
2016-05-28 22:48:40,214 - requests.packages.urllib3.connectionpool - DEBUG - "GET /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e/logs?timestamps=0&tail=all&follow=1&stderr=0&stdout=1 HTTP/1.1" 200 None
2016-05-28 22:48:40,220 - requests.packages.urllib3.connectionpool - DEBUG - "GET /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e/json HTTP/1.1" 200 None
2016-05-28 22:48:40,243 - requests.packages.urllib3.connectionpool - DEBUG - "GET /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e/logs?timestamps=0&tail=all&follow=1&stderr=1&stdout=0 HTTP/1.1" 200 None
2016-05-28 22:48:40,246 - requests.packages.urllib3.connectionpool - DEBUG - "GET /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e/json HTTP/1.1" 200 None
2016-05-28 22:48:40,248 - docker.auth.auth - DEBUG - File doesn't exist
2016-05-28 22:48:40,369 - requests.packages.urllib3.connectionpool - DEBUG - "DELETE /v1.21/containers/aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e?force=True&link=False&v=False HTTP/1.1" 204 0
2016-05-28 22:48:40,369 - golem.docker.job - DEBUG - Container aad5181ce1d36048b8d0cdfaf47d7b2e20b0fb295bcd3d5698b395ecad7c310e removed
2016-05-28 22:49:19,536 - pystun - DEBUG - Do Test1
2016-05-28 22:49:19,536 - pystun - DEBUG - Trying STUN host: stun.ekiga.net
2016-05-28 22:49:19,537 - pystun - DEBUG - sendto: ('stun.ekiga.net', 3478)
2016-05-28 22:49:19,652 - pystun - DEBUG - recvfrom: ('217.10.68.152', 3478)
2016-05-28 22:49:19,653 - pystun - DEBUG - Result: {'ExternalIP': '46.171.25.50', 'Resp': True, 'ExternalPort': 40103, 'ChangedPort': 3479, 'SourcePort': 3478, 'SourceIP': '217.10.68.152', 'ChangedIP': '217.116.122.138'}
2016-05-28 22:49:19,653 - pystun - DEBUG - Do Test2
2016-05-28 22:49:19,653 - pystun - DEBUG - sendto: ('stun.ekiga.net', 3478)
2016-05-28 22:49:21,657 - pystun - DEBUG - sendto: ('stun.ekiga.net', 3478)
2016-05-28 22:49:23,661 - pystun - DEBUG - sendto: ('stun.ekiga.net', 3478)
2016-05-28 22:49:25,663 - pystun - DEBUG - sendto: ('stun.ekiga.net', 3478)
2016-05-28 22:49:27,668 - pystun - DEBUG - Result: {'ExternalIP': None, 'Resp': False, 'ExternalPort': None, 'ChangedPort': None, 'SourcePort': None, 'SourceIP': None, 'ChangedIP': None}
2016-05-28 22:49:27,668 - pystun - DEBUG - Do Test1
2016-05-28 22:49:27,668 - pystun - DEBUG - sendto: ('217.116.122.138', 3479)
2016-05-28 22:49:27,726 - pystun - DEBUG - recvfrom: ('217.116.122.138', 3479)
2016-05-28 22:49:27,727 - pystun - DEBUG - Result: {'ExternalIP': '46.171.25.50', 'Resp': True, 'ExternalPort': 1024, 'ChangedPort': 3478, 'SourcePort': 3479, 'SourceIP': '217.116.122.138', 'ChangedIP': '217.10.68.152'}
2016-05-28 22:49:27,727 - golem.core.hostaddress - DEBUG - nat_type Symmetric NAT, external_ip 46.171.25.50, external_port 1024
2016-05-28 22:49:27,728 - golem.task.taskmanager - INFO - Task abf7be62-1f7b-4858-8812-bdc769b3d265 added
2016-05-28 22:49:28,234 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2016-05-28 22:49:28,249 - golem.resource.ipfs.resourcesmanager - DEBUG - IPFS: Resource registered /home/chfast/Projects/golem/golem/gnr/task/scripts/docker_blendertask.py (Qmd13m72zUhtfJXvErAH4myd9gwXUTMbDut5RBZZucBfkh)
2016-05-28 22:49:28,251 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2016-05-28 22:49:28,371 - golem.resource.ipfs.resourcesmanager - DEBUG - IPFS: Resource registered /home/chfast/Projects/golem/golem/gnr/benchmarks/blender/blender_task/scene-Helicopter-27-cycles.blend (QmdGeXF5JkkHmk1pEQDuPuPiBQsgfwmkALoc1ubxAc9JWa)
2016-05-28 22:49:28,371 - golem.resource.ipfs.resourceserver - DEBUG - IPFS: resource list: [[[u'', u'task', u'scripts', u'docker_blendertask.py'], u'Qmd13m72zUhtfJXvErAH4myd9gwXUTMbDut5RBZZucBfkh'], [[u'', u'benchmarks', u'blender', u'blender_task', u'scene-Helicopter-27-cycles.blend'], u'QmdGeXF5JkkHmk1pEQDuPuPiBQsgfwmkALoc1ubxAc9JWa']]
2016-05-28 22:49:42,808 - golem.network.transport.tcpnetwork - DEBUG - Connection to host 52.37.205.43: 40103
2016-05-28 22:49:42,808 - golem.network.transport.tcpnetwork - DEBUG - Connection to host 52.40.149.71: 40103
2016-05-28 22:49:42,808 - golem.network.transport.tcpnetwork - DEBUG - Connection to host 52.40.149.24: 40103
2016-05-28 22:49:43,019 - golem.network.transport.tcpnetwork - DEBUG - Connection established 52.40.149.71 40103
2016-05-28 22:49:43,028 - golem.network.transport.tcpnetwork - DEBUG - Connection established 52.37.205.43 40103
2016-05-28 22:49:43,037 - golem.network.transport.tcpnetwork - DEBUG - Connection established 52.40.149.24 40103
2016-05-28 22:49:43,660 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."positive_computed", "t1"."negative_computed", "t1"."wrong_computed", "t1"."positive_requested", "t1"."negative_requested", "t1"."positive_payment", "t1"."negative_payment", "t1"."positive_resource", "t1"."negative_resource" FROM "localrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'2187d5909c195c440810a86f280db74eb9a7403c47a487fbcbdeb6bb67a530ea5e3d0cf21e384ca7a3d808ebef3d7332074351aeebdcde38b4f382019e5e5f61'])
2016-05-28 22:49:43,661 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."requesting_trust_value", "t1"."computing_trust_value", "t1"."gossip_weight_computing", "t1"."gossip_weight_requesting" FROM "globalrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'2187d5909c195c440810a86f280db74eb9a7403c47a487fbcbdeb6bb67a530ea5e3d0cf21e384ca7a3d808ebef3d7332074351aeebdcde38b4f382019e5e5f61'])
2016-05-28 22:49:43,661 - golem.task.tasksession - DEBUG - Computing trust level: 0.0
2016-05-28 22:49:43,661 - golem.task.taskmanager - INFO - Cannot get next task for estimated performance 12001.0
2016-05-28 22:49:43,776 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."positive_computed", "t1"."negative_computed", "t1"."wrong_computed", "t1"."positive_requested", "t1"."negative_requested", "t1"."positive_payment", "t1"."negative_payment", "t1"."positive_resource", "t1"."negative_resource" FROM "localrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'e2a031cda080822b2812c6c46e3a2ab54a505343ffb8528f98be6bb6921e60361568c561a24cc69e66e64cdae3b92c889b344b4460ac6854fd52e1caffc209a5'])
2016-05-28 22:49:43,777 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."requesting_trust_value", "t1"."computing_trust_value", "t1"."gossip_weight_computing", "t1"."gossip_weight_requesting" FROM "globalrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'e2a031cda080822b2812c6c46e3a2ab54a505343ffb8528f98be6bb6921e60361568c561a24cc69e66e64cdae3b92c889b344b4460ac6854fd52e1caffc209a5'])
2016-05-28 22:49:43,777 - golem.task.tasksession - DEBUG - Computing trust level: 0.0
Unhandled Error
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 100, in _read
    data = w.doRead()
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/endpoints.py", line 102, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 460, in dataReceived
    self._interpret(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 631, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 605, in _interpret
    SafeProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 491, in _interpret
    self.session.interpret(m)
  File "/home/chfast/Projects/golem/golem/golem/task/tasksession.py", line 64, in interpret
    MiddlemanSafeSession.interpret(self, msg)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/session.py", line 288, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/session.py", line 95, in interpret
    action(msg)
  File "/home/chfast/Projects/golem/golem/golem/task/tasksession.py", line 328, in _react_to_want_to_compute_task
    msg.max_memory_size, msg.num_cores, self.address)
  File "/home/chfast/Projects/golem/golem/golem/task/taskmanager.py", line 152, in get_next_subtask
    ctd = task.query_extra_data(estimated_performance, num_cores, node_id, node_name)
  File "/home/chfast/Projects/golem/golem/gnr/task/blenderrendertask.py", line 277, in query_extra_data
    self._update_task_preview()
  File "/home/chfast/Projects/golem/golem/gnr/task/renderingtask.py", line 177, in _update_task_preview
    self._mark_task_area(sub, img_task, sent_color)
exceptions.TypeError: _mark_task_area() takes exactly 5 arguments (4 given)

2016-05-28 22:49:44,101 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."positive_computed", "t1"."negative_computed", "t1"."wrong_computed", "t1"."positive_requested", "t1"."negative_requested", "t1"."positive_payment", "t1"."negative_payment", "t1"."positive_resource", "t1"."negative_resource" FROM "localrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'b7fb2bc01b2293aade74ef8fca1a490c2ffdfd3e666f624fd55061987157f8b48d0ad5b193768a3dab43ecea1e59ba57339db24c32730845ab98f3b7b4b4abfe'])
2016-05-28 22:49:44,102 - peewee - DEBUG - ('SELECT "t1"."id", "t1"."created_date", "t1"."modified_date", "t1"."node_id", "t1"."requesting_trust_value", "t1"."computing_trust_value", "t1"."gossip_weight_computing", "t1"."gossip_weight_requesting" FROM "globalrank" AS t1 WHERE ("t1"."node_id" = ?)', [u'b7fb2bc01b2293aade74ef8fca1a490c2ffdfd3e666f624fd55061987157f8b48d0ad5b193768a3dab43ecea1e59ba57339db24c32730845ab98f3b7b4b4abfe'])
2016-05-28 22:49:44,103 - golem.task.tasksession - DEBUG - Computing trust level: 0.0
Unhandled Error
Traceback (most recent call last):
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 100, in _read
    data = w.doRead()
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/chfast/.virtualenvs/golem/local/lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/endpoints.py", line 102, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 460, in dataReceived
    self._interpret(data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 631, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 605, in _interpret
    SafeProtocol._interpret(self, data)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/tcpnetwork.py", line 491, in _interpret
    self.session.interpret(m)
  File "/home/chfast/Projects/golem/golem/golem/task/tasksession.py", line 64, in interpret
    MiddlemanSafeSession.interpret(self, msg)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/session.py", line 288, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/chfast/Projects/golem/golem/golem/network/transport/session.py", line 95, in interpret
    action(msg)
  File "/home/chfast/Projects/golem/golem/golem/task/tasksession.py", line 328, in _react_to_want_to_compute_task
    msg.max_memory_size, msg.num_cores, self.address)
  File "/home/chfast/Projects/golem/golem/golem/task/taskmanager.py", line 152, in get_next_subtask
    ctd = task.query_extra_data(estimated_performance, num_cores, node_id, node_name)
  File "/home/chfast/Projects/golem/golem/gnr/task/blenderrendertask.py", line 277, in query_extra_data
    self._update_task_preview()
  File "/home/chfast/Projects/golem/golem/gnr/task/renderingtask.py", line 177, in _update_task_preview
    self._mark_task_area(sub, img_task, sent_color)
exceptions.TypeError: _mark_task_area() takes exactly 5 arguments (4 given)
```

**Comment by mfranciszkiewicz** [comment]
This is a duplicate of #390 and was fixed in #391. This problem no longer appears in a packaged version, also a quick test confirmed that the `develop` branch should be free of this bug. Can you confirm that #391 was applied to your codebase?
