### ISSUE TITLE
Loader FrozenImporter cannot handle module golem.os

### ISSUE THREAD

**Issue by Wiezzel** [golemfactory/clay#4040]
## Description

**Golem Version**: 0.19.1 ([build 3966](https://buildbot.golem.network/buildbot/#/builders/2/builds/3966))

**Golem-Messages version** (leave empty if unsure): 2.24.3

**Electron version** (if used): ???

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro 1809

**Branch** (if launched from source): ---

**Mainnet/Testnet**: testnet

**Description of the issue**:  

Clean installation, first start from "Golem Testnet" icon. The following error appears in logs:
```
2019-03-25 13:12:49 ERROR    golem.docker.hypervisor.hyperv      Failed to free memory
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 442, in get_code
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod02_archive.py", line 358, in extract
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod02_archive.py", line 97, in __enter__
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\Golem\\golemapp.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\docker\hypervisor\hyperv.py", line 359, in _check_memory
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 611, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 444, in get_code
ImportError: Loader FrozenImporter cannot handle module golem.os
```

GUI displays the classic "Golem is having trouble connecting" message.

**Actual result**:

**Screenshots**:

## Steps To Reproduce
1. Install Golem
2. Launch
3. Accept terms, provide password, etc.
4. Wait

## Expected behavior
No errors, I suppose.

## Logs and any additional context
[golem.error.log](https://github.com/golemfactory/golem/files/3003205/golem.error.log)
[golem.log](https://github.com/golemfactory/golem/files/3003206/golem.log)
[gui.log](https://github.com/golemfactory/golem/files/3003207/gui.log)

## Proposed Solution?
???

**Comment by Wiezzel** [comment]
Probably related to #4042

**Comment by ZmijaWA** [comment]
This is not a problem anymore.
