### ISSUE TITLE
node_integration_test failure - TransactionStorage initialization failed

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#4232]
When re-using keys in the `node_integration_tests/` only the key is copied, not the `tx.json` containing the latest nonce.

Please add the `tx.json` to the re-use dir so it always has the latest nonce that belongs to the shared key.

Example of a failed test because of this ( first failure `test_frame_restart`):
https://buildbot.golem.network/buildbot/#/builders/15/builds/678

**Comment by maaktweluit** [comment]
This morning the [integration test failed](https://buildbot.golem.network/buildbot/#/builders/15/builds/701) on this issue again, but slightly different error:
```
2019-05-29 04:40:25 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 900, in runUntilCurrent
    self.fireSystemEvent("shutdown")
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 686, in fireSystemEvent
    event.fireEvent()
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 422, in fireEvent
    result = callable(*args, **kwargs)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/client.py", line 642, in quit
    self.transaction_system.stop()
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/ethereum/transactionsystem.py", line 323, in stop
    self._payment_processor.sendout(0)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/ethereum/paymentprocessor.py", line 236, in sendout
    closure_time,
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 199, in batch_transfer
    gas,
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 450, in _create_and_send_transaction
    return self._sign_and_send_transaction(tx)
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 397, in _sign_and_send_transaction
    return self._geth_client.send(tx)
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_sci/client.py", line 98, in send
    return self.web3.eth.sendRawTransaction(hex_data).hex()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/web3/eth.py", line 250, in sendRawTransaction
    [raw_transaction],
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/web3/manager.py", line 106, in request_blocking
    raise ValueError(response["error"])
builtins.ValueError: {'code': -32000, 'message': 'nonce too low'}
```
