### ISSUE TITLE
node_integration_tests::test_exr - unknown file extension: .exr

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#4265]
Found by integration tests: https://buildbot.golem.network/buildbot/#/builders/15/builds/707

```
Traceback (most recent call last):
  File "/golem/entrypoints/verifier_entrypoint.py", line 15, in <module>
    params['output_format'],
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 221, in verify
    make_verdict(subtask_file_paths, crops, results)
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 132, in make_verdict
    crop_data['crop']['outfilebasename'] + "metrics.txt")
  File "/golem/entrypoints/scripts/verifier_tools/image_metrics_calculator.py", line 63, in calculate_metrics
    PROVIDER_RESULT_CROP_NAME_PREFIX + os.path.basename(reference_crop_path)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 1917, in save
    raise ValueError('unknown file extension: {}'.format(ext))
ValueError: unknown file extension: .exr
```

**Comment by maaktweluit** [comment]
This turned out to be an old issue, there was a wrongly cached image on the buildbot worker.
An issue has been made to catch this: #4267

Thanks @zakaprov for looking this up.

Build passed this morning: https://buildbot.golem.network/buildbot/#/builders/15/builds/712
