### ISSUE TITLE
b0.20 windows binary - No module named 'eventlet.hubs.epolls'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4271]
## Description

**Golem Version**:

**Golem-Messages version** (leave empty if unsure):  golem-0.19.2+dev547.g43a8acf, binaries build on b0.20 branch

**Electron version** (if used): - 

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Description of the issue**:

Golem after installation from binaries bulid on b0.20 branch is not starting, in golem.log info logs are not created, latest entries is closing Golem before update. In GUI Golem hangs before  password modal. Debug logs gives an error `No module named 'eventlet.hubs.epolls'`

**Actual result**:

Golem is not starting.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Use binaries build on b0.20 branch', run installer.
2. In terminal run Golem on debug
3. See error

## Expected behavior

Golem should launch and connect to nodes

## Logs and any additional context

```
C:\Users\ederenn>golemapp.exe --mainnet --log-level=DEBUG 
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golemapp.py", line 304, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\click\core.py", line 722, in __call__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\click\core.py", line 697, in main
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\click\core.py", line 895, in invoke
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\click\core.py", line 535, in invoke
  File "C:\BuildbotWorker\buildpackage_windows\build\golemapp.py", line 145, in start
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\node.py", line 25, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 69, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 62, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskcomputer.py", line 18, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\docker\manager.py", line 16, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\docker\hypervisor\hyperv.py", line 10, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\__init__.py", line 19, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\__init__.py", line 10, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\convenience.py", line 4, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\greenpool.py", line 4, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\queue.py", line 49, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\event.py", line 3, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\hubs\__init__.py", line 19, in <module>
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\eventlet\hubs\__init__.py", line 19, in <genexpr>
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[6404] Failed to execute script golemapp
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ederenn** [comment]
repeated on dwonloaded Linux build
https://buildbot.golem.network/buildbot/#/builders/5/builds/4336

when binary is built locally Golem launches

something may be wrong on buildbots

related: https://github.com/golemfactory/golem/issues/4302
