### ISSUE TITLE
cannot serialize unknown object: golem.model.TaskPayment

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#4290]
This morning [node_integration_tests on develop](https://buildbot.golem.network/buildbot/#/builders/15/builds/718) broke with this error:

```
2019-06-06 04:41:31 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/test_node_integration/build/golemapp.py", line 221, in _start
    node.start()
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/node.py", line 197, in start
    self._reactor.run()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/home/buildbot-worker/worker/test_node_integration/build/apps/core/verification_queue.py", line 84, in callback
    result=args[0][2])
  File "/home/buildbot-worker/worker/test_node_integration/build/apps/core/task/coretask.py", line 216, in verification_finished_
    verification_finished()
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/core/common.py", line 192, in func_wrapper
    return func(*args, **kwargs)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/taskmanager.py", line 748, in verification_finished_
    verification_finished()
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/server/verification.py", line 105, in verification_finished
    private_key=self.keys_auth._private_key,  # noqa pylint: disable=protected-access
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_messages/utils.py", line 50, in copy_and_sign
    msg.sign_message(private_key)
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_messages/message/base.py", line 588, in sign_message
    self.sig = self._get_signature(private_key, msg_hash)
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_messages/message/base.py", line 573, in _get_signature
    msghash=msg_hash or self.get_short_hash()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_messages/message/base.py", line 198, in get_short_hash
    payload = serializer.dumps(self.slots())
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/golem_messages/serializer.py", line 27, in _curry
    ) from e
golem_messages.exceptions.SerializationError: (ValueError (cannot serialize unknown object: <golem.model.TaskPayment object at 0x7f0bac1b5b38>)

**Comment by kubkon** [comment]
I've managed to replicate the bug on the latest `develop` branch while trying to run a Wasm task.

**Comment by jiivan** [comment]
`ETS.add_payment_info()` changed return type from `int` to `model.TaskPayment`.
