### ISSUE TITLE
b0.20 Linux binary - No module named 'eventlet.hubs.epolls

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4302]
# Description

**Golem Version**:

**Golem-Messages version** (leave empty if unsure): , binaries build on b0.20 branch
https://buildbot.golem.network/buildbot/#/builders/2/builds/4468 

**Electron version** (if used): - 

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Mainnet/Testnet**: mainnet

**Description of the issue**:

Golem after installation from binaries bulid on b0.20 branch is not starting, in golem.log info logs are not created, latest entries is closing Golem before update. In GUI Golem hangs before  password modal. Debug logs gives an error `No module named 'eventlet.hubs.epolls'`

When binary is built locally Golem launches
Something may be wrong on buildbots

**Actual result**:

Golem is not starting.

Short description of steps to reproduce the behavior:
e.g.

Use binaries build on b0.20 branch', run installer.
In terminal run Golem on debug
See error
Expected behavior
Golem should launch and connect to nodes

## Expected behavior

Golem should launch and connect to nodes

## Logs and any additional context

```
ederenn@GOLEM2008-VM-UBNT18:~$ golemapp --mainnet --log-level=DEBUG
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 313, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 152, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 26, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 69, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 61, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 18, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/docker/manager.py", line 16, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/docker/hypervisor/hyperv.py", line 10, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/os_win/__init__.py", line 19, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/__init__.py", line 10, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/convenience.py", line 4, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/greenpool.py", line 4, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/queue.py", line 49, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/event.py", line 3, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 19, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 19, in <genexpr>
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[4472] Failed to execute script golemapp
```

**Comment by hnyztang** [comment]
b0.20 cent OS binary - No module named 'eventlet.hubs.epolls  
How to fix it?

**Comment by maaktweluit** [comment]
@hnyztang please update golem to the latest version ( 0.22.1 ) and check if this issue persists
