### ISSUE TITLE
golem.verificator.blender_verifier --- Finishing verification with fail

### ISSUE THREAD

**Issue by ZmijaWA** [golemfactory/clay#4334]
## Description

**Golem Version**:golem-0.19.2+dev584.g27d254c

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):0.20.0

**OS** [e.g. Windows 10 Pro]: MAC

**Branch** (if launched from source):

**Mainnet/Testnet**: Mainnet

**Description of the issue**:
Subtask failed. 
As you can see in the log file:
```
2019-06-13 12:54:11 WARNING  golem.verificator.blender_verifier  Failure callback <twisted.python.failure.Failure golem.task.taskthread.JobException: Subtask computation failed with exit code 1>
2019-06-13 12:54:11 WARNING  apps.core.verification_queue        Finishing verification with fail

```

**Actual result**:

The task fails on verification. So the eventual task will be a timeout.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
run golem
put classroom task
Choose the main file
start the task

The subtask

 will be computed by the provider, but it will fail on the veryfication process.

## Expected behavior
_(What is the expected behavior and/or result in this scenario)_

## Logs and any additional context
```
019-06-13 12:54:08 WARNING  golem.docker.task_thread            Task error - exit_code=1
stderr:
Traceback (most recent call last):
  File "/golem/entrypoints/verifier_entrypoint.py", line 15, in <module>
    params['output_format'],
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 214, in verify
    crops_borders
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 90, in prepare_data_for_blender_verification
    crops_borders
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 56, in prepare_crops
    subtask_image_box,
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 61, in __init__
    self.box = crop_box or self._generate_random_crop_box()
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 91, in _generate_random_crop_box
    span=crop_height
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 106, in _get_coordinate_limits
    coordinate_beginning_limit) / 100
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (91,91, 0)

tail of stdout:
relative_crop_width: 0.1, relative_crop_height: 0.1
-> subtask_box.left=0.0
-> subtask_box.right=1.0
-> subtask_box.top=0.9075
-> subtask_box.bottom=1.0
x_beginning=0.39, x_end=0.49


2019-06-13 12:54:08 WARNING  golem.task.taskthread               Task computing error Subtask computation failed with exit code 1
2019-06-13 12:54:08 WARNING  golem.verificator.blender_verifier  Verification process exception [Failure instance: Traceback: <class 'golem.task.taskthread.JobException'>: Subtask computation failed with exit code 1
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:884:_bootstrap
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:916:_bootstrap_inner
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:140:run
--- <exception caught here> ---
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:127:run
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:220:_run_docker_job
]
2019-06-13 12:54:08 WARNING  golem.verificator.blender_verifier  Failure callback <twisted.python.failure.Failure golem.task.taskthread.JobException: Subtask computation failed with exit code 1>
2019-06-13 12:54:08 WARNING  apps.core.verification_queue        Finishing verification with fail
2019-06-13 12:54:11 WARNING  golem.docker.task_thread            Task error - exit_code=1
stderr:
Traceback (most recent call last):
  File "/golem/entrypoints/verifier_entrypoint.py", line 15, in <module>
    params['output_format'],
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 214, in verify
    crops_borders
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 90, in prepare_data_for_blender_verification
    crops_borders
  File "/golem/entrypoints/scripts/verifier_tools/verifier.py", line 56, in prepare_crops
    subtask_image_box,
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 61, in __init__
    self.box = crop_box or self._generate_random_crop_box()
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 91, in _generate_random_crop_box
    span=crop_height
  File "/golem/entrypoints/scripts/verifier_tools/crop_generator.py", line 106, in _get_coordinate_limits
    coordinate_beginning_limit) / 100
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (82,82, 0)

tail of stdout:
relative_crop_width: 0.1, relative_crop_height: 0.1
-> subtask_box.left=0.0
-> subtask_box.right=1.0
-> subtask_box.top=0.815
-> subtask_box.bottom=0.9075
x_beginning=0.21, x_end=0.31


2019-06-13 12:54:11 WARNING  golem.task.taskthread               Task computing error Subtask computation failed with exit code 1
2019-06-13 12:54:11 WARNING  golem.verificator.blender_verifier  Verification process exception [Failure instance: Traceback: <class 'golem.task.taskthread.JobException'>: Subtask computation failed with exit code 1
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:884:_bootstrap
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:916:_bootstrap_inner
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:140:run
--- <exception caught here> ---
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:127:run
/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/docker/task_thread.py:220:_run_docker_job
]
2019-06-13 12:54:11 WARNING  golem.verificator.blender_verifier  Failure callback <twisted.python.failure.Failure golem.task.taskthread.JobException: Subtask computation failed with exit code 1>
2019-06-13 12:54:11 WARNING  apps.core.verification_queue        Finishing verification with fail

```

```
MacBook-Pro-ukasz:bin lukaszzmijewski$ ./golemcli --mainnet tasks dump 7c152138-8dc9-11e9-a9c8-e593c8c41e5e
{
    "preview": "/Users/lukaszzmijewski/Library/Application Support/golem/default/mainnet/ComputerRes/7c152138-8dc9-11e9-a9c8-e593c8c41e5e/tmp/current_task_preview.PNG",
    "id": "7c152138-8dc9-11e9-a9c8-e593c8c41e5e",
    "name": "classroom",
    "type": "Blender",
    "subtasks_count": 11,
    "progress": 0.0,
    "options": {
        "frame_count": 1,
        "output_path": "/Users/lukaszzmijewski/Documents/classroom_2019-06-13_12-53-32",
        "format": "PNG",
        "resolution": [
            400,
            400
        ],
        "frames": "1",
        "compositing": false,
        "samples": 21
    },
    "time_started": 1560423212.135485,
    "time_remaining": null,
    "last_updated": 1560423213.262989,
    "status": "Waiting",
    "estimated_cost": "550000000000000000",
    "estimated_fee": "677600000000028",
    "compute_on": "cpu",
    "timeout": "1:00:00",
    "subtask_timeout": "0:15:00",
    "bid": 0.2,
    "resources": [
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/lamps/lamps.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/dustBin/textures/dustbin_wireframe.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_darkWood.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_05.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/cork.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/pencil_colorMask.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wallClock/textures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_scratch.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_03.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_leather.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wallClock/textures/wallClock.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/dustBin/textures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/radiator/radiator.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wastes/wastes.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wastes/textures/crinkledPaper_02.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_wallPaint.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_01.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/suitcase/suitcase.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_paintedPlasterWall.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/blackBoard.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_brightWood.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/books/textures/zapBook.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/coatStand/coatStand.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/woodPlanks.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/__ENV/Garage/Garage.hdr",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/pencil_glossyMask.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/desks/desks.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/pencil_color.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_04.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_brownWood.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/chairs/chairs.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/pencil_brandMask.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/officeSupplies.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/glass.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_bluredMetal.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/ceilingAirVent_AO.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_07.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/officeSupplies/textures/eraser.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_paper_01.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_bareMetal.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_frostedGlass.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/ReadMe.txt",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/radiator/textures/radiator_AO.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/books/books.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wastes/textures/crinkledPaper.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/base_woodFloor.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wallClock/wallClock.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/radiator/textures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/dustBin/dustBin.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/ceiling_AO.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/assets/wastes/textures/crinkledPaper_03.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/_baseTextures/Thumbs.db",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_06.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_02.jpg",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/classroom.blend",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/childDrawing/childDrawing_08.png",
        "/Users/lukaszzmijewski/Documents/Task examples/classroom/textures/europeMap.png"
    ],
    "concent_enabled": false,
    "cost": null,
    "fee": null
}
Completed in 0.01 s
```

[golem.log](https://github.com/golemfactory/golem/files/3285746/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by weaselix** [comment]
https://github.com/golemfactory/golem/pull/4350
