### ISSUE TITLE
sqlite3.ProgrammingError: Cannot operate on a closed database

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4380]
## Description

**Golem Version**:    ] GOLEM Version: 0.19.2+dev610.g7dab45b

**Golem-Messages version** (leave empty if unsure):  golem_messages Version: 3.7.0

**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): b0.20

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

after restart of an app error appears in logs

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.

prerequisites: some tasks finished and in timeout

1. Launch  Golem 
2. Restart an app.
3. Check logs for error

## Logs and any additional context

```ERROR    [golem.task.taskserver              ] TaskServer.sync_network job <bound method TaskMessagesQueueMixin.connect_to_nodes of <golem.task.taskserver.TaskServer object at 0x7f0fc51d56d8>> failed
Traceback (most recent call last):
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 208, in sync_network
    job()
  File "/home/ederenn/projects/golem/golem/task/server/queue_.py", line 97, in connect_to_nodes
    for node_id in msg_queue.waiting():
  File "/home/ederenn/projects/golem/golem/network/transport/msg_queue.py", line 69, in waiting
    ).group_by(model.QueuedMessage.node):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 2289, in next
    obj = self.qrw.iterate()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 2340, in iterate
    row = self.cursor.fetchone()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ederenn** [comment]
encountered again on Linux 18.04
rc 0.20.0
https://buildbot.golem.network/buildbot/#/builders/2/builds/4749

```
2019-07-04 16:02:19 ERROR    golem.task.taskserver               TaskServer.sync_network job <bound method TaskMessagesQueueMixin.connect_to_nodes of <golem.task.taskserver.TaskServer object at 0x7ffa62e72e10>> failed
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 208, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/server/queue_.py", line 97, in connect_to_nodes
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/msg_queue.py", line 69, in waiting
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2289, in next
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2340, in iterate
sqlite3.ProgrammingError: Cannot operate on a closed database.
 ```

**Comment by mbenke** [comment]
Seen again on develop:

```
ERROR    [golem.task.taskserver              ] TaskServer.sync_network job <bound method TaskMessagesQueueMixin.connect_to_nodes of <golem.task.taskserver.TaskServer object at 0x7f359aafd978>> failed
Traceback (most recent call last):
  File "/home/ben/github/golem/golem/task/taskserver.py", line 237, in sync_network
    job()
  File "/home/ben/github/golem/golem/task/server/queue_.py", line 98, in connect_to_nodes
    for node_id in msg_queue.waiting():
  File "/home/ben/github/golem/golem/network/transport/msg_queue.py", line 69, in waiting
    ).group_by(model.QueuedMessage.node):
  File "/home/ben/.virtualenvs/golem-dev/lib/python3.6/site-packages/peewee.py", line 2289, in next
    obj = self.qrw.iterate()
  File "/home/ben/.virtualenvs/golem-dev/lib/python3.6/site-packages/peewee.py", line 2340, in iterate
    row = self.cursor.fetchone()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by ederenn** [comment]
appeared again on Windows, Linux:
```
2019-08-07 13:40:05 INFO     golemapp                            GOLEM Version: 0.20.1+dev83.g3693079
2019-08-07 13:40:05 INFO     golemapp                            Protocol Version: 32
2019-08-07 13:40:05 INFO     golemapp                            golem_messages Version: 3.7.0
```
build: https://buildbot.golem.network/buildbot/#/builders/2/builds/5053


```
2019-08-07 14:06:13 ERROR    golem.task.taskserver               TaskServer.sync_network job <bound method TaskMessagesQueueMixin.connect_to_nodes of <golem.task.taskserver.TaskServer object at 0x00000292D7E1A0F0>> failed
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 208, in sync_network
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\server\queue_.py", line 98, in connect_to_nodes
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\network\transport\msg_queue.py", line 69, in waiting
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\peewee.py", line 2289, in next
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\peewee.py", line 2340, in iterate
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by ederenn** [comment]
encountered on 0.21.0 binaries, Linux 18.04
```2019-10-16 15:45:15 ERROR    golem.task.taskserver               TaskServer.sync_network job <bound method TaskMessagesQueueMixin.connect_to_nodes of <golem.task.taskserver.TaskServer object at 0x7f7dc9672128>> failed
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 285, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/server/queue_.py", line 98, in connect_to_nodes
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/msg_queue.py", line 69, in waiting
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2289, in next
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/peewee.py", line 2340, in iterate
sqlite3.ProgrammingError: Cannot operate on a closed database.
```
