### ISSUE TITLE
Hyper-V enters reconfiguration loop and fails

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4429]
## Description

**Golem Version**: 0.20.0

**Golem-Messages version** (leave empty if unsure): 

**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Golem was running normally and performing computations, at some point app shut down with no warning. After app restart in `golem log` appeared error stack trace.
It's a node set on virtual machine, 16 GB RAM,  at the point of crash 11.3 GB free disc space, 10.1 when Golem is running.
After system restart it was possible to run Golem and perform computations, no additional space freed.

**Actual result**:

Golem crashes without warning 

## Logs and any additional context

```
2019-07-04 14:07:51 ERROR    os_win.utils.jobutils               WMI job failed: {'InstanceID': 'E4C92FB5-794B-4658-9506-ED47287B239C', 'Description': 'Initializing and Restoring Virtual Machine', 'ElementName': 'Restoring', 'JobStatus': 'Job is completed with error', 'ElapsedTime': datetime.timedelta(0, 0, 188554), 'Cancellable': True, 'JobType': 15, 'Owner': 'DESKTOP-BJS0R4R\\ederenn', 'PercentComplete': 10, 'JobState': 10, 'StatusDescriptions': ('Job is completed', 'Job is completed with error'), 'OperationalStatus': (17, 6), 'TimeSubmitted': datetime.datetime(2019, 7, 4, 12, 7, 51), 'UntilTime': None, 'TimeOfLastStateChange': datetime.datetime(2019, 7, 4, 12, 7, 51), 'DetailedStatus': None, 'LocalOrUtcTime': 2, 'ErrorCode': 32768, 'ErrorDescription': None, 'ErrorSummaryDescription': None}.
2019-07-04 14:07:53 ERROR    os_win.utils.jobutils               WMI job failed: {'InstanceID': '63FD6708-5DD7-4915-A5DB-B3590B7BABF0', 'Description': 'Initializing and Restoring Virtual Machine', 'ElementName': 'Restoring', 'JobStatus': 'Job is completed with error', 'ElapsedTime': datetime.timedelta(0, 0, 194737), 'Cancellable': True, 'JobType': 15, 'Owner': 'DESKTOP-BJS0R4R\\ederenn', 'PercentComplete': 10, 'JobState': 10, 'StatusDescriptions': ('Job is completed', 'Job is completed with error'), 'OperationalStatus': (17, 6), 'TimeSubmitted': datetime.datetime(2019, 7, 4, 12, 7, 52), 'UntilTime': None, 'TimeOfLastStateChange': datetime.datetime(2019, 7, 4, 12, 7, 53), 'DetailedStatus': None, 'LocalOrUtcTime': 2, 'ErrorCode': 32768, 'ErrorDescription': None, 'ErrorSummaryDescription': None}.
2019-07-04 14:07:53 ERROR    golem.docker.hypervisor.hyperv      Hyper-V: Failed to restore VM golem
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\docker\hypervisor\hyperv.py", line 147, in restore_vm
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\_utils.py", line 189, in inner
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\oslo_utils\excutils.py", line 220, in __exit__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\oslo_utils\excutils.py", line 196, in force_reraise
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\six.py", line 693, in reraise
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\_utils.py", line 146, in inner
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\compute\vmutils.py", line 684, in set_vm_state
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\jobutils.py", line 74, in check_ret_val
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\jobutils.py", line 118, in _wait_for_job
os_win.exceptions.WMIJobFailed: WMI job failed with status 10. Error summary description: None. Error description: None Error code: 32768.
2019-07-04 14:07:53 INFO     golem.docker.hypervisor.hyperv      Hyper-V: VM golem cannot be restored. Removing the saved state ...
2019-07-04 14:07:53 INFO     golem.docker.hypervisor.hyperv      Hyper-V: VM golem cannot be restored. Booting ...
2019-07-04 14:07:55 WARNING  golem.docker.hypervisor.hyperv      Not enough space on system drive. VM state cannotbe saved on system shutdown
2019-07-04 14:07:55 ERROR    os_win.utils.jobutils               WMI job failed: {'InstanceID': 'D9C77FCA-FC85-433C-A083-CDB084580E52', 'Description': 'Modifying Resource', 'ElementName': 'Modifying Resource', 'JobStatus': 'Job is completed with error', 'ElapsedTime': datetime.timedelta(0, 0, 9887), 'Cancellable': False, 'JobType': 31, 'Owner': 'DESKTOP-BJS0R4R\\ederenn', 'PercentComplete': 0, 'JobState': 10, 'StatusDescriptions': ('Job is completed', 'Job is completed with error'), 'OperationalStatus': (17, 6), 'TimeSubmitted': datetime.datetime(2019, 7, 4, 12, 7, 55), 'UntilTime': None, 'TimeOfLastStateChange': datetime.datetime(2019, 7, 4, 12, 7, 55), 'DetailedStatus': None, 'LocalOrUtcTime': 2, 'ErrorCode': 32775, 'ErrorDescription': "'golem' failed to modify device 'Processor'. (Virtual machine ID 3C464F0E-7279-4AAC-8BD8-08A057899FD7)\n\nCannot change the processor settings of virtual machine 'golem' while it is in a saved state. (Virtual machine ID 3C464F0E-7279-4AAC-8BD8-08A057899FD7)", 'ErrorSummaryDescription': "Failed to modify device 'Processor'.\n\nCannot change the processor settings of a virtual machine now."}.

```

```
ERROR    [golem.docker.hypervisor.hyperv     ] Hyper-V: reconfiguration of VM "golem" failed
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\docker\hypervisor\hyperv.py", line 299, in constrain
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\compute\vmutils.py", line 336, in update_vm
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\compute\vmutils.py", line 301, in _set_vm_vcpus
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\_utils.py", line 240, in inner
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\_utils.py", line 189, in inner
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\oslo_utils\excutils.py", line 220, in __exit__
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\oslo_utils\excutils.py", line 196, in force_reraise
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\six.py", line 693, in reraise
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\_utils.py", line 146, in inner
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\jobutils.py", line 246, in modify_virt_resource
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\jobutils.py", line 74, in check_ret_val
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\os_win\utils\jobutils.py", line 118, in _wait_for_job
os_win.exceptions.WMIJobFailed: WMI job failed with status 10. Error summary description: Failed to modify device 'Processor'.

Cannot change the processor settings of a virtual machine now.. Error description: 'golem' failed to modify device 'Processor'. (Virtual machine ID 3C464F0E-7279-4AAC-8BD8-08A057899FD7)

Cannot change the processor settings of virtual machine 'golem' while it is in a saved state. (Virtual machine ID 3C464F0E-7279-4AAC-8BD8-08A057899FD7) Error code: 32775.
INFO     [golem.docker.hypervisor.hyperv     ] Hyper-V: reconfiguration of VM "golem" finished
INFO     [golem.docker.hypervisor            ] Docker: starting VM golem
ERROR    [golem.docker.hypervisor            ] Docker: failed to start the VM: CalledProcessError(1, ['docker-machine', '--native-ssh', 'start', 'golem'])
ERROR    [golem.docker.hypervisor.hyperv     ] Hyper-V: VM failed to start, this can be caused by insufficient RAM or HD free on the host machine
ERROR    [golem.docker.manager               ]
                ***************************************************************
                No supported VM hypervisor was found.
                Golem will not be able to compute anything.
                hypervisor.setup() returned CalledProcessError(1, ['docker-machine', '--native-ssh', 'start', 'golem'])
                ***************************************************************

ERROR    [golem.node                         ]
                    There was a problem setting up the environment: No VM hypervisor found.
                    Golem will run with limited functionality to support
                    communication with local clients.
```

more errors in full log below

[golem.log](https://github.com/golemfactory/golem/files/3359461/golem.log)

**Comment by Wiezzel** [comment]
I am unable to reproduce the issue. From the logs I can tell that the following happened:
1. Golem attempted to resume a saved VM.
2. Resuming failed probably due to low disk space. This is an expected situation handled by Golem.
3. Golem attempted to remove the saved VM state thus changing its status to 'disabled'.
4. Removing the saved VM state failed *silently* without raising any error. **This is where the bug is.**
5. Golem assumed the VM is disabled and attempted to change its configuration.
6. Changing the configuration failed because the VM wasn't actually disabled but still suspended.
7. Retry loop for start_vm caused 6. to occur a few times until finally giving up.
