### ISSUE TITLE
AttributeError: 'Server' object has no attribute 'socket'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4453]
## Description

**Golem Version**: 0.20.0

**Golem-Messages version** (leave empty if unsure): 3.7.0

**Electron version** (if used): 0.2.0

**OS** [e.g. Windows 10 Pro]:

**Branch** (if launched from source): -

**Mainnet/Testnet**: testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Encountered error `AttributeError: 'Server' object has no attribute 'socket'` in running app

## Logs and any additional context
```
2019-07-10 20:23:59 ERROR    golem.task.taskserver               TaskServer.sync_network job functools.partial(<bound method PendingConnectionsServer.sync_network of <golem.task.taskserver.TaskServer object at 0x11a9e72e8>>, timeout=900) failed
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskserver.py", line 208, in sync_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpserver.py", line 271, in sync_network
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 176, in dropped
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/server/queue_.py", line 88, in remove_session_by_node_id
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/server/queue_.py", line 92, in remove_session
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 979, in disconnect
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 108, in disconnect
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 140, in _send_disconnect
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/tasksession.py", line 990, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 201, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/session.py", line 115, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/network/transport/tcpnetwork.py", line 297, in send_message
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 186, in getHandle
AttributeError: 'Server' object has no attribute 'socket'
```

[golem.log](https://github.com/golemfactory/golem/files/3379028/golem.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ederenn** [comment]
encountered on again on branch b0.21, Linux 18.04

```
ERROR [golem.client ] p2pservice.sync_network failed
Traceback (most recent call last):
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/client.py", line 1420, in _run
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/p2pservice.py", line 256, in sync_network
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/p2pservice.py", line 954, in _sync_peer_keeper
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/p2pservice.py", line 622, in send_find_nodes
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 213, in send_find_node
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/p2p/peersession.py", line 132, in send
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 201, in send
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 115, in send
File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 297, in send_message
File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 224, in getHandle
AttributeError: 'Server' object has no attribute 'socket'
```

**Comment by ederenn** [comment]
encountered on 0.21.0 binaries, Linux 18.04
```ERROR    [golem.task.taskserver              ] TaskServer.sync_network job functools.partial(<bound method PendingConnectionsServer.sync_network of <golem.task.taskserver.TaskServer object at 0x7f6a2106ad68>>, timeout=900) failed
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 285, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpserver.py", line 271, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 182, in dropped
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/server/queue_.py", line 89, in remove_session_by_node_id
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/server/queue_.py", line 93, in remove_session
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 1017, in disconnect
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 108, in disconnect
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 140, in _send_disconnect
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 1028, in send
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 201, in send
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 115, in send
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 297, in send_message
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 224, in getHandle
AttributeError: 'Server' object has no attribute 'socket'
```

**Comment by etam** [comment]
This is closely related to #4409

**Comment by etam** [comment]
merged to b0.21
