### ISSUE TITLE
Restarting heavy task cause bottleneck on RPCs

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#4473]
## Description

**Golem Version**: 0.20.0, 0.20.1

**Golem-Messages version** (leave empty if unsure): - 

**Electron version** (if used): 0.2.0, 0.2.1

**OS** [e.g. Windows 10 Pro]: MacOS Mojave 10.14.5

**Branch** (if launched from source): - 

**Mainnet/Testnet**: Testnet

**Description of the issue**:

When user restarts a timed out heavy task (by means; 25 frames - 50 subtasks) which already had some computed subtasks, while Golem copying task definition and computed results to the new created task, the process creates a bottleneck on main thread (or rpc thread) and blocking RPCs and pubsubs.

**Actual result**:

Copying task results shouldn't hang the thread belong to RPCs

## Steps To Reproduce

1. Launch the app
2. Create a task with mutli-frame and multi-subtask,
in my case is `The Butterfly's Sowing` file can be found [here](https://www.nicolasfenix.com/blog/2016/the-butterflys-sowing.html)
with 25 frames and 50 subtasks 720x400 pixels, 40 min task and subtask timeout
3. Wait for some computation and timeout
4. After timeout, restart the task 
5. You will be able to see the bottleneck until task results copied to the new created task.

## Logs and any additional context
```
2019-07-15 13:43:45 INFO     golem.task.taskmanager              Task 32b197c2-a6e4-11e9-850d-fd1bfb720dba put into restarted state
2019-07-15 13:43:45 INFO     golem.ethereum.fundslocker          Locking funds for task: 'cd5ece34-a6f5-11e9-81d6-fd1bfb720dba' price: 0.400 GNTB num: 50
2019-07-15 13:43:45 INFO     golem.ethereum.transactionsystem    Locking 20.000 GNTB and 0.00334000 ETH for 50 payments
2019-07-15 13:43:45 INFO     golem.task.rpc                      Enqueue new task <Task: <TaskHeader: {'mask': None, 'timestamp': 1563191025, 'signature': None, 'task_id': 'cd5ece34-a6f5-11e9-81d6-fd1bfb720dba', 'task_owner': {'node_name': 'testo', 'key': 'fd1bfb720dba0eec89fc091002390df7e4ee1a6d91fcbc9105526c7a59c56e8bae1c162f19d05fc95d8f01bed3e8f5f946f216849016bea840bb26e818193767', 'prv_port': 40103, 'pub_port': 40103, 'p2p_prv_port': 40102, 'p2p_pub_port': 40102, 'prv_addr': '10.30.30.98', 'pub_addr': '5.226.70.18', 'prv_addresses': ['10.30.30.98'], 'hyperdrive_prv_port': 3282, 'hyperdrive_pub_port': 3282, 'port_statuses': {40102: 'open', 40103: 'open', 3282: 'open'}, 'nat_type': []}, 'deadline': 1563194625, 'subtask_timeout': 3600, 'environment': 'BLENDER', 'min_version': '0.20.0', 'estimated_memory': 0, 'max_price': 400000000000000022, 'subtasks_count': 50, 'concent_enabled': True}>>
2019-07-15 13:43:45 INFO     golem.network.p2p.p2pservice        Estimated network size: 16
2019-07-15 13:43:45 INFO     golem.network.p2p.p2pservice        Performance for env `BLENDER`: rank(0.0) = 0.0
2019-07-15 13:43:45 INFO     golem.task.rpc                      Task cd5ece34-a6f5-11e9-81d6-fd1bfb720dba initial mask size: 0 expected number of providers: 50.0 potential number of providers: 16
2019-07-15 13:43:45 INFO     golem.task.taskmanager              Task cd5ece34-a6f5-11e9-81d6-fd1bfb720dba added
2019-07-15 13:43:46 INFO     golem.task.rpc                      Resource package created. res_id='cd5ece34-a6f5-11e9-81d6-fd1bfb720dba'
2019-07-15 13:43:46 INFO     golem.task.rpc                      Task created. task_id='cd5ece34-a6f5-11e9-81d6-fd1bfb720dba'
2019-07-15 13:43:46 INFO     golem.task.rpc                      Ensuring deposit. min=40.00000000 optimal=80.00000000 task_id='cd5ece34-a6f5-11e9-81d6-fd1bfb720dba'
2019-07-15 13:43:47 INFO     golem.task.rpc                      Deposit confirmed. task_id='cd5ece34-a6f5-11e9-81d6-fd1bfb720dba'
2019-07-15 13:43:47 INFO     golem.task.taskmanager              Task cd5ece34-a6f5-11e9-81d6-fd1bfb720dba started
2019-07-15 13:43:47 INFO     golem.task.rpc                      Task enqueued. task_id='cd5ece34-a6f5-11e9-81d6-fd1bfb720dba'
2019-07-15 13:51:13 INFO     golem.client                        Updating masks
2019-07-15 13:51:13 INFO     golem.task.taskmanager              task is not active: cbaef90c-9d9a-11e9-981a-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:51:13 INFO     golem.task.taskmanager              task is not active: 5a9c9402-a6db-11e9-a8da-fd1bfb720dba, status: TaskStatus.restarted
2019-07-15 13:51:13 INFO     golem.task.taskmanager              task is not active: 9db0674c-9990-11e9-b414-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:51:13 INFO     golem.task.taskmanager              task is not active: 926bccb4-a574-11e9-9552-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:51:13 INFO     golem.task.taskmanager              task is not active: 32b197c2-a6e4-11e9-850d-fd1bfb720dba, status: TaskStatus.restarted
2019-07-15 13:51:13 INFO     golem.client                        Updating mask for task 'cd5ece34-a6f5-11e9-81d6-fd1bfb720dba' Mask size: 0
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.187.161.156:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.198.71.45:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.198.119.10:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.205.37.180:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=94.23.196.166:40104
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=188.165.227.180:40104
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=188.165.227.180:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=139.99.157.15:40104
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.198.173.21:40102
2019-07-15 13:51:13 INFO     golem.network.transport.session     Sending disconnect message. reason=Timeout, address=35.190.194.220:40102
2019-07-15 13:51:30 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.190.194.220:40102
2019-07-15 13:51:30 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=94.23.196.166:40104
2019-07-15 13:51:30 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.198.71.45:40102
2019-07-15 13:51:30 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.187.161.156:40102
2019-07-15 13:51:30 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=139.99.157.15:40104
2019-07-15 13:51:31 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.198.173.21:40102
2019-07-15 13:51:31 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=188.165.227.180:40104
2019-07-15 13:51:31 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.205.37.180:40102
2019-07-15 13:51:31 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=35.198.119.10:40102
2019-07-15 13:51:31 INFO     golem.network.transport.session     Received disconnect message. reason=Timeout, address=188.165.227.180:40102
2019-07-15 13:51:45 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd70f8142-a6f5-11e9-95c1-fd1bfb720dba'
2019-07-15 13:51:45 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd70f8142-a6f5-11e9-95c1-fd1bfb720dba'
2019-07-15 13:51:59 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd22b49ae-a6f5-11e9-a6f9-fd1bfb720dba'
2019-07-15 13:51:59 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd22b49ae-a6f5-11e9-a6f9-fd1bfb720dba'
2019-07-15 13:52:14 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cecfd8ba-a6f5-11e9-8693-fd1bfb720dba'
2019-07-15 13:52:14 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cecfd8ba-a6f5-11e9-8693-fd1bfb720dba'
2019-07-15 13:52:28 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cff81022-a6f5-11e9-ad76-fd1bfb720dba'
2019-07-15 13:52:28 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cff81022-a6f5-11e9-ad76-fd1bfb720dba'
2019-07-15 13:52:56 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd0d0d948-a6f5-11e9-9164-fd1bfb720dba'
2019-07-15 13:52:56 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd0d0d948-a6f5-11e9-9164-fd1bfb720dba'
2019-07-15 13:53:22 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'ce9a18f6-a6f5-11e9-8ce2-fd1bfb720dba'
2019-07-15 13:53:22 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'ce9a18f6-a6f5-11e9-8ce2-fd1bfb720dba'
2019-07-15 13:53:35 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd3e66300-a6f5-11e9-b0f9-fd1bfb720dba'
2019-07-15 13:53:35 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'd3e66300-a6f5-11e9-b0f9-fd1bfb720dba'
2019-07-15 13:53:59 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cf3d0106-a6f5-11e9-b3dc-fd1bfb720dba'
2019-07-15 13:53:59 WARNING  golem.task.taskmanager              Could not obtain computation time for subtask: 'cf3d0106-a6f5-11e9-b3dc-fd1bfb720dba'
2019-07-15 13:53:59 CRITICAL twisted                             Unhandled error in Deferred:
2019-07-15 13:53:59 CRITICAL twisted                             
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/deferred.py", line 28, in sync_wait
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 172, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/rpc.py", line 192, in _restart_subtasks
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/deferred.py", line 30, in sync_wait
twisted.internet.defer.TimeoutError: Command timed out
2019-07-15 13:53:59 WARNING  twisted                             dropping connection to peer tcp4:127.0.0.1:61000 with abort=True: WebSocket ping timeout (peer did not respond with pong in time)
2019-07-15 13:53:59 INFO     golem.client                        Updating masks
2019-07-15 13:53:59 INFO     golem.task.taskmanager              task is not active: cbaef90c-9d9a-11e9-981a-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:53:59 INFO     golem.task.taskmanager              task is not active: 5a9c9402-a6db-11e9-a8da-fd1bfb720dba, status: TaskStatus.restarted
2019-07-15 13:53:59 INFO     golem.task.taskmanager              task is not active: 9db0674c-9990-11e9-b414-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:53:59 INFO     golem.task.taskmanager              task is not active: 926bccb4-a574-11e9-9552-fd1bfb720dba, status: TaskStatus.finished
2019-07-15 13:53:59 INFO     golem.task.taskmanager              task is not active: 32b197c2-a6e4-11e9-850d-fd1bfb720dba, status: TaskStatus.restarted
2019-07-15 13:53:59 WARNING  twisted                             session closed with reason wamp.close.transport_lost [()]
2019-07-15 13:53:59 INFO     golem.client                        Updating mask for task 'cd5ece34-a6f5-11e9-81d6-fd1bfb720dba' Mask size: 0
2019-07-15 13:54:00 INFO     golem.network.p2p.peersession       Starting peer session. address=94.23.196.166:40104
2019-07-15 13:54:00 INFO     golem.network.p2p.p2pservice        Adding peer. node='Drohlum compute'(8a9dd5f9..4acd49dd), address=94.23.196.166:40104, key_difficulty=14
2019-07-15 13:54:01 WARNING  golem.rpc.session                   RPC: Cannot publish 'evt.net.connection', session is not yet established
2019-07-15 13:54:01 INFO     golem.rpc.session                   Client connected, starting WAMP-Ticket challenge.
2019-07-15 13:54:01 INFO     golem.rpc.session                   WAMP-Ticket challenge received.
2019-07-15 13:54:21 INFO     golem.client                        Updating masks
```

## Proposed Solution?
Move the copying process to another thread.

**Comment by etam** [comment]
Currently creating task rpc call returns task id asap and rest is done in background. Restarting task should behave similarly.
