### ISSUE TITLE
golem.database; migrate_payment TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4499]
## Description

**Golem Version**:  GOLEM Version: 0.20.0+dev259.g917ad6c

**Golem-Messages version** (leave empty if unsure):  golem_messages Version: 3.9.0

**Electron version** (if used): 0.2.1

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): develop

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During providing for other node. Both nodes on develop. 

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem on develop two nodes, provider and requestor
2. Request small task 400x400, Hellispoter, 1 frame, 5 subtasks, 30 min task, 10 min subtask, 0,2 bid
3.Go to provider's logs

## Logs and any additional context

```
2019-07-17 17:43:27 ERROR    golem.database                      Migration problem. db_row=('{"node_info": null, "fee": 133860000000000, "block_hash": "1280ae932e54b7f8487f45d8c10533f7eb6b0cd39f05e8d0867673565ce62b3e", "block_number": 8067086, "check": null, "tx": "3c81b1a1526d002f5196ba279936c7ac498ed8b4330063860ad42119648dfa3f"}', 3, '10d4425e30c45c7409f712b0c4f85dce2272cfab', '3b363eba41aaab', '2afb2cf8-9c0f-11e9-8eea-6c15fa96c125', '2019-07-01 16:47:55.547497')
Traceback (most recent call last):
  File "<string>", line 68, in migrate
  File "<string>", line 45, in migrate_payment
TypeError: 'NoneType' object is not subscriptable
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
might be related: #4500
