### ISSUE TITLE
migrate_payment sqlite3.IntegrityError: NOT NULL constraint failed: taskpayment.node

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4500]
## Description

**Golem Version**:  GOLEM Version: 0.20.0+dev259.g917ad6c

**Golem-Messages version** (leave empty if unsure):  golem_messages Version: 3.9.0

**Electron version** (if used): 0.2.1

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): develop

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During providing for other node. Both nodes on develop. 

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem on develop two nodes, provider and requestor
2. Request small task 400x400, Hellispoter, 1 frame, 5 subtasks, 30 min task, 10 min subtask, 0,2 bid
3.Go to provider's logs

## Logs and any additional context

```
2019-07-17 17:43:27 ERROR    golem.database                      Migration problem. db_row=('{"node_info": {"node_name": null, "key": null, "prv_port": null, "pub_port": null, "p2p_prv_port": null, "p2p_pub_port": null, "prv_addr": null, "pub_addr": null, "prv_addresses": [], "hyperdrive_prv_port": null, "hyperdrive_pub_port": null, "port_statuses": {}, "nat_type": null}, "fee": 35700000000000, "block_hash": "6256b653efe93cd673561a2c42e568e2839ee618f4363658ea6b83c9b6314d21", "block_number": 6747138, "check": null, "tx": "268d3978a22d86ab84413f3b6306f72297057b48c030509a6aa10cc8f3565a1d"}', 3, '1f3f9148d33a29d8c8a8b61b5d11983a83a2e817', '8c22836379471f', 'a900bc9a-edb8-11e8-9a02-6c15fa96c125', '2018-11-21 19:14:55.666239')
Traceback (most recent call last):
  File "<string>", line 68, in migrate
  File "<string>", line 48, in migrate_payment
sqlite3.IntegrityError: NOT NULL constraint failed: taskpayment.node
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
might be related: #4499
