### ISSUE TITLE
Blender benchmark fails with 'params.json' missing

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#4619]
## Description

**Golem Version**: 0.20.1

**Golem-Messages version** (leave empty if unsure): release

**Electron version** (if used): release

**OS** [e.g. Windows 10 Pro]: Windows, release: 10, version: 10.0.18362, machine: AMD64

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Blender benchmark failed and stopped golem startup.

## Steps To Reproduce

Reported repeatedly by windows users

## Expected behavior
Successful golem startup. 

## Logs and any additional context
```python
2019-07-26 10:06:23 INFO     golem.client                        Starting network ...
2019-07-26 10:06:24 INFO     golem.resource.hyperdrive.resourcesmanager Initializing HyperdriveResourceManager, using <HyperdriveAsyncClient hyperg at http://localhost:3292/api>
2019-07-26 10:06:24 INFO     golem.docker.manager                Docker: configuration unchanged
2019-07-26 10:06:24 INFO     golem.task.benchmarkmanager         Running all benchmarks with num_cores=7
2019-07-26 10:06:24 INFO     golem.task.benchmarkmanager         Running benchmark for BLENDER
2019-07-26 10:06:29 WARNING  golem.docker.task_thread            Task error - exit_code=1
stderr:
Traceback (most recent call last):
  File "/golem/entrypoints/render_entrypoint.py", line 5, in <module>
    with open('params.json', 'r') as params_file:
FileNotFoundError: [Errno 2] No such file or directory: 'params.json'

tail of stdout:


2019-07-26 10:06:29 WARNING  golem.task.taskthread               Task computing error Subtask computation failed with exit code 1
2019-07-26 10:06:29 WARNING  golem.task                          Failed to compute benchmark Subtask computation failed with exit code 1
2019-07-26 10:06:29 ERROR    golem.task.benchmarkmanager         Unable to run BLENDER benchmark: Subtask computation failed with exit code 1
2019-07-26 10:06:29 CRITICAL golem.client                        Can't start network. Giving up.
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 331, in start
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 383, in start_network
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskserver.py", line 131, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskcomputer.py", line 78, in __init__
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\deferred.py", line 33, in sync_wait                                                 
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\python\failure.py", line 385, in raiseException
Exception: Subtask computation failed with exit code 1
```

[golem 0.20.1.log](https://github.com/golemfactory/golem/files/3515474/golem.0.20.1.log)

## Proposed Solution?
It's been suggested that there is some problem with mounting docker resources under MSWin.

**Comment by mfranciszkiewicz** [comment]
It appears that volumes aren't correctly mounted for Golem VM with VirtualBox (Docker Toolbox).

Workaround:
1. Make sure that Golem VM is running with `docker-machine status golem`
    - if not, start Golem and wait for it to fail
2. In a command line window, run:
```
@FOR /f "tokens=*" %i IN ('docker-machine env golem') DO @%i
docker-machine ssh golem "sudo /sbin/mount.vboxsf c/Users /c/Users"
```
3. Start Golem
