### ISSUE TITLE
Payment history window issue

### ISSUE THREAD

**Issue by chfast** [golemfactory/clay#466]
When payments are disabled and button <kbd>View Payments History</kbd> is clicked:

```
Traceback (most recent call last):
  File "/home/chfast/Projects/golem/golem/gnr/customizers/gnrmainwindowcustomizer.py", line 209, in _show_payments_clicked
    PaymentsDialogCustomizer(payments_window, self.logic)
  File "/home/chfast/Projects/golem/golem/gnr/customizers/customizer.py", line 15, in __init__
    self.load_data()
  File "/home/chfast/Projects/golem/golem/gnr/customizers/paymentsdialogcustomizer.py", line 9, in load_data
    for payment in payments:
TypeError: iteration over non-sequence
```

**Comment by chfast** [comment]
Fixed in https://github.com/imapp-pl/golem/pull/447/commits/7c199c1df535a066404136ae62b3fb51b695986d.
