### ISSUE TITLE
WASM task info / task progress error

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4675]
## Description

**Golem Version**: 0.20.2

**Electron version** (if used): ?

**Branch** (if launched from source): b0.20

**Mainnet/Testnet**: testnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
P2 label is set for Severity-Low/ Effort-easy

**Description of the issue**:

```
AttributeError: 'WasmTask' object has no attribute 'subtasks': Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 429, in as_future
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 875, in get_tasks
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 873, in <genexpr>
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 832, in get_task
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 1074, in get_task_dict
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/core/common.py", line 176, in func_wrapper
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/task/taskmanager.py", line 1006, in query_task_state
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/wasm/task.py", line 435, in get_progress
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/apps/wasm/task.py", line 389, in get_total_tasks
    
builtins.AttributeError: 'WasmTask' object has no attribute 'subtasks'
```

**Comment by cryptobench** [comment]
@shadeofblue I assume this is from my message on the rocket chat? If so:

I just upgraded to 0.20.2 from 0.20.1 and tried to launch a wasm task, and I did get a task ID but nothing popped up in the GUI under tasks or in the CLI. 

I deleted the whole rinkeby folder and launched Golem again and then everything was working again.

**Comment by shadeofblue** [comment]
okay, we decided it's not a big issue at this moment... thanks for the update @cryptobench
