### ISSUE TITLE
Tasks suddenly 'freeze' and does not start any subtasks.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/clay#4696]
## Description
Launching a Blender task on the testnet suddenly freeze and do nothing. I launched a task and 2 out of 10 subtasks computed and then nothing more happened. Subtasks aren't even being started according to the GUI. No failures or timeouts. 10 Nodes connected, and developer mode in the GUI reports 0 tasks active on the network.  

**Golem Version**:
0.20.2
**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):
0.20.2 Release 
**OS** [e.g. Windows 10 Pro]:
Mac OS
**Branch** (if launched from source):

**Mainnet/Testnet**:
Testnet
**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Actual result**:
Tasks running timer keeps counting up and eventually timeout.

**Screenshots**:
![image](https://user-images.githubusercontent.com/33448819/64440231-e4f96980-d0cb-11e9-985c-e3f4f51e7282.png)

![image](https://user-images.githubusercontent.com/33448819/64440248-ee82d180-d0cb-11e9-8a64-235c3723b73e.png)

![image](https://user-images.githubusercontent.com/33448819/64440794-ebd4ac00-d0cc-11e9-8478-a56a06bb3a15.png)

Tried restarting the task that went stuck at 2 subtasks, and the next one does absolutely nothing. 

I am connected to peers on the network.

> PhillipMBP:~ golemgrid$ golemcli network show --json
{
  "headers": [
    "ip",
    "port",
    "id",
    "name"
  ],
  "values": [
    [
      "188.165.227.180",
      40102,
      "31401dea11dc8dee...b5f57c339e5cb8a1",
      "Ruggu git"
    ],
    [
      "35.198.173.21",
      40102,
      "e314b570c56eb449...c4dea5242d93ff19",
      "testnet-gf-devel-2 git"
    ],
    [
      "35.198.119.10",
      40102,
      "cde73fb1b26ae227...c33cfafbe5261156",
      "testnet-gf-devel-0 git"
    ],
    [
      "35.190.194.220",
      40102,
      "56a87e232975cd2e...fd9552c37bc948fd",
      "testnet-gf-compute-0 compute"
    ],
    [
      "94.23.196.166",
      40104,
      "551839a2606d308a...b9ca0255cc6d6219",
      "Drohlum compute"
    ],
    [
      "35.198.71.45",
      40102,
      "626b3ec66cadf733...78e88ee09e8da6e4",
      "testnet-gf-devel-1 git"
    ],
    [
      "35.187.161.156",
      40102,
      "cde03546b6fe61aa...d1bec18a6d39d75d",
      "testnet-gf-compute-2 compute"
    ],
    [
      "35.205.37.180",
      40102,
      "236d629ed1778eb3...52196c6f7bb0ec85",
      "testnet-gf-compute-1 compute"
    ],
    [
      "188.165.227.180",
      40104,
      "b5b25574de599b20...cf74ab560ff19720",
      "Ruggu compute"
    ]
  ]
}

## Steps To Reproduce
Don't know if this is reproduceable, but this is what I did:
1. Launch a Blender task
2. My first blender task finished perfectly.
3. Launch second Blender task
4. Maybe 1-2 subtasks finish and then nothing more

## Expected behavior
Task finish as expected.

## Logs and any additional context
[golem.zip](https://github.com/golemfactory/golem/files/3584623/golem.zip)

**Blender task that finished** = 8dc4ede2-d096-11e9-991a-46cb63f127ae
**Blender task that got stuck at 2 subtask** = c336359e-d09c-11e9-bbac-46cb63f127ae
**Third blender task that was a restart of the one stuck at 2 subtasks** = e6065b12-d0a8-11e9-9a7f-46cb63f127ae

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by cryptobench** [comment]
![image](https://user-images.githubusercontent.com/33448819/64452157-1717c500-d0e6-11e9-8ebe-a2bce75b521e.png)
Still an issue. This is the same task as above.

Uploading logs if you want to see if there's any difference to the previous one uploaded.

[Logs.zip](https://github.com/golemfactory/golem/files/3585262/Logs.zip)

**Comment by cryptobench** [comment]
Spotted an error that has been popping up fairly frequently.

```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2019-09-06 22:52:58 ERROR    sentry.errors.uncaught              ["Can't resolve seeds.test.golem.network:40102. [Errno 8] nodename nor servname provided, or not known"]
2019-09-06 22:52:58 ERROR    sentry.errors                       Sentry responded with an error: <urlopen error [Errno 8] nodename nor servname provided, or not known> (url: https://talkback.golem.network/api/2/store/)
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/raven/utils/http.py", line 31, in connect
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno 8] nodename nor servname provided, or not known```

**Comment by cryptobench** [comment]
Issue is fixed after i deleted the whole rinkeby folder and restarting Golem and let it recreate everything. Closing issue
