### ISSUE TITLE
NameError: free variable 'dc' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4764]
## Description

**Golem Version**: INFO     0.20.2+dev538.g964b8e3

**Golem-Messages version** (leave empty if unsure): golem_messages Version: 3.11.0

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

In `golem.log` appeared error `NameError: free variable 'dc' referenced before assignment in enclosing scope`
No particular reason, node was just started.

## Logs and any additional context
```ERROR    [asyncio                            ] Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=681301.292927569 AsyncioSelectorReactor.callLater.<locals>.run() at /home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 288, in run
NameError: free variable 'dc' referenced before assignment in enclosing scope
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
Looks like an twisted internal error. I'll report it upstream. I'm not sure if we'll be able to do anything about it before release.
Is it somehow reproducible? Does it causes any visible effects?

**Comment by etam** [comment]
https://twistedmatrix.com/trac/ticket/9708

**Comment by ederenn** [comment]
happened randomly after starting a node just before connecting to other nodes
