### ISSUE TITLE
reentrant call inside logger

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4768]
## Description

**Golem Version**: INFO     0.20.2+dev538.g964b8e3

**Golem-Messages version** (leave empty if unsure): golem_messages Version: 3.11.0

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During closing Golem from console stack trace appeared. Binary Golem was run from console window, binary electron separately from other console. Single crtl c to close Golem. Electron has been closed first. No other errors during this run of Golem.

## Logs and any additional context

```
INFO     [golem.client                       ] Updating masks
^CWARNING  [twisted                            ] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
INFO [actix_server::builder] SIGINT received, exiting
WARNING  [twisted                            ] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
--- Logging error ---
INFO [actix_server::builder] SIGINT received, exiting
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/home/ederenn/.local/share/golem/default/mainnet/logs/golem.error.log'>
Call stack:
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 295, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 243, in main
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 204, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 200, in _start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 203, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 267, in run
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    raise RuntimeError(
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1404, in _run_once
    logger.log(level, 'poll took %.3f ms: %s events',
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/node/controller.py", line 169, in signal_handler
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 190, in _log
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 595, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_stdlib.py", line 116, in __call__
  File "/usr/lib/python3.6/logging/__init__.py", line 1361, in log
    Log 'msg % args' with the integer severity 'level'.
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/node/controller.py", line 169, in signal_handler
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 190, in _log
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 595, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_stdlib.py", line 116, in __call__
  File "/usr/lib/python3.6/logging/__init__.py", line 1361, in log
    Log 'msg % args' with the integer severity 'level'.
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
Message: <twisted.logger._stdlib.StringifiableFromEvent object at 0x7fcfd40241d0>
Arguments: ()
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
Reported upstream: https://github.com/crossbario/crossbar/issues/1639

**Comment by etam** [comment]
So the upstream bug report was closed. We're not supposed to run crossbar router by importing classes into our code. Let's continue at #4769.
