### ISSUE TITLE
 subtask fail `None of the Docker images are available` on verification stops task from finishing

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4792]
## Description

**Golem Version**: 0.21.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 0.2.3

**OS** [e.g. Windows 10 Pro]: Any, checked on Linux

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

When one of the subtasks fails with error `None of the Docker images are avaliable`  this subtask is not computed again. In logs repeats info
```INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s)
INFO     [golem.task.taskmanager             ] no more computation needed: b4337cf6-ee7e-11e9-96ed-5ad86f3605c2
INFO     [golem.network.transport.session    ] Sending disconnect message. reason=NoMoreMessages, address=84.10.50.51:60852
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s)
INFO     [golem.task.taskmanager             ] no more computation needed: b4337cf6-ee7e-11e9-96ed-5ad86f3605c2
INFO     [golem.network.transport.session    ] Sending disconnect message. reason=NoMoreMessages, address=173.208.179.154:4264
```

Rest of the subtasks were finished in less than on hour, this one remained in `Failure` state until task timeout (1,5h more) Task has ended in timeout.

Faling node name `bigarmsbiggut12` id: `f080031296b3668368e7b9b81f1a9bdd4cadb7f6755f9438a19ed9eb1fcab23261961dc8543bdefdecd6e181da26c832bf2f68b9f51fd208aa95322632f5e357`

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem
2. Start a longer task, at least 20 frames 40 subtasks. In this case BlenderBoy resolution and samples. frames: 40-59, subtasks 40, bid 0.1
3. Wait for verification failure on specific node
4. Task will end in timeout.

## Logs and any additional context

failed subtask id:
`c80cc638-ee7e-11e9-bedd-5ad86f3605c2`
logs:
[golem (3).log](https://github.com/golemfactory/golem/files/3725405/golem.3.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
There is no "None of the Docker images are avaliable" in the attached log file. The only thing related to subtask `c80cc638-ee7e-11e9-bedd-5ad86f3605c2` is 
```
2019-10-14 14:58:22 INFO     golem.task.taskmanager              Subtask 'c80cc638-ee7e-11e9-bedd-5ad86f3605c2' dies with status 'Starting'
```
But another important thing is 
```
2019-10-14 14:58:31 CRITICAL twisted                             Unhandled error in Deferred:
2019-10-14 14:58:31 CRITICAL twisted                             
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 405, in _offer_chosen
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 493, in _get_next_ctd
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskmanager.py", line 472, in get_next_subtask
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/blender/task/blenderrendertask.py", line 433, in query_extra_data
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 349, in _update_frame_task_preview
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 459, in __mark_sub_frame
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/resources/imgrepr.py", line 148, in save_with_extension
FileNotFoundError: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/b4337cf6-ee7e-11e9-96ed-5ad86f3605c2/tmp/current_task_preview5.PNG_tmp.png' -> '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/b4337cf6-ee7e-11e9-96ed-5ad86f3605c2/tmp/current_task_preview5.PNG'
```
And I can improve that.
Edit: it's actually the same as #4801, but I see that it's not handling `FileNotFoundError`.

**Comment by etam** [comment]
https://github.com/golemfactory/golem/issues/4801#issuecomment-557482440
