### ISSUE TITLE
 Session.onUserError(): "TypeError: get_subtask() missing 1 required positional argument: 'task_id'"

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4888]
## Description

**Golem Version**:  GOLEM Version: 0.21.0+dev413.g4be8f69

**Golem-Messages version** (leave empty if unsure):  3.14.0

**Electron version** (if used): 0.21.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

In logs appeared an error 
```
2019-11-14 15:44:49 ERROR    twisted                             Session.onUserError(): "TypeError: get_subtask() missing 1 required positional argument: 'task_id'"
Traceback (most recent call last):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 322, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 1006, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/txaio/tx.py", line 429, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
builtins.TypeError: get_subtask() missing 1 required positional argument: 'task_id'
```

happens after typing in cli `golemcli tasks subtasks show <id>`

## Logs and any additional context

[golem (2) (1).log](https://github.com/golemfactory/golem/files/3847475/golem.2.1.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by kmazurek** [comment]
https://github.com/golemfactory/golem/pull/4893
