### ISSUE TITLE
problem converting GNT to GNTB; 'insufficient funds for gas * price + value'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4943]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev469.ge527148

**Golem-Messages version** (leave empty if unsure): 3.14.0

**Electron version** (if used): 0.21.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04; Windows 10 Pro

**Branch** (if launched from source): b0.22 based

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Problem with converting GNT to GNTB gives error in log, repeats multiple times until conversion is finished.

**Actual result**:

No converted money in a wallet

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch new mainnet Golem instance - could be created by renaming mainnet folder
2. Send from other node some ETH first (in this example 0,02 ETH)
3. Right after send some GNT (in this example 5 GNT)
4. See error in logs of a supplied node.

## Logs and any additional context

```
2019-11-26 17:11:36 CRITICAL golem_sci.implementation            web3 JSON rpc critical error ValueError({'code': -32000, 'message': 'insufficient funds for gas * price + value'},)
2019-11-26 17:11:36 ERROR    golem                               Service Error: Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 1078, in _run
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 64, in curry
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 1030, in _try_convert_gnt
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 678, in open_gate
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 449, in _create_and_send_transaction
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 396, in _sign_and_send_transaction
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/client.py", line 98, in send
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/web3/eth.py", line 250, in sendRawTransaction
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/web3/manager.py", line 106, in request_blocking
    
builtins.ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
NoneType: None
2019-11-26 17:11:36 INFO     golem.resources                     Finished resource handshake with 'ef4493d5..bc89fccd'
2019-11-26 17:11:40 INFO     golem.task.taskserver               requestor is DenyReason.temporarily_blocked. node=5ad86f36..34d07c7d
2019-11-26 17:11:46 INFO     golem.task.taskserver               requestor is DenyReason.temporarily_blocked. node=5ad86f36..34d07c7d
2019-11-26 17:11:48 INFO     golem_sci.transactionsstorage       Saving transaction 0xe7e813264d2009ab33c0f962f620796c9e3ff3368efaa127d2783b043c3d395d, nonce=0
```

time of a last error entry
```
2019-11-27 03:50:32 ERROR  (...)
builtins.ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
NoneType: None
```

conversion times:
```
2019-11-26 17:14:25 INFO     golem.ethereum.transactionsystem    Opening GNT-GNTB conversion gate 0xb5ce55da4bde8a3be7634c529c74411a2d173d7fbf865c1e4c380c14aec87f00
```

```
2019-11-26 17:27:39 INFO     golem.ethereum.transactionsystem    Converting 5.000000 GNT to GNTB
```

sender:
```
2019-11-26 17:01:37 INFO     golem.ethereum.transactionsystem    Trying to withdraw 0.020000 ETH to 0x6948303274466941d8cd4f0897C3721C2ABF9b4f
2019-11-26 17:01:40 INFO     golem_sci.transactionsstorage       Saving transaction 0xcc0f1d43d434099bcd177953168b62180eedbacb2b56db449381842720a6b64d, nonce=515
2019-11-26 17:01:51 INFO     golem.ethereum.transactionsystem    Trying to withdraw 5.000000 GNT to 0x6948303274466941d8cd4f0897C3721C2ABF9b4f
2019-11-26 17:01:52 INFO     golem_sci.transactionsstorage       Saving transaction 0x71498a15144b07299f43a9deb83db069892b94f73264d28abd0d2d5be212f8d7, nonce=516
```

full logs:
win:
[golem.2019-11-27.log](https://github.com/golemfactory/golem/files/3904983/golem.2019-11-27.log)

linux:
[golem.log](https://github.com/golemfactory/golem/files/3904985/golem.log)
[golem.2019-11-26.log](https://github.com/golemfactory/golem/files/3904986/golem.2019-11-26.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by jiivan** [comment]
We still need to release SCI and update it in requirements
