### ISSUE TITLE
Failed to update balance: ValueError({'code': -32000, 'message': 'header not found'},)

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4944]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev469.ge527148

**Golem-Messages version** (leave empty if unsure): 3.14.0

**Electron version** (if used): 0.21.0

**OS** [e.g. Windows 10 Pro]: Linux 18.04;

**Branch** (if launched from source): b0.22 based

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

In logs appeared errors 

```
Failed to update ETH balance: ValueError({'code': -32000, 'message': 'header not found'},)
```

```
Failed to update GNT balance: ValueError({'code': -32000, 'message': 'header not found'},)
```

appears after:
```
problem converting GNT to GNTB; 'insufficient funds for gas * price + value' 
```
https://github.com/golemfactory/golem/issues/4943

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch new mainnet Golem instance - could be created by renaming mainnet folder
2. Send from other node some ETH first (in this example 0,02 ETH)
3. Right after send some GNT (in this example 5 GNT)
4. See error in logs of a supplied node.

## Logs and any additional context

```
2019-11-26 17:37:34 WARNING  golem.ethereum.transactionsystem    Failed to update ETH balance: ValueError({'code': -32000, 'message': 'header not found'},)
2019-11-26 17:37:34 WARNING  golem.ethereum.transactionsystem    Failed to update GNT balance: BlockNumberOutofRange()
2019-11-26 17:37:42 CRITICAL twisted                             
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 136, in _readOrWrite
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 326, in dataReceived
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/tcpnetwork.py", line 352, in _interpret
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 190, in interpret
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/session.py", line 75, in interpret
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 179, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/history.py", line 375, in wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 634, in _react_to_task_to_compute
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 64, in curry
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ethereum/transactionsystem.py", line 488, in get_available_gnt
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 187, in get_gntb_balance
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/golem_sci/implementation.py", line 379, in _call
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/web3/contract.py", line 1021, in call
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/web3/contract.py", line 1317, in parse_block_identifier
web3.exceptions.BlockNumberOutofRange
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by ederenn** [comment]
happened also in 23.1 version when restarting an app

```
GOLEM Version: 0.22.2+dev40.gc2d81e8
Protocol Version: 32
 golem_messages Version: 3.15.0
```

```WARNING  [golem.ethereum.transactionsystem   ] Failed to update ETH balance: GethError({'code': -32000, 'message': 'header not found'},)
WARNING  [golem.ethereum.transactionsystem   ] Failed to update GNT balance: BlockNumberOutofRange()
WARNING  [golem.ethereum.transactionsystem   ] Failed to update GNTB balance: BlockNumberOutofRange()
WARNING  [golem.ethereum.transactionsystem   ] Failed to update deposit balance: BlockNumberOutofRange()
```
