### ISSUE TITLE
task_computation_cancelled AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5011]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev519.gbda31db
                               GOLEM Version: 0.21.0+dev518.g740764a
                                GOLEM Version: 0.21.0+dev516.gb4c6fa7
**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

`'NoneType' object has no attribute 'value'` appears in logs when computing gwasm tasks

**Actual result**:

Gwasm tasks are not finishing

## Steps To Reproduce

1. Launch the Golem
2. Request a Gwasm tasks, text approx 550 words, 10 subtasks, 2 min for a subtask, 10 min for a task, bid 0.1
3.Wait for computations to start
4. Check logs for error

## Logs and any additional context

```
>> tasks subtasks list af73a61c-219f-11ea-b309-350634f06032
┌──────────────┬────────────────────────────────────────┬─────────────┬────────────┐
│  node        │  subtask id                            │  status     │  progress  │
├──────────────┼────────────────────────────────────────┼─────────────┼────────────┤
│  vvv mojave  │  c1213022-219f-11ea-b3f3-350634f06032  │  Finished   │  100.0 %   │
│  maczmija    │  c1239208-219f-11ea-8998-350634f06032  │  Finished   │  100.0 %   │
│  maczmija    │  c125f2b0-219f-11ea-b65b-350634f06032  │  Finished   │  100.0 %   │
│  maczmija    │  c125f2b1-219f-11ea-883f-350634f06032  │  Failure    │  0.0 %     │
│  maczmija    │  c128568c-219f-11ea-baef-350634f06032  │  Failure    │  0.0 %     │
│  maczmija    │  c12ab8dc-219f-11ea-9899-350634f06032  │  Failure    │  0.0 %     │
│  maczmija    │  c12ab8dd-219f-11ea-a678-350634f06032  │  Failure    │  0.0 %     │
│  maczmija    │  c12d5cb8-219f-11ea-a82b-350634f06032  │  Failure    │  0.0 %     │
│  vvv lin     │  c12f7d9c-219f-11ea-8df4-350634f06032  │  Finished   │  100.0 %   │
│  vvv lin     │  c12f7d9d-219f-11ea-8e81-350634f06032  │  Finished   │  100.0 %   │
│  vvv lin     │  c1322bac-219f-11ea-97a7-350634f06032  │  Failure    │  0.0 %     │
│  tempest     │  c13442ae-219f-11ea-9857-350634f06032  │  Finished   │  100.0 %   │
│  tempest     │  c13442af-219f-11ea-b597-350634f06032  │  Finished   │  100.0 %   │
│  tempest     │  c136a49a-219f-11ea-b647-350634f06032  │  Failure    │  0.0 %     │
│  tempest     │  c1390710-219f-11ea-90e0-350634f06032  │  Failure    │  0.0 %     │
│  tempest     │  c1390711-219f-11ea-8c35-350634f06032  │  Failure    │  0.0 %     │
│  tempest     │  c13bdbc0-219f-11ea-9cac-350634f06032  │  Failure    │  0.0 %     │
│  vvv mojave  │  cf1ed576-219f-11ea-b351-350634f06032  │  Verifying  │  0.0 %     │
│  maczmija    │  cf213ac6-219f-11ea-8893-350634f06032  │  Finished   │  100.0 %   │
│  maczmija    │  cf2607a2-219f-11ea-9bfc-350634f06032  │  Failure    │  0.0 %     │
│  vvv mojave  │  171e9a68-21a0-11ea-9c60-350634f06032  │  Finished   │  100.0 %   │
│  vvv mojave  │  21db8490-21a0-11ea-aac6-350634f06032  │  Finished   │  100.0 %   │
│  vvv mojave  │  2d30c074-21a0-11ea-b55d-350634f06032  │  Finished   │  100.0 %   │
│  vvv mojave  │  3df43030-21a0-11ea-8d7b-350634f06032  │  Finished   │  100.0 %   │
│  vvv mojave  │  4fbdf774-21a0-11ea-952c-350634f06032  │  Verifying  │  0.0 %     │
│  vvv mojave  │  5a75bf4c-21a0-11ea-88c7-350634f06032  │  Verifying  │  0.0 %     │
│  vvv mojave  │  682c5fb4-21a0-11ea-87c2-350634f06032  │  Verifying  │  0.0 %     │
└─────
```

```
2019-12-18 15:07:42 INFO     golem.task.tasksession              Provider can't compute subtask. subtask_id: 'c1322bac-219f-11ea-97a7-350634f06032', reason: None 
2019-12-18 15:07:42 INFO     golem.task.taskserver               requestor is DenyReason.temporarily_blocked. node=89b2d9f3..f9501dd3 
2019-12-18 15:07:42 CRITICAL twisted                             Unhandled error in Deferred: 
2019-12-18 15:07:42 CRITICAL twisted                              
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\tasksession.py", line 734, in _react_to_cannot_compute_task
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\core\common.py", line 189, in func_wrapper
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\task\taskmanager.py", line 869, in task_computation_cancelled
AttributeError: 'NoneType' object has no attribute 'value'
```

after requesting the gwasm task

```
2019-12-18 18:55:12 INFO     golem.task.rpc                      Creating task. task_dict={'bid': 1.0, 'name': 'g_flite', 'options': {'input_dir': '\\\\?\\C:\\Users\\ederenn\\Desktop\\workspace\\in', 'js_name': 'g_flite.js', 'output_dir': '\\\\?\\C:\\Users\\ederenn\\Desktop\\workspace\\out', 'output_path': '\\\\?\\C:\\Users\\ederenn\\Desktop', 'subtasks': {'subtask_0': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_1': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_2': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_3': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_4': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_5': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_6': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_7': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_8': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}, 'subtask_9': {'exec_args': ['in.txt', 'in.wav'], 'output_file_paths': ['in.wav']}}, 'wasm_name': 'g_flite.wasm'}, 'subtask_timeout': '00:02:00', 'timeout': '00:10:00', 'type': 'wasm'} 
```

full log:
requestor:
[golem.log](https://github.com/golemfactory/golem/files/3983673/golem.log)

providers:
[golem (5).log](https://github.com/golemfactory/golem/files/3983694/golem.5.log)
[golem (6).log](https://github.com/golemfactory/golem/files/3983695/golem.6.log)
[golem (7).log](https://github.com/golemfactory/golem/files/3983697/golem.7.log)

## Proposed Solution?
Modify GM to make error field required

**Comment by jiivan** [comment]
Modify GM to make error field required

**Comment by ederenn** [comment]
Happened again in 0.22.1 version in concent task
task requested 

Task: small shark resolution and sampling from file, 2 frames, 4 subtasks, bid 0.1

```
2020-01-23 17:55:08 INFO     golem.task.tasksession              Provider can't compute subtask. subtask_id: '1b95589c-3e01-11ea-b790-1a933e629084', reason: None 
2020-01-23 17:55:08 CRITICAL twisted                             Unhandled error in Deferred: 
2020-01-23 17:55:08 CRITICAL twisted                              
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 737, in _react_to_cannot_compute_task
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 189, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskmanager.py", line 883, in task_computation_cancelled
AttributeError: 'NoneType' object has no attribute 'value'
````

full log below:
[golem (12).log](https://github.com/golemfactory/golem/files/4110100/golem.12.log)

**Comment by etam** [comment]
fix merged to b0.22
