### ISSUE TITLE
in _calculate_efficiency TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5014]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev516.gb4c6fa7

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Linux 18.04

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

`in _calculate_efficiency TypeError: unsupported operand type(s) for /: 'int' and 'NoneType' appeared in logs, most probably after providing for gwasm task

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the Golem on requestor and three providers
2. Request a Gwasm tasks, text approx 550 words, 10 subtasks, 2 min for a subtask, 10 min for a task, bid 0.1
3. Wait for computations to start
4. Check provider logs

## Logs and any additional context

```
2019-12-18 15:07:43 INFO     golem.task.taskcomputer             Task 'c12f7d9d-219f-11ea-8e81-350634f06032' computed, work_wall_clock_time 1.6171543598175049 
2019-12-18 15:07:43 INFO     golem.task.taskcomputer             Task 'c12f7d9c-219f-11ea-8df4-350634f06032' computed, work_wall_clock_time 1.6554396152496338 
2019-12-18 15:07:43 CRITICAL twisted                             Unhandled error in Deferred: 
2019-12-18 15:07:43 CRITICAL twisted                              
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 680, in <lambda>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 610, in task_computed
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 613, in _task_finished
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskcomputer.py", line 876, in task_finished
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 995, in finished_subtask_listener
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ranking/manager/database_manager.py", line 167, in update_requestor_efficiency
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/ranking/manager/database_manager.py", line 136, in _calculate_efficiency
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
```

[golem (6).log](https://github.com/golemfactory/golem/files/3984034/golem.6.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by jiivan** [comment]
fixed in #5030
