### ISSUE TITLE
it is not possible to delete finished task API tasks from the task list

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5022]
## Description

**Golem Version**: GOLEM Version: 0.21.0+dev531.g329e2ba 

**Golem-Messages version** (leave empty if unsure): 3.14.1

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: any

**Branch** (if launched from source):

**Mainnet/Testnet**: testnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

It is not possible to remove task api tasks from the task list once they are finished. Task delete is treated as abort after the task is finished, and `tasks purge` gives an error

**Actual result**:

not possible to remove finished tasks from the task list

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app on testnet
2. Create a task API task
3. Wait for task to finish or timeout
4. Try to remove created task with `tasks delete <task_id>`
5. Try to remove all the tasks with `tasks purge`

## Expected behavior
Task should be deleted

## Logs and any additional context

```
ederenn@GOLEM2008-UBNT18:~/Desktop$ golemcli tasks delete fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2
ERROR [golemcli] wamp.error.runtime_error: Task not active, can not abort. task_id=fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2
ederenn@GOLEM2008-UBNT18:~/Desktop$ golemcli tasks purge 
ERROR [golemcli] wamp.error.runtime_error: Task not active, can not abort. task_id=fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2
ederenn@GOLEM2008-UBNT18:~/Desktop$ golemcli tasks list
┌────────────────────────────────────────┬───────┬──────────────────┬────────────┬──────────────┐
│  id                                    │  ETA  │  subtasks_count  │  status    │  completion  │
├────────────────────────────────────────┼───────┼──────────────────┼────────────┼──────────────┤
│  fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2  │       │                  │  Timeout   │              │
│  791db440-2326-11ea-8107-1a83d0c4dce2  │       │                  │  Finished  │              │
└────────────────────────────────────────┴───────┴──────────────────┴────────────┴──────────────┘
ederenn@GOLEM2008-UBNT18:~/Desktop$ 
related https://github.com/golemfactory/golem/issues/5020
```

Additional problem:
When task was created in `blenderapp:0.7.0` and the new container `blenderapp:0.7.2` can not clean up the task  and gives error in logs:

```
ERROR    [twisted                            ] Session.onUserError(): "RuntimeError: Task not active, can not abort. task_id=fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2"
Traceback (most recent call last):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/ederenn/projects/golem/golem/client.py", line 763, in delete_task
    yield deferred_from_future(rtm.delete_task(task_id))
  File "/home/ederenn/projects/golem/golem/core/deferred.py", line 75, in adapt
    extracted = result.result()
  File "/home/ederenn/projects/golem/golem/task/requestedtaskmanager.py", line 577, in delete_task
    await self.abort_task(task_id)
  File "/home/ederenn/projects/golem/golem/task/requestedtaskmanager.py", line 554, in abort_task
    f"Task not active, can not abort. task_id={task_id}")
builtins.RuntimeError: Task not active, can not abort. task_id=fcf6b99a-1dc4-11ea-b8aa-1a83d0c4dce2
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by jiivan** [comment]
possibly fixed by #5021
