### ISSUE TITLE
Verification fails when using disallow node/IP

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/clay#5045]
**Golem Version**: 0.22

**Golem-Messages version** (leave empty if unsure): 3.14.3

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04.3 LTS

**Branch** (if launched from source): b0.22

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:
When requesting a task with the option `DISALLOW_NODE_TIMEOUT_SECONDS` or `DISALLOW_IP_TIMEOUT_SECONDS` enabled, subtask verification will fail with the below exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/data/golem/golem_git/apps/core/verification_queue.py", line 85, in callback
    result=args[0][2])
  File "/data/golem/golem_git/apps/core/task/coretask.py", line 228, in verification_finished_
    verification_finished()
  File "/data/golem/golem_git/golem/core/common.py", line 205, in func_wrapper
    return func(*args, **kwargs)
  File "/data/golem/golem_git/golem/task/taskmanager.py", line 784, in verification_finished_
    verification_finished()
  File "/data/golem/golem_git/golem/task/server/verification.py", line 150, in verification_finished_old
    verification_failed,
  File "/data/golem/golem_git/golem/task/server/verification.py", line 86, in verification_finished
    ip=self.address,
AttributeError: 'TaskServer' object has no attribute 'address'
```

## Steps To Reproduce
1. Launch a Golem node in version 0.22 with the fields `DISALLOW_NODE_TIMEOUT_SECONDS` and `DISALLOW_IP_TIMEOUT_SECONDS` set to some integer value (not `None`). These values can be changed either in the `app_cfg.ini` file or via the Golem CLI.
2. Request a task which requires verification on the requestor's side (e.g. Blender).
3. Wait for at least one subtask to reach the `Verifying` state.
4. If the problem is reproduced, the subtask's verification should eventually fail with the error stated above.

## Expected behavior
Verification should be performed correctly and the subtask should be either accepted or rejected by the requestor.

**Comment by kmazurek** [comment]
Closed by #5057
