### ISSUE TITLE
Error connecting to app, app not enabled

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#5120]
## Description

**Golem Version**: 7835ab417b373449cfa7c5db25707a4f8369c0f0

**OS**: Linux

**Branch**: develop

**Description of the issue**:

An error occurred, when creating a Task-API task.

## Steps To Reproduce

Hard to tell. It happened once so far in `test_regular_task_api_run` integration task.

## Expected behavior

Duh...

## Logs and any additional context

https://buildbot.golem.network/buildbot/#/builders/15/builds/976

```
ERROR    golem.task.requestedtaskmanager     Failed to shut down client. app_id='daec55c08c9de7b71bf4ec3eb759c83b'
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 293, in _task_creation_ctx
    await async_generator.yield_()
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/async_generator/_impl.py", line 106, in yield_
    return await _yield_(value)
  File "/home/buildbot-worker/worker/test_node_integration/build/.venv/lib/python3.6/site-packages/async_generator/_impl.py", line 99, in _yield_
    return (yield _wrap(value))
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 256, in init_task
    await self._init_task(task_id)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 272, in _init_task
    app_client = await self._get_app_client(task.app_id)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 811, in _get_app_client
    service = await self._get_task_api_service(app_id)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 831, in _get_task_api_service
    f"Error connecting to app, app not enabled. app={app_id}")
RuntimeError: Error connecting to app, app not enabled. app=daec55c08c9de7b71bf4ec3eb759c83b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 306, in _task_creation_ctx
    await self._shutdown_app_client(app_id)
  File "/home/buildbot-worker/worker/test_node_integration/build/golem/task/requestedtaskmanager.py", line 965, in _shutdown_app_client
    await self._app_clients[app_id].shutdown()
KeyError: 'daec55c08c9de7b71bf4ec3eb759c83b'
```

**Comment by etam** [comment]
fix merged to b0.23
