### ISSUE TITLE
in after_disconnection      builtins.AttributeError: 'NoneType' object has no attribute 'dropped'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5122]
## Description

**Golem Version**:  GOLEM Version: 0.22.1+dev102.g85a1283 

**Golem-Messages version** (leave empty if unsure):3.15.0

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04, Windows

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After starting the app error appears in logs

```
2020-03-06 14:12:51 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 267, in run
    
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    raise RuntimeError(
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    try:
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 141, in _readOrWrite
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/network.py", line 172, in connectionLost
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 405, in trigger
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 1079, in _process
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 423, in _trigger
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 433, in _process
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 286, in execute
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/transitions/core.py", line 1037, in callback
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/transport/network.py", line 154, in after_disconnection
    
builtins.AttributeError: 'NoneType' object has no attribute 'dropped'
 
```

Also node is not connecting with other nodes despite running `network connect` from cli.

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the GOLEM Version: 0.22.1+dev102.g85a1283 app
2.Check logs for error

## Logs and any additional context

full log:
[golem (13).log](https://github.com/golemfactory/golem/files/4298516/golem.13.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
fix merged to b0.23
