### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ederenn\\AppData\\Local\\Temp\\tmpydcgk346'

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5126]
## Description

**Golem Version**: 0.22.1+dev104.g9a13476

**Golem-Messages version** (leave empty if unsure): 3.15.0

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Windows 10 Pro

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

After shutting down Golem error appears in logs:

```
WARNING  [twisted                            ] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
INFO     [golem.network.concent.client       ] Waiting for received messages queue to empty
INFO     [golem.network.concent.client       ] <ConcentClientService(Thread-7, started daemon 1196)> stopped
WARNING  [golem.core.processmonitor          ] Subprocess 4464 terminated
INFO     [golem.rpc.session                  ] Client connected, starting WAMP-Ticket challenge.
INFO     [golem.rpc.session                  ] WAMP-Ticket challenge received.
WARNING  [twisted                            ] session closed with reason wamp.close.transport_lost [()]
INFO     [golem.docker.hypervisor.hyperv     ] Hyper-V: Saving state of VM golem ...
Traceback (most recent call last):
  File "C:\Python36\lib\weakref.py", line 624, in _exitfunc
  File "C:\Python36\lib\weakref.py", line 548, in __call__
  File "C:\Python36\lib\tempfile.py", line 797, in _cleanup
  File "C:\Python36\lib\shutil.py", line 494, in rmtree
  File "C:\Python36\lib\shutil.py", line 376, in _rmtree_unsafe
  File "C:\Python36\lib\shutil.py", line 374, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ederenn\\AppData\\Local\\Temp\\tmpydcgk346'

C:\Users\ederenn>

```

**Actual result**:

no additional problems besides error in logs

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app from console
2. Wait for Golem to start and keep node running for a while.
3. Press ctrl c
4. See error in console and in `golem.log`

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by Sahilpreet-2213** [comment]
same problem ?

**Comment by Sahilpreet-2213** [comment]
same problem
