### ISSUE TITLE
OperationalError: table dockerwhitelist has no column named created_date

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5148]
## Description

**Golem Version**:  0.22.1+dev122.g7c01432 

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04

**Branch** (if launched from source): b0.23

**Mainnet/Testnet**: mainnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

Upgrading source Golem on b0.23 branch from `f5a985ec7`, to `7c0143248` resulted with an db error `OperationalError: table dockerwhitelist has no column named created_date`

**Actual result**:

It is not possible to run the app, Golem is crashing

## Logs and any additional context

```
WARNING  [golem.db                           ] execute_sql() retry timeout after 104664 iterations. Giving up. sql='INSERT INTO "dockerwhitelist" ("repository", "created_date", "modified_date") VALUES (?, ?, ?)', params=['golemfactoryapps', datetime.datetime(2020, 3, 26, 17, 3, 22, 772395, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 3, 26, 17, 3, 22, 772399, tzinfo=datetime.timezone.utc)]
CRITICAL [golem.client                       ] Can't start network. Giving up. 
Traceback (most recent call last):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: table dockerwhitelist has no column named created_date

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ederenn/projects/golem/golem/client.py", line 373, in start
    self.start_network()
  File "/home/ederenn/projects/golem/golem/client.py", line 425, in start_network
    task_finished_cb=self._task_finished_cb,
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 147, in __init__
    register_built_in_repositories()
  File "/home/ederenn/projects/golem/golem/envs/default.py", line 58, in register_built_in_repositories
    Whitelist.add(DOCKER_REPOSITORY)
  File "/home/ederenn/projects/golem/golem/envs/docker/whitelist.py", line 27, in add
    golem.model.DockerWhitelist.create(repository=repository)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 4977, in create
    inst.save(force_insert=True)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 5170, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 3584, in execute
    cursor = self._execute()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 2939, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/ederenn/projects/golem/golem/database/database.py", line 30, in execute_sql
    return super().execute_sql(sql, params, require_commit)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 3837, in execute_sql
    self.commit()
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/peewee.py", line 3830, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: table dockerwhitelist has no column named created_date
INFO     [golem.client                       ] Shutting down ... 
INFO     [golem.client                       ] Stopping network ... 
INFO     [golem.network.concent.client       ] Waiting for received messages queue to empty 
INFO     [golem.network.concent.client       ] <ConcentClientService(Thread-1, started daemon 139973211985664)> stopped 
WARNING  [twisted                            ] Native worker received SIGTERM - shutting down .. 
ederenn@GOLEM2008-UBNT18:~/bin$ 
```
[golem (2).log](https://github.com/golemfactory/golem/files/4389020/golem.2.log)

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
fix merged to b0.23
