### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by m135858** [golemfactory/clay#5199]
## Description

**Golem Version**: golem-0.23.1-windows

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]:Windows, release: 10, version: 10.0.19041

**Branch** (if launched from source):

**Mainnet/Testnet**: both of them(Mainnet/Testnet)

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P3 label is set for Severity-Low/Effort-hard

**Description of the issue**:

_I installed golem and then ran it mainnet but  initial connection had some problems with golem.log

**Actual result**:

_2020-11-04 12:48:28 INFO     golemapp                            GOLEM Version: 0.23.1
2020-11-04 12:48:28 INFO     golemapp                            Protocol Version: 32
2020-11-04 12:48:28 INFO     golemapp                            golem_messages Version: 3.15.0
2020-11-04 12:48:28 INFO     golemapp                            system: Windows, release: 10, version: 10.0.19041, machine: AMD64
2020-11-04 12:48:31 ERROR    sentry.errors                       Sentry responded with an error: <urlopen error [Errno 11002] getaddrinfo failed> (url: https://talkback.golem.network/api/5/store/)
Traceback (most recent call last):
  File "C:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\BuildbotWorker\buildpackage_windows\build\.venv\lib\site-packages\raven\utils\http.py", line 31, in connect
  File "C:\Python36\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python36\lib\socket.py", line 745, in getaddrinfo
    addrlist.append((_intenum_converter(af, AddressFamily),
socket.gaierror: [Errno 11002] getaddrinfo failed

**Screenshots**:
![z1](https://user-images.githubusercontent.com/72839061/98102012-453e9380-1ea8-11eb-8212-1375efe0fc29.jpg)
![z2](https://user-images.githubusercontent.com/72839061/98102017-48398400-1ea8-11eb-8e20-0fb133fd4959.jpg)

## Logs and any additional context
_Please upload your logs if possible_

## Proposed Solution?
_What could be a solution for that issue

**Comment by cryptobench** [comment]
Being stuck at the connecting screen can sometime be caused by not having your ports forwarded. (40102, 40103 and 3282)
