### ISSUE TITLE
scale_factor=0 bug

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#628]
In `framerenderingtask` in function `_open_frame_preview` if `scale_factor` is set to zero then the preview is not created and PIL throws and error. 
We have to identify the sitution when `scale_factor` may be set to 0.

**Comment by magdasta** [comment]
Can you tell me how to reproduce this?

**Comment by banasiakadam60** [comment]
I'm not sure, probably I'm the only person how saw this bug. I've just find out that, for some reason `__get_border` method wasn't call. On my machine I just need to start _stylized_levi_ task with a few frames and I got such error:

```
Unhandled Error
Traceback (most recent call last):
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/adam/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/adam/Repo/golem/golem/network/transport/tcpnetwork.py", line 464, in dataReceived
    self._interpret(data)
  File "/home/adam/Repo/golem/golem/network/transport/tcpnetwork.py", line 635, in _interpret
    FilesProtocol._interpret(self, data)
  File "/home/adam/Repo/golem/golem/network/transport/tcpnetwork.py", line 609, in _interpret
    SafeProtocol._interpret(self, data)
  File "/home/adam/Repo/golem/golem/network/transport/tcpnetwork.py", line 495, in _interpret
    self.session.interpret(m)
  File "/home/adam/Repo/golem/golem/task/tasksession.py", line 68, in interpret
    MiddlemanSafeSession.interpret(self, msg)
  File "/home/adam/Repo/golem/golem/network/transport/session.py", line 291, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/adam/Repo/golem/golem/network/transport/session.py", line 97, in interpret
    action(msg)
  File "/home/adam/Repo/golem/golem/task/tasksession.py", line 343, in _react_to_want_to_compute_task
    msg.max_memory_size, msg.num_cores, self.address)
  File "/home/adam/Repo/golem/golem/task/taskmanager.py", line 162, in get_next_subtask
    extra_data = task.query_extra_data(estimated_performance, num_cores, node_id, node_name)
  File "/home/adam/Repo/golem/gnr/task/blenderrendertask.py", line 311, in query_extra_data
    self._update_frame_task_preview()
  File "/home/adam/Repo/golem/gnr/task/framerenderingtask.py", line 184, in _update_frame_task_preview
    self.__mark_sub_frame(sub, frame, sent_color)
  File "/home/adam/Repo/golem/gnr/task/framerenderingtask.py", line 299, in __mark_sub_frame
    img_task = self._open_frame_preview(preview_task_file_path)
  File "/home/adam/Repo/golem/gnr/task/framerenderingtask.py", line 195, in _open_frame_preview
    img.save(preview_file_path, "BMP")
  File "/home/adam/golem/golem/exe.linux-x86_64-2.7/lib/python27/PIL/Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "/home/adam/golem/golem/exe.linux-x86_64-2.7/lib/python27/PIL/BmpImagePlugin.py", line 272, in _save
    (rawmode, stride, -1))])
  File "/home/adam/golem/golem/exe.linux-x86_64-2.7/lib/python27/PIL/ImageFile.py", line 487, in _save
    e.setimage(im.im, b)
exceptions.SystemError: tile cannot extend outside image
```

I talked about this bug with Ola on gitter
