### ISSUE TITLE
unable to install from windows - pyelliptic error

### ISSUE THREAD

**Issue by bloose007** [golemfactory/clay#662]
```
c:\Users\simpsons\golem\golem>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyelliptic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyelliptic\__init__.py", line 43, in <module>
  File "C:\Python27\lib\site-packages\pyelliptic\openssl.py", line 528, in <module>
  File "C:\Python27\lib\site-packages\pyelliptic\openssl.py", line 67, in __init__
  File "c:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
>>>
```

**Comment by mfranciszkiewicz** [comment]
Your 32-bit python installation is most probably trying to load a 64-bit version of `libeay32.dll` (or a 64-bit version of one of its dependencies). To fix this you can either:
- Copy a 32-bit version of `libeay32.dll` to your working directory;
- Modify the `PATH` environment variable, so that it will point to a directory with a 32-bit version first.

**Comment by mfranciszkiewicz** [comment]
"Running from the source" wiki section for Windows has been updated and now includes a full installation guide.
