### ISSUE TITLE
AttributeError: 'Ui_MainWindow' object has no attribute 'previewsSlider'

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/clay#748]
Runtime error. Launch golemapp on Linux and observe:
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lfoniok/Golem/golem/gui/startapp.py", line 92, in start_gui_process
    gui_app = GUIApp(rendering)
  File "/home/lfoniok/Golem/golem/gui/startapp.py", line 64, in __init__
    MainWindowCustomizer)
  File "/home/lfoniok/Golem/golem/gui/applicationlogic.py", line 78, in register_gui
    self.customizer = customizer_class(gui, self)
  File "/home/lfoniok/Golem/golem/gui/controller/mainwindowcustomizer.py", line 63, in __init__
    self.preview_controller = PreviewController(self.gui, self.logic, self)
  File "/home/lfoniok/Golem/golem/gui/controller/previewcontroller.py", line 32, in __init__
    super(PreviewController, self).__init__(gui, logic)
  File "/home/lfoniok/Golem/golem/gui/controller/customizer.py", line 17, in __init__
    self._setup_connections()
  File "/home/lfoniok/Golem/golem/gui/controller/previewcontroller.py", line 57, in _setup_connections
    self.gui.ui.previewsSlider.valueChanged.connect(self._update_slider_preview)
AttributeError: 'Ui_MainWindow' object has no attribute 'previewsSlider'

**Comment by Elfoniok** [comment]
On my machine ui_AppMainWindow is old and not generated during start of golem applications.
This raises a question if those should be generated and attached to commits which change UI files, or should any before start of golem up start qt ui compiler?

**Comment by Elfoniok** [comment]
Turns out every developer should launch setup.py script.
