### ISSUE TITLE
`GLIBC_2.18' not found error on Centos 7

### ISSUE THREAD

**Issue by JMVoid** [golemfactory/clay#817]
Following the instruction to  install golem on Centos 7 cloud server of following version:
Linux 3.10.0-229.1.2.el7.centos.onapp.x86_64 #1 SMP Tue Apr 7 13:04:56 EEST 2015 x86_64 x86_64 x86_64 GNU/Linux
------------------
After executed golem.sh. the log file contain following error message:
----------------------------------
Traceback (most recent call last):
  File "/home/mfrancis/Projects/golem-remote/scripts/packaging/cx_Freeze/initscripts/Console.py", line 58, in <module>
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
  File "golemapp.py", line 7, in <module>
  File "/home/mfrancis/Projects/golem-remote/golem/node.py", line 10, in <module>
  File "/home/mfrancis/Projects/golem-remote/golem/client.py", line 43, in <module>
  File "/home/mfrancis/Projects/golem-remote/golem/task/taskserver.py", line 12, in <module>
  File "/home/mfrancis/Projects/golem-remote/golem/task/taskcomputer.py", line 19, in <module>
  File "/home/ethereum/golem/exe.linux-x86_64-2.7/lib/python27/apps/blender/benchmark/benchmark.py", line 5, in <module>
    from apps.blender.task.blenderrendertask import BlenderRendererOptions
  File "/home/mfrancis/Projects/golem-remote/apps/blender/task/blenderrendertask.py", line 15, in <module>
  File "/home/mfrancis/Projects/golem-remote/apps/rendering/resources/renderingtaskcollector.py", line 4, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ethereum/golem/exe.linux-x86_64-2.7/libstdc++.so.6)

**Comment by mfranciszkiewicz** [comment]
Please try removing `/home/ethereum/golem/exe.linux-x86_64-2.7/libstdc++.so.6`

**Comment by johndoe26** [comment]
After upgraded to  glibc2.18 and gcc 5.2. THIS error have been solved

**Comment by JMVoid** [comment]
After upgraded to glibc2.18 and gcc 5.2. THIS error have been solved
